### ISSUE TITLE
Class App\Providers\Dispatcher does not exist

### ISSUE THREAD

**Issue by HKGeeks** [JeroenNoten/Laravel-AdminLTE#10]
I follow the installation instruction for the "Menu configuration at runtime"

I got an error message, Class App\Providers\Dispatcher does not exist

How can I fix it?

I am using Laravel 5.1 and want to build a runtime menu. Thanks

**Comment by JeroenNoten** [comment]
Hi,

Add this at the top of that file:

    use Illuminate\Contracts\Events\Dispatcher;

I will update it in the README as well.
