### ISSUE TITLE
How to use chartisan front end library located in node_moudules

### ISSUE THREAD

**Issue by oitcode** [jeroennoten/Laravel-AdminLTE#1005]
I have installed chartisan npm package using npm install and now the i can see its folder in node_modules too.

But not sure how to use it with Laravel-AdminLTE. Is there anything I need to do in config/adminlte.php or add any script tag in main_views master.blade.php?

In general the question would be how to use js framework installed by npm in node_modules directory?

Please help.

**Comment by Shidersz** [comment]
Closed, no feedback from author...
