### ISSUE TITLE
How to use the href whit route in Navbar Notification?

### ISSUE THREAD

**Issue by NamJinn21** [jeroennoten/Laravel-AdminLTE#1006]
i'm using the Navbar Notification that you provides in a controller.
I trying to use the href when we created the notification dropdown main content using route but it doesn't work.
It doesn't take me to the route that I want "viewnotification", but it takes me to this route "/%7Broute("
how can i use it?

 $dropdownHtml = '';

    foreach ($notifications as $key => $not) {
        $icon = "<i class='mr-2 {$not['icon']}'></i>";

        $time = "<span class='float-right text-muted text-sm'>
                   {$not['time']}
                 </span>";

        $dropdownHtml .= "<a href='{route('viewnotification')}' class='dropdown-item'>
                            {$icon}{$not['text']}{$time}
                          </a>";

        if ($key < count($notifications) - 1) {
            $dropdownHtml .= "<div class='dropdown-divider'></div>";
        }
    }

**Comment by Shidersz** [comment]
@NamJinn21 the syntax `"{...}"` inside a string is used to inject variables inside a string, read [here](https://stackoverflow.com/questions/5605965/php-concatenate-or-directly-insert-variables-in-string) for info. On your case, try:

```php
foreach ($notifications as $key => $not) {
    $icon = "<i class='mr-2 {$not['icon']}'></i>";

    $time = "<span class='float-right text-muted text-sm'>
               {$not['time']}
             </span>";

    $myRoute = route('viewnotification');

    $dropdownHtml .= "<a href='{$myRoute}' class='dropdown-item'>
                        {$icon}{$not['text']}{$time}
                      </a>";

    if ($key < count($notifications) - 1) {
        $dropdownHtml .= "<div class='dropdown-divider'></div>";
    }
}
```

**Comment by NamJinn21** [comment]
@Shidersz thank you it works, thanks for the help and the info.
