### ISSUE TITLE
How to insert session in adminlte.php

### ISSUE THREAD

**Issue by wilmancoder** [jeroennoten/Laravel-AdminLTE#1008]
in the adminlte.php structure there is a form like this :

[
    'text' => 'test_text',
    'route' => 'test_route',
],

the question is how to insert Session in "text" array?

**Comment by Shidersz** [comment]
@wilmancoder Please, specify what you want to do with an example... You can't access the session data from a configuration file. Probably you will need to add that menu item from [Menu Configuration At Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime)...

**Comment by wilmancoder** [comment]
> Please, specify what you want to do with an example... You can't access the session data from a configuration file. Probably you will need to add that menu item from

example :
[
'text' => 'test_text (count incoming data)',
'route' => 'test_route',
],

**Comment by Shidersz** [comment]
Closed, the solution involves using [Menu Configuration At Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime)
