### ISSUE TITLE
Menu multilevel not working

### ISSUE THREAD

**Issue by codzero** [jeroennoten/Laravel-AdminLTE#101]
I'm using Top Navigation and the multi level menu only works with level 1, the level 2 and 3 not appears. How can I to fix it ?

Thanks!

**Comment by miy4mori** [comment]
Mayby you need delete can property from array.

```php
[
    [
        'header' => 'BLOG',
        'can' => 'manage-blog'
    ],
    [
        'text' => 'Add new post',
        'url' => 'admin/blog/new',
        'can' => 'add-blog-post' //remove this or config correctly
    ],
]
```
Please upload you config if you can.

**Comment by jeroennoten** [comment]
AdminLTE does not support multilevel topmenu's, so this is unfortunately not possible.

**Comment by diegocar448** [comment]
Multilevel dont work?
