### ISSUE TITLE
How to delete a plugin correctly

### ISSUE THREAD

**Issue by alejandromora99** [jeroennoten/Laravel-AdminLTE#1010]
I just installed the datatables plugin, but I realized that I will not use it, what is the correct way to remove it ?, deleting the folder inside vendor ?. Thanks

**Comment by Shidersz** [comment]
@alejandromora99 If you have used `php artisan adminlte:plugins install --plugin=datatables` to install the plugin, then it will copy the plugin files from the `vendor/almasaeed2010/adminlte/plugins/` folder (related to **AdminLTE** package) to `public/vendor/datatables/` folder. In this case you will need to remove the `public/vendor/datatables/` folder and the plugin configuration from the `config/adminlte.php` file. The `vendor` folder is managed by composer, and the content there is modified when you run `composer install` and or `update` commands, you should not touch any files in that folder.

**Comment by alejandromora99** [comment]
Thanks for explaining, I love this package :)
