### ISSUE TITLE
How to include blade file within Adminlte template

### ISSUE THREAD

**Issue by alejandromora99** [jeroennoten/Laravel-AdminLTE#1011]
I have the following question, I have the following code in a .blade.php file:
```
@if (session()->has('success'))
    <div class="alert alert-success">
        {{session()->get('success')}}
    </div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
```
 and I want to implement it in my entire project, is there any way to do it without having to do an include in each of my templates? Is there a way to do the include in the base adminlte template?

**Comment by Shidersz** [comment]
@alejandromora99 Yea, you may create a base layout for your entire application and then extends that layout, check next related issue: https://github.com/jeroennoten/Laravel-AdminLTE/issues/925

**Comment by alejandromora99** [comment]
But how could I make it stay inside the content section? I just tried: 
```
@extends('adminlte::page')
@section('content')
<h1>test</h1>
    @include('dashboard.partials.session-flash-status')
    @include('dashboard.partials.validation-error')
@endsection

```
then use this file as the master, like in a template "x":

```
@extends('dashboard.master')

@section('content')
  #example code
@endsection
```
then use this file as the master, but it doesn't show me the h1 or error messages

**Comment by Shidersz** [comment]
@alejandromora99 By creating a new section and yielding it...

```blade
@extends('adminlte::page')
@section('content')
    @yield('dashboard_content')
    <h1>test</h1>
    @include('dashboard.partials.session-flash-status')
    @include('dashboard.partials.validation-error')
@endsection
```

Then...

```blade
@extends('dashboard.master')

@section('dashboard_content')
  #example code
@endsection
```

**Comment by alejandromora99** [comment]
thank you man, it helped me a lot
