### ISSUE TITLE
How to add login view inside dashboard content box?

### ISSUE THREAD

**Issue by alejandromora99** [jeroennoten/Laravel-AdminLTE#1018]
Hi !, I was wondering if it is possible to add the login view inside a view that is using the template, I tried this:

```
@extends('dashboard.master')
@section('dashboard_content')

    @include('adminlte::auth.login')


@endsection
```

But it only shows the login view

**Comment by Shidersz** [comment]
I do not think that is possible. I'm not even sure why you want such a thing...

**Comment by alejandromora99** [comment]
I just wanted to keep the style of the page, without removing the navigation bar, but that's fine, thanks for your answer :)
