### ISSUE TITLE
MakeAuthCommand vs AuthMakeCommand

### ISSUE THREAD

**Issue by kdv88** [jeroennoten/Laravel-AdminLTE#102]
In Laravel 5.4 it seems there has been a change: MakeAuthCommand has been renamed to AuthMakeCommand

Rename it in laravel-adminlte/src/Console/MakeAdminLteCommand.php and in the registerCommands() and it seems to be working great again!

**Comment by Lvkz** [comment]
@jeroennoten I think this one can be closed as well since #104 was resolved.

**Comment by jeroennoten** [comment]
Solved in v1.20.0!
