### ISSUE TITLE
.dl-horizontal class not working

### ISSUE THREAD

**Issue by gaztum** [jeroennoten/Laravel-AdminLTE#1020]
### Describe the bug
.dl-horizontal class not working

### Steps To Reproduce
1. Go to https://adminlte.io/themes/dev/AdminLTE/pages/UI/general.html
2. Scroll down to 'Description Horizontal'
3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/61505273/144245201-e2fee818-1b9f-453c-bf52-ccf6df81e2c6.png)

| Item    | Version
| ------- | -------
| Laravel | 8

**Comment by Shidersz** [comment]
Hi @gaztum , please report the issue on the [ColorlibHQ/AdminLTE](https://github.com/ColorlibHQ/AdminLTE) package, the problem is related to the underlying package. This just provides integration with the **Laravel framework** among other things.

**Comment by Shidersz** [comment]
Closed, issue do not belongs to this package.
