### ISSUE TITLE
[FEATURE] Supporting RTL in the design

### ISSUE THREAD

**Issue by moazbasheer** [jeroennoten/Laravel-AdminLTE#1023]
I'm always frustrated when I try to use this template's pages as RTL with languages like Arabic.
I think you have to support it the next versions.

**Comment by resslinger** [comment]
It will be available, if adminlte is upgraded to Bootstrap 5.

**Comment by Grand-Community** [comment]
is it supported now ?

**Comment by dfsmania** [comment]
@Grand-Community No, this package just integrates version `3.2` of [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) into Laravel. Versions `4.x` of `AdminLTE` will support **RTL**, but it's currently on development and was made from scratch, so a lot of effort will be required to integrate it here, including losing some of the features existing on `v3.2`, like the `IFrame` mode.
