### ISSUE TITLE
[BUG] Cannot use positional argument after named argument during unpacking in vendor/SRC/AdminLTEServiceProvider in laravel 8 and php 8.0

### ISSUE THREAD

**Issue by eldyyuda11** [jeroennoten/Laravel-AdminLTE#1024]
I'm try to use packet in laravel 8 and php 8 and after login i'm get some bug in file AdminLTEServiceProvider.php at vendor folder in this line 
![Screenshot (126)](https://user-images.githubusercontent.com/58543729/145407871-b245fb7b-88bf-4452-b3e0-fb71c232f2eb.png)

$events->listen(
            BuildingMenu::class,
            function (BuildingMenu $event) use ($config) {
                $menu = $config->get('adminlte.menu', []);
                $menu = is_array($menu) ? $menu : [];
                $event->menu->add(...$menu);
            }
        );

**Comment by Shidersz** [comment]
Please, edit your post and give a better explanation or details of the problem you are facing...

**Comment by Shidersz** [comment]
Share you menu definition on the `config/adminlte.php` file...

**Comment by eldyyuda11** [comment]
> Share you menu definition on the `config/adminlte.php` file...

i gotta the problem thank you so much sirr,
