### ISSUE TITLE
[QUESTION] How to use x-adminlte-alert correctly?

### ISSUE THREAD

**Issue by vitkuz573** [jeroennoten/Laravel-AdminLTE#1025]
### Is your request related to a problem? Please describe.
If you use x-adminlte-alert, it is not displayed as a popup notification, but as:
![image](https://user-images.githubusercontent.com/37330183/145344709-67c1d247-d720-4700-be85-6fbf7a0c0498.png)
which clearly does not resemble what is shown on https://adminlte.io/themes/v3/pages/UI/modals.html

**Comment by REJack** [comment]
that's a Bootstrap Alert in AdminLTE look (BS3 like Alert), do you mean one of the toasts?

**Comment by Shidersz** [comment]
@vitkuz573 `x-adminlte-alert` implements an alert as described in the next link: https://adminlte.io/themes/v3/pages/UI/general.html

The toast you linked are part of a plugin, maybe **sweetalert2**, check issue https://github.com/jeroennoten/Laravel-AdminLTE/issues/777 if you want to know how you can use it.
