### ISSUE TITLE
[FEATURE] Disable Dark Mode Route

### ISSUE THREAD

**Issue by MarioVillani** [jeroennoten/Laravel-AdminLTE#1026]
Hello,
what's the cleanest way to disable POST adminlte/darkmode/toggle route?

I don't want to use the feature in the project, so i've added

 _'layout_dark_mode' => null_

in my adminlte.php config file but the route is still available.

**Comment by Shidersz** [comment]
@MarioVillani I think currently there is no way to disable loading of darkmode routes. I will review this on the future.
