### ISSUE TITLE
AdminLTE can Attribute not working 

### ISSUE THREAD

**Issue by Lcova76** [jeroennoten/Laravel-AdminLTE#1028]
In the Wiki Page it shows;

The can Attribute:
....... You can also use multiple conditions entries with an array, check the next example for details:

[
    [
        'text' => 'Add new post',
        'url'  => 'admin/blog/new',
        **_'can'  => ['add-blog-post', 'other-right'],_**
    ],
]

So, for the previous example:
**the link will show if the user has the add-blog-post  or other-right permissions._**

I cant make this to work..
It only works if i have BOTH permissions..

**Comment by Shidersz** [comment]
Hi @Lcova76 , the package covers this situation with a test and it is currently successful (see this [test](https://github.com/jeroennoten/Laravel-AdminLTE/blob/eef86553d9a9988df29aa5d93a4d69a69087ee50/tests/Menu/BuilderTest.php#L727)).

1. Are you using latest package version?
2. Have you created a [custom filter](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) that overwrites the package default one?

**Comment by Lcova76** [comment]
> Hi @Lcova76 , the package covers this situation with a test and it is currently successful (see this [test](https://github.com/jeroennoten/Laravel-AdminLTE/blob/eef86553d9a9988df29aa5d93a4d69a69087ee50/tests/Menu/BuilderTest.php#L727)).
> 
>     1. Are you using latest package version?
> 
>     2. Have you created a [custom filter](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) that overwrites the package default one?

1- It's an old version.. 1.23.. I managed to update to 1.27 with "composer update jeroennoten/laravel-adminlte"..
But having trouble to update to the latest version..

Since which version the can attibute accept's an array??

**Comment by Shidersz** [comment]
Latest version is `v3.7.2`, I'm not sure is `1.23` and `1.27` are valid versions of this package...
