### ISSUE TITLE
[Question] I can't subscribe the event `DarkModeWasToggled`

### ISSUE THREAD

**Issue by h-kusaba-1001** [jeroennoten/Laravel-AdminLTE#1029]
### Describe 
I cannot subscribe event `DarkModeWasToggled`.

HTML Body and dark-mode-wiget toggle is working well.
fetching `/adminlte/darkmode/toggle` (POST) is working too..
I suspect `DarkModeController@toggle` and  `DarkModeWasToggled` is not workling in `dd()` debuging.

I'd like to know other people having same problem, and a best way to debuging in event and listner.

### Environment

| Item    | Version
| ------- | -------
| Laravel | 8.69.0
| Project |  v3.7.1
| OS      | Amazonlinux2(docker)

**Comment by Shidersz** [comment]
hi @h-kusaba-1001 I'm not sure if you are asking for help to listen on `DarkModeWasToggled` event or if you need help to debug the event object. Please, share a snippet of your code and explain what is your goal...

**Comment by h-kusaba-1001** [comment]
Hello @Shidersz 
I asked for help to listen on DarkModeWasToggled event, But **It was self-solved**.
I had a lack of confirmation.

I set event and listener.
In Chrome's network tab, It's working collectly.
I shoud watch it, before this issue create.

thank you for your kindness.
I'm gonna close this issue.
