### ISSUE TITLE
Menu Active

### ISSUE THREAD

**Issue by rodrigompais** [jeroennoten/Laravel-AdminLTE#1031]
Hi guys, how are you?
I made my menu, but it is getting so active, has anyone gone through this? Is it possible to modify and not get this gray color?
![image](https://user-images.githubusercontent.com/59613110/147681109-85f34548-af92-49cc-aa67-9efb14d08392.png)

and
![image](https://user-images.githubusercontent.com/59613110/147681145-10991ef4-5449-4c2a-914b-bb657fded808.png)

**Comment by Shidersz** [comment]
It is the standard behaviour of the **AdminLTE** template. You may try to add the `nav-legacy` class on `classes_sidebar_nav` configuration option. See documentation of that option on [Layout And Styling Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration). I'm not sure if there are other alternatives.
