### ISSUE TITLE
[FEATURE] Disabling the side menu on certain pages

### ISSUE THREAD

**Issue by vitkuz573** [jeroennoten/Laravel-AdminLTE#1032]
Is it possible to completely disable the side menu on a particular page, and if so, how do I do it?

**Comment by Shidersz** [comment]
@vitkuz573 what do you mean with disabling the sidebar menu?

I know you can change configuration options on the controller before rendering the view, this way you can alternate the layout to use for certain pages. To set configuration values at runtime, pass an array to the config helper, for example:

```php
config(['adminlte.layout_topnav' => true]);
```

**Comment by vitkuz573** [comment]
I mean how to remove this menu from a certain page

![image](https://user-images.githubusercontent.com/37330183/149096486-4bef635b-7591-47d4-ab9d-b2e1e0e89d88.png)

**Comment by Shidersz** [comment]
@vitkuz573 There is no support from the underlying **AdminLTE** package for that. I think your only option is to use `Javascript/JQuery` to remove the main menu wrapper from the `dom` and probably you will need to change the style of other elements of the layout. Maybe @REJack has a better vision on how you may proceed on this approach.

**Comment by REJack** [comment]
I've added a body class to hide the sidebar completely that comes with v3.2.

**Comment by Shidersz** [comment]
@vitkuz573 We will try to include this feature after **AdminLTE v3.2** is released. Temporarily, you may check what changes you need to do on your project form next commit: https://github.com/ColorlibHQ/AdminLTE/commit/0927e68fa4e52e7f82f4ce076c1e9f3c043ae9ed

**Comment by Shidersz** [comment]
@vitkuz573 The latest release `v3.8.0` includes `AdminLTE 3.2.0`. So you may start experimenting with `sidebar-hidden` on the body class.

- You may try to add it using the `adminlte.php` config file, option `classes_body`.
- Or using jQuery/Javascript to add the classes on the `body` tag

Please, report any problem or bug you may face with this new class on the [ColorlibHQ/AdminLTE](https://github.com/ColorlibHQ/AdminLTE) package.

**Comment by vitkuz573** [comment]
Thank you!

**Comment by royallife88** [comment]
@Shidersz  How I can hide the specific single menu or submenu item conditionally for config/adminlte.php?

**Comment by Shidersz** [comment]
@royallife88 Read about the [can attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) and how to define permissions with [Laravel's Gate](https://laravel.com/docs/9.x/authorization#gates).

**Comment by dfsmania** [comment]
A solution is provided on the underlying `AmindLTE` package, see https://github.com/jeroennoten/Laravel-AdminLTE/issues/1032#issuecomment-1035835679
