### ISSUE TITLE
Breadcrumbs - advice on best way to implement

### ISSUE THREAD

**Issue by rightwayround** [jeroennoten/Laravel-AdminLTE#1036]
### Is your request related to a problem? Please describe.
I'm looking to add breadcrumbs, can you advise the best way to go about this.

### Describe the solution you'd like
Ideally some information, would be great to see this info in the documentation.

### Describe alternatives you've considered
I've had a look here https://github.com/jeroennoten/Laravel-AdminLTE/pull/689 but it wasn't committed.

### Additional context
Add any other context or screenshots about the feature request here. - no all good

**Comment by Shidersz** [comment]
@rightwayround The [AdminLTE demo site](https://adminlte.io/themes/v3/index.html) implements breadcrumbs on the content header section, you can inspect the HTML on his pages to get an idea on how you can implement the breadcrumbs inside the `content_header` section yielded by this package.

The easy way will be to define the breadcrumb on each page you create, the hardest way will be to use `Javascript` and/or `jQuery` on a main or base layout to access the current active item on the sidebar menu and automatically generate the breadcrumbs from that information.

**Comment by rightwayround** [comment]
👍 thanks
