### ISSUE TITLE
[QUESTION] is it possible to append a css or js to all pages ?

### ISSUE THREAD

**Issue by AMoktar** [jeroennoten/Laravel-AdminLTE#1037]
First of all, many thanks for this great package 

I want to append some css and js to all pages

**Comment by REJack** [comment]
there are 2 ways IMHO,

1. create a override template that extends `adminlte::page` (inline)
2. create a plugin that is activated in the config so it will used in all pages (non-inline)

**Comment by Shidersz** [comment]
@AMoktar for option **2**, read the [plugin configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration) docs on the wiki...

**Comment by AMoktar** [comment]
what if enabled_laravel_mix=true :) ??

**Comment by Shidersz** [comment]
Please, check issues: #1030 and #490
