### ISSUE TITLE
[FEATURE] Edit theme for specific routes

### ISSUE THREAD

**Issue by piyushmanolkar** [jeroennoten/Laravel-AdminLTE#1038]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.0
| Project Version         | v3

### Current Behavior

Theme is global

### Expected Behavior

Change theme for specific routes/roles

**Comment by Shidersz** [comment]
@piyushmanolkar What you mean with change theme? Can you give some more details of your needs?

However, you may change the `adminlte.php` configuration at runtime using the Laravel [config helper](https://laravel.com/docs/8.x/configuration#accessing-configuration-values), for example:

On a controller/route, before rendering the page, you may execute...

```php
config(['adminlte.some_config' => 'some_new_value']);
```

**Comment by piyushmanolkar** [comment]
For example, I'm making a multi-tenancy app, And I need to change the theme dynamically based on the tenants website color palette, now if i do change the config at runtime, it will affect all of the tenants, so I can't do that, so I need a solution to change the color scheme/theme of the navbar / sidebar only for specific routes / event.

**Comment by Shidersz** [comment]
In `Laravel` the application follows a `request-response` cycle, if you change the config depending on the tenant accessing the website, I believe it should work, the config will change only for that `request-response` cycle. Is similar to managing user preferences.

Sorry, but I can't imagine other solution by now, maybe someone can help you.

**Comment by valentinomariotto** [comment]
@piyushmanolkar how did you end up doing this?

I was thinking of booting different adminlte config files depending on the domain name (I have different subdomains which should be styled differently). 
But the color palette of bootstrap is limited, especially for items such as buttons: we have btn-primary or btn-danger or btn-outline-info classes, but we cannot use a btn-cyan class.
So how can I dynamically change the color of the --primary variable?

**Comment by piyushmanolkar** [comment]
@valentinomariotto I ended up using the method suggested by dfsmania, Checking what tenant it is before the page is rendered Used the config file to set required color for that tenant.

**Comment by valentinomariotto** [comment]
@piyushmanolkar thank you for replying. 
So in the config/adminlte.php file you can set the bootstrap classes to apply to some elements.. but those classes only admit a limited color palette. 
For example you can set `'classes_sidebar_colors' => 'sidebar-dark-primary'`, or `'sidebar-dark-teal' `.
But you cannot set `'classes_auth_btn' => 'btn-flat btn-teal'`, as bootstrap doesn't have that class.

Did you have this issue?
