### ISSUE TITLE
DataTables export only visible columns

### ISSUE THREAD

**Issue by princenaar** [jeroennoten/Laravel-AdminLTE#1039]
Hello, I'm using the dataTables x-component feature. I have a table with a lot of columns and for better visibility, I've hidden some of them. In the plugin, all the columns of the table are exported to Excel unless you add `no-export` attribute, but here, the hidden columns are not exported. Can you help me please ?

**Comment by Shidersz** [comment]
Please, share some example code that reproduces your issue. I have tested and columns that are defined with [visible=false](https://datatables.net/reference/option/columns.visible) are currently exported by the buttons extensions.

**Comment by princenaar** [comment]
This is the configuration variable in the controller :

```
$config = [
          'data' => $data,
          'order' => [[1, 'asc']],
          'columns' => [null, null, null, null, null, ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false],
          ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['visible' => false], ['orderable' => false]],
        ];
```

And this is the code in the blade file : 
` <x-adminlte-datatable id="table2" :heads="$heads" :config="$config" with-buttons />
`
The file contains the first five columns only.

**Comment by Shidersz** [comment]
@princenaar Please, create a minimal example (for example, with 3 columns and just one column not visible) and some dummy data. Then provide the way you define the `$heads`, the `$data` and the `$config` variable.

**Comment by princenaar** [comment]
```
    public function index()
    {

      $heads = [
        'Prénom',
        'Nom',
        ['label' => 'Mail', 'no-export' => false, 'width' => 5],
        ['label' => 'Actions', 'no-export' => true, 'width' => 5],
      ];


       $data = [];
       $btnEdit = '<button class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
               <i class="fa fa-lg fa-fw fa-pen"></i>
           </button>';
       $btnDelete = '<button class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                 <i class="fa fa-lg fa-fw fa-trash"></i>
             </button>';
       for ($i=0; $i < 5; $i++) {
         array_push($data, [
           'Prenom'.$i,
           'Nom'.$i,
           'Mail'.$i,
           '<nobr>'.$btnEdit.$btnDelete.'</nobr>'
          ]);
       }
      $config = [
        'data' => $data,
        'order' => [[1, 'asc']],
        'columns' => [null, null, ['visible' => false], ['orderable' => false]],
      ];
        return view('demande.index', compact('config', 'heads'));
    }

```

**Comment by Shidersz** [comment]
@princenaar In this particular case I think the problem is related to the existence of the `no-export => false` property for the **mail** head definition. Internally, `isset()` is used to check if property `no-export` is defined. So, it won't matters what value you put on the property, if it is defined, the column won't be exported. If this is the situation you are facing, just remove the `no-export` property form these columns you want to be exported. If this do not fix your problem I will give a better test later.

**Comment by princenaar** [comment]
Thanks a lot. This was the problem. Everything is working now.
