### ISSUE TITLE
make:adminlte is not defined in Laravel 5.4

### ISSUE THREAD

**Issue by mushroomgroover** [jeroennoten/Laravel-AdminLTE#104]
![error](https://user-images.githubusercontent.com/10472490/29065325-52cabc44-7c5e-11e7-98c2-4b5974dc3a40.JPG)

As seen on the image above.

**Comment by simik-ru** [comment]
See my pull request here: https://github.com/jeroennoten/Laravel-AdminLTE/pull/106/files

**Comment by mushroomgroover** [comment]
Thank you! @simik-ru
I also found out this was mentioned in #102
