### ISSUE TITLE
Creating separator in the Sidebar

### ISSUE THREAD

**Issue by joaquin-gs** [jeroennoten/Laravel-AdminLTE#1042]
Hi guys
This is not an issue nor a feature, but I didn't know where to ask for it.
If you take a look to the page:  https://adminlte.io/themes/v3/pages/widgets.html

You will see there a rounded picture and the name of "Alexander Pierce" with a horizontal separation line under it. The HTML code reveals a class = "user-panel" with an image and a <div> for info inside it.

How can I specify that, for the sidebar, in the config/adminlte.php file?

Cheers,

**Comment by Shidersz** [comment]
Hi @joaquin-gs , that is not supported by the package configuration. We use the [legacy user menu](https://adminlte.io/themes/v3/pages/examples/legacy-user-menu.html) in the case you have follow the installation of the authentication scaffolding.

However, you have the possibility to [publish](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) the package views that defines the layout and then edit the [left-sidebar](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/sidebar/left-sidebar.blade.php) blade layout to include your custom user menu.
