### ISSUE TITLE
Issue With Select 2 - Livewire

### ISSUE THREAD

**Issue by tmgomas** [jeroennoten/Laravel-AdminLTE#1049]
Hey  

When I Try to edit some Select2 Value its now showing Selected Value, Its Showing Placeholder value but value already selected and load to select2 component..

Here is My Blade Component

```
            @php
            $config = [
                "placeholder" => "Select  options...",
                "allowClear" => true,
            ];
            @endphp
            <div class="col-lg-12">
                <div wire:ignore>
                    <x-adminlte-select2 name="dist_pro_id"  id="dist_pro_id" wire:model.defer='dist_pro_id' :config="$config" label="Proovince" igroup-size="sm">
                        <option></option>
                        @foreach ($provinces as $province)
                            <option value="{{ $province->pro_id }}">{{ $province->pro_name_en }}</option>
                        @endforeach
                    </x-adminlte-select2>
                </div>
            </div> 
```

**Comment by Shidersz** [comment]
Please, add more details, maybe a video showing the issue you are facing. I'm still not sure why are you adding `livewire` directives to the `x-adminlte-select2` component. The components provided by this package are **Laravel components**, they extends from `Illuminate\View\Component`, not from `Livewire\Component`.

> When I Try to edit some Select2 Value...

What you mean with edit?
- The user choice a new value from the list?
- You use `javascript/jQuery` to change the value?

**Comment by Shidersz** [comment]
Closed, no feedback. Provide more information and reopen if still facing the problem...
