### ISSUE TITLE
[Question]: Starter guide?

### ISSUE THREAD

**Issue by raminhaghighitalab** [jeroennoten/Laravel-AdminLTE#1050]
I download the file but  i cant run it can you send me the command witch i have to do step by step because i tried the installation guide but it does not working?

**Comment by tmgomas** [comment]
Follow the Wiki Section

**Comment by Shidersz** [comment]
First of all, this package offers an integration of [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) for [Laravel](https://laravel.com/). So be sure to first understand the Laravel framework, or search on the `AdminLTE` site for integrations with other frameworks. Assuming, you want to integrate **AdminLTE** on **Laravel**, you may start at:

1) [Laravel installation](https://laravel.com/docs/8.x/installation) docs. I usually use the [install via composer](https://laravel.com/docs/8.x/installation#installation-via-composer)...
2) Read all the **basics documentation** for `Laravel`.
3) Once you are familiarized with `Laravel`, you may follow [the install guide for this package](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation).
4) Then read the [usage section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage) to create a basic page.
5) Finally, you can go deeper and read all the other wiki documentation (configurations, components, plugins, etc).

Be patience, it will be a long way if you are not familiarized with **Laravel**.
