### ISSUE TITLE
[question] is there any way to change the usermenu content

### ISSUE THREAD

**Issue by AMoktar** [jeroennoten/Laravel-AdminLTE#1051]
is there any way to display an icon instead of displaying the user name in the usermenu in the top navbar ?
this is for minizing the header as much as possible
Thanks

**Comment by Shidersz** [comment]
Yea, you can [publish the default package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and then edit the published views to add your customization. In your particular case, you will need to focus on:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/navbar/menu-item-dropdown-user-menu.blade.php

And change next code:

```blade
{{-- User menu toggler --}}
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
    @if(config('adminlte.usermenu_image'))
        <img src="{{ Auth::user()->adminlte_image() }}"
             class="user-image img-circle elevation-2"
             alt="{{ Auth::user()->name }}">
    @endif
    <span @if(config('adminlte.usermenu_image')) class="d-none d-md-inline" @endif>
        {{ Auth::user()->name }}
    </span>
</a>
```

to remove or change the `<span>` that shows the name...

**Comment by AMoktar** [comment]
Thanks @Shidersz you are awesome.
I really appreciate your help.
