### ISSUE TITLE
[FEATURE] Add custom markup to x-adminlte-card header

### ISSUE THREAD

**Issue by rightwayround** [jeroennoten/Laravel-AdminLTE#1052]
I know that there are option such as collapsible, removable & maximizable that can add html to the header of a card - but how would I go about adding custom html in there? A `<select>`, for example?

Thanks

**Comment by Shidersz** [comment]
There is no way, currently, to add extra markup on the header section using the component. You may, however:

1) Add an `id` attribute to the component and append extra markup using `Javascript/JQuery`.
2) Make your own custom copy of the component with an extra `headerSlot`. Read the [Laravel documentation about components](https://laravel.com/docs/8.x/blade#components) fi you do not have experience on how to work with they.

On the future we going to provide a way to publish the components, so once published, people can add their customizations...

**Comment by rightwayround** [comment]
Ok, will make a copy.

Thanks for a great package & continued dedication.

**Comment by Shidersz** [comment]
Thanks to you, I will keep this open to add it on a future release.

**Comment by rightwayround** [comment]
Thanks
