### ISSUE TITLE
[QUESTION] How to display the data to be edited in x-adminlte-text-editor

### ISSUE THREAD

**Issue by dirgareborn** [jeroennoten/Laravel-AdminLTE#1053]
### Screenshots
If applicable, add screenshots to help explain your problem or to shown the issue.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 
| Project | 
| OS      | 

### Additional context
Add any other context about the problem here. If you already have ideas to solve the issue, add them here or create a Pull Request (PR).

**Comment by Shidersz** [comment]
Closed, no feedback!
