### ISSUE TITLE
wire:model in file Input (Livewire)

### ISSUE THREAD

**Issue by desyashasyi** [jeroennoten/Laravel-AdminLTE#1054]
I have a modal as follow, in Livewire. However, after I click Import Button, the modal disappear, dan the web page is frozen. What is the problem?

```blade
<div>
    <x-adminlte-modal id="importSubject" title="Import Subject" size="md" theme="teal"
    icon="fas fa-subject" v-top static-backdrop>

        <div wire:ignore>
            <x-adminlte-input-file  id="subjectFile" name="subjectFile" label="Upload subject file"
            placeholder="Choose  files..." igroup-size="lg" legend="Choose" wire:model="fileSubject">
                <x-slot name="appendSlot">
                    <x-adminlte-button wire:click="importSubject" theme="primary" label="Import"/>
                </x-slot>
                <x-slot  name="prependSlot">
                    <div class="input-group-text text-primary">
                        <i class="fas fa-file-upload"></i>
                    </div>
                </x-slot>
            </x-adminlte-input-file>
        </div>
        <x-slot name="footerSlot">
            <x-adminlte-button theme="danger" label="Dismiss" data-dismiss="modal"/>
        </x-slot>
    </x-adminlte-modal>
</div>
```

**Comment by Shidersz** [comment]
The blade components provided by this package do not offer support to `Livewire`, they are **Laravel** components and they extends from `Illuminate\View\Component`, not from `Livewire\Component`.

For example, when you define:

```blade
<x-adminlte-button wire:click="importSubject" theme="primary" label="Import"/>
```

Livewire says that `wire:click` listens for a "click" event, and fires the "importSubject" method in the component.

But our **button component** do not provide that method, unless you have created a copy of our component and customized it to be a **Livewire component**. So, I recommend to check for errors on a browser's console tool.

**Comment by desyashasyi** [comment]
Thank you very much for the reply. I did not find any serious issue.

![image](https://user-images.githubusercontent.com/48233515/152734834-011236e4-4f3e-4453-98ba-b8d998b94ce9.png)

"But our button component do not provide that method, unless you have created a copy of our component and customized it to be a Livewire component. So, I recommend to check for errors on a browser's console tool."

Hot to make customisation?

**Comment by desyashasyi** [comment]
I solved the problem by putting wire:ignore.self at the modal config.

**Comment by Shidersz** [comment]
@desyashasyi Ok, nice to know you have solved it. However, I'm still curious on how you get the `wire:click` directive to work on the button...
