### ISSUE TITLE
Target class [JeroenNoten\LaravelAdminLte\Components\Widget\Card] does not exist.

### ISSUE THREAD

**Issue by rightwayround** [jeroennoten/Laravel-AdminLTE#1055]
### Describe the bug
Just done `composer u`, now receiving `Target class [JeroenNoten\LaravelAdminLte\Components\Widget\Card] does not exist.`

### Steps To Reproduce
1. `composer u`

### Expected behavior
Not to break

| Item    | Version
| ------- | -------
| Laravel | latest
| Project | JeroenNoten\LaravelAdminLte
| OS      | various

**Comment by Shidersz** [comment]
@rightwayround components classes where moved to `Views/Components` to follow the Laravel way... Probably you need to clear your application caches...

```sh
php artisan cache:clear
```

Maybe `view:clear` too!

**Comment by rightwayround** [comment]
`view:clear` solved it, thanks. Will remember that!
