### ISSUE TITLE
[FEATURE] In Laravel 9, publish languages from "resources/lang" to "lang"

### ISSUE THREAD

**Issue by gpibarra** [jeroennoten/Laravel-AdminLTE#1069]
See
https://laravel.com/docs/9.x/upgrade#the-lang-directory

**Comment by Shidersz** [comment]
@gpibarra Thanks for share the info!

**Comment by fatihdurmaz** [comment]
When will laravel 9 support come? @Shidersz

**Comment by Shidersz** [comment]
@fatihdurmaz Not really sure. I need to get some time to review the upgrade guide from **Laravel**, and check if we need to make any changes. You may try to install the package on a new fresh **Laravel 9.x** application to check and report issues...

**Comment by EvanSchleret** [comment]
I confirm the need. I wasted some 2 hours trying to figure out why my messages weren't showing haha. It would be great to make the modification for Laravel 9.

Regards
