### ISSUE TITLE
iCheck checkbox and radio not working

### ISSUE THREAD

**Issue by raulneis** [jeroennoten/Laravel-AdminLTE#107]
If I add a checkbox to the html:
```html
<input type="checkbox" />
```

And then in my script (at the end of the page):
```javascript
$('.input[type="checkbox"]').iCheck()
```

It hides the input element (which is correct), but does not show the iCheck.

**Comment by jeroennoten** [comment]
You should add the JavaScript and CSS yourself, the iCheck plugin is only loaded at the login page.

Add it like this:
```
@section('css')
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/plugins/iCheck/square/blue.css') }}">
@stop

@section('js')
    <script src="{{ asset('vendor/adminlte/plugins/iCheck/icheck.min.js') }}"></script>
    <script>
        $('.input[type="checkbox"]').iCheck()
    </script>
@stop
```

**Comment by cfmorales** [comment]
Hi jeroennoten I've done this but i have the same problem than raulneis, still not working

**Comment by zacka32** [comment]
not sav  to php
