### ISSUE TITLE
[QUESTION] Is there a way to use expandable tables properly?

### ISSUE THREAD

**Issue by throcha3** [jeroennoten/Laravel-AdminLTE#1070]
### Describe the solution you'd like
It's shown in the adminlte page the power of Expandable Tables, but it is not mentioned anything about it in this repo's wiki.
Is it possible to use it within the xblade component or we have to do using html?
![image](https://user-images.githubusercontent.com/19838710/154811824-2b33956c-6a18-4a4b-86b2-36743bd64280.png)

**Comment by Shidersz** [comment]
The [x-adminlte-datatable](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables) blade component works around the [Datatable](https://datatables.net/) plugin. This package do no offers any built-in component around that `expandable` tables. You will need to create the tables on your own, or design a new blade component around it to reuse on your application.

**Comment by throcha3** [comment]
Thanks!
