### ISSUE TITLE
[FEATURE] manage js manually - notifications

### ISSUE THREAD

**Issue by rightwayround** [jeroennoten/Laravel-AdminLTE#1071]
I would like to use my own js for notifications - I am enforcing CSP on my app and cannot use js that is in ordinary script tags on the page.

### Describe the solution you'd like
A flag to set "manage own js".

### Describe alternatives you've considered
Reimplementing notifications dynamically at page load

**Comment by Shidersz** [comment]
Please, add more details to help you understand your goal. However, remember you can always [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) to cover particular situations.

**Comment by rightwayround** [comment]
Sorry, I'm probably a bit too niche with my requirements - I've gone about it a different way.

Thanks
