### ISSUE TITLE
[BUG] Datatable doesn't work in Laravel 9

### ISSUE THREAD

**Issue by DanielMalmgren** [jeroennoten/Laravel-AdminLTE#1073]
### Describe the bug
When using the x-adminlte-datatable tag in Laravel 9 my app crashes.

I get Illuminate \ Contracts \ Container \ BindingResolutionException:
Target class [JeroenNoten\LaravelAdminLte\Components\Tool\Datatable] does not exist.

### Expected behavior
My table should appear.

### Environment

| Item    | Version
| ------- | -------
| Laravel | 9.1.0
| Project | 3.8.0
| OS      | Ubuntu 20.04
| PHP      | 8.1.2

**Comment by resslinger** [comment]
You use a wrong namespace.

Please use:
JeroenNoten\LaravelAdminLte\View\Components\Tool\Datatable

**Comment by DanielMalmgren** [comment]
Where do I change that? The only thing I've done is put the x-adminlte-datatable tag in my Blade template and it worked in Laravel 8, I've never put any namespace anywhere...

**Comment by DanielMalmgren** [comment]
Oh, sorry. Seems the problem was in my compiled views. A simple artisan view:clear solved the problem, everything's working now again!
