### ISSUE TITLE
[BUG]Cache problem when modify adminlte.php - Doesnt update in browser

### ISSUE THREAD

**Issue by Lukaum** [jeroennoten/Laravel-AdminLTE#1076]
Using with laravel 9 and php 8.1, whenever I make some modification inside adminlte.php, and refresh the browser all the modified datas has not updated.

So every modify needs to run in terminal, to work properly: >php artisan config:cache.

How can i fix this?

**Comment by fatihdurmaz** [comment]
I have that same problem. I think it is due to laravel 9.

**Comment by KostKostY1** [comment]
Try running > php artisan config:clear and dont run anything after that.

When you config:cache you cache the settings so when you reload you get the cached version. 
Use it once when you are done (or even better run php artisan optimize) to cache the whole application.

**Comment by resslinger** [comment]
It's normal to clear the config cache over console after a change in a config file.
