### ISSUE TITLE
How to add a custom top navbar menu item?

### ISSUE THREAD

**Issue by royallife88** [jeroennoten/Laravel-AdminLTE#1077]
How to add a custom top navbar menu item? I wanted to add a language selection dropdown in the top navbar with the full-screen widget. How can I do this? Any help?

**Comment by Shidersz** [comment]
@royallife88 Check issue https://github.com/jeroennoten/Laravel-AdminLTE/issues/981, it may help you!

**Comment by royallife88** [comment]
Thank you, It worked.
