### ISSUE TITLE
Summernote with livewire

### ISSUE THREAD

**Issue by tmgomas** [jeroennoten/Laravel-AdminLTE#1079]
I am Using Laravel 8 with livewire 2 My issue i am trying to update the things with livewire summer not showing old value ... i can insert date with summer not but not update that data.

**Comment by Shidersz** [comment]
Please, add more details with a minimal example code of your current implementation and a better explanation of your problem, with some screenshoots or a video maybe. It will be too hard to help you solve your issue from that short description...

Also, take into consideration this section should be used to report package's issues or improvements, and not to report problems with integrations with some other package, like Livewire. Thanks!

**Comment by Shidersz** [comment]
Closed, no feedback...
