### ISSUE TITLE
make:adminlte not working in new projects

### ISSUE THREAD

**Issue by javiersm79** [jeroennoten/Laravel-AdminLTE#108]
I make a new fresh Laravel Project y install via composer the package. But the command 

> **php artisan make:adminlte**

It's not working

**Comment by simik-ru** [comment]
See my pull request for the fix: https://github.com/jeroennoten/Laravel-AdminLTE/pull/106

**Comment by javiersm79** [comment]
Thnx @simik-ru .. I worked..

**Comment by jeroennoten** [comment]
Solved in v1.20.0!
