### ISSUE TITLE
Laravel livewire not working!

### ISSUE THREAD

**Issue by Soltee** [jeroennoten/Laravel-AdminLTE#1080]
| Question              |   Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 9.3.1
| Project Version         | ^3.8

### Problem

![Screenshot 2022-03-07 at 11-28-55 Books](https://user-images.githubusercontent.com/37467008/156975156-831944ea-3a6c-4c5b-beff-789d4456ae00.png)

Shows @livewireStyes and @livewireScripts text on the page.

**Comment by shankhadevpadam** [comment]
```php
php artisan optimize:clear
```

**Comment by Shidersz** [comment]
Have you installed `Livewire`? If yes, what version?

**Comment by Soltee** [comment]
@shankhadevpadam 
     I have published views files, so now it is working but Thank you.
@Shidersz   
     I have published views files, so now it is working  But, I have installed livewire version 2.10.

**Comment by Shidersz** [comment]
@Soltee If now is working, can we close this one?

**Comment by Soltee** [comment]
@Shildersz Yeah! Absolutely.
