### ISSUE TITLE
How to make Select2 with Search work in Livewire?

### ISSUE THREAD

**Issue by desyashasyi** [jeroennoten/Laravel-AdminLTE#1081]
Hi all,
I have implemented Select2 with Search in Livewire component. But it does not work. What is the problem.

The following is my code.

#### Component's Controller

```php
<?php

namespace Modules\ArSys\Http\Livewire\Option\Research;

use Livewire\Component;
use Modules\ArSys\Entities\ResearchType;

class Type extends Component
{
    public function render()
    {
        $config = [
            "placeholder" => "Select multiple options...",
            "allowClear" => true,
            "liveSearch" => true,
            "liveSearchPlaceholder" => "Search...",
        ];

        $researchType = ResearchType::all();
        
        return view('arsys::livewire.option.research.type', ['config' => $config, 'researchType' => $researchType]);
    }
}
```

#### Component's View
```blade
<div>
    
    <x-adminlte-select2 id="sel2Category" name="sel2Category" label="Categories"
        label-class="text-danger" igroup-size="sm" :config="$config">
        
        <x-slot name="appendSlot">
            <x-adminlte-button theme="outline-dark" label="Clear" icon="fas fa-lg fa-ban text-danger"/>
        </x-slot>

        @foreach ($researchType as $type)
            <option>{{$type->code}}-{{$type->description}}</option>
        @endforeach
    </x-adminlte-select2>
</div>
```

![image](https://user-images.githubusercontent.com/48233515/157155229-87340cb9-751c-4b19-abb2-45b3e4cbf264.png)

**Comment by Shidersz** [comment]
@desyashasyi There are no `liveSearch` option, neither `liveSearchPlaceholder` option for the **select2 plugin**. Always give a read to the plugin documentation: [Select2 Options](https://select2.org/configuration/options-api)

Also, take a look to this link: https://stackoverflow.com/questions/36188356/enable-select2-multi-select-search-box

> The answer is that the select2 input element becomes the search box for multiple selects without back end data

> if you start typing , your results will start filtering the options

> if you have it set to load remote ajax data, it actually does retain a search box, but for multiple selects without a data source, the input is the search bar, which is fairly intuitive

**Comment by Shidersz** [comment]
Closed because no feedback, reopen in case you need more help...
