### ISSUE TITLE
[QUESTION]: How to remove default menu from config file?

### ISSUE THREAD

**Issue by profesorapatriciafigueroa** [jeroennoten/Laravel-AdminLTE#1082]
I was creating a menu with subitems extracted from the database.

I was implemented the method EventServiceProvider , adding code at boot.

I need clean the previous menu, I don´t know how to remove it. 

I deleted the item menu from my config.adminlte but it continuos appears.

Thanks for your help
I was creating a menu with subitems extracted from the database.

I was implemented the method EventServiceProvider , adding code at boot.

I need clean the previous menu, I don´t know how to remove it. 

I deleted the item menu from my config.adminlte but it continuos appears.

Thanks for your help

**Comment by Shidersz** [comment]
Hi @profesorapatriciafigueroa , Probably you have cached the `Laravel` configuration files on the past...

Read next link for more details:
https://dev.to/kenfai/laravel-artisan-cache-commands-explained-41e1

So, you may try next command on your `Laravel` application root folder:
```sh
php artisan config:clear
```

**Comment by profesorapatriciafigueroa** [comment]
Hola Diego, Ya corri ese comando y nada :(

**Comment by Shidersz** [comment]
@profesorapatriciafigueroa Do not remove the `menu` configuration option from the `config/adminlte.php` file. If you do that, the `menu` config will fallback to the one available on the package, at `vendor/jeroennoten/laravel-adminlte/config/adminlte.php`. Just define the `menu` as an empty array:

```php
'menu' => [],
```

**Comment by Shidersz** [comment]
Closed because no feedback, reopen in case you need more help...
