### ISSUE TITLE
[BUG] Top navigation broken with mobile view

### ISSUE THREAD

**Issue by InfoO2** [jeroennoten/Laravel-AdminLTE#1084]
I created a fresh new laravel project with fresh adminlte, with just enable layout_topnav and layout_fixed_navbar in the config file, but it seems broken in mobile view as in picture
<img width="914" alt="Capture" src="https://user-images.githubusercontent.com/101692842/158524051-2ab40b30-1323-45d0-8e91-added760e1da.PNG">
.

**Comment by Shidersz** [comment]
Check the Wiki:

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#admin-panel-classes

You will need to also set `classes_topnav_nav` to `navbar-expand-md` or `navbar-expand-lg` when using top navigation layout.

**Comment by InfoO2** [comment]
I think some text should be added in layout_topnav to avoid another ticket open

**Comment by Shidersz** [comment]
@InfoO2 Yea, I will put some note on it later...
