### ISSUE TITLE
adminlte.php how to access config('app.locale')

### ISSUE THREAD

**Issue by fatihdurmaz** [jeroennoten/Laravel-AdminLTE#1085]
hello, how can I find which language is selected from within the adminlte.php file.

my code : 
$defaultLocale = config('app.locale');
but not working

**Comment by Shidersz** [comment]
Form what `adminlte.php` file you want to access the configuration? You can't access config from another config file, just the environment:

```php
$defaultLocale = env('APP_LOCALE', 'en');
```

Please, give more details...

**Comment by fatihdurmaz** [comment]
$defaultLocale = env('APP_LOCALE', 'en');
I can access with this method
but
$defaultLocale = config('app.locale');
I can't access this config method

**Comment by fatihdurmaz** [comment]
thank you so much.
My adminlte.php => `$appConfig = include(config_path('app.php'));`
and` $appConfig['locale'] `is working
