### ISSUE TITLE
[QUESTION] section height 100%

### ISSUE THREAD

**Issue by rightwayround** [jeroennoten/Laravel-AdminLTE#1086]
### Describe the question
I want to make a section height 100% but am failing

### Steps To Reproduce
I have attempted [this](https://stackoverflow.com/questions/42194886/how-to-make-the-row-stretch-remaining-height):

```html
@section('content_header')

    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Page title</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item active">Page title</li>
            </ol>
        </div>
    </div>

@stop


@section('content')
    <style>
        html,
        body {
            height: 100%;
        }

        .flex-fill {
            flex: 1;
        }

    </style>

    <div class="container-fluid d-flex h-100 flex-column">
        <!-- I want this container to stretch to the height of the parent -->
        <div class="row">
            <div class="col">
                <h5>Header</h5>
            </div>
        </div>
        <div class="row bg-light flex-fill d-flex justify-content-start">
            <!-- I want this row height to filled the remaining height -->
            <div class="col" style="background-color: grey">
                <!-- if row is not the right to stretch the remaining height, this column also fine -->
                Content
            </div>
        </div>
    </div>
@endsection

```
...  and various other methods don't have the desired results

| Item    | Version
| ------- | -------
| Laravel | 9
| OS      | valet

### Additional context
Any help appreciated, if there's a helper utility I am missing or something?

**Comment by rightwayround** [comment]
Only just seen this reply - thank you - I will have a go at getting this to work.

**Comment by rightwayround** [comment]
Yep that works exactly as expected, thanks again.

I didn't know of the `config()` function, can you direct me to any docs regarding it so I can educate myself further?

**Comment by Shidersz** [comment]
It is part of Laravel, see https://laravel.com/docs/9.x/configuration#accessing-configuration-values, I suggest you to give a fast read to **Laravel - The Basics** section too, it is a must before starting to work with the framework...

**Comment by rightwayround** [comment]
Ha, I must have skipped that chapter. Will read. Cheers
