### ISSUE TITLE
[QUESTION] Error view(page)

### ISSUE THREAD

**Issue by InfoO2** [jeroennoten/Laravel-AdminLTE#1087]
I couldn't find any error pages to publish, how to do it?
I checked the wiki page but i failed to find, please help

**Comment by resslinger** [comment]
There's no error page in this package. You can create own error pages, if you want.

**Comment by Shidersz** [comment]
You may check examples from the **AdminLTE** demo site:
https://adminlte.io/themes/v3/pages/examples/404.html
https://adminlte.io/themes/v3/pages/examples/500.html

The code is available on:
https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/examples/404.html
https://github.com/ColorlibHQ/AdminLTE/blob/master/pages/examples/500.html

Look at the inner markup on the `content-wrapper` element.
