### ISSUE TITLE
How use all colors in the theme palette of bootstrap?

### ISSUE THREAD

**Issue by NamJinn21** [jeroennoten/Laravel-AdminLTE#1089]
Hi, I'm trying to use the entire bootstrap color palette:
![image](https://user-images.githubusercontent.com/37020393/160474819-a8b50b5a-de12-4788-a95a-f9d87f2cecb1.png)

i created a button:
![image](https://user-images.githubusercontent.com/37020393/160475017-c1b54a83-ad76-47b9-8605-505b1cc9c7d5.png)
but this way the background color is not displayed
![image](https://user-images.githubusercontent.com/37020393/160475545-36f6a9b5-113a-438a-8847-081d74af629f.png)
How can I use these colors?

**Comment by Shidersz** [comment]
The available colors palette is the one supported on the underlying [AdminLTE 3 package](https://adminlte.io/themes/v3/pages/UI/general.html). That package is based on **Bootstrap 4**, and I believe the picture you attached is from **Bootstrap 5**.

Maybe @REJack  can give you more info about this...

**Comment by Shidersz** [comment]
Closed, this is not a package issue... You may create your own style sheet with extra colors in the worst case. Also, take a look at next link for more information:
https://stackoverflow.com/questions/39457166/how-to-extend-bootstrap-color-classes
