### ISSUE TITLE
menu header item bug

### ISSUE THREAD

**Issue by uprightc** [jeroennoten/Laravel-AdminLTE#109]
please add @elseif  in menuitem.blade.php
```
@if (is_string($item) )
    <li class="header">{{ $item }}</l i>
 @ elseif( isset($item['header']) )
    <li class="header">{{ $item['header'] }}</l i>
@else

```

**Comment by jeroennoten** [comment]
Hi! Could you make a PR for this? That would be awesome!

**Comment by jeroennoten** [comment]
BTW, I think this is not necessary anymore now. Because the menu builder now takes care of this (since version 1.20.0). So please update the package to the latest version.
