### ISSUE TITLE
How to specify custom error bag for errors

### ISSUE THREAD

**Issue by yungifez** [jeroennoten/Laravel-AdminLTE#1090]
Hi i'm looking for a way to specify custom error bags like that of jetstream for updating profile

**Comment by yungifez** [comment]
Jetstream uses an updateProfileInformatiom error bag for validation 
I can't display the errors due to this
The errors are not in the default error bag

**Comment by Shidersz** [comment]
Not sure how to help you. You should add details of what are you trying to do, we do not offer a profile view out of the box... Is your problem related to a [blade component](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Components-Categories)?
