### ISSUE TITLE
[BUG] Datatables with data from the database

### ISSUE THREAD

**Issue by luanpereira** [jeroennoten/Laravel-AdminLTE#1091]
### Describe the bug
About datatables, I made the example from the Wiki, but it doesn't work with data from the database. Does anyone have an example?

### Steps To Reproduce
![image](https://user-images.githubusercontent.com/1236217/163767043-871e0454-5160-4197-b13c-39066d0d9b3a.png)
![image](https://user-images.githubusercontent.com/1236217/163767134-d001e33b-5e5a-4334-8f7f-f369d00498a6.png)

| Item    | Version
| ------- | -------
| Laravel | 9.3
| Project |
| OS      | macos

**Comment by Shidersz** [comment]
@luanpereira Some observations:

- There is no need to use @`foreach` to create rows manually if you setup the `data` on the **config property**.
- The number of items specified on the `columns` option of the configuration must match the number of columns you are using on the `data`. If you do not need to specify any special configuration for a particular column, you can remove the `columns` array from con configuration.

**Comment by luanpereira** [comment]
Hi, @Shidersz, sure!

`paginateRequest()` is a abstraction, this method is encapsulated an implementation the `paginate`  from `Illuminate\Database\Eloquent Model::paginate`.

About your observations: I will go make the tests, thanks.

**Comment by Shidersz** [comment]
Closed, no feedback!
