### ISSUE TITLE
[BUG] Search input and entries selector vanishing

### ISSUE THREAD

**Issue by rogerlauermann** [jeroennoten/Laravel-AdminLTE#1092]
### Describe the bug
The search input and entries selector goes away when do something in page. Even when goes to create form and comes back, it goes away.

### Steps To Reproduce

![Screenshot from 2022-04-19 14-29-08](https://user-images.githubusercontent.com/56614166/164063424-92ca275f-8541-4a80-8b41-1228f3394608.jpg)

![Screenshot from 2022-04-19 14-29-14](https://user-images.githubusercontent.com/56614166/164063510-d2d3dcea-806e-49dd-8631-fba613093f9e.jpg)

| Item    | Version
| ------- | -------
| Laravel | 8.81.0
| Project | 
| OS      | Ubuntu 20.04

**Comment by Shidersz** [comment]
Please, share the code you are using to display the table (`controller` and `view`). I believe it may be a problem with your logic...

**Comment by rogerlauermann** [comment]
![Screenshot from 2022-04-19 18-19-43](https://user-images.githubusercontent.com/56614166/164104184-82f21cd7-4be8-4d15-98f5-b0249602dada.jpg)

![Screenshot from 2022-04-19 18-20-03](https://user-images.githubusercontent.com/56614166/164104217-eceb0386-7e89-4cf2-9bee-05d5b49e84fd.jpg)

In first time it works perfectly, after any action it stops.

**Comment by Shidersz** [comment]
The problem will be hard to track, since you have implemented it on top of `Livewire` and there is more code that you have not shared. You may check for errors on the browser's console tool. Also, I suggest to start with a minimal example of code until you get it working. In that case, you can share that minimal example here in order to get some help...

**Comment by rogerlauermann** [comment]
Thanks for the answer, I'll change my datatable component, i found PowerGrid, for now is working fine.
