### ISSUE TITLE
[BUG] Problem after install AdminLTE in Laravel 9

### ISSUE THREAD

**Issue by ngeoffroy** [jeroennoten/Laravel-AdminLTE#1095]
### Describe the bug
Hi everyone! I installed AdminLTE to my project in Laravel 9 guided by the instructions in the document, but when I check the admin lte status, the basic and main views are not installed, the same with the basic routes. I tried to update the composer adminlte and reinstall again with the php install and nothing. 

The result in the dashboard route is like a document html. Below I detach a photo.

I tried to rename the dashboard.blade from laravel to another, thought that could be the reason of the problem, but nothing, and i used the interactive and force installation but nothing too.

### Screenshots

Thats the view of the dashboard after installed admin lte
![image](https://user-images.githubusercontent.com/81689515/166150464-7966c9a9-687b-4fb7-98ac-4756d4a4d49b.png)

AdminLTE status
![image](https://user-images.githubusercontent.com/81689515/166150487-e0b39a53-b6ff-40b1-9cc6-e53014344ed8.png)

Messages after installed and update the composer admin LTE

![image](https://user-images.githubusercontent.com/81689515/166150509-d0234e38-12f5-476a-baf2-7bfd787609e8.png)

| Item    | Version
| ------- | -------
| Laravel | 9
| Project | 
| OS      | Windows 10

**Comment by Shidersz** [comment]
Hi @ngeoffroy, I see no problem on your installation procedure...

>but when I check the admin lte status, the basic and main views are not installed, the same with the basic routes

Check the `required` column, publishing the **basic views, main views, and routes** are not required to use the package, they are optionally installed in case you need to make some additional customization on that resource.

**Comment by Shidersz** [comment]
Closed, no feedback!
