### ISSUE TITLE
[FEATURE] remove opacity from style attribute

### ISSUE THREAD

**Issue by AngelicaGiraldo0908** [jeroennoten/Laravel-AdminLTE#1099]
### Is your request related to a problem? Please describe.
I need remove the style on the logo, in the adminlte config file, line 48 to 53, I don´t see any option for remove style.
the actual style is "opacity: .8;"

### Describe the solution you'd like
I want to set style like this "'logo_img_style= none" or 'logo_img_style' = null, or other value
![remove](https://user-images.githubusercontent.com/92491645/167271712-1d3a3f7a-c0ce-4a26-8550-f5349e24925d.png)

**Comment by Shidersz** [comment]
@AngelicaGiraldo0908 Currently you have at least two options to solve this:

1. [Publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) to customize they as you want.
2. Target the element from `CSS` to overwrite the opacity style. Or add a `class` in the configuration options that adds your extra customization (see `'logo_img_class'` option).

**Comment by dfsmania** [comment]
Closed, no feedback...
