### ISSUE TITLE
How to disable the default tree menu?

### ISSUE THREAD

**Issue by HKGeeks** [JeroenNoten/Laravel-AdminLTE#11]
I had deleted the config/adminlte.php menu section, but the default menu still in the page, and I found that it is loading vendor/jeroennoten/laravel-adminlte/config/adminlte.php config file, how can I disable the default menu, and run only AppServiceProvider runtime menu? Thanks.

**Comment by JeroenNoten** [comment]
You should not have deleted the config file. Publish the config file again and make the array that configures the menu empty.

    menu => []

**Comment by jltabbia** [comment]
How can I incorporate png images to the admin menu, thanks
