### ISSUE TITLE
Laravel 5.5 installation problem

### ISSUE THREAD

**Issue by njxqlus** [jeroennoten/Laravel-AdminLTE#110]
When trying to install `composer require jeroennoten/laravel-adminlte` on Laravel 5.5 I have the next problem:

```
Problem 1
    - Conclusion: don't install jeroennoten/laravel-adminlte v1.19.2
    - Conclusion: don't install jeroennoten/laravel-adminlte v1.19.1
    - Conclusion: remove laravel/framework 5.5.x-dev
    - Installation request for jeroennoten/laravel-adminlte ^1.19 -> satisfiable by jeroennoten/laravel-adminlte[v1.19.0, v1.19.1, v1.19.2].
    - Conclusion: don't install laravel/framework 5.5.x-dev
    - jeroennoten/laravel-adminlte v1.19.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev].
    - Can only install one of: laravel/framework[5.1.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.2.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.3.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.4.x-dev, 5.5.x-dev].
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].


Installation failed, reverting ./composer.json to its original content.
```

My part of composer.json:
```
"require": {
    "php": ">=7.0.0",
    "barryvdh/laravel-debugbar": "~3.0",
    "doctrine/dbal": "^2.6",
    "fideloper/proxy": "~3.3",
    "laravel/framework": "5.5.*",
    "laravel/tinker": "~1.0",
    "santigarcor/laratrust": "4.0.*"
  },
  "require-dev": {
    "barryvdh/laravel-ide-helper": "^2.4",
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~6.0"
  },
```

**Comment by jeroennoten** [comment]
Hey! Try it again, I just released a new version of this package with Laravel 5.5 support, so it should work now.

Please reopen this issue when you still have the same problem.

**Comment by Dach0** [comment]
Hi there, I have the same problem with Laravel 5.8 i guess.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install jeroennoten/laravel-adminlte v1.24.2
    - Conclusion: don't install jeroennoten/laravel-adminlte v1.24.1
    - Conclusion: remove laravel/framework v5.8.0
    - Installation request for jeroennoten/laravel-adminlte ^1.24 -> satisfiable by jeroennoten/laravel-adminlte[v1.24.0, v1.24.1, v1.24.2].
    - Conclusion: don't install laravel/framework v5.8.0
    - jeroennoten/laravel-adminlte v1.24.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.1.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.2.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.3.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.8.0].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.0].
    - Installation request for laravel/framework (locked at v5.8.0, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.0].


Installation failed, reverting ./composer.json to its original content.` 

Should I use Laravel < 5.8.0 or there is a workaround?

**Comment by Lucky-Loek** [comment]
See #282

**Comment by robertogallea** [comment]
I filed a pull request with the required modification to support laravel 5.8

**Comment by Marschtech** [comment]
I have the problem below to install the LTE package. Can someone help me?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeroennoten/laravel-adminlte ^2.0 -> satisfiable by jeroennoten/laravel-adminlte[v2.0.0].
    - jeroennoten/laravel-adminlte v2.0.0 requires laravel/framework ~6.0.0 -> satisfiable by laravel/framework[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by REJack** [comment]
You need to change ^2.0 to ^1.0 in your composer.jso, v2 is only for Laravel 6.0+.
