### ISSUE TITLE
Want the full installation: Please get me instruction.

### ISSUE THREAD

**Issue by AiFxApp** [jeroennoten/Laravel-AdminLTE#1102]
## Follow Here:

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation

## My steps:

1. `laravel new PROJECT_NAME`

2 . `composer require laravel/ui`

3. `php artisan ui bootstrap --auth`

4. `composer require jeroennoten/laravel-adminlte`

5. `php artisan adminlte:install --force`

6. `php artisan adminlte:status`

```php
Checking the resources installation ...
 7/7 [============================] 100%
All resources checked succesfully!

+------------------+------------------------------------------+---------------+----------+
| Package Resource | Description                              | Status        | Required |
+------------------+------------------------------------------+---------------+----------+
| assets           | The AdminLTE required assets             | Installed     | true     |
| config           | The default package configuration file   | Installed     | true     |
| translations     | The default package translations files   | Installed     | true     |
| main_views       | The default package main views           | Not Installed | false    |
| auth_views       | The default package authentication views | Mismatch      | false    |
| basic_views      | The default package basic views          | Mismatch      | false    |
| basic_routes     | The package routes                       | Not Installed | false    |
+------------------+------------------------------------------+---------------+----------+

Status legends:
+---------------+----------------------------------------------------------------------------------------------+
| Status        | Description                                                                                  |
+---------------+----------------------------------------------------------------------------------------------+
| Installed     | The resource is installed and matches with the default package resource                      |
| Mismatch      | The installed resource mismatch the package resource (update available or resource modified) |
| Not Installed | The package resource is not installed                                                        |
+---------------+----------------------------------------------------------------------------------------------+
---

* I would like to have this list complete before I move forward (ALL INSTALLED and no MIS-MATCH). 
* How do i complete this. please.

* I know I cant use the same commend to install / update plugins. 
* Is there a CMD to use or what is the best practice here?

**Comment by dfsmania** [comment]
@AiFxApp Please, read https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Artisan-Console-Commands to check how you may install additional resources. However, note you may not want to publish all the package resources (read carefully what each one provides). Usually, the required resources are enough to start, then you may publish the `auth_views` if you want to implement an authentication scaffolding, and the `main_views` if you want to make any customization on the blade views provided by the package.

**Comment by AiFxApp** [comment]
Progress Report: 
![image](https://user-images.githubusercontent.com/89227642/169574997-d5d475ee-0491-486a-8c5b-cec8eff998b8.png)

**Comment by AiFxApp** [comment]
Thanks - yeah, I wasn't sure if this was an error of a build and grow method. 
I will add as I go the features I need.

**Comment by dfsmania** [comment]
You are welcome!

- The `basic_views` is just a replacement for the `home.blade.php` file, with a very basic example that uses the package layout template.
- The `basic_routes` adds the authentication routes on the `routes/web.php` file, but this is already handled by the authentication scaffolding most of the time (it was just inherited from old package versions). It also adds a route to the home view, but that is just too basic that you can do it manually.

Sincerely, I never had to mess with these two package resources, they are somehow deprecated at this point.

**Comment by dfsmania** [comment]
No more feedback, considered solved!
