### ISSUE TITLE
[FEATURE] How to implement different UI  for Admin and User? 

### ISSUE THREAD

**Issue by aangrapei** [jeroennoten/Laravel-AdminLTE#1103]
In other case i want to use Admin LTE for two UI, for Admin and for User with Different Menu and Color, but in this template only one Layout. Can i use **config** to set for Two or more Color, nav or menu... ? Thank you

**Comment by dfsmania** [comment]
On Laravel, you may change [configuration](https://laravel.com/docs/9.x/helpers#method-config) at runtime. So, depending on the user that is authenticated you may use differents AdminLTE configuration. You may add the logic on the `boot()` method of the `app/Providers/AppServiceProvider.php` file, for example.

Also, check the closed issues for more information:

https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+is%3Aclosed+config+at+runtime

**Comment by dfsmania** [comment]
Closed, no feedback!
