### ISSUE TITLE
[FEATURE] set sidebar menu active by route name

### ISSUE THREAD

**Issue by donny26utama** [jeroennoten/Laravel-AdminLTE#1104]
I have to create a CRUD, your setting menu is something like this:

```
        [
            'text' => 'Product',
            'route' => 'product.index',
            'icon' => 'fas fa-box',
        ],
```
when I am on the `create` or `show` or `update` page..  sidebar menu `Product` is not active. I want when I am on all of the `product` routes, the sidebar `Product` to be active.

before I use this package, I usually use the wildcard route to set active. example like this:
```
<a class="sidebar-link" {{Route::is(['product.*']) ? 'active' : ''}}></a>
```

**Comment by dfsmania** [comment]
Hi @donny26utama , for these cases you may use the [Active Attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-active-attribute) of the menu configuration with a **wildcard** or a **regular expression**. Check the documentation on the wiki.

**Comment by dfsmania** [comment]
Closed, no feedback!
