### ISSUE TITLE
The sub menu is loaded open and doesn't collapse

### ISSUE THREAD

**Issue by ronlinet** [jeroennoten/Laravel-AdminLTE#1117]
I have updated to v3.8.2 and the now is the submenu loaded with all child items open. Clicking on the parent menu item doesn’t collapse anything. Regarding the menu array I am using the minimal [sub menu demo](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-submenu-attribute).  

My system is Laravel 6.0.4 with PHP 7.2

![image](https://user-images.githubusercontent.com/2538315/181353825-f6a2b194-7fdb-4792-961d-dffde687c375.png)

**Comment by REJack** [comment]
May you need to republish your views 😉

**Comment by dfsmania** [comment]
Please, check you have followed the instructions from [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating). Also use your browser's console, and attach any error you may see there...

**Comment by ronlinet** [comment]
Yes publish the views fix the issue. Bellow is the magic   
```
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets --force 
php artisan config:clear
php artisan cache:clear
php artisan config:cache
```
