### ISSUE TITLE
[QUESTION] How to Insert callbacks into summernote component?

### ISSUE THREAD

**Issue by xSirLalo** [jeroennoten/Laravel-AdminLTE#1118]
<html><body>

Question | Answer
-- | --
Laravel Version | 7.30.6

<h3 dir="auto">Question</h3>
<p dir="auto">My question is in the title<br>
The editor in question : <a href="https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Advanced-Forms-Components#texteditor" rel="nofollow">https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Advanced-Forms-Components#texteditor</a></p>

<p>Code that I need to put</p>

```
$('#summernote').summernote({
  callbacks: {
    onPaste(e) {
      const bufferText = ((e.originalEvent || e).clipboardData || window.clipboardData).getData('Text');
      e.preventDefault();
      document.execCommand('insertText', false, bufferText);
    }
  }
});
```

<p dir="auto">Thanks for your help !</p>
</body>
</html>

**Comment by dfsmania** [comment]
You can use the **plugin API**, for example:

```blade
<x-adminlte-text-editor name="myTextEditor"/>

@push('js')
<script>

    $(document).ready(function() {
        $('#myTextEditor').on('summernote.paste', function(e) {
            console.log('Called event paste!');
        });
    })

</script>
@endpush
```

**Comment by xSirLalo** [comment]
> You can use the **plugin API**, for example:
> 
> ```
> <x-adminlte-text-editor name="myTextEditor"/>
> 
> @push('js')
> <script>
> 
>     $(document).ready(function() {
>         $('#myTextEditor').on('summernote.paste', function(e) {
>             console.log('Called event paste!');
>         });
>     })
> 
> </script>
> @endpush
> ```


It worked for me a lot, thanks!
