### ISSUE TITLE
x-adminlte-select-bs not render as in documentation

### ISSUE THREAD

**Issue by AdeSupriyadi** [jeroennoten/Laravel-AdminLTE#1124]
I try example in documentation (copy-paste code), but the result not same with in documentation.

## select-bs + options
```
{{-- Example with multiple selections (for SelectBs) --}}
@php
    $config = [
        "title" => "Select multiple options...",
        "liveSearch" => true,
        "liveSearchPlaceholder" => "Search...",
        "showTick" => true,
        "actionsBox" => true,
    ];
@endphp
<x-adminlte-select-bs id="optionsCategory" name="optionsCategory[]" label="Categories"
    label-class="text-danger" :config="$config" multiple>
    <x-slot name="prependSlot">
        <div class="input-group-text bg-gradient-red">
            <i class="fas fa-tag"></i>
        </div>
    </x-slot>
    <x-adminlte-options :options="['News', 'Sports', 'Science', 'Games']"/>
</x-adminlte-select-bs>
```
result showing in documentation:
![image](https://user-images.githubusercontent.com/14267724/185730050-41ecb8bd-dd3b-42a1-80f7-76460804e89f.png)

result in my app
![image](https://user-images.githubusercontent.com/14267724/185730073-f10fd09f-2147-4bf4-93f5-9d01b34ca5b2.png)

How to make component rendered as in document screenshoot?

**Comment by AdeSupriyadi** [comment]
Oh no
its not installed via artisan command as shown here:
![image](https://user-images.githubusercontent.com/14267724/185730983-37bf0db4-afdd-4699-ba0a-f6e62fb61248.png)

then I download it manually. and work like charm

**Comment by dfsmania** [comment]
@AdeSupriyadi Yes, the plugin required for this component needs to be installed manually, as explained on the [documentation here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Advanced-Forms-Components#required-plugin-configuration-5)
