### ISSUE TITLE
Redraw DataTable

### ISSUE THREAD

**Issue by cucubelo** [jeroennoten/Laravel-AdminLTE#1127]
Hello, sorry for my English.

I am using livewire and when updating data the datatable does not redraw
![CONTROLLER](https://user-images.githubusercontent.com/30784561/186461500-254be040-48c7-4f70-abf4-2156d1d8cd18.png)
![html](https://user-images.githubusercontent.com/30784561/186461504-bd2170d0-84d1-4e5a-96a6-c146de2641b4.png)

**Comment by dfsmania** [comment]
Hi @cucubelo , I'm not really familiarized with `Livewire`. But I recommend to share a complete minimal example (maybe with dummy data), and to explain how do you expect the update (redraws) procedure should work. I may assume that the table should be updated every time you change the select input, but I'm not sure...

Also, share your code with [markdown code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), it will be more easy to copy and test the shared code...

**Comment by billyboy35** [comment]
Hi @cucubelo I'm not sure that the two work together, it's still some overlay of javascript. Do you have an error with the browser console ?

**Comment by cucubelo** [comment]
Hello, thank you very much for answering.
The expectation is that changing the select will redraw the table.

[Controller]
```
 private function ConfigDataTables(){
        
        $data =  [];

      
        $this->btnDetails = '<button class="btn btn-success btn-xs " title="Details"><i class="fa fa-lg fa-fw fa-eye"></i></button>';
        $this->btnDelete = '<button class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete"><i class="fa fa-lg fa-fw fa-trash"></i></button>';

        foreach ($this->list as  $value) {
            $data[] = [
                $value->id,
                $value->data1,
                $value->data2,
                $value->data3,
                $value->data4,
                $value->data5,
                $value->data6,
                '<span>'.$this->btnDetails.'</span>'
            ];
        } 
        

        $this->heads = [
            'ID',
            'Data1',
            'Data2',
            'Data3,
            'Data4',
            'Data5,
            'Data6,
            'Actions'
        ];

        $this->config['data']= $data;
        $this->config['destroy'] = true;
        
        

    }
```
[View]

```
<div  >

    <x-adminlte-select name="preventaCarton_select_id" id="preventaCarton_select_id" label="{{_('Preventa Carton')}}" wire:change='change' wire:model='preventaCarton_select_id' >
        <x-slot name="prependSlot">
            <div class="input-group-text">
                <i class="fa-solid fa-calendar-check"></i>
            </div>
        </x-slot>
    <option value="">{{_('Select option..')}}</option>
        @foreach ( $events  as $event)        
            
            <option value="{{$event->id}}" >{{$event->Data}}</option>
        @endforeach
    </x-adminlte-select>

    <x-adminlte-datatable id="dtTable" :heads='$heads' :config='$config'  wire:model='list'
    striped hoverable bordered comprossed class="text-center" head-theme="dark"  theme="light">
  
    
    @foreach ($config['data'] as $row )
        <tr>
            @foreach ($row as $cell )
                <td>{!! $cell !!}</td>
            @endforeach
        </tr>
    @endforeach

    </x-adminlte-datatable>

</div>
```


This way it works but only when initializing, then when changing the option it doesn't redraw


sorry for my English

**Comment by dfsmania** [comment]
@cucubelo First of all, the components provided by this package are not `Livewire` components, they are [blade components](https://laravel.com/docs/9.x/blade#components) and extends from a `Illuminate\View\Component`, not from `Livewire\Component`. I'm not 100% sure, but I believe you will need to create your own customized version of the components to use they with `Livewire`.

**Comment by dfsmania** [comment]
Closed, no more feedback!
