### ISSUE TITLE
Root composer.json requires laravel/ui 4.* -> satisfiable by laravel/ui[v4.0.0, v4.0.1, 4.x-dev].[BUG]

### ISSUE THREAD

**Issue by equipocorp26** [jeroennoten/Laravel-AdminLTE#1128]
Launch this error when i try run

**Comment by REJack** [comment]
It would be helpful, if you provide some steps to reproduce, infos about your laravel installation (you can use for this `artisan about`) and important the installed version number of laravel-adminlte.

**Comment by dfsmania** [comment]
Closed, no feedback provided!
