### ISSUE TITLE
[ENHANCEMENT] Update Installation documentation

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#1129]
I'm following the [Installation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation) documentation, and I noticed that in step 2, it states that after the `php artisan adminlte:install` command, it installs translations into the `resources/lang/vendor/adminlte/` folder. However, upon review, it is installing in `~/lang/vendor/adminlte/` folder.

This change was based on issue #1069 .

**Comment by dfsmania** [comment]
@PiousVenom Thanks, done!
