### ISSUE TITLE
[QUESTION] Help understanding the login routes and auth pages

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#1130]
I am starting a new project (Project B) using Laravel 9 and Laravel-AdminLTE 3.8.4. In a previous project (Project A), I used Laravel 8 and Laravel-AdminLTE 3.6, I'm noticing a couple of differences that I'm not sure how to explain. The biggest is that for some reason, in Project A, I have a folder `resources/views/vendor/adminlte`, which looks to be published views. I can't seem to find the command to make that happen in Project B. Also, in my `routes/web.php` of Project A, I don't have a defined `login` route, yet it works. In Project B, this doesn't work at all unless I define it. Am I missing something in how this works?

**Comment by PiousVenom** [comment]
> For login to work, you need to install an authentication scaffolding (step 3 of the [installation procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation)). I do not remember if the authentication routes are installed within the previous scaffolding installation, but I usually add the sentence `Auth::routes();` at the top of the `routes/web.php` file if it do not exists, and then I define all other routes within a group with the authentication middleware, something like next:

Thanks for your reply!

Whenever I run the command to require `laravel/ui`, when I go to `localhost/login`, I get an exception `Vite manifest not found`. I haven't run npm commands, as I wasn't planning on using it in my project. Is there a way to disable this like we do with Mix?

**Comment by dfsmania** [comment]
I'm not sure, since I haven't installed this package with `Laravel 9` yet, maybe someone can help...

**Comment by ASertacAkkaya** [comment]
You have to run `npm install` and `npm run dev` if you're installing laravel/ui. Check here for more: https://github.com/laravel/ui
