### ISSUE TITLE
[BUG] Rendering blade components (select2) via AJAX doesn't initiate @push('js')

### ISSUE THREAD

**Issue by kname97** [jeroennoten/Laravel-AdminLTE#1131]
Rendering blade components (select2) via AJAX doesn't initiate @push('js')

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/53926205/192160235-69579b72-575c-4db6-8174-c3e15479a2f4.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/53926205/192160253-a5f4fab8-e8dd-402b-b3c9-b680dc5571ab.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/53926205/192160265-af356bcc-4ec9-4386-b625-c9ff41e4444f.png">

**Comment by dfsmania** [comment]
@kname97 Please, provide a minimal example of code that reproduces the issue.

**Comment by kname97** [comment]
my view 
![image](https://user-images.githubusercontent.com/53926205/192294473-130747f6-9f16-44aa-990e-e061ef02ad1f.png)

**Comment by kname97** [comment]
I found solution for my error.

I insert `@stack('js')` in the bottom of view like this and it works perfectly.
![image](https://user-images.githubusercontent.com/53926205/192319235-3dea91da-bdfd-4d2a-a34c-f8f0f84ee7d8.png)
