### ISSUE TITLE
[QUESTION] How to fill data via ajax?

### ISSUE THREAD

**Issue by xSirLalo** [jeroennoten/Laravel-AdminLTE#1136]
I want to use the Select2 component of AdminLTE, filling the data by AJAX.
![image](https://user-images.githubusercontent.com/32373378/197848727-2bdde2cd-a480-47a5-aeba-0d3717c5f5e0.png)

**Comment by dfsmania** [comment]
@xSirLalo I don't think the component is able to support that advanced usage. But, you could try destroying and then initializing the target element again, example:

```js
$('#tags').select2('destroy');
$('#tags').select2({
    placeholder: 'Seleccione una o más etiquetas...',
    allowClear: true,
    tags: true,
    /* all your other config ... */
});
```

**Comment by xSirLalo** [comment]
My only solution was to use plain HTML and JQUERY, Thank you.
![image](https://user-images.githubusercontent.com/32373378/197874160-8d61aaa6-09e0-462a-9cd7-f00154a80e6a.png)

![image](https://user-images.githubusercontent.com/32373378/197874189-d06228ce-a5ae-4d0e-bf5e-841d8d6228c4.png)
