### ISSUE TITLE
Undefined constant "JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper"[BUG]

### ISSUE THREAD

**Issue by DavitMnacakanyan** [jeroennoten/Laravel-AdminLTE#1137]
![image](https://user-images.githubusercontent.com/46101387/197854100-84d3e8b1-eb8b-417d-a9ee-7cd52e41e0fb.png)

Laravel 9 Supported ?

**Comment by dfsmania** [comment]
@DavitMnacakanyan Based on the shared image, it appears that you have published the package view files some time ago, but you haven't updated it to the latest version. Please, try to follow the [update procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating)

**Comment by DavitMnacakanyan** [comment]
Thank You
