### ISSUE TITLE
[BUG] Al utilizar el nuevo CDN de sweetalert2

### ISSUE THREAD

**Issue by F3l1x2301** [jeroennoten/Laravel-AdminLTE#1138]
### Steps To Reproduce
1. Go to admintle.php
2. En la parte de lplugins
3. En el item Sweetalert2

### Expected behavior
Esperaba que el CDN estuviera actulizado con el actual. 

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel |  9
| Project |  Click_voto

**Comment by dfsmania** [comment]
The plugins configuration that comes with the package is just an example, to show how it can be used...

**Comment by F3l1x2301** [comment]
Ha entiendo, perfecto. La idea sería entonces ir haciendo las modificaciones en las configuraciones de acuerdo a los requerimientos que se vayan teniendo. Ok. 
Gracias. Bendiciones.

**Comment by dfsmania** [comment]
Yea, the config comes with a predefined example of options, but you may change it as you want. For the plugins, I usually installs all the plugins files I need inside the `public/vendor` folder and then I setup the configuration to point to these files. Refer to [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration). At next I share an example of the config I use most of the time:

```php
    'plugins' => [
        'BootstrapSelect' => [
            'active' => false,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => 'vendor/bootstrap-select/js/bootstrap-select.min.js',
                ],
                [
                    'type' => 'css',
                    'asset' => true,
                    'location' => 'vendor/bootstrap-select/css/bootstrap-select.min.css',
                ],
            ],
        ],
        'BootstrapSwitch' => [
            'active' => false,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => 'vendor/bootstrap-switch/js/bootstrap-switch.min.js',
                ],
            ],
        ],
        ...
    ]
```
