### ISSUE TITLE
[FEATURE]: Auto show right sidebar when section is present

### ISSUE THREAD

**Issue by atulmahankal** [jeroennoten/Laravel-AdminLTE#1140]
### Describe the bug
The `'right_sidebar' => false` option may be used to enable the right sidebar on all pages.

### Expected behavior
It may be auto, if `@section('right-sidebar)` is present on a blade view extending the layout.

**Comment by dfsmania** [comment]
This may be a good change for a future major version, however changing this right now may lead to backward compatibility problems...
