### ISSUE TITLE
[QUESTION]: How to set active class on link when redirect to another page?

### ISSUE THREAD

**Issue by arthororamada** [jeroennoten/Laravel-AdminLTE#1141]
How To Set/Keep 'active' class (SIDEBAR) on link or li when redirect to another page?

Dashboard (Side Bar)

the default url is /dashboard 

then I want to retain the active status of the dashboard (sidebar) if i click the new page  (/dashboard/list/details).

Thank you!

**Comment by arthororamada** [comment]
Thank youu @dfsmania

**Comment by dfsmania** [comment]
Your welcome! Is the problem solved? Can we close the issue?
