### ISSUE TITLE
[BUG] livewire wire: click not working 

### ISSUE THREAD

**Issue by valgwapo123** [jeroennoten/Laravel-AdminLTE#1142]
Livewire wire:click not working in laravel version 9.39.0

**Comment by dfsmania** [comment]
Please, add more details, maybe a minimal example using the package that can reproduce the issue. Have you already enable [Livewire Support](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration#livewire)?

**Comment by dfsmania** [comment]
Closed, no details...
