### ISSUE TITLE
Two Select2 Elements in One Page

### ISSUE THREAD

**Issue by desyashasyi** [jeroennoten/Laravel-AdminLTE#1144]
I added two elements on one page, but the result was unexpected. What is the problem?
The first selectr2  (first image) worked, but the last did not.

![Screen Shot 2022-11-18 at 01 37 36](https://user-images.githubusercontent.com/48233515/202530340-18310045-9bc4-4dba-8c86-29cfb6d1e8c9.png)
![Screen Shot 2022-11-18 at 01 37 44](https://user-images.githubusercontent.com/48233515/202530328-b667a605-27ee-4cd3-bc3b-f8cd15a74994.png)

```blade
<div>
    <div class="row">
        <div class="col-md-5">
            <div wire:ignore>
                <x-adminlte-select2 data-select2-id="program" id="program" wire:model="program" name="data-select2-id" >
                    @foreach ($programs as $index => $program)
                        <option value="{{$program->id}}">{{++$index}}. {{$program->description}}</option>
                    @endforeach
                </x-adminlte-select2>
            </div>
                
        </div>
        @if($specializations != null)
            <div class="col-md-5">
                <div wire:ignore.self>
                    <x-adminlte-select2 data-select2-id="specialization" id="specialization" wire:model="specialization" name="specialization" >
                        @foreach ($specializations as $index => $specialization)
                            <option value="{{$specialization->data->id}}">{{++$index}}. {{$specialization->data->description}}</option>
                        @endforeach
                    </x-adminlte-select2>
                </div>
            </div>
        @endif
    </div>
    @push('scripts')
        <script>
            $(document).ready(function () {
                $('#program').select2();
                            $('#program').on('change', function (e) {
                                let program = $(this).val();
                                @this.set('program', program);
                            });
                         
                            $('#specialization').select2();
                            $('#specialization').on('change', function (e) {
                                let specialization = $(this).val();
                                @this.set('specialization', specialization);
                            });
                        });  
        </script>
    @endpush
</div>
```

**Comment by dfsmania** [comment]
```blade
@push('scripts')
        <script>
            $(document).ready(function () {
                $('#program').select2();
                            $('#program').on('change', function (e) {
                                let program = $(this).val();
                                @this.set('program', program);
                            });
                         
                            $('#specialization').select2();
                            $('#specialization').on('change', function (e) {
                                let specialization = $(this).val();
                                @this.set('specialization', specialization);
                            });
                        });  
        </script>
    @endpush
```

Have you checked your **browser's console** for errors?

Whats is `@this.set('specialization', specialization);` ??? Should not be `$this.set('specialization', specialization);` instead ???

**Comment by desyashasyi** [comment]
There is no error in the developer console.  I changed Javascript to this, but the unexpected appearance still occurred.

@push('scripts')
        <script>
            $(document).ready(function () {
                $('#program').select2();
                            $('#program').on('change', function (e) {
                                let data = $(this).val();
                                @this.set('program', data);
                            });
                         
                            $('#specialization').select2();
                            $('#specialization').on('change', function (e) {
                                let data2 = $(this).val();
                                @this.set('specialization', data2);
                            });
                        });  
        </script>
    @endpush

https://user-images.githubusercontent.com/48233515/202631093-625c033d-5633-40a4-8a79-548faf15a074.mp4



However, actual data from the select2 component can be saved via the livewire:model without a problem.

**Comment by dfsmania** [comment]
is `@this` a reference to the `livewire` component?

Try without calling `$('#program').select2()` and `$('#specialization').select2();` since the plugin initialization is doing inside the blade component you are using, see next for reference:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/components/form/select2.blade.php

**Comment by desyashasyi** [comment]
> https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/components/form/select2.blade.php

I have tried to modify the code as per your recommendation. But it still failed to work properly. The problem is related to dynamic loading of select2 options.  Is there any example of using select2 for dynamic loading?

**Comment by dfsmania** [comment]
@desyashasyi I did not say you have to modify the component's code.

I say, you can't re-initialize the `select2` component from your `JS` code (next block), since it is already initialized inside the component's code. So, try with next change:

```blade
@push('scripts')
    <script>
        $(document).ready(function () {
            //$('#program').select2();
            $('#program').on('change', function (e) {
                let data = $(this).val();
                @this.set('program', data);
            });
                         
            //$('#specialization').select2();
            $('#specialization').on('change', function (e) {
                let data2 = $(this).val();
                @this.set('specialization', data2);
            });
        });  
    </script>
@endpush
```

If you want to re-initialize the `select2` component that was already initialized by the underlying component, then you will need to [destroy](https://select2.org/programmatic-control/methods#destroying-the-select2-control) it first, as indicated on the link.

**Comment by desyashasyi** [comment]
Hi @dfsmania, thank you for the explanation. However, I could not understand how to destroy the initiation. 
My select2 purpose is adding three components of seect2. The two last components (Label Program of Study and Supervisor are dependent on the first select2 component(label Program of Study). As you can see from the video, with the current code, I could get the function of select2 components properly. However, there is still some problem that occurs. The form page flickers when I click the select2 component. another problem is when I click one of two dependent components. The placeholder is gone. what is your recommendation?

![image](https://user-images.githubusercontent.com/48233515/206133531-2f226685-255e-4008-b822-0aab084c445e.png)


https://user-images.githubusercontent.com/48233515/206134307-d6d2473c-2b93-48f3-9841-8b4181881d1c.mp4



Livewire Component

`<?php

namespace App\Http\Livewire\Arsys\Components\Dropdown;

use Livewire\Component;
use App\Models\ArSys\StudyProgram;
use App\Models\ArSys\StudySpecializationPivot;
use App\Models\ArSys\Staff;
class ProfileStudent extends Component
{
    public $program;
    public $specialization;
    public $department;
    public $faculty;

    public $programs;
    public $specializations;

    public $staff;
    public $staffs;

    public $selectedProgram = NULL;
    public $listeners = ['selectProgram', 'selectSpecialization', 'selectStaff'];
    public function render()
    {
        return view('livewire.arsys.components.dropdown.profile-student');
    }
    public function mount(){
        $this->programs = StudyProgram::all();
        $this->specializations = collect();
        $this->staffs = collect();
    }

    public function selectProgram($program){
        $this->selectedProgram = $program;
        if (!is_null($program)) {
            $this->specializations = StudySpecializationPivot::where('program_id', $this->program)->get();
            $this->staffs = Staff::where('program_id', $this->program)->get();
            $this->department = StudyProgram::where('id', $program)->first()->department->abbrev.'-'.
                                StudyProgram::where('id', $program)->first()->department->description;
            $this->faculty = StudyProgram::where('id', $program)->first()->department->faculty->abbrev.'-'.
                             StudyProgram::where('id', $program)->first()->department->faculty->description;
        }
        //$this->specialization = null;
        //$this->emit('reloadSelectSpecialization');
        //$this->emit('reloadSelectStaff');
        $this->emit('setProgram_UserProfileCreateFormStudent', ['program' => $this->program]);
    }

    public function selectSpecialization(){
        $this->emit('setSpecialization_UserProfileCreateFormStudent', ['specialization' => $this->specialization]);
    }
    
    public function selectStaff(){
        $this->emit('setSupervisor_UserProfileCreateFormStudent', ['supervisor' => $this->staff]);
    }

    public function hydrate()
    {
        $this->emit('reloadSelectSpecialization');
        $this->emit('reloadSelectStaff');
    }
}
`

Livewire Blade
`<div>
    @section('plugins.Select2', true)
    <div class="row">
        <div class="col-md-6">
            <x-adminlte-input placeholder="Not defined" wire:model="faculty" name="faculty" label="Faculty" style="width: 100%" disabled/>
        </div>
        <div class="col-md-6">
            <x-adminlte-input placeholder="Not defined" wire:model="department" name="department" label="Department" style="width: 100%" disabled/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5" wire:ignore>
            @if (!is_null($programs))
                <x-adminlte-select2 label="Program of study" style="width: 100%" id="program" name="prog">
                    <option default>Please select your program of study</option>
                    @foreach ($programs as $index => $program)
                        <option value="{{$program->id}}"><b>{{$program->code}}</b>-{{$program->description}}</option>
                    @endforeach
                </x-adminlte-select2>
            @endif
        </div>
        <div class="col-md-5">
            <x-adminlte-select2 label="Specialization" style="width: 100%" wire:model="specialization" id="specialization" name="spec">
                <option default>Please select your specialization</option>
                @foreach ($specializations as $index => $specialization)
                    <option value="{{$specialization->id}}"><b>{{$specialization->data->abbrev}}</b>-{{$specialization->data->description}}</option>
                @endforeach
            </x-adminlte-select2>
        </div>  
    </div>
    <div class="row">
        <div class="col-md-6">
            <x-adminlte-select2 label="Supervisor" style="width: 100%" wire:model="staff" id="staff" name="prog">
                <option default>Please select your supervisor</option>
                @foreach ($staffs as $index => $staff)
                    <option value="{{$staff->id}}">{{$staff->first_name}} {{$staff->last_name}} {{$staff->front_title}}, {{$staff->rear_title}}</option>
                @endforeach
            </x-adminlte-select2>
        </div>
    </div>  
    

    @push('scripts')
    <script>
        //var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        $(document).ready(function () {
            $('#program').on('change', function (e) {
                let dataProgram = $(this).val();
                @this.set('program', dataProgram);
                console.log('here');
                window.livewire.emit('selectProgram', { program : dataProgram });
            });
           
            $('#specialization').on('change', function (e) {
                let dataSpecialization = $(this).val();
                @this.set('specialization', dataSpecialization);
                window.livewire.emit('selectSpecialization', { specialization : dataSpecialization });
                //console.log('here');
            });
            $('#staff').on('change', function (e) {
                let dataStaff = $(this).val();
                @this.set('staff', dataStaff);
                window.livewire.emit('selectStaff', { staff : dataStaff });
                //console.log('here');
            });

            window.livewire.on('reloadSelectSpecialization',()=>{
                 $('#specialization').select2();
            });
            window.livewire.on('reloadSelectStaff',()=>{
                $('#staff').select2();
            });

        });
    </script>
@endpush
</div>
`

**Comment by desyashasyi** [comment]
This is the final solution to my select2 problem.

expected page components

![image](https://user-images.githubusercontent.com/48233515/207197100-fdd75d42-7866-4b5e-ad35-9f0b7d321ed5.png)

Dropdowns 2 & 3 depending on dropdown 1.

The controller code:
`<?php

namespace App\Http\Livewire\Arsys\User\Profile\Create;

use Livewire\Component;
use App\Models\ArSys\Student;
use App\Models\ArSys\StudyProgram;
use App\Models\ArSys\StudySpecializationPivot;
use App\Models\ArSys\Staff;
use Auth;
use Jantinnerezo\LivewireAlert\LivewireAlert;
class Students extends Component
{
    use LivewireAlert;
    public $program;
    public $specialization;
    Public $supervisor;
    public $studentNumber;
    public $phoneNumber;
    public $email;
    public $firstName;
    public $lastName;

    public $faculty;
    public $department;

    public $programs;
    public $specializations;
    public $staffs;
    public $listeners = ['setProgram_UserProfileCreateFormStudent', 
                        'setSupervisor_UserProfileCreateFormStudent',
                        'setSpecialization_UserProfileCreateFormStudent'];
    public function render()
    {
        if (!is_null($this->program)) {
            $this->specializations = StudySpecializationPivot::where('program_id', $this->program)->get();
            $this->staffs = Staff::where('program_id', $this->program)->get();
            $this->department = StudyProgram::where('id', $this->program)->first()->department->abbrev.'-'.
                                StudyProgram::where('id', $this->program)->first()->department->description;
            $this->faculty = StudyProgram::where('id', $this->program)->first()->department->faculty->abbrev.'-'.
                             StudyProgram::where('id', $this->program)->first()->department->faculty->description;
        }
        return view('livewire.arsys.user.profile.create.students');
    }

    public function mount(){
        $this->programs = StudyProgram::all();
        $this->specializations = collect();
        $this->staffs = collect();
    }

    public function hydrate()
    {
        $this->emit('reloadSelectSpecialization');
        $this->emit('reloadSelectStaff');
        $this->emit('reloadSelectProgram');
    }

    public function resetForm(){
        $this->resetErrorBag();
        $this->resetValidation();
    }
    public function setProgram_UserProfileCreateFormStudent($program){
       $this->program = $program;
       $this->resetForm();
    }   
    public function setSpecialization_UserProfileCreateFormStudent($specialization){
        $this->specialization = $specialization;
        $this->resetForm();
    }   
    public function setSupervisor_UserProfileCreateFormStudent($supervisor){
        $this->supervisor = $supervisor;
        $this->resetForm();
    }   

    protected $rules = [
        'program' => 'required',
        'specialization' => 'required',
        'supervisor' => 'required',
        'studentNumber' => 'required|max:7',
        'phoneNumber' => 'required',
        'email' => 'required|email',
        'firstName' => 'required',
        'lastName' => 'required',
    ];
    protected $messages = [
            'program.required' => 'The Program of Study is required',
            'email.required' => 'The Email Address cannot be empty.',
    ];

    public function save(){
        $this->validate();
        if(is_null(Student::where('code', Auth::user()->sso)->first())){
            if(is_null($this->specialization))
                $specialization = null;
            else
                $specialization = $this->specialization;
            Student::create([
                'user_id' => Auth::user()->id,
                'program_id' => $this->program,
                'specialization_id' => $specialization,
                'supervisor_id' => $this->supervisor,
                'student_number' => $this->studentNumber,
                'code' => Auth::user()->sso,
                'first_name' => $this->firstName,
                'last_name' => $this->lastName,
                'email' => $this->email,
                'phone' => $this->phoneNumber,
            ]);
            $this->alert('success', 'The profile has been recorded');
            return redirect()->route('arsys.user.profile.view');
        }else{
            $this->alert('warning', 'The profile is already in database');
            return redirect()->route('arsys.user.profile.view');
        }
    }
}
`

Blade code

`<div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <x-adminlte-input placeholder="Not defined" wire:model="faculty" name="faculty" label="Faculty" style="width: 100%" disabled/>
                </div>
                <div class="col-md-6">
                    <x-adminlte-input placeholder="Not defined" wire:model="department" name="department" label="Department" style="width: 100%" disabled/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <x-adminlte-select2 label="Program of study" style="width: 100%" wire:model="program" id="program" name="program">
                        <option default>Please select your program of study</option>
                        @foreach ($programs as $index => $program)
                            <option value="{{$program->id}}"><b>{{$program->code}}</b>-{{$program->description}}</option>
                        @endforeach
                        @error('program') <span class="text-danger">{{ $message }}</span><br> @enderror
                    </x-adminlte-select2>

                </div>  
                <div class="col-md-5">
                    <x-adminlte-select2 label="Specialization" style="width: 100%" wire:model="specialization" id="specialization" name="specialization">
                        <option default>Please select your specialization</option>
                        @foreach ($specializations as $index => $specialization)
                            <option value="{{$specialization->id}}"><b>{{$specialization->data->abbrev}}</b>-{{$specialization->data->description}}</option>
                        @endforeach
                        @error('specialization') <span class="text-danger">{{ $message }}</span><br> @enderror
                    </x-adminlte-select2>
                </div>  
            </div>
            <div class="row">
                <div class="col-md-6">
                    <x-adminlte-select2 label="Supervisor" style="width: 100%" wire:model="supervisor" id="staff" name="supervisor">
                        <option default>Please select your supervisor</option>
                        @foreach ($staffs as $index => $staff)
                            <option value="{{$staff->id}}">{{$staff->first_name}} {{$staff->last_name}} {{$staff->front_title}}, {{$staff->rear_title}}</option>
                        @endforeach
                        @error('supervisor') <span class="text-danger">{{ $message }}</span><br> @enderror
                    </x-adminlte-select2>
                </div>
            </div>  
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <x-adminlte-input type="number" placeholder="Student number" wire:model="studentNumber" name="studentNumber" label="Student number" style="width: 100%"/>
            @error('studentNumber') <span class="text-danger">{{ $message }}</span><br> @enderror
        </div>
        <div class="col-md-3">
            <x-adminlte-input name="phoneNumber" wire:model="phoneNumber" label="Phone number" type="number" style="width: 100%"/>
            @error('phoneNumber') <span class="text-danger">{{ $message }}</span><br> @enderror
        </div>
        <div class="col-md-4" >
            <x-adminlte-input name="email" wire:model="email" type="email" label="email" style="width: 100%"/>
            @error('email') <span class="text-danger">{{ $message }}</span><br> @enderror
        </div>     
    </div>
    <div class="row">
        <div class="col-md-4">
            <x-adminlte-input wire:model="firstName" name="firstName" label="First name" style="width: 100%"/>
            @error('firstName') <span class="text-danger">{{ $message }}</span><br> @enderror
        </div>
        <div class="col-md-5" >
            <x-adminlte-input wire:model="lastName" name="lastName" label="Last name" style="width: 100%"/>
            @error('lastName') <span class="text-danger">{{ $message }}</span><br> @enderror
        </div>     
    </div>
    <x-adminlte-button theme="success" class="btn btn-sm" icon="fa fa-save" wire:click="save" label="Save"/>
    @push('scripts')
        <script>
            //var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
            $(document).ready(function () {
                $('#program').on('change', function (e) {
                    let dataProgram = $(this).val();
                    @this.set('program', dataProgram);
                    //console.log('here');
                    //window.livewire.emit('selectProgram');
                });
            
                $('#specialization').on('change', function (e) {
                    let dataSpecialization = $(this).val();
                    @this.set('specialization', dataSpecialization);
                    //window.livewire.emit('selectSpecialization');
                    //console.log('here');
                });
                $('#staff').on('change', function (e) {
                    let dataStaff = $(this).val();
                    @this.set('supervisor', dataStaff);
                    //window.livewire.emit('selectStaff');
                    //console.log('here');
                });

                window.livewire.on('reloadSelectSpecialization',()=>{
                    $('#specialization').select2('destroy');
                    $('#specialization').select2();
                });
                window.livewire.on('reloadSelectStaff',()=>{
                    $('#staff').select2('destroy');
                    $('#staff').select2();
                });
                window.livewire.on('reloadSelectProgram',()=>{
                    $('#program').select2('destroy');
                    $('#program').select2();
                });

            });
        </script>
    @endpush
</div>`
