### ISSUE TITLE
How can I organize the side menu by user type 

### ISSUE THREAD

**Issue by Betuntun** [jeroennoten/Laravel-AdminLTE#1148]
How can I organize the side menu by user (user type) example

admin can see everything but lower level users only some things
![image](https://user-images.githubusercontent.com/36393621/204362927-a190470e-f74e-4929-a227-c9e5b21defcd.png)

**Comment by dfsmania** [comment]
Hi @Betuntun , with **Laravel's Gate** you may give a try to the [can attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute). If you are planning to use a third-party package to manage roles and permissions, like `Laratrust`, then you may read [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters).
