### ISSUE TITLE
Input Validation Class Not Working?

### ISSUE THREAD

**Issue by reasecret** [jeroennoten/Laravel-AdminLTE#1149]
I'm working on Laravel 9 with Livewire and jeroennoten/Laravel-AdminLTE 3.8.4.

And have a basic input like this:

```
<div class="col-md-6">
    <x-adminlte-input wire:model="brandName" name="brandName"/>
    <x-adminlte-button wire:click.prevent="saveBrand" label="Save" theme="primary" />
</div>
```

Validation error is showing but is-invalid class is not working:
![resim](https://user-images.githubusercontent.com/32717963/204628946-83086849-100b-4dd9-925e-b55cf6733823.png)

Am I doing something wrong?

**Comment by dfsmania** [comment]
@reasecret can you attach the `html` markup generated (including the `.form-group` that wraps the input). You can use your browser's inspector to get it...

**Comment by reasecret** [comment]
> @reasecret can you attach the `html` markup generated (including the `.form-group` that wraps the input). You can use your browser's inspector to get it...

This is validated html output:
```
<div class="col-md-6">
    <div class="form-group">
        <div class="input-group adminlte-invalid-igroup">
            <input id="brandName" name="brandName" value="" class="form-control" wire:model="brandName" placeholder="Brand">
        </div>
        <span class="invalid-feedback d-block" role="alert">
            <strong>The brand name field is required.</strong>
        </span>
    </div>
    <button type="button" class="btn btn-primary" wire:click.prevent="saveBrandAndReturn">
         Save And Go Back </button>
                <button type="button" class="btn btn-primary" wire:click.prevent="saveBrandAndSaveNew">
         Save And Create New 
    </button>
</div>
```

Looks like `is-invalid` class not adding to input.

**Comment by dfsmania** [comment]
Yea, I see, could you provide the full code of your component? So I can play with it locally. Unfortunately, these components were not designed taking `Livewire` into account. The `input` component extends from the `input-group-component`:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/src/View/Components/Form/InputGroupComponent.php

And the `isInvalid()` method of it is used to check for validation errors. I'm not sure why, but the `adminlte-invalid-igroup` is added correctly to the `input-group` element, but the `is-invalid` is not added to the underlying `input`. However, both classes depends on the result of `isInvalid()` method. Maybe is related to how `Livewire` works and is not re-rendering the input element in this situation, but I'm not sure. So I need to create a playground to trace the behavior...

**Comment by reasecret** [comment]
This is my component.

```
<?php

namespace App\Http\Livewire\Admin\BrandManagement;

use App\Models\Brand;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Livewire\Component;

class CreateBrand extends Component
{
    public $brandName;
    public $brandSlug;

    public function render()
    {
        return view('livewire.admin.brand-management.create-brand')->extends('adminlte::page')->section('content');
    }

    // Generating slug realtime
    public function updatedBrandName()
    {
        $this->brandSlug = SlugService::createSlug(Brand::class, 'slug', $this->brandName);
    }

    public function saveBrand()
    {
        $this->validate([
            'brandName' => 'required',
        ]);

        Brand::create([
            'name' => $this->brandName,
        ]);

        session()->flash('brandSaved', 'Brand Saved');

        return redirect()->route('admin.brand.list');
    }
}

```

**Comment by dfsmania** [comment]
@reasecret This problem is related to how `Livewire` works, the validation errors are not flashed to the session, see https://github.com/livewire/livewire/issues/621

I have already tried to implement a workaround for this situation in the past, check issue https://github.com/jeroennoten/Laravel-AdminLTE/issues/972 and the PR https://github.com/jeroennoten/Laravel-AdminLTE/pull/1035, but I think now I need to review it, and move the next code:

```blade
@php
    $setErrorsBag($errors);
@endphp
```

from the `input-group-component.blade.php` file to the blade file of each of the components, for example, the new `input.blade.php` should be like:

```blade
@extends('adminlte::components.form.input-group-component')

@php
    $setErrorsBag($errors);
@endphp

@section('input_group_item')

    {{-- Input --}}
    <input id="{{ $id }}" name="{{ $name }}"
        value="{{ $getOldValue($errorKey, $attributes->get('value')) }}"
        {{ $attributes->merge(['class' => $makeItemClass()]) }}>

@overwrite
```

However, until a new release with that fix is created, you may try the next solution on your `saveBrand()` method to manually flash the errors into the session:

```php
public function saveBrand()
{
    try {

        $this->validate([
            'brandName' => 'required',
        ]);

        Brand::create([
            'name' => $this->brandName,
        ]);

        session()->flash('brandSaved', 'Brand Saved');

        return redirect()->route('admin.brand.list');

    } catch (\Illuminate\Validation\ValidationException $e) {

        session()->flash('errors', $e->validator->errors());
        throw $e;
    }
}
```

**Comment by reasecret** [comment]
try & catch working well. Using this solution for now and waiting for fix.
