### ISSUE TITLE
[BUG] x-adminlte-input Undefined variable $errors

### ISSUE THREAD

**Issue by Globax** [jeroennoten/Laravel-AdminLTE#1158]
I have issue with x-adminlte-input, it returns error https://share.cleanshot.com/D1lzbQ73

**Comment by dfsmania** [comment]
@Globax what version of this package are you using? Can you check in what line of this package that error is generated?

**Comment by Globax** [comment]
@dfsmania 
Package version is 3.8.5

Error comes from https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/components/form/input.blade.php line 5
There is $errors variable which is not defined anywhere.

**Comment by dfsmania** [comment]
That's strange, because that change is new and not included on a release still, however you may be using `dev-master` on your `composer.json` file. How is defined the route that redirects to that view, it needs to be using the `web` middleware, otherwise the `errors` bag from `Laravel` won't be available and so the error...

**Comment by Globax** [comment]
My `composer.json` https://share.cleanshot.com/ZGzg0CHw, i added package with `composer require jeroennoten/laravel-adminlte` by this instructions https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation

And yes, issue was with `web` middleware, i use PHP 8 attributes (`spatie/laravel-route-attributes`) to define resources and i was defined only resource. 

I added `web` middleware to controller and now it works.

Thank you for your quick help :)

**Comment by dfsmania** [comment]
I will keep this open, just to add a safety check to cover the issue when not using the `web` middleware.
