### ISSUE TITLE
Manage menu by roles and not by permissions[FEATURE]

### ISSUE THREAD

**Issue by hernandohack** [jeroennoten/Laravel-AdminLTE#1165]
Currently in the menus, each menu option can be managed with permissions.

'can' => 'admin'

but I want to manage each menu option, by role.

I want to be able to assign a menu option, if a user is of a specific role type.

how can I do this?

### Describe the solution you'd like
I tried to do something like this:

'can' => 'is, admin'

But it does not work.

**Comment by dfsmania** [comment]
@hernandohack I think there is a way to implement your custom **menu filter**, please refer to next documentation:

[Custom Menu Filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters)

**Comment by dfsmania** [comment]
Closed, no more feedback...
