### ISSUE TITLE
[FEATURE] Add Button to Card Component

### ISSUE THREAD

**Issue by owindev** [jeroennoten/Laravel-AdminLTE#1170]
### Is your request related to a problem? Please describe.

Some of the projects I have done have datatables on top of card, with a Button of some sort in the card to add an entry.

### Describe the solution you'd like

Add a way to define a button in the card component.

### Additional context
An example for reference

![image](https://user-images.githubusercontent.com/26231737/221385956-5badd7bc-79ce-4d48-ad63-eebac03cf9e5.png)

**Comment by dfsmania** [comment]
@owindev You can use the `toolsSlot` or the `footerSlot` to add extra elements like that to a `card`. Check the [Card Documentation and Examples](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Widget-Components#card).

**Comment by owindev** [comment]
Understood. I'll close this out.
