### ISSUE TITLE
How to change the name on the top of navbar [help]

### ISSUE THREAD

**Issue by Ivcast20** [jeroennoten/Laravel-AdminLTE#1173]
Hi, I'm using the tamplate but I want to know if is there a way to change the name for other item in the name or add another things

**Comment by dfsmania** [comment]
Please, take a tour around the [Wiki Pages](https://github.com/jeroennoten/Laravel-AdminLTE/wiki), specially the [Basic Configuration Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration). I think you are looking for the `logo` config on [Admin Panel Logo](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#admin-panel-logo). In any other case, please add more details or screenshot about what you want to change...

**Comment by dfsmania** [comment]
Closed, no feedback!
