### ISSUE TITLE
Top Navbar - Custom right links area don't render my language menu

### ISSUE THREAD

**Issue by julianovmartins** [jeroennoten/Laravel-AdminLTE#1175]
I'm trying to add a language selector, but so far, without success. Am I missing something?

In AdminLTE, there is the following file:
[/vendor/adminlte/partials/navbar/navbar-layout-topnav.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/navbar/navbar-layout-topnav.blade.php#L35)

It has the following directive:
```
@yield('content_top_nav_right')
```

So I created a new blade file:
```
/resources/views/mysite/partials/navbar/custom_content_top_nav_right.blade.php
```

And tried to add the following content:
```
@extends('adminlte::partials.navbar.navbar-layout-topnav')

@section('content_top_nav_right')
    <!-- Language Dropdown Menu -->
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="flag-icon flag-icon-us"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right p-0">
            <a href="#" class="dropdown-item active">
                <i class="flag-icon flag-icon-us mr-2"></i> English
            </a>
            <a href="#" class="dropdown-item">
                <i class="flag-icon flag-icon-de mr-2"></i> German
            </a>
            <a href="#" class="dropdown-item">
                <i class="flag-icon flag-icon-fr mr-2"></i> French
            </a>
            <a href="#" class="dropdown-item">
                <i class="flag-icon flag-icon-es mr-2"></i> Spanish
            </a>
        </div>
    </li>
@endsection
```

I've also tried extending directly to `page`, but with no success.
```
@extends('adminlte::page')
```

I also tried to publish the views, but still, the language menu doesn't appear.
```
php artisan adminlte:install --only=main_views
```

So I edited the published file:
/resources/views/vendor/adminlte/partials/navbar/navbar-layout-topnav.blade.php

And replaced:
```
@yield('content_top_nav_right')
```

By:
```
@include('mysite.partials.navbar.custom_content_top_nav_right')
```
And I removed the `@extend`, `@section`, and `@endsection` directives from my file above.

None of the alternatives worked.

So I ran:
```
php artisan optimize:clear
```
It didn't work either.

It gives the impression that the published view files are not being read.

### Expected behavior
https://adminlte.io/themes/v3/pages/examples/language-menu.html

### Environment

| Item    | Version
| ------- | -------
| Laravel | 10.0
|JetStream| 3.0
| Laravel-AdminLTE | Master
| OS      | macOS Monterey

**Comment by dfsmania** [comment]
Hi @julianovmartins , I have played with your example. On my testing project, the dropdown was not rendered right because it miss the next `css` file that is included on the **AdminLTE v3** example:

```html
<link rel="stylesheet" href="../../plugins/flag-icon-css/css/flag-icon.min.css">
```

If you inspect the the `navbar`, you should see the `html` code of your language dropdown there, but nothing will be rendered until you include that file.

To include the file, you can use the [plugins configuration feature](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration).

**Comment by julianovmartins** [comment]
Hello @dfsmania,

Thanks for the tip.

I had already tested it with just text, without the icon flags.

![Captura de Tela 2023-03-27 às 09 50 58](https://user-images.githubusercontent.com/2169618/227944901-5e0ca3ee-9b88-43a9-ab74-0f9be2a87d35.png)

Butut my item still doesn't appear on that menu.

![Captura de Tela 2023-03-27 às 09 46 55](https://user-images.githubusercontent.com/2169618/227944926-bd5bebf3-a75c-4f4b-9c88-ce4582084618.png)

**Comment by dfsmania** [comment]
@julianovmartins  That's rare, just try with a basic example:

```blade
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content_top_nav_right')
    <li class="nav-item">
        <a class="nav-link">TEST</a>
    </li>
@endsection

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop
```

That example works on my local environment. However, I'm on **Laravel 8.x**, but I don't think that may cause your issue.

**Comment by julianovmartins** [comment]
Hi @dfsmania,

You are correct; putting the code block inside the `welcome.blade.php` works perfectly.

But within my directories structure, it doesn't work.
```
/resources/views/mysite/partials/navbar/custom_content_top_nav_right.blade.php
```

Is there any directory depth rule for the blade templates engine?

![Captura de Tela 2023-03-27 às 12 28 54](https://user-images.githubusercontent.com/2169618/227989678-61fd742a-3849-4c03-a039-ba1e920a991f.png)

**Comment by dfsmania** [comment]
@julianovmartins I don't think there is a depth rule, it should be another thing...

So, the next code on your `welcome.blade.php` doesn't work?

```blade
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content_top_nav_right')
    @include('mysite.partials.navbar.custom_content_top_nav_right')
@endsection

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop
```

Where `'mysite.partials.navbar.custom_content_top_nav_right'` is defined just as:

```blade
<li class="nav-item">
    <a class="nav-link">TEST</a>
</li>
```

**Comment by julianovmartins** [comment]
Work:
![Captura de Tela 2023-03-27 às 12 58 35](https://user-images.githubusercontent.com/2169618/227996971-58d1ae5a-080d-401f-8c5a-24f72978120e.png)

Does not work:
![Captura de Tela 2023-03-27 às 13 03 10](https://user-images.githubusercontent.com/2169618/227998171-7009a965-ab87-4157-b375-e8ac3b39c171.png)

**Comment by dfsmania** [comment]
@julianovmartins OK, anyway, I believe that after you `@extends()` the **partial view**, you will still need to customize the published views to include that extension instead of the one provided by the package. That's not too clean...

If your goal is to have the **language dropdown** available on all pages extending form the `adminlte:page`, I suggest you to create an application base layout, and all common markup/customizations there, then extend your views from that base layout. Check issue #1093 for details about creating a blade layout.

**Comment by julianovmartins** [comment]
Just FYI, I tested it on Laravel 8, and the issue persists.

> I suggest you to create an application base layout...

Perfect, I will work with a base template, as you suggested. This is much cleaner for maintenance since all sections will be in one place.

Thank you for all the support, @dfsmania!

**Comment by dfsmania** [comment]
Closing, I hope the suggestions helped you, reopen if you have any other issue related to this...
