### ISSUE TITLE
[BUG] Select2 bugged styles

### ISSUE THREAD

**Issue by jordihuertas** [jeroennoten/Laravel-AdminLTE#1177]
### Steps To Reproduce
Migrate from 2.4 to 3.x

### Screenshots
2.4
![imagen](https://user-images.githubusercontent.com/28887168/227942336-065818c6-8b0a-48f6-93a4-5c80fd89ceeb.png)

3.0
![imagen](https://user-images.githubusercontent.com/28887168/227942242-e4219eb3-7156-410d-a23d-a22af635dc17.png)

### Environment

| Item    | Version
| ------- | -------
| PHP | 8.0.2
| Laravel | 9.52.4
| jeroennoten/laravel-adminlte | 3.8.6

**Comment by dfsmania** [comment]
@jordihuertas Migration from **AdminLTE v2** template to **AdminLTE v3** may content a lot of breaking changes. Please, share the code of your `select2` definition, and be sure to setup the `select2` plugin files on the [plugins configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)...

**Comment by dfsmania** [comment]
Closing, no feedback!

**Comment by DanielJoseDolz** [comment]
I am having the same issue
