### ISSUE TITLE
[QUESTION] Is there a way to not allow sidebar to collapse

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#1180]
As stated, I'm just looking for a way to remove the hamburger lines in the top nav, and prevent the sidebar from collapsing. Is this possible?

**Comment by dfsmania** [comment]
Hi @PiousVenom , the **AdminLTE** is a responsive template, and by default the sidebar will get collapsed on low screen sizes. So, if you hide/remove the **hamburger button** completely there will be no way to expand the sidebar on low screen sizes (for example, when you access the panel from a cellphone).

However, if you want to hide the **hamburger button** on big screen sizes (`>= md` breakpoint), you may [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and then edit the file: `resources/views/vendor/adminlte/partials/navbar/menu-item-left-sidebar-toggler.blade.php`. It will be enough to add the class `d-md-none` to the element wrapping the **hamburger button**:

```blade
<li class="nav-item d-md-none"> {{-- NOTE d-md-none was added here --}}
    <a class="nav-link" data-widget="pushmenu" href="#"
        @if(config('adminlte.sidebar_collapse_remember'))
            data-enable-remember="true"
        @endif
        @if(!config('adminlte.sidebar_collapse_remember_no_transition'))
            data-no-transition-after-reload="false"
        @endif
        @if(config('adminlte.sidebar_collapse_auto_size'))
            data-auto-collapse-size="{{ config('adminlte.sidebar_collapse_auto_size') }}"
        @endif>
        <i class="fas fa-bars"></i>
        <span class="sr-only">{{ __('adminlte::adminlte.toggle_navigation') }}</span>
    </a>
</li>
```

**Comment by dfsmania** [comment]
Closed, no feedback!
