### ISSUE TITLE
[QUESTION] Is it possible to create a menu for different routes?

### ISSUE THREAD

**Issue by NathanLisandro** [jeroennoten/Laravel-AdminLTE#1186]
I want to create a menu for different pages. How can I do that? For example, let's say we have a page called 'Supermarket' with one menu that has several items. Then, we have the 'Work With Us' page. When the user clicks on 'Work With Us', I want another menu to appear when the page opens. I'm not sure if I explained it clearly."

**Comment by dfsmania** [comment]
Check [Menu configuration at runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime). Also, you may try to search on the closed issues for more feedback.

**Comment by dfsmania** [comment]
Closed, no feedback!
