### ISSUE TITLE
[QUESTION] Datatable slows down for larage dataset

### ISSUE THREAD

**Issue by MarienMupenda** [jeroennoten/Laravel-AdminLTE#1188]
### Description
I have built a datatable with more than 2000 students, and the page is slowing down, is the any what to do server-side pagination ?

### Steps To Reproduce
Fake more that 10000 records
Create a datatable and fill the records on it.

| Item    | Version
| ------- | -------
| Laravel | 10.x

**Comment by dfsmania** [comment]
Yeah, I think it's possible to implement server side processing, but I have never give it a try. You may check the issue: https://github.com/jeroennoten/Laravel-AdminLTE/issues/931 for more information, and share some code example if you made it work...
