### ISSUE TITLE
[QUESTION] Customize package due to translations on the Laravel DB migrations

### ISSUE THREAD

**Issue by AriRodriguezH** [jeroennoten/Laravel-AdminLTE#1195]
#### Spanish

Recientemente cambie la tabla de usuarios de que se genera en automatico en laravel 10, cambie los nombres de las variables al español, una de esas fué la variable "name", me di cuenta que este cambio afecto a la barra de navegación superior donde antes colocaba el usuario logueado, ahora simplemente no muestra nada, no tengo alguna idea de que apartado tengo que mover para que nuevamente me pueda aparecer el nombre del usuario logueado arriba sin modificar mis variables nuevamente

Si alguien sabe como lograrlo y me pudise indicar los pasos se lo agradecería

#### English

> Recently I changed the users table that is generated automatically in Laravel 10, I changed the names of the variables to Spanish, one of those was the "name" variable, I realized that this change affected the top navigation bar where before I placed the logged in user, now it simply does not show anything, I have no idea which section I have to move so that the name of the logged in user can appear again without modifying my variables again.
>
> If anyone knows how to achieve this and could tell me the steps I would appreciate it.

**Comment by dfsmania** [comment]
Hola @AriRodriguezH , por favor las consultas en inglés para la próxima. Lo primero que vas a tener que hacer es publicar las vistas del paquete (ver [Views Customization](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization)). Luego vas a tener que modificar el archivo `partials/navbar/menu-item-dropdown-user-menu.blade.php` publicado para cambiar todas las referencias `Auth::user()->name` a su correspondiente nombre, en principio. Quizás haga falta hacer otras modificaciones...

De todas maneras, muchos otros paquetes para `Laravel` que quieras usar en un futuro pueden estar dependiendo de sus migraciones originales para los usuarios y quizás en un futuro se te complique integrar otras utilidades. No es un cambio que yo haría, a menos que sea obligatorio por alguna circunstancia...

**Comment by dfsmania** [comment]
Closed, no feedback...
