### ISSUE TITLE
[BUG] Calendar not working inside modal.

### ISSUE THREAD

**Issue by smukhishahadat** [jeroennoten/Laravel-AdminLTE#1201]
### Describe the bug

Calendar not working inside modal.
`<x-adminlte-input-date name="idDisabled" value="2020-10-04" :config="$config" disabled/>`
#### I am using this modal
`<x-adminlte-modal id="DetailsModal" title="" theme="purple" icon="fas fa-eye" size='lg'>`

How can i use calendar,select2 inside modal.

**Comment by dfsmania** [comment]
Please, share a minimal example of code that we can use to test/investigate the issue, and explain what it's not working.

**Comment by smukhishahadat** [comment]
# My code in modal
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/62495642/7cc0f6f7-eed8-4270-9ce0-b485e7a2623f)
# Design View
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/62495642/09dfb496-5979-4cc3-9158-03099d9dc26e)

# Modal
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/62495642/ac2d07ae-7325-4da0-8c61-7a7deff8bd8e)

**Comment by smukhishahadat** [comment]
> Please, share a minimal example of code that we can use to test/investigate the issue, and explain what it's not working.

https://github.com/jeroennoten/Laravel-AdminLTE/issues/1201#issuecomment-1644639003

**Comment by dfsmania** [comment]
Please, give details about the issue, and use [Github Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to share the code. Also, try to create a **minimal example** of code that reproduces the issue, do not share all of your development code.

**Comment by smukhishahadat** [comment]
> Please, give details about the issue, and use [Github Code Blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to share the code. Also, try to create a **minimal example** of code that reproduces the issue, do not share all of your development code.

I want to popup a calendar on modal body. But this is not working. How can i popup a calendar on modal boy for collect date of birth. Please help me.

**Comment by dfsmania** [comment]
Sorry, but I don't have the time to create and share a working example for your use case. I was expecting this from your side. However, and since you are loading the **blade component** using an `AJAX` call be sure to use the `render()` method on the controller to return the view. Also, replace `@section('js') ... @endsection` with `@push('js') ... @endpush` on your main blade view, the one that triggers the `AJAX` call, since `@section()` replaces a whole section and you may stack code in this situation.
