### ISSUE TITLE
Laravel-AdminLTE for Livewire V3.0 (beta)

### ISSUE THREAD

**Issue by desyashasyi** [jeroennoten/Laravel-AdminLTE#1207]
How to use Laravel-AdminLTE for Livewire V3.0 (beta)?

**Comment by dfsmania** [comment]
The instructions [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration#livewire) does not work for **Livewire 3.0**? Obviously, you will need to target the required version of `Livewire` with the composer command.

**Comment by dfsmania** [comment]
@desyashasyi Just in case, check if this recently detected bug helps to solve your issue:

https://github.com/jeroennoten/Laravel-AdminLTE/pull/1210

**Comment by desyashasyi** [comment]
Thank you very much. I solved the problem.

**Comment by dfsmania** [comment]
@desyashasyi OK, if you think the solution may help others, please share it here.
