### ISSUE TITLE
[FEATURE] adminlte with breeze

### ISSUE THREAD

**Issue by marindumont** [jeroennoten/Laravel-AdminLTE#1208]
can you make a tuto to explain how install adminlte with breeze ? because ui is deprecied

**Comment by dfsmania** [comment]
Sorry, but this package does not currently offer any views replacement for the breeze authentication scaffolding. So, you can:

1. Install a new `Laravel` application.
2. Install the `Breeze` scaffolding, and let this package manage all the authentication logic.
3. Install this package following [the installation instructions](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation), but avoid the **step 3**.
4. Use the template provided by this package on those views that you can access after successfully logged in with breeze.

**Comment by dfsmania** [comment]
Duplicated of #842
