### ISSUE TITLE
Japanese translation of 'remember_me'

### ISSUE THREAD

**Issue by hgpwhgpw** [jeroennoten/Laravel-AdminLTE#1212]
### Describe the bug
https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/lang/ja/adminlte.php#L9
Would you change Japanese translation of 'remember_me'.
Current source, 'remember_me' is translated into 'パスワードを記憶する', but it's means to save password.

### Expected behavior
`'remember_me' => '認証状態を保持する',`
This means to keep me log-in state.

or

`'remember_me' => 'ブラウザに認証情報を記憶する',`
This means to save log-in state in your browser.

**Comment by dfsmania** [comment]
Hi @hgpwhgpw , If you feel like creating a **Pull Request** for this you will be welcome. You may check: https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/.github/CONTRIBUTING.md

Otherwise, I will fix it later...

**Comment by hgpwhgpw** [comment]
@dfsmania 
Thank you for replaying!
I'll create a Pull Request.

**Comment by dfsmania** [comment]
I will keep this open, then when the PR is created I will link the issue there and this will be auto closed.
