### ISSUE TITLE
[BUG] Changing user's primary key type to varchar(string) triggers an error

### ISSUE THREAD

**Issue by lpesar** [jeroennoten/Laravel-AdminLTE#1214]
### Describe the bug

When change the user's primary key of int to varchar I get an error

### Steps To Reproduce

Change type primary key of the user's migration

```php
namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $keyType = 'string';
    protected $primaryKey = 'email';
    public $incrementing = false;
    public $timestamps = false;
    
}
```

| Item    | Version
| ------- | -------
| Laravel | 10
| Project |  v3.9.2
| OS      |  windows 11

**Comment by dfsmania** [comment]
@lpesar Please, share the error you are facing. However, I'm not sure why are you doing such modification on the default Laravel's migrations (they set `ID` (integer) as the primary key for user's table). My advice is to not change that unless you really need that change, lots of packages may have conflicts with that modification.

**Comment by dfsmania** [comment]
Closed, no feedback!
