### ISSUE TITLE
[QUESTION] How to use the Input Mask plugin in x-adminlte-input

### ISSUE THREAD

**Issue by Raphael2132** [jeroennoten/Laravel-AdminLTE#1217]
I added the plugin to the admin settings but I don't know how to use the mask in the x-adminlte-input field.

I need to create a telephone field with a mask (99) 9 9999-9999.

I didn't find a practical example of using this plugin in the Form Components documentation.

If anyone can help me configure the Input Mask within a Laravel project with Admin, I would appreciate it.

**Comment by dfsmania** [comment]
First, add the required configuration on the **AdminLTE file config** (plugins section), for example:

```php
'InputMask' => [
    'active' => false,
    'files' => [
        [
            'type' => 'js',
            'asset' => false,
            'location' => 'https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8/jquery.inputmask.min.js',
        ],
    ],
],
```

> Note that for the purpose of this example I'm using a CDN file, but you may also include files that were installed locally (with `'asset' => true` and the corresponding location).

Then, on a blade view extending this template, for example:

```blade
...
{{-- Include Input Mask files for this view --}}
@section('plugins.InputMask', true)
...
{{-- Define a new input component --}}
<x-adminlte-input label="Input Mask Test" name="iMaskTest"/>
...
{{-- Add required Javascript to initilize Input Mask plugin --}}
@push('js')
<script>

    $(document).ready(function() {

        // Init input mask on the target element.

        $('#iMaskTest').inputmask({
            "mask": "(99) 9 9999-9999",
             // Specifying other options...
        });
    });

</script>
@endpush
```

**Comment by Raphael2132** [comment]
> First, add the required configuration on the **AdminLTE file config** (plugins section), for example:
> 
> ```
> 'InputMask' => [
>     'active' => false,
>     'files' => [
>         [
>             'type' => 'js',
>             'asset' => false,
>             'location' => 'https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8/jquery.inputmask.min.js',
>         ],
>     ],
> ],
> ```
> 
> > Note that for the purpose of this example I'm using a CDN file, but you may also include files that were installed locally (with `'asset' => true` and the corresponding location).
> 
> Then, on a blade view extending this template, for example:
> 
> ```
> ...
> {{-- Include Input Mask files for this view --}}
> @section('plugins.InputMask', true)
> ...
> {{-- Define a new input component --}}
> <x-adminlte-input label="Input Mask Test" name="iMaskTest"/>
> ...
> {{-- Add required Javascript to initilize Input Mask plugin --}}
> @push('js')
> <script>
> 
>     $(document).ready(function() {
> 
>         // Init input mask on the target element.
> 
>         $('#iMaskTest').inputmask({
>             "mask": "(99) 9 9999-9999",
>              // Specify other options...
>         });
>     });
> 
> </script>
> @endpush
> ```

Thank you very much, it worked perfectly, I thought there was a specific input for the mask but then you have to do the mask by script

**Comment by Raphael2132** [comment]
Thank you very much, it worked perfectly, I thought there was a specific input for the mask but then you have to do the mask by script
