### ISSUE TITLE
Why doesn't admin styles load in Laravel 10 in production?

### ISSUE THREAD

**Issue by srnatan** [jeroennoten/Laravel-AdminLTE#1219]
I'm a newbie with laravel and I'm having problems that I hope you can help me to fix.

It is a project that I have locally with Laravel v10.9.0 (PHP v8.1.10). I have AdminLte installed with [https://github.com/jeroennoten/Laravel-AdminLTE/wiki.](https://stackoverflow.com/)

I have moved the project to a server that is managed and to which I have no console access (I can't run php artisan).

The laravel home page is the default one for the installation, I have only worked on the backend part of the project and the styles are loaded without problem.

But when I enter some of the paths that I have locally that load the admin dashboard the styles are not loaded. Looking at the code I see the following style, in my project in local, mydomain.com/vendor/adminlte/dist/css/adminlte.min.css and if I access to this domain I see all the css code.

However if I do the same on the web server I don't see anything, it doesn't give any error, but the page is blank. On the web server if I modify the url and before /vendor I put /public to get mydomain.com/public/vendor/adminlte/dist/css/adminlte.min.css I see the css with all the styles.

Can anyone know what is going on? I cleared the caches manually, config, views, routes, but everything is still the same. Thanks!

**Comment by dfsmania** [comment]
Hi @srnatan , it may be a problem with the configuration of your production server:

You may review the `APP_URL` configuration in your Laravel `.env` file, and/or check the configuration of the service (apache, nginx, ...) that is serving your web application, for example the **DocumentRoot** in case of apache.

The first thing you may try is changing `APP_URL` to `https://mydomain.com/public` or `http://mydomain.com/public` depending on the `http` schema you are using.

**Comment by srnatan** [comment]
Oh, yes!!! Now it does load the styles, but obviously it shows up in the url and I don't want it to do that. With an htaccess it is not possible to do this "redirection".
Thank you very much!!!
