### ISSUE TITLE
[QUESTION]: Doubt about the use of Tailwind

### ISSUE THREAD

**Issue by srnatan** [jeroennoten/Laravel-AdminLTE#1223]
I have a question about the use of AdminLte and tailwind. When integrating AdminLte with Laravel, which is the CSS engine, tailwind or bootstrap?
I have adminlte installed and everything looks correct and if I use components they look as it appears in the documentation, but I also have a view with datatables. Inside a datatable view I want to include some tags with my own styles, I have written them with tailwind but they don't load, I have seen the app.css and there is tailwind and I have my tailwind.config.js file.
But I think there is something I don't know or I am not taking into account.
Can someone clarify how to write your own styles when you have adminlte installed. Bootsrap installed? Tailwind? in which file new styles would be loaded.
Forgive me but I am new to Laravel. Thanks!

**Comment by dfsmania** [comment]
Hi @srnatan , the **AdminLTE** template is based on **Bootstrap** (currently **Bootstrap 4**). To add custom styles, or plugins refer to next section:

[Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)

You may add your customs `css`of `js` files inside a folder under the `public/vendor` folder and then include they in your views by adding a new **plugin configuration entry**.

Extra reference that may help you:

[How to use plugins with asset=true configuration](https://github.com/jeroennoten/Laravel-AdminLTE/issues/1218)

On the other hand, I don't think you can integrate Tailwind and Bootstrap together, they both provides classes with names that conflicts with each other. Search for `tailwind` on the [closed issues](https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+is%3Aclosed) to get more information, I think you are not the first trying to mix they together...

**Comment by srnatan** [comment]
Now everything makes sense, thank you very much!
