### ISSUE TITLE
[QUESTION]: Help with menu configuration

### ISSUE THREAD

**Issue by SigalZ** [jeroennoten/Laravel-AdminLTE#1224]
I hope I'm writing this in the right place.

Your documentation for the menu configuration does not match the config file.

For example, in the wiki you have this:

```
'menu' => [
    'MAIN NAVIGATION',
    [
        'text' => 'Blog',
        'url'  => 'admin/blog',
    ],
```

But in the config file you have this:
```
'menu' => [
        // Navbar items:
        [
            'type'         => 'navbar-search',
            'text'         => 'search',
            'topnav_right' => true,
        ],
        [
            'type'         => 'fullscreen-widget',
            'topnav_right' => true,
        ],
```
I don't know where I can find what are the options for 'type'?

Can you please help?

Thank you

**Comment by dfsmania** [comment]
Hi @SigalZ , the `type` property is only used to identify the [Special Menu Items](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Special-Menu-Items). The rest of properties available are listed in the [Menu Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration) section.

The examples on the **wiki** are just used to show some use cases, they don't need to match with the initial configuration provided by the package.

**Comment by SigalZ** [comment]
@dfsmania thank you very much. Somehow I missed that link.
