### ISSUE TITLE
[QUESTION] - Passing data from Controller to Blade - Datatable

### ISSUE THREAD

**Issue by eaglefox82** [jeroennoten/Laravel-AdminLTE#1225]
### Passing Data from Controller to Datatable

I am facing an issue with the data not being displayed correctly with my datatable in Laravel 10

### Controller Function

```
public function index()
    {
        $members = Member::where('active', '=', 'Y')->get();
        $heads = [
            'Membership Number',
            'First Name',
            'Last Name',
            'Rank',
            'Action',];


         return view('Member.index', compact('members', 'heads'));
    }

```

### Blade View

```
  @php
            $config = [
                'data' => $members,
                'order' => [[1, 'asc']],
                'colunms' => [['data' => 'membership_number'], ['data' => 'first_name'], ['data' => 'last_name'], ['data' => 'rank']]
            ];
        @endphp

        <x-adminlte-datatable id="members" :heads=$heads :config=$config head-theme="dark" striped hoverable with-button beautify>
             @foreach($config['data'] as $row)
                <tr>
                   @foreach($row as $cell)
                        <td>{!! $cell !!}</td>
                    @endforeach
                </tr>
            @endforeach

        </x-adminlte-datatable>
```

I just get the following:
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/20160019/cb2b30b4-94be-4691-8f55-ced044de8b9b)

Also note here that the search and pagination has also not showing 

I expected the following view
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/20160019/78e1533b-1694-4438-b059-783138977205)

If I define each column using 
```
<td> {{ $member->membership_number }}</td> 
```

This works, but again the search box and the pagination does not show

if I just have the following:

```
 <x-adminlte-datatable id="members" :heads=$heads :config=$config head-theme="dark" striped hoverable with-button beautify>
</x-adminlte-datatable>

```

Search and pagination shows, but no data

Please point out where the issue in my code is.

**Comment by dfsmania** [comment]
Hi @eaglefox82 , I'm seeing two mistakes:

1. If you are passing the data via the `config` property (on `config['data']`), then you shouldn't use the `foreach` loop to construct it manually.

2. From the `Datatables` plugin:

   > Note that if you use [columns](https://datatables.net/reference/option/columns) to define your columns, you must have an entry in the array for every single column that you have in your table (these can be null if you don't wish to specify any options).
   
   You have 5 columns defined on your `$heads`, so you will need 5 entries on the columns property. Remember that all the properties you setup on `$config` are directly bridged to the plugin properties.
   
So, try with next code:

```blade
 @php
    $config = [
        'data' => $members,
        'order' => [[1, 'asc']],
        // NOTE: null added to complete 5 entries...
        'colunms' => [['data' => 'membership_number'], ['data' => 'first_name'], ['data' => 'last_name'], ['data' => 'rank'], null]
    ];
@endphp

<x-adminlte-datatable id="members" :heads=$heads :config=$config head-theme="dark"
    striped hoverable with-button beautify>
</x-adminlte-datatable>
```

**Comment by dfsmania** [comment]
Closed, no feedback...
