### ISSUE TITLE
[QUESTION] Add new notifications

### ISSUE THREAD

**Issue by alvarobm98** [jeroennoten/Laravel-AdminLTE#1226]
Hello, I am recently creating a project in Laravel and I have decided to use Laravel 9 with AdminLTE 3. I had in another Laravel project a Toast alert system that works great and that I would like to implement instead of using sweetalert. My problem is that notifications outside the AdminLTE project are displayed in the upper right corner, but in the AdminLTE project they appear in the lower left corner, showing outside the "boundaries" of the screen. Which leads me to think that there is some conflict, I have changed all the classes of my alert system and it still gives me the same error, so I ask if it is possible to include a different alert system without it "breaking". A greeting and thanks in advance

**Comment by dfsmania** [comment]
Hi @alvarobm98 , if your toast is a third-party or a custom plugin, remember you need to configure the plugins files, before you can use it. Please, see https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration

**Comment by alvarobm98** [comment]
I have already tried that, as I have mentioned, the notifications work correctly in any Laravel project, except when I add them to a Laravel project with AdminLTE, it is as if there was some kind of conflict but I don't understand where it is because I ask if it was compatible adding another alert system other than swetalert2
