### ISSUE TITLE
[QUESTION]: Extending the registration form

### ISSUE THREAD

**Issue by LuisDonaldo2003** [jeroennoten/Laravel-AdminLTE#1227]
I have a problem, I want to edit the login but when I edit and put the controller variables (they are already in the controller and model), because when I create a user as it reloads, it does not show me any error or anything.
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/105167486/90967c0d-40e7-4abe-876b-100a2d1d5421)
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/105167486/ccb95f05-e89f-43d2-abef-60afe5a3d0fd)
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/105167486/507f6f84-8ec7-42d2-89b4-ea01ca56141a)

**Comment by dfsmania** [comment]
Hi @LuisDonaldo2003 , you will also, and should, first update the **user migration** to support the new columns for the new data you want to store when registering a user. Then run the migrations again so your database structure now supports that new data.

**Comment by dfsmania** [comment]
Closed, no feedback!
