### ISSUE TITLE
[QUESTION]: x-adminlte-input with label to the left instead of on top

### ISSUE THREAD

**Issue by Arametheus** [jeroennoten/Laravel-AdminLTE#1228]
This is more a question right now then a feature.

using x-adminlte-input is there away to make the label to the left instead of on top of the input field??

just wanted to make sure I wasn't missing something.

Thanks in advance.

**Comment by dfsmania** [comment]
Hi @Arametheus , if you are looking for a layout like the one mentioned on [Bootstrap 4 Horizontal Form](https://getbootstrap.com/docs/4.0/components/forms/#horizontal-form), then you can use the components like this:

```blade
<form>
    {{-- Name --}}
    <x-adminlte-input id="iName" name="iName" label="Name" placeholder="Name..."
        fgroup-class="row" label-class="col-2" igroup-class="col-4" enable-old-support/>

    {{-- Surname --}}
    <x-adminlte-input id="iSurname" name="iSurname" label="Surname" placeholder="Surname..."
        fgroup-class="row" label-class="col-2" igroup-class="col-4" enable-old-support/>
</form>
```
![Screenshot 2023-11-09 at 15-05-07 LaradminTest Tests](https://github.com/jeroennoten/Laravel-AdminLTE/assets/63609705/7e48f66c-8d5a-4b00-9d7e-23f33af5dfbf)

Note the classes customization on `from-group`, `input-group` and `label` elements. A reference of the available properties for the components can be found on:
- https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Forms-Components#input-group-component
- https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Forms-Components#input
