### ISSUE TITLE
[FEATURE] Support for Livewire SPA - wire:navigate

### ISSUE THREAD

**Issue by torresdistrib** [jeroennoten/Laravel-AdminLTE#1229]
I've search in wiki and in the documentation but didn't found any reference on how to add differente atributes to anchor tags, namely, on how to add the atribute wire:navigate so to build a SPA as per the documentation in the livewire documentation: [link](https://livewire.laravel.com/docs/navigate).

any pointer on this, or should is just build my navbar outside of AdminLTE?

Thanks

**Comment by dfsmania** [comment]
Hi @torresdistrib , unfortunately when this package was created, `Livewire` wasn't still born. So, you won't find so much native support for it.

However, in your situation, you can [publish the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and customize they to add your required support. For example, to change a sidebar link you can look at the published file: `resources/views/vendor/adminlte/partials/sidebar/menu-item-link.blade.php`. Then you can change that file to add the required attribute: `wire:navigate`:

```blade
<li @isset($item['id']) id="{{ $item['id'] }}" @endisset class="nav-item">

    {{-- YOU CAN ADD WIRE:NAVIGATE HERE --}}
    <a class="nav-link {{ $item['class'] }} @isset($item['shift']) {{ $item['shift'] }} @endisset"
       href="{{ $item['href'] }}" @isset($item['target']) target="{{ $item['target'] }}" @endisset
       {!! $item['data-compiled'] ?? '' !!} wire:navigate>

        <i class="{{ $item['icon'] ?? 'far fa-fw fa-circle' }} {{
            isset($item['icon_color']) ? 'text-'.$item['icon_color'] : ''
        }}"></i>

        <p>
            {{ $item['text'] }}

            @isset($item['label'])
                <span class="badge badge-{{ $item['label_color'] ?? 'primary' }} right">
                    {{ $item['label'] }}
                </span>
            @endisset
        </p>

    </a>

</li>
```

Note, you will also need to apply this procedure for other menu items available in the `sidebar` or `navbar`.

**Comment by torresdistrib** [comment]
Hi!
thanks for the suggestion, yeah that will work!
