### ISSUE TITLE
[BUG] Datatable order not working

### ISSUE THREAD

**Issue by liana13** [jeroennoten/Laravel-AdminLTE#1237]
'order' => [[3, 'asc']], not working in datatable. Can you check it please?

**Comment by liana13** [comment]
`@php
        $heads = [
            'ID',
            'Full Name',
            ['label' => 'Phone', 'width' => 20],
            ['label' => 'Email', 'width' => 35],
            ['label' => 'Role', 'width' => 15],
            ['label' => 'Actions', 'no-export' => true, 'width' => 8],
        ];

        $config = [
            'data' => [],
            'order' => [[2, 'asc']],
            'columns' => [null, null, null, null, null, ['orderable' => true]],
        ];

        foreach ($users as $user) {
            $btnDetails = '<a href="'.route('admin.users.edit',['user'=>$user->id]).'" class="text-olive mx-1" title="Edit"><i class="fa fa-lg fa-fw fa-pen"></i></a>';
            $btnDelete = '<a href="#" data-action="'.route('admin.users.destroy',['user'=>$user->id]).'" class="text-danger btn-remove" title="Delete"><i class="fa fa-lg fa-fw fa-trash"></i></a>';
            $row = [$user->id, $user->full_name, $user->phone_number, $user->email, $user->role_name, $btnDetails.$btnDelete];
            $config['data'] [] = $row;
        }
    @endphp

    <x-adminlte-datatable id="accounts-table" :heads="$heads">
        @foreach($config['data'] as $row)
            <tr>
                @foreach($row as $cell)
                    <td>{!! $cell !!}</td>
                @endforeach
            </tr>
        @endforeach
    </x-adminlte-datatable>`

here is my code

**Comment by dfsmania** [comment]
Ok, I can see you're misusing the `x-adminlte-datatable` component. If you take an in-depth look, you will see that you have never passed all the `$config` values to the component. You're just manually defining the rows and cells of the datatable. Also, if you are already defining the data in the `$config` object, there is no need to manually generate it inside the component again, it is better to use the component like this:

```blade
<x-adminlte-datatable id="accounts-table" :heads="$heads" :config="$config"/>
```

**Comment by liana13** [comment]
Thank you!
