### ISSUE TITLE
[BUG] Missing file vendor/icheck-bootstrap/icheck-bootstrap.min.css

### ISSUE THREAD

**Issue by SawantTejas** [jeroennoten/Laravel-AdminLTE#1238]
### Missing file from the source resources/assets/vendor/icheck-bootstrap/icheck-bootstrap.min.css
This creates a redirection issue while authenticating users through /login route. On successful login, 404 Not found page is returned with the URL vendor/icheck-bootstrap/icheck-bootstrap.min.css. On further inspection I noticed this file is missing in the directory resources/assets/vendor/icheck-bootstrap/

### Steps To Reproduce
1. Go to '/login' route. 
2. Enter correct credentials
3. Click on Sign In
4. Validate the error 404 | Not Found on URLvendor/icheck-bootstrap/icheck-bootstrap.min.css

### Expected behavior
The login should successfully redirect to the login page.

### Screenshots
![Screenshot 2023-12-26 140022](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75907043/dc8e422b-c893-4936-b009-680c9f7f8f23)

**Comment by dfsmania** [comment]
Hi @SawantTejas , you can install `icheck-bootstrap` plugin with the command:

```sh
php artisan adminlte:plugins install --plugin icheckBootstrap
```

That command will install the plugin on `public/vendor/icheck-bootstrap/` folder (see [Plugins Installation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration#install-a-plugin-with-the-artisan-command) for more details). However, I'm not sure why you got a redirection to **404 Not Found**. I usually got a login form without an unstyled checkbox (i.e. a normal bootstrap styled checkbox) when this plugin isn't installed. The redirection after login should be managed by your controller, in my case I have this route:

```sh
POST            login ........................................ Auth\LoginController@login
```

And `app/Http/Controllers/Auth/LoginController` is:

```php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
}
```

That code comes with the `Laravel/ui` package that provides the authentication scaffolding on my environment. Have you used other authentication scaffolding package like `Breeze` or `Jetstream`?

**Comment by SawantTejas** [comment]
Hi @dfsmania, Thank you so much for your prompt response. Installing the plugin worked for me. I was assuming the file to be missing from the source since the older version maybe had it in the source itself. My Login Controller is the same as yours and I am not sure either how the form did not use the normal bootstrap styled checkbox while the plugin wasn't installed. I will close this issue with this comment since my question has been answered.
