### ISSUE TITLE
[QUESTION] Is there a way to use this package with another AdminLTE-compatible Admin template?

### ISSUE THREAD

**Issue by francescoseu** [jeroennoten/Laravel-AdminLTE#1239]
Is there a way to use this package not with the default AdminLTE V3 theme, but with other AdminLTE-compatible templates? E.g. the [premium Admin templates](https://adminlte.io/premium/) one can buy on the AdminLTE website.
If so, how can I configure the package to use the other theme? Thanks.

**Comment by dfsmania** [comment]
Hi @francescoseu , I don't believe that will be possible, this package was created around the free version of **AdminLTE**, without any knowledge about the premium versions.
