### ISSUE TITLE
How to modify the config values dynamically in adminlte.php?

### ISSUE THREAD

**Issue by devsantoshm** [jeroennoten/Laravel-AdminLTE#1241]
### Is your request related to a problem? Please describe.
I want to dynamically modify the values of the admilte.php configuration file

'logo' => '<b>Tutos</b>CODERS',
'logo_img' => 'vendor/adminlte/dist/img/AdminLTELogo.png',

### Describe the solution you'd like
 use App\Models\Setting;
$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
        $settings = Setting::first();
         $event->menu->logo(['logo' => $setting->company]);
      });

In serviceprovider I tried to execute this code, but it doesn't work, I guess there must be another way, does anyone know how to solve it?

**Comment by dfsmania** [comment]
In Laravel, you can change any configuration value dynamically, just use the `config()` helper:

https://laravel.com/docs/10.x/helpers#method-config

For example:

```php
config(['adminlte.logo' => $setting->company]);
```

Check issue #510 also.
