### ISSUE TITLE
How to enable dark mode in iFrame mode?

### ISSUE THREAD

**Issue by ruanpepe** [jeroennoten/Laravel-AdminLTE#1242]
I'm starting a new project using iFrame mode, but dark mode is not working like in other projects without iFrame mode.
Is this the expected behavior?

**Comment by dfsmania** [comment]
For what I've tested locally, toggling dark mode does not affect the already opened tabs on the **IFrame mode**, but when you open a new tab, it inherits the dark mode state of the main body tag. Is this the problem you're facing too?

If not, please add more details and screenshots explaining the problem.

**Comment by ruanpepe** [comment]
Yes. This is my situation.
This way, the user will need to reopen all tabs every time he switches the dark mode.

**Comment by dfsmania** [comment]
Ok, I will try to find a solution for this...

**Comment by ruanpepe** [comment]
Thank you!

**Comment by dfsmania** [comment]
@ruanpepe please, try to check the fix on the new version of the package

**Comment by ruanpepe** [comment]
Everything working well now.
Thank you!
