### ISSUE TITLE
[BUG] There is a bug with the panelAutoHeight

### ISSUE THREAD

**Issue by pedroideavity** [jeroennoten/Laravel-AdminLTE#1245]
The panelAutoHeight property is always defining a height for the page (min-height), and sometimes the layout is unconfigured because it is assigning a random height.
Is there any way to resolve this?
![unnamed](https://github.com/jeroennoten/Laravel-AdminLTE/assets/54036996/e2f4a2e8-689d-489a-935f-071ae9f7c33a)

Laravel Framework 10.43.0

**Comment by dfsmania** [comment]
Hi @pedroideavity , that height is calculated with some `Javascript` on the [ColorlibHQ/AdminLTE V3.x](https://github.com/ColorlibHQ/AdminLTE/tree/v3) package, it's not random, and we don't mess with that inside this package.

You can try to open an issue on the previous mentioned package sharing more detailed info. Also, you can check the package's distributed files, particularly `/vendor/almasaeed2010/adminlte/dist/js/adminlte.js` to check how height is calculated for the `.content-wrapper` element.

**Comment by dfsmania** [comment]
Related to the underlying AdminLTE package
