### ISSUE TITLE
[BUG] Error while inserting custom plugin 

### ISSUE THREAD

**Issue by sagarsutar007** [jeroennoten/Laravel-AdminLTE#1247]
### Describe the bug
When I try to add custom plugin used inside the admin panel It throws Fatal error. I have the files in place also when I take the files array  of custom plugin and put it inside any other plugin's files array it works. Right now I am running it like that. Please help me solve this issue. 

### Steps To Reproduce
1. Go to 'config/adminlte.php'
2. Try adding
      'CustomPlugin' => [
            'active' = true,
            'files' =>[
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => 'assets/js/custom.js',
                ],
                [
                    'type' => 'css',
                    'asset' => true,
                    'location' => 'assets/css/custom.css',
                ],
            ],
        ]
3. Save and Run

### Expected behavior
It should have added those files into my blade pages.

### Screenshots
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/78399767/75a383a2-852f-45a6-ae2d-2d22c8b39a5d)

![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/78399767/c4c18f84-76ae-49df-b99f-d867c8f94402)

### Environment

| Item    | Version
| ------- | -------
| Laravel | 10
| Project | Inventory
| OS      | Windows 11

**Comment by dfsmania** [comment]
@sagarsutar007 You have mistyped `'active' = true,` instead of  `'active' => true,`. Maybe that's the reason of your error.

**Comment by sagarsutar007** [comment]
Thanks for the solutions @dfsmania. That was the issue. Totally missed it.
