### ISSUE TITLE
[QUESTION]: AdminLTE color style configuration and role based menu

### ISSUE THREAD

**Issue by Zisou1** [jeroennoten/Laravel-AdminLTE#1249]
i'm using adminlte , laravel . i'm a beginner , when changing the topnavbar color the red , the widgets and the username dropdown text , are in black , how can i change the text and widget color to white so that the contrast works great .

i want also to change the color of the topnav of the sidebar if it's possible to the same red as the navbar . also when using the adminlte.php config file and adding menu items , i want for example to show some menu items only if they have admin role , but i can't put conditions inside the adminlte.php file , how can i do that ? 

Thank you very much for you time .

**Comment by dfsmania** [comment]
@Zisou1 You can't customize any colors you want, but there are some color configurations supported. To play with the supported color variants, use the [AdminLTE v3 Demo Page](https://adminlte.io/themes/v3/), open the right sidebar menu, and play with the bottom options, as seen in the next image:

![Screenshot 2024-02-13 at 12-13-03 AdminLTE 3 Dashboard](https://github.com/jeroennoten/Laravel-AdminLTE/assets/63609705/288c4703-7084-4a7a-bf78-e5741984f967)

When you find a combination that satisfies you, then you can use the classes option on the `adminlte.php` configuration file to setup it, for this read the Wiki documentation: [Layout And Styling Config / Admin Panel Classes](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#admin-panel-classes), particularly the `classes_sidebar` and `classes_topnav` options.

For a role based menu, try reading next options to see if anything matches your goals:

- [Menu Configuration /  The "Can" Attributte](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute)
- [Menu Configuration / Menu Config at Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime)

Or search the closed issues, you'll probably find an answer for your case there:

https://github.com/jeroennoten/Laravel-AdminLTE/issues?page=1&q=is%3Aissue+is%3Aclosed+role+menu

**Comment by dfsmania** [comment]
Closed due to no feedback!
