### ISSUE TITLE
QUESTION: Passing a model to a Gate

### ISSUE THREAD

**Issue by amnoth** [jeroennoten/Laravel-AdminLTE#125]
Is there a way to pass a model to a gate when building the menu items? I have tried a few different things but none seem to work.

**Menu Example**

```php
$event->menu->add([
    'header' => 'HEADER', 
    'can' => 'update' // Doesn't seem like you can pass a model here...
]);
```

**Laravel Documentation**

```php
if (Gate::forUser($user)->allows('update', $model)) {
    // The user can update the model...
}
```

The only way I managed to get it to work was to edit the GateFilter.php and add a model property to the item and pass it if set.

**Modified GateFilter.php**

```php
protected function isVisible($item)
{
    if (isset($item['model'])) {
        return ! isset($item['can']) || $this->gate->allows($item['can'], $item['model']);
    }
    return ! isset($item['can']) || $this->gate->allows($item['can']);
}
```

Am I missing something?

**Comment by jeroennoten** [comment]
Good one! Would be awesome if you could make a PR for this improvement.
