### ISSUE TITLE
[Question] IframeMode first display view

### ISSUE THREAD

**Issue by SMEWebify** [jeroennoten/Laravel-AdminLTE#1253]
Hi All

When using iframe mode we get a message " No tab selected!"
it is possible to set a default tab in the configuration:
```php
        'default_tab' => [
            'url' => 'opportunities',
            'title' => 'null',
        ],
```

![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75578469/40d907af-3c55-4348-b06d-b0fa1f839633)
But this tab is not loading?

My original need is to display a dashboard for example when loading

visibly the blade view where the @extends('adminlte::page', ['iFrameEnabled' => true]) is located is never displayed?

Regards

kévin

**Comment by dfsmania** [comment]
@SMEWebify See the Wiki: https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage#tabbed-iframe-mode

It stands that the main view of the app, i.e, the view you hit after the login procedure, should be defined as just:

```php
@extends('adminlte::page', ['iFrameEnabled' => true])
```

I believe other content defined on that main view will be totally ignored.

On the other hand, I have tested default tab locally and it's working here, can you share all your I-Frame configuration and also check on the developers console for errors?

**Comment by SMEWebify** [comment]
> It stands that the main view of the app, i.e, the view you hit after the login procedure, should be defined as just:
> 
> ```
> @extends('adminlte::page', ['iFrameEnabled' => true])
> ```
> 
> I believe other content defined on that main view will be totally ignored.


So far we agree

> On the other hand, I have tested default tab locally and it's working here, can you share all your I-Frame configuration and also check on the developers console for errors?

adminlte.php menu link to display on defaut tab
```
[
            'text'        => 'opportunities_trans_key',
            'url'         => 'opportunities',
            'icon'        => 'fa fa-tags',
            'can'         => ['opportunities-menu'],
        ],
```

adminlte.php iframe config
```php 
 'iframe' => [
        'default_tab' => [
            'url' => 'opportunities',
            'title' => 'OPP',
        ],
        'buttons' => [
            'close' => true,
            'close_all' => true,
            'close_all_other' => true,
            'scroll_left' => true,
            'scroll_right' => true,
            'fullscreen' => true,
        ],
        'options' => [
            'loading_screen' => 1000,
            'auto_show_new_tab' => true,
            'use_navbar_items' => false,
        ],
    ],
```
after connection
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75578469/7a03f20d-d19a-44ac-80a2-17706a3c05b7)
after click on OPP
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75578469/e9c3371c-2313-4412-93e3-cda29f58e83e)

no specific error in browser console

It's not really a problem in the end, but it raises questions about the architecture, maybe I should make a page dedicated to the iFrame like on the demo site


![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75578469/c47ed613-58ce-47c3-b3ea-f6cecfb2dbb8)
so the user will always arrive on a dashboard, but to go to an iframe navigation on another page if he wishes.

**Comment by SMEWebify** [comment]
Hi  @dfsmania 

Yes I tested these two possibilities (simplest page possible) or the full URL 

I'll create a dedicated page for Iframe

thanks anyway

Kévin

**Comment by dfsmania** [comment]
@SMEWebify Ok, please read the updated comment!

**Comment by SMEWebify** [comment]
@dfsmania 

FYI, I am not publishing the view.

I added url() but that didn't solve it, by trying something else, I changed

` <div id="panel-default" class="tab-pane fade" role="tabpanel" aria-labelledby="tab-default">`

by 

`<div id="panel-default" class="tab-pane active" role="tabpanel" aria-labelledby="tab-default">`

![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/75578469/5b525f10-5e98-42c2-b696-a14716164157)
I have the view displayed, but with a display bug

**Comment by dfsmania** [comment]
Ok, there's something weird happening, the initial set of classes won't matter because they are managed dinamically by the AdminLTE package. On my testing environment, after loading I ended up with the next markup:

```html
<div id="panel-default" class="tab-pane fade active show" role="tabpanel" aria-labelledby="tab-default">
    <iframe src="..." style="height: 740px;"></iframe>
</div>
```

Could you use the inspector tool to check what markup do yo end with?

**Comment by SMEWebify** [comment]
what do you get on the first load?

For me 
```html
<div id="panel-default" class="tab-pane fade" role="tabpanel" aria-labelledby="tab-default">
                <iframe src="opportunities"></iframe>
            </div>
```
            
I get this after the click  on 'OPP'
```html
            <div id="panel-default" class="tab-pane fade active show" role="tabpanel" aria-labelledby="tab-default">
                <iframe src="opportunities" style="height: 1105.02px;"></iframe>
            </div>
```

**Comment by dfsmania** [comment]
@SMEWebify On the first load, after the login procedure, I get what I posted before. Somehow, the **AdminLTE** package is not managing the default tab in your environment...

**Comment by SMEWebify** [comment]
@dfsmania  thx, i close this topic
