### ISSUE TITLE
[FEATURE] sidebar menu bottom left fixed settings bar 

### ISSUE THREAD

**Issue by guga121** [jeroennoten/Laravel-AdminLTE#1254]
### Is your request related to a problem? Please describe.
Hello, It's possible to create buttons links from the BuildingMenu that are fixed to the bottom of the sidebar and just be icon links (not full sidebar width) ?
Like this:

![adminlte-menu](https://github.com/jeroennoten/Laravel-AdminLTE/assets/1516945/c70c5856-05f9-4f03-93dd-c79f1425f5ed)

Thanks !

### Describe the solution you'd like
A clear and concise description of what you want to happen or the enhancement you want.

**Comment by dfsmania** [comment]
Hello @guga121 there's no built-in support for that. But you are able to publish the package views and edit they to include whatever you want on the left-side menu. Take the issue #926 as a reference...

**Comment by guga121** [comment]
Thank you Diego for your quick response. Very helpfull as always!! 
Regards
