### ISSUE TITLE
[BUG] Error - Call to undefined LayoutHerlper::isPreloaderEnabled()

### ISSUE THREAD

**Issue by wbetalleluzd** [jeroennoten/Laravel-AdminLTE#1257]
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/4992150/f1c2494a-37c4-4ada-82a8-a63d89e297a5)

Just updated today.

I comment that and is running now.

```blade
{{-- Preloader Animation --}}
{{-- @if($layoutHelper->isPreloaderEnabled())
@include('adminlte::partials.common.preloader')
@endif --}}
```

**Comment by wbetalleluzd** [comment]
{{-- Preloader Animation --}}
{{--  @if($layoutHelper->isPreloaderEnabled())
       @include('adminlte::partials.common.preloader')
@endif  --}}

I comment that and is running now.

**Comment by dfsmania** [comment]
@wbetalleluzd Please see #1256 , probably you published the package views previously and now you need to follow the complete [Update Procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating).

**Comment by adrianblynch** [comment]
> @wbetalleluzd Please see #1256 , probably you published the package views previously and now you need to follow the complete [Update Procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating). In other words, you need to update the previously published views in order to synchronize them with the new package version.

Should this have been a major update rather than a minor? I suppose it's a tricky one where publishing is involved.

**Comment by resslinger** [comment]
I have reverted the patch version v3.9.5 and released the minor version v3.10.0.

**Comment by dfsmania** [comment]
Oh, we could actually add backward compatibility by adding again `LayoutHerlper::isPreloaderEnabled()` that just call the method that is now in the `PreloaderHelper` class.

On the other hand, if you want to access the new features, the review of previously published views is mandatory.

**Comment by SammyJoseph** [comment]
There was not any method called isPreloaderEnabled() in vendor\jeroennoten\laravel-adminlte\src\Helpers\LayoutHelper.php
I added the method after line 24:

/**
     * Check if the preloader animation is enabled.
     *
     * @return bool
     */
    public static function isPreloaderEnabled()
    {
        return config('adminlte.preloader.enabled', false);
    }

**Comment by resslinger** [comment]
You have to publish / update the viwes like the update guide. Please check other issues before creating an new one for the same topic.

**Comment by dfsmania** [comment]
@SammyJoseph The method was moved to a new class, due to a split-out refactor, it's now on the `PreloaderHelper.php` class:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/21b94f6d7716ebde46849fcd77ec33c1565794ec/src/Helpers/PreloaderHelper.php#L13

Please, follow the [update procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) and update your published views to sync them with the newest package version.

**Comment by pervilla** [comment]
I solved it with the following: `php artisan adminlte:install --only=main_views --force`

**Comment by dfsmania** [comment]
> I solved it with the following: `php artisan adminlte:install --only=main_views --force` Reference: [https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating](url)

@pervilla You should be careful about using `--force`, because you will lose previous changes on the published views. You usually publish the views when you need to make a customization. So, it's always recommended to backup your set of published views before executing the previous command.

**Comment by dfsmania** [comment]
Closed, a solution to the issue was provided!
