### ISSUE TITLE
ISSUE: Angular2 With Laravel-AdminLTE

### ISSUE THREAD

**Issue by umeshka** [jeroennoten/Laravel-AdminLTE#126]
Hi,
When i give url path in adminlte.php then entire page is  reloaded. below are the image for you reference.
I am using (Laravel , AdminLTE and Angular2).

![image](https://user-images.githubusercontent.com/22589628/30209872-b316711c-94b7-11e7-9e89-d320c2a68c72.png)

![image](https://user-images.githubusercontent.com/22589628/30209974-0f69160e-94b8-11e7-93d2-e2b99bd07dcb.png)

Thanks and Regards,
Umesh B. K

**Comment by jeroennoten** [comment]
You could customize the templates to achieve this behavior. See the README on how to customize templates.
