### ISSUE TITLE
Sub menu active based on url does not work

### ISSUE THREAD

**Issue by Tonmoy-DAPL** [jeroennoten/Laravel-AdminLTE#1268]
### Describe the issue
The followings is happening on my site
https://example.com/admin/users-list

_Menu lIst_
**Users**
  **--List**    (sub menu is active for https://example.com/admin/users-list)
  
_Menu lIst_
**Users**
  **--List**   (sub menu is not active for https://example.com/admin/users-detail/7)
  
  How can i activate the sub menu for the following
https://example.com/admin/users-detail/7

**Comment by dfsmania** [comment]
@Tonmoy-DAPL in these situations you can use the [active property](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-active-attribute), so for example, for the list menu entry you can define the active property as next:

```php
'active' => ['admin/user-list', 'admin/user-detail/*']
```

The definition was done considering `https://example.com` is your root URL, if it's `https://example.com/admin` then you should remove the `admin/` prefix in the active property.

**Comment by Tonmoy-DAPL** [comment]
@dfsmania 
Thanks for your help
It's working perfect on my server
