### ISSUE TITLE
[QUESTION] AdminLTE with AWS Cloud9

### ISSUE THREAD

**Issue by carbauma** [jeroennoten/Laravel-AdminLTE#1270]
Hello,
I know how to use adminLTD with Visual Studio Code, but when I do the same with Cloud9, it does not work. 
Can you explain my why?

**Comment by dfsmania** [comment]
This question will be hard to answer without sharing any details, both **Visual Studio Code** and **AWS Cloud 9** are IDEs, and them should not have any effect on how this package works. An IDE is just a tool (or set of tools) that helps you develop/built your application faster. So, if you have Laravel 7+ working in your IDE, this package should also work there.

**Comment by carbauma** [comment]
Thank you dfsmania, I know that are just IDEs, but it is strange that I am following the same steps in both IDEs and the problem is only with Cloud9. I have created right now a new environment with cloud9 and then I have installed composer and laravel, finally I have implemented AdminLTD, and when I make a preview, is like it does not show the css styles.

**Comment by dfsmania** [comment]
@carbauma Use your browser's console, check for errors there, maybe there is some access permission problem in your filesystem, or maybe your Laravel root URL is not correctly configured.

**Comment by carbauma** [comment]
@dfsmania  you are right!
I have checked the browser's console, and basically the error is this one:

"Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS."

Do you know what I have to do?
thank you!

**Comment by dfsmania** [comment]
Not really, but looking on the internet may help, for example:
https://stackoverflow.com/questions/72289798/laravel-include-css-file-from-mixed-content

**Comment by carbauma** [comment]
Thank you @dfsmania I have use in the file .env this "ASSET_URL=https://example.com " and is working :)
