### ISSUE TITLE
[QUESTION] I can't use more than one top navbar per page?

### ISSUE THREAD

**Issue by felpinhou** [jeroennoten/Laravel-AdminLTE#1273]
### Describe the bug
I wanted to use the navbars from my own template, is this possible?

### Screenshots
If applicable, add screenshots to help explain your problem or to shown the issue.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 
| Project | 
| OS      | 

### Additional context
Add any other context about the problem here. If you already have ideas to solve the issue, add them here or create a Pull Request (PR).

**Comment by dfsmania** [comment]
@felpinhou Please, take the time to add more details, add screenshots, etc. Otherwise it'll hard to imagine what are your goals.

You can add your own customizations to the layout template provided by the package, but it'll be up to you to make it work nicely. In order to add or change the layout template, follow the instructions on [Views Customizations](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization)

**Comment by felpinhou** [comment]
I want to use two navbars, one on the home page and one on the dashboard, but whenever I do this, the page is broken
![Captura de tela 2024-04-24 101839](https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/ebc48679-e0c1-4051-9327-3924d41fb9cf)
this dashboard

![Captura de tela 2024-04-24 101911](https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/6ce69803-788c-4506-9b86-fb8c51f2eaed)

this is home, but 
Whenever I enter a dashboard page, the navbar keeps flashing without css

**Comment by felpinhou** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/70e48b6e-b10b-47ce-b47b-92693ca76f12

:C

**Comment by felpinhou** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/d17bc735-9c32-495f-89ba-7abf0ad21b60

this is my code... im brasilian kkkk, I have to deliver this project today without these css breaks

**Comment by dfsmania** [comment]
@felpinhou You need to understand that this isn't a problem on this package, it's related to your integration. I can see something weird in your `index.blade.php` file. You are defining a new `body` tag without closing it:

```php
@section('header')
    {{-- The next body tag is really wrong here!!! REMOVE THIS!! --}}
    <body class="hold-transition layout-top-nav sidebar-collapse sidebar-closed">

    @component('parts.top-navbar-dashboard')
    @endcomponent
@endsection
```
The body tag is already defined in the `adminlte::page` blade layout, and it's dynamically managed by the `AdminLTE` package. Defining it again, even more without closing it, will cause a lot of conflicts. I'm not sure what you've tried to do there but it's really weird.

**Comment by felpinhou** [comment]
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/c2c0021d-bbee-4ec8-90fa-3aee7129dc9f)

the body is already closed, in the default-template

**Comment by felpinhou** [comment]
but these css breaks still persist, but when I remove the navbar from the pages this break still continues :((

**Comment by felpinhou** [comment]
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/2fbf4506-932e-4f37-9d43-540a48b37f70)

like this? So, I put the class that made the sidebar collapsed in ''classes_body"

but it still gives those css loading errors

**Comment by felpinhou** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/assets/88860868/537c38cb-1a60-4cbf-be15-561cbd7dfe10

the page works normally when it doesn't have the top-navbar-dashboard, but when we enter the dashboard where the menu appears, it keeps giving these css errors

**Comment by dfsmania** [comment]
Yes, like that. You don't need to add `sidebar_collapsed` class, Since I see you're using `layout_topnav=true`, and that's mean without sidebar. Read [Layout Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#layout)

**Comment by felpinhou** [comment]
Before arriving at this result, I tried to use the adminlte:config navbar, but I can't use different navbars on different pages, there are pages where I can't use the navbar, there are pages where the navbar has to be different and it doesn't work with this navbar from adminlte:config

**Comment by dfsmania** [comment]
@felpinhou it's hard to guess what are you trying to achieve. In your `Laravel` project, you may extend the layout provided by this package to create an admin panel, the pages that don't need to show an admin panel, like your home page or other landing pages may be created with your own template. Once you arrive at the administration panel, there is no way to use different navbars while you keep navigating on it.

However, what you mean with different navbars? they have different links, or they have a different look/style?

**Comment by dfsmania** [comment]
Well, I'm sure you can have a landing page, designed with your own style and with your own navbar implementation. The admin panel might then by accessed after the login process. Please, review your code, use the browser's console tool to check for errors, etc.

I can't help you much more here, the admin panel layout we offer here is bound to the underlying AdminLTE package, and it do not support replacing the navbar with your custom navbar.

**Comment by dfsmania** [comment]
@felpinhou If you're using Firefox on your testing, please check if you have this bug called `Flash of Unstyled Content`:

https://stackoverflow.com/questions/21147149/flash-of-unstyled-content-fouc-in-firefox-only-is-ff-slow-renderer

Some solutions are provided there...

**Comment by dfsmania** [comment]
Closed, no more feedback, not a package bug.
