### ISSUE TITLE
[FEATURE] When update to Bootstrap 5 please....

### ISSUE THREAD

**Issue by wbetalleluzd** [jeroennoten/Laravel-AdminLTE#1278]
Please, Bootstrap 5
Thank you so much....

**Comment by wbetalleluzd** [comment]
Actually they are using Bootstrap 5...

**Comment by dfsmania** [comment]
> Actually they are using Bootstrap 5...

It's still on a development stage, the beta wasn't released. I follow the update of this package weekly and in the last 6 months I don't see anyone actively working on the package. The main developer/maintainer of the package was really busy from his own personal activities.
