### ISSUE TITLE
Data Table hide seach an lengthChange

### ISSUE THREAD

**Issue by Danielpx** [jeroennoten/Laravel-AdminLTE#1281]
How to hide search and show number rows per page?

**Comment by Danielpx** [comment]
ok finish

**Comment by dfsmania** [comment]
For future readers, you'll need to change the [Datatable's dom config](https://datatables.net/reference/option/dom), an example of how to customize the `dom` is available [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#examples)
