### ISSUE TITLE
[QUESTION] WHERE SHOULD I DIRECT LAYOUT LIVEWIRE

### ISSUE THREAD

**Issue by marwandhiaurrahman** [jeroennoten/Laravel-AdminLTE#1284]
I would like to ask when I use livewire where should I point my layout when using this package

| Item    | Version
| ------- | -------
| Laravel | 10
| Livewire | 3

**Comment by dfsmania** [comment]
Hi @marwandhiaurrahman , I suggest you to add more details about your question, with code or examples that gives a better idea of what you want to achieve.

**Comment by marwandhiaurrahman** [comment]
when i use Larave-AdminLTE with Livewire i have error like this
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/45331803/1719ba7d-0fe2-465c-9050-1cb26ddb5d3b)

after that i try change in config/livewire.php
    `'layout' => 'components.layouts.app', `
to
   ` 'layout' => 'vendor.adminlte.master',`
   
and now i have this error , a blank page
![image](https://github.com/jeroennoten/Laravel-AdminLTE/assets/45331803/cc688406-1174-4ea5-8bda-62e05fb12e70)

i think i sholud change my layout livewire to the correct file, but i dont know how to do that

**Comment by dfsmania** [comment]
From the **Livewire** configuration file you can read:

```php
    /*
    |---------------------------------------------------------------------------
    | Layout
    |---------------------------------------------------------------------------
    | The view that will be used as the layout when rendering a single component
    | as an entire page via `Route::get('/post/create', CreatePost::class);`.
    | In this case, the view returned by CreatePost will render into $slot.
    |
    */

    'layout' => 'components.layouts.app',
```

So, this configuration is expecting you to setup a blade view path where your application layout component is defined. By default, it expects you to have a `resources/views/components/layout/app.blade.php` file defined in your project that provides a `$slot` variable, this way your controllers returning a `Livewire` component will be rendered inside that layout, inside the `$slot` section. You should read the **Livewire** documentation about [Layout Files](https://livewire.laravel.com/docs/components#layout-files) to initially setup that view. Note it provides a `$slot` variable.

Now, assuming that you want to use the Admin panel layout provided by this package. You should define an application layout that extends from the provided package layout, see how to use this package [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage). I will start trying with:

#### resources/views/components/layout/app.blade.php
```blade
@extends('adminlte::page')

@section('title' )
    {{ $title }}
@stop

@section('content_header')
    <h1>My dashboard</h1>
@stop

@section('content')
    {{ $slot }}
@stop

@section('css')
    {{-- Add here extra stylesheets --}}
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
@stop

@section('js')
    <script> console.log("Hi, I'm using the Laravel-AdminLTE package!"); </script>
@stop
```

> [!IMPORTANT]
> If your project was working previously, check if you don't already had an application layout inside `resources/views/layouts/` folder.

**Comment by marwandhiaurrahman** [comment]
oke thanks a lot , now livewire with this package its work
