### ISSUE TITLE
[QUESTION]: Installation of New Dashboard Layouts

### ISSUE THREAD

**Issue by aeusteixeira** [jeroennoten/Laravel-AdminLTE#1287]
Hey guys,

I'm using Laravel-AdminLTE and would like to know how I can install new dashboard layouts. Does anyone know of any packages or resources that offer additional layout options for AdminLTE that are compatible with this package?

I appreciate any help or suggestions!

**Comment by dfsmania** [comment]
@aeusteixeira I suggest you add some reference image of what you need.

**Comment by dfsmania** [comment]
No feedback!
