### ISSUE TITLE
[QUESTION]: Is it possible to move the view files out of the vendor folder

### ISSUE THREAD

**Issue by Web-krunch** [jeroennoten/Laravel-AdminLTE#1288]
Hi,

I'm not sure if this has been answered yet, but I installed this in my laravel app and I would like to be able to make some edits the the layout. Is it possible to move it from vendor/jeroennoten to my resources views folder and have the pages access that instead?

**Comment by dfsmania** [comment]
@Web-krunch I think you're looking for this: [Views Customizations](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization)

**Comment by Web-krunch** [comment]
Oh jeez. I'm such an idiot. Thank you so much for responding
