### ISSUE TITLE
[QUESTION]: Assign datatable to js variable so table can be reload?

### ISSUE THREAD

**Issue by servitux** [jeroennoten/Laravel-AdminLTE#1289]
In file `datatable.blade.php` change

```blade
@push('js')
<script>
    $(() => {
        $('#{{ $id }}').DataTable( @json($config) );
    })
</script>
@endpush
```

to

```blade
@push('js')
<script>
        var {{ $id }} = $('#{{ $id }}').DataTable( @json($config) );
</script>
@endpush
```

so you can do

`table1.ajax.reload(null,false);`

in your blade without reloading all page

**Comment by dfsmania** [comment]
Hi @servitux , after the Datatables initialization, you can access the table with:

```js
var myTable = $('#id-of-target-datatable').DataTable();
```

where `#id-of-target-datatable` refers to the ID of the target datatable element, the one you usually set through the `id` property of the component.

**Comment by dfsmania** [comment]
Closed, answer given and no feedback provided!

**Comment by brito101** [comment]
I modified the script part to the following:

` @isset($config['refresh'])
        <script>
            $(() => {
                var {{ $id }} = $('#{{ $id }}').DataTable(@json($config));
                setInterval(function() {
                    {{ $id }}.ajax.reload();
                }, {{ $config['refresh'] }})
            });
        </script>
    @else
        <script>
            $(() => {
                $('#{{ $id }}').DataTable(@json($config));
            })
        </script>
        @endif
    @endpush`

In the settings I put the refresh index and its value in seconds, if it exists, it will change the default and insert the upload based on the value passed:

` 'refresh' => 3000,`
