### ISSUE TITLE
[QUESTION] Remove the transition effect on the page change & speed up the page loading time

### ISSUE THREAD

**Issue by chanakaDe** [jeroennoten/Laravel-AdminLTE#1292]
### Is your request related to a problem? Please describe.
I notice the page loading time is really slow with this transition which looks like the page is loading from bottom. AdminLTE Laravel is a good package, but this effect makes it not so professional.

### Describe the solution you'd like
How can we make it smooth & fast like in this page: https://adminlte.io/docs/3.0/index.html
This has no any animations & page loads very fast.
Check the screen recording for more information on this issue.
https://www.loom.com/share/b172de22548c478eb0ee9af91e4c4acf?sid=ed68f652-e9e4-43d5-a34c-0413e07a5a0b

**Comment by dfsmania** [comment]
Hi @chanakaDe , please check documentation at the Wiki pages: [Basic Config / Preloader Animation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#preloader-animation).

You can disable the preloader animation, or change the image shown there. Note the preloader was initially designed by the AdminLTE team to hide rendering effects of some elements, for example, when you use a jquery plugin to transform a checkbox into another with a better look and feel.

On the other hand, the speed time for loading a page depends on a number of things, like the resources of the server, the amount of data that page uses, the time of the underlying database queries to retrieve that data, etc. The AdminLTE documentation page is just text with some style, so there's no reason to be slow.

**Comment by chanakaDe** [comment]
@dfsmania Thank you so much. It worked.
I like this AdminLTE Laravel implementation because it work like a charm. Just for curiosity, Is there any SPA version of this? I would like to try.

Thank you in advance :-)

**Comment by dfsmania** [comment]
@chanakaDe I'm not sure if there is another SPA like implementation around. However, you can give a try to [Livewire+Navigate](https://livewire.laravel.com/docs/navigate). Note, this will require to [publish the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) to add the required customization when generating the links of the menu.

To integrate `Livewire` you may check [Integrating Livewire](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration#livewire).

**Comment by dfsmania** [comment]
Closed, a solution was provided!
