### ISSUE TITLE
[QUESTION]: How can I change the main background and color of the left sidebar.

### ISSUE THREAD

**Issue by mldgato** [jeroennoten/Laravel-AdminLTE#1296]
I need to change the style of the Dashboard, I want to change the color of the left sidebar and the background, for example:

![2024-07-17_11-13-55](https://github.com/user-attachments/assets/f11fdd39-9693-4232-90e2-de701ed4a7e3)

Thank you very much for the help.

**Comment by dfsmania** [comment]
Hi @mldgato , for a basic color customization you may use the [AdminLTE Panel Classes Options](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#admin-panel-classes) of the configuration file, for example:

#### config/adminlte.php
```php
'classes_content_wrapper' => 'bg-primary',
'classes_content_header' => 'bg-primary',
'classes_content' => '',
'classes_sidebar' => 'sidebar-light-primary elevation-4',
```

If you need to include your own defined set of classes with extra style (for example, one that defines an image background), you may include the file with the classes definitions using the [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration).

Another alternative that'll give you more control is to publish the [package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization), then make any customization you need on the published views at `resources/views/vendor/adminlte`.
