### ISSUE TITLE
VerifyCsrfToken  middleware is Missing when I installed Laravel-AdminLTE in my project

### ISSUE THREAD

**Issue by chanakaDe** [jeroennoten/Laravel-AdminLTE#1298]
Hi,
I noticed some basic Laravel files have gone missing when I installed  Laravel-AdminLTE in my project.
Few more middleware  files are missing too.
Is this a known issue?
I need to disable CSRF Protection for Specific Routes.
Is there a way this could work without a middleware?

**Comment by dfsmania** [comment]
Hi @chanakaDe Laravel files are not deleted during the installation process. Did you use the installation process mentioned [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation)?

On the other hand, what Laravel version are you using, and what version of the package are you installing?

**Comment by chanakaDe** [comment]
Hi @dfsmania Thank you so much.
I'm using Laravel Framework 11.19.0.
Yes I followed the instruction thee & got the latest version.
Is there a known way to repair Laravel installation ? :-)

**Comment by dfsmania** [comment]
I don't know if there is a way to restore a Laravel installation. If your project was tracked with a control version system, then you can figure out what files you deleted locally and restore they from the upstream.

If you just deleted files from the **vendor** folder, then executing **composer install** or **composer update** should restore them.

I'm not sure what you have done, can you share some screenshots or details of your issues?

**Comment by chanakaDe** [comment]
@dfsmania  t seems in Laravel 11, we have no Middleware folder by default.
""Laravel 11 does not include the app/Http/Middleware folder unless you create or need custom middleware. This is because Laravel tries to keep the directory structure minimal and only includes directories that are actually in use."". Not an issue. Thank you for information.

**Comment by dfsmania** [comment]
@chanakaDe Oh, yeah they simplified the folder structure in version 11 (some middlewares were moved to the illuminate framework I think). So, it was just a misunderstood or this package have some kind of issue when installing on Laravel 11?
Can we close the issue?

**Comment by chanakaDe** [comment]
@dfsmania  yes of course we can close the issue.
There are no issues with this package & Laravel 11. 
Works fine.
Sorry for my misunderstanding if that caused any trouble. 👍🏻
