### ISSUE TITLE
Menu configuration at runtime support sub-menu (level 2)

### ISSUE THREAD

**Issue by HKGeeks** [JeroenNoten/Laravel-AdminLTE#13]
Hi JeroenNoten,

Can it support sub-menu at runtime? thanks.

**Comment by JeroenNoten** [comment]
This is already possible, just specify submenu:

            $event->menu->add([
                'text' => 'Pages',
                'submenu' => [
                    // submenu here
                ]
            ]);

**Comment by HKGeeks** [comment]
Is that right?

```
$event->menu->add([
                    'text' => 'Databases',
                    'icon' => 'user',
                    'submenu' => [
                        'text' => 'Admin',
                        'url'  => 'admin/db-admin',
                        'icon' => 'user',
                    ]
                ]);
```

**Comment by JeroenNoten** [comment]
No, the submenu array must be an array of items:

    $event->menu->add([
        'text' => 'Databases',
        'icon' => 'user',
        'submenu' => [
            [
              'text' => 'Admin',
              'url'  => 'admin/db-admin',
              'icon' => 'user',
            ]
        ]
    ]);

**Comment by HKGeeks** [comment]
Thanks! It works!!

**Comment by johnef** [comment]
@jeroennoten can I do `forloop` in the  `sub-menu` at runtime?
I try something like this but didn't work

```
$event->menu->add([
    'text' => 'Databases',
    'icon' => 'user',
    'submenu' => [
        foreach ( $category as $cat ) {
				$event->menu->add(
					[
						'text'        => $cat->title,
						'label'       => $cat->proItem->count(),
						'label_color' => 'success',
						'url'         => 'admin/product-category/' . $cat->id,
					]
				);
			}
    ]
]);
```
