### ISSUE TITLE
select2 arrow with RTL direction [BUG]

### ISSUE THREAD

**Issue by maaaom** [jeroennoten/Laravel-AdminLTE#1300]
### Describe the bug
When I have select2 with adminLTE-RTL the arrow of dropdown overlapping the text in dropdown list.

### Steps To Reproduce
```
<div class="form-group">
                                    <label class="font-weight-bolder">{{__('App.sort_by')}}</label>
                                    <x-adminlte-select2 name="sort">
                                        <option>{{__('App.ASC')}}</option>
                                        <option>{{__('App.DESC')}}</option>
                                    </x-adminlte-select2>
                                </div>
```

### Expected behavior
the arrow should be in deferent side of the box.

### Screenshots
![Screen Shot 2024-08-04 at 11 36 28 PM](https://github.com/user-attachments/assets/fdc10ba5-7c02-44df-9ee6-84a3ff20d45e)

**Comment by dfsmania** [comment]
Closed, no feedback!
