### ISSUE TITLE
How can I apply a different layout (CSS) to this package?

### ISSUE THREAD

**Issue by aeusteixeira** [jeroennoten/Laravel-AdminLTE#1302]
I love this package and have developed at least four systems with it. However, they end up looking very similar, and some clients who use more than one of these systems have complained about this. Does anyone know of an external package that changes the CSS of all components, pages, etc., providing a different look?

**Comment by aeusteixeira** [comment]
I know I can write the CSS as needed, but I was wondering if anyone knows of any external packages that already provide a distinct look and feel out of the box.

**Comment by dfsmania** [comment]
Hello @aeusteixeira , I can't help you here, this package is based on the [AdminLTE v3](https://adminlte.io/themes/v3/) template, and most of the Admin templates looks similar, there's always a sidebar, navbar, footer, etc.

However, you are able to customize some colors of the template among other things, play with the right sidebar on the demo site I linked previously. Most of those options are supported on this package using the configuration.

Read the Wiki pages to know about the available layout options, specially the section [Layout and Styling Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration).
