### ISSUE TITLE
In the root menu items, the href attribute is not being set.

### ISSUE THREAD

**Issue by serg1764** [jeroennoten/Laravel-AdminLTE#1303]
Hello. This issue might have already been discussed here, but I couldn't find an answer. Maybe it's not even a bug.

In the root menu items, the href attribute isn't set.
For example, when I create

Goods
Electronics (no href attribute, even though it's specified in the 'menu' array in config/adminlte.php)
-- Phones (has href, link works)
-- Laptops (has href, link works)
Is there a way to fix this? Maybe there's some setting for it.
(At least for the desktop version)

**Comment by dfsmania** [comment]
Hi @serg1764 , If you're speaking about [submenu items](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-submenu-attribute), they are not intended to work as links, they just group other items in a submenu.

However, if you want to customize your own behavior, then you can [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and for this case change the logic in `resources/views/vendor/adminlte/partials/sidebar/menu-item-treeview-menu.blade.php`.

**Comment by serg1764** [comment]
Thank you so much, guys.

I did it roughly as recommended by rsscomunicamasa.

dfsmania, your advice will come in handy in the future.
I looked at the code in resources/views/vendor/adminlte/partials/sidebar/menu-item-treeview-menu.blade.php.
I might add some more logic too.)))
