### ISSUE TITLE
[BUG] Strange behavior menu with filter 

### ISSUE THREAD

**Issue by AlfioSaitta** [jeroennoten/Laravel-AdminLTE#1304]
### Describe the bug
I'm creating menus in runtime via a service, and everything seems to work as it should, but the items totally disappear if i add a new property and a filter.... in this case "CAN" to display or not a certain item.

I added some code to understand what was happening, and as i said... items with the value "can" are not read by the filter service.

### Steps To Reproduce

1. Added a menus with a **can** field in a ServiceProvider with a menuBuilder:

```
        $event->menu->add(
        [
            'text' => trans('app.dashboard'),
            'icon' => 'fa fa-home',
            'can' => 'dashboard',
            'url' => route('backend.dashboard'),
        ],
        [
            'text' => trans('app.terminal'),
            'icon' => 'fa fa-desktop',
            //'can' => 'users.manage',
            'url' => route('backend.terminal'),
        ],

```

2. Added a new FilterInterface...

```
    public function transform($item)
    {
        if ( isset($item['can']) && $item['type'] === 'text' ) {
            error_log('CAN:   ' . json_encode($item['can']), 0);
        } else {
            error_log('NO CAN:   ' . json_encode($item['class']));
        }

        if (!$this->isVisible($item)) {
            return false;
        }
        return $item;
    }
```

3. As a result, only items without the "can" parameter are caught by the filter:

```
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
[php:notice] [pid 111840:tid 111840] [client .:2038] NO CAN:   "", referer: https://???/backend/user/202/profile
```

### Expected behavior
Naturally, whether the item is displayed or not depends on the **can** parameter

### Screenshots
![image](https://github.com/user-attachments/assets/152fe9f4-3b1e-44dd-8ac9-b06bf73418f4)

### Environment
| Item    | Version
| ------- | -------
| Laravel | 9.52.16
| Project | ???
| OS      | Debian

**Comment by dfsmania** [comment]
Hi @AlfioSaitta , the [can attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) is already a built-in attribute that integrates with [Laravel's Gate](https://laravel.com/docs/11.x/authorization#gates). So, you can try with a different attribute name or you might try Laravel's Gate to perform your authorization rules...

**Comment by AlfioSaitta** [comment]
> Hi @AlfioSaitta , the [can attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) is already a built-in attribute that integrates with [Laravel's Gate](https://laravel.com/docs/11.x/authorization#gates). So, you can try with a different attribute name or you might try Laravel's Gate to perform your authorization rules...
> 
> If you still want to use the `can` attribute with your own filter implementation, then comment the `GateFilter` from the list of available [Menu Filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-filters) in the config file, and add your own filter to that list instead.

Thanks so much for the clarification. Initially as per your advice... i changed the attribute name to 'canuse', after this... i have disabled the Gate rule for use my own 'can' filter.
