### ISSUE TITLE
Cannot scroll or set width of right-sidebar

### ISSUE THREAD

**Issue by mjhcremer** [jeroennoten/Laravel-AdminLTE#1306]
### Describe the bug
If the content of the right-sidebar is to long I don't have the option to scroll.
How can I set the width of the right-sidebar it is to small for my project.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 11
| Project | 3.13.0
| OS      | MacOs

**Comment by dfsmania** [comment]
Please, read discussion in #906
It's not possible from this package, you'll have to download the AdminLte package, customize and built it to create your own customized distribution files for that package. Then replace the original distribution files used by this package with your own files.
