### ISSUE TITLE
[QUESTION] Is it possible to implement the "can" in menu and use the laravel spatie permisisons?

### ISSUE THREAD

**Issue by djgraphics28** [jeroennoten/Laravel-AdminLTE#1315]
### Is your request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when...

### Describe the solution you'd like
A clear and concise description of what you want to happen or the enhancement you want.

**Comment by dfsmania** [comment]
Hi @djgraphics28 , next time take your time to fill up the issue with details please. For your question it should be possible using a custom filter. Check [Menu Filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-filters) in the WIKI.
