### ISSUE TITLE
[FEATURE] x-adminlte-datatable responsive for devices

### ISSUE THREAD

**Issue by sistemas-snte56** [jeroennoten/Laravel-AdminLTE#1319]
### Is your request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when...

### Describe the solution you'd like
A clear and concise description of what you want to happen or the enhancement you want.

**Comment by dfsmania** [comment]
@sistemas-snte56 The `x-adminlte-datatable` component relies on the underlying [Datatables plugin](https://datatables.net/), that plugin already has some responsive implementation for devices, a horizontal scroll should appear when the screen width isn't enough. Please, fill with more details if you have any other issue...
