### ISSUE TITLE
[BUG] Navbar Links not works if redirect was there

### ISSUE THREAD

**Issue by hawkiq** [jeroennoten/Laravel-AdminLTE#1321]
### Describe the bug
I've added Menu links in navbar to change language for admin panel
by adding code in adminlte.php
```php
[
            'type' => 'navbar-menu', 
            'text' => '',
            'icon' => 'fas fa-globe',
            'topnav_right' => true,
            'submenu'     => [
                [
                    'text' => 'English',
                    'url'  => 'language/en',
                ],
                [
                    'text' => 'Arabic',
                    'url'  => 'language/ar',
                ],
            ],
        ],
```

everything was working perfect until I activated IFrame mode then when I click on language it will open new tab instead of refreshing the page, Is there any ability to prevent open link in new Tap for specific links and used as config

for example
```php
[
            'type' => 'navbar-menu', 
            'text' => '',
            'icon' => 'fas fa-globe',
            'topnav_right' => true,
            'submenu'     => [
                [
                    'text' => 'English',
                    'url'  => 'language/en',
                    'target'=>'page'// tab - blank - or whatever name you suggest
                ],
                [
                    'text' => 'Arabic',
                    'url'  => 'language/ar',
                    'target'=>'tab'
                ],
            ],
        ],
```

### Expected behavior
When changing language it should refresh the whole page not opening in new tab

### Screenshots
![image](https://github.com/user-attachments/assets/44acc1d1-2310-43d0-ab43-9e1dcfc691f6)

### Environment

| Item    | Version
| ------- | -------
| Laravel | 8.83.27
| OS      | Windows - Linux

**Comment by dfsmania** [comment]
@hawkiq We rely on the implementation of [AdminLTE/IFrame](https://adminlte.io/docs/3.2/javascript/iframe.html). There's an option to avoid capturing all navbar items (available in our config file too), but there's no way to disable it for a particular item. Maybe you can use some Javascript/JQuery to catch the `click` event on that link and `event.preventDefault()`, then call the redirects from Javascript.

**Comment by hawkiq** [comment]
> @hawkiq We rely on the implementation of [AdminLTE/IFrame](https://adminlte.io/docs/3.2/javascript/iframe.html). There's an option to avoid capturing all navbar items (available in our config file too), but there's no way to disable it for a particular item. Maybe you can use some Javascript/JQuery to catch the `click` event on that link and `event.preventDefault()`, then call the redirects from Javascript.
> ### Use next example as reference (tested locally)
> 
> To disable **IFrame capturing** at you particular item, yo may follow next steps:
> 
> On your menu item configuration add an `id` property (note type property is no needed here):
> 
> ```
> [
>     'id' => 'lang-selector',
>     'text' => '',
>     'icon' => 'fas fa-globe',
>     'topnav_right' => true,
>     'submenu' => [
>         [
>             'text' => 'English',
>             'url'  => 'language/en',
>         ],
>         [
>             'text' => 'Arabic',
>             'url'  => 'language/ar',
>         ],
>     ],
> ],
> ```
> 
> Then, in your [application layout](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage#recommended-way-of-use) or where you define common code for your layout, you may include next JQuery code:
> 
> ```js
> $(document).ready(function() {
> 
>     // XXX: Test disable IFrame mode capturing on particular navbar link:
> 
>     $('#lang-selector .dropdown-item').on('click', function(e) {
>         e.preventDefault();
>         e.stopPropagation();
>         window.location.href = $(this).attr('href');
>     });
> });
> ```

I can confirm this works perfectly , but since I don't want to edit any files I used option in config 'use_navbar_items' => false, so it wont capture navbar links only and this was fine for me.
