### ISSUE TITLE
[BUG]Dropdown not working on bootstrap 5.3

### ISSUE THREAD

**Issue by vicky-project** [jeroennoten/Laravel-AdminLTE#1322]
### Describe the bug
When using bootstrap v5.3 dropdown not working while click icon on navbar item.

### Steps To Reproduce
I found in file NavbarNotification.php in method makeAnchorDefaultAttrs sent data-toggle attribute since it is not working now in bootstrap 5.3

### Expected behavior
Please to replace attribute data-toggle to data-bs-toggle instead. I don't now it will be working on another bootstrap version or not. Maybe you can resolve this issue. Thanks!

| Item    | Version
| ------- | -------
| Laravel | 11.30.0
| Project | 3.14.2
| OS      | Linux

**Comment by dfsmania** [comment]
@vicky-project , This package integrates **AdminLTE v3.2** template into Laravel, which is based on **Bootstrap 4.x**. I'm not sure how you are using **Bootstrap 5.x** with this package, but that's a mistake, you will have a lot of conflicts. Currently there's a **AdminLTE v4** in development for **Bootstrap 5.x**, maybe you can look around it if **Bootstrap 5.x** is a must for your project.  Read #1286 for more details...

**Comment by dfsmania** [comment]
Closed, no feedback, explanation given...
