### ISSUE TITLE
[FEATURE] Page Title / Header placement next to the Hamburger Menu

### ISSUE THREAD

**Issue by CreativeWolf** [jeroennoten/Laravel-AdminLTE#1324]
Firstly, thank you for this fantastic work!
### Is your request related to a problem? Please describe.
I've chosen to use the sidebar as navbar and with that there's a lot of estate space in the top, in particular the page title / header can be placed there. 

### Describe the solution you'd like
I'd like to be able to configure the Page title / header and place it next to the hamburger menu

### Describe alternatives you've considered
The alternatives are wasting a lot of estate space

### Additional context
Attached screenshot for reference and you can see the page title - "Departments" can rather be placed next to the hamburger menu instead, thus saving a lot of estate space.
<img width="953" alt="adminlte-screenshot" src="https://github.com/user-attachments/assets/92337e70-387f-4a2f-9fcd-84536e6cc88f">

**Comment by dfsmania** [comment]
Hello @CreativeWolf , that is a such customization you can make by [publishing the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and do some changes on the layout. After publishing the package views, first edit next file to add the **content header** into the **navbar**:

#### resources/views/vendor/adminlte/partials/navbar/navbar.blade.php
```blade
@inject('layoutHelper', 'JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper')

<nav class="main-header navbar
    {{ config('adminlte.classes_topnav_nav', 'navbar-expand') }}
    {{ config('adminlte.classes_topnav', 'navbar-white navbar-light') }}">

    {{-- Navbar left links --}}
    <ul class="navbar-nav">
        {{-- Left sidebar toggler link --}}
        @include('adminlte::partials.navbar.menu-item-left-sidebar-toggler')

        {{-- NEW CONTENT HEADER NOW ON NAVBAR --}}
        @hasSection('content_header')
            <span class="content-header p-0 m-0">
                @yield('content_header')
            </span>
        @endif

        {{-- Configured left links --}}
        @each('adminlte::partials.navbar.menu-item', $adminlte->menu('navbar-left'), 'item')

        {{-- Custom left links --}}
        @yield('content_top_nav_left')
    </ul>

    {{-- Navbar right links --}}
    <ul class="navbar-nav ml-auto">
        {{-- Custom right links --}}
        @yield('content_top_nav_right')

        {{-- Configured right links --}}
        @each('adminlte::partials.navbar.menu-item', $adminlte->menu('navbar-right'), 'item')

        {{-- User menu link --}}
        @if(Auth::user())
            @if(config('adminlte.usermenu_enabled'))
                @include('adminlte::partials.navbar.menu-item-dropdown-user-menu')
            @else
                @include('adminlte::partials.navbar.menu-item-logout-link')
            @endif
        @endif

        {{-- Right sidebar toggler link --}}
        @if($layoutHelper->isRightSidebarEnabled())
            @include('adminlte::partials.navbar.menu-item-right-sidebar-toggler')
        @endif
    </ul>

</nav>
```

Then just comment out the **content header** section from next file:

#### resources/views/vendor/adminlte/partials/cwrapper/cwrapper-default.blade.php
```blade
@inject('layoutHelper', 'JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper')
@inject('preloaderHelper', 'JeroenNoten\LaravelAdminLte\Helpers\preloaderHelper')

@if($layoutHelper->isLayoutTopnavEnabled())
    @php( $def_container_class = 'container' )
@else
    @php( $def_container_class = 'container-fluid' )
@endif

{{-- Default Content Wrapper --}}
<div class="{{ $layoutHelper->makeContentWrapperClasses() }}">

    {{-- Preloader Animation (cwrapper mode) --}}
    @if($preloaderHelper->isPreloaderEnabled('cwrapper'))
        @include('adminlte::partials.common.preloader')
    @endif

    {{-- Content Header --}}
    {{--
    @hasSection('content_header')
        <div class="content-header">
            <div class="{{ config('adminlte.classes_content_header') ?: $def_container_class }}">
                @yield('content_header')
            </div>
        </div>
    @endif
    --}}

    {{-- Main Content --}}
    <div class="content">
        <div class="{{ config('adminlte.classes_content') ?: $def_container_class }}">
            @stack('content')
            @yield('content')
        </div>
    </div>

</div>
```

However take note that long titles on the navbar won't look nicely on devices with small screen width (like a cellphone). I can't include this option on the base package because this isn't also compatible with the **layout topnav only mode** (i.e. when there isn't a sidebar).

**Comment by CreativeWolf** [comment]
Thank you for taking your time for putting this how-to together for me, appreciate it a lot.

I also understand why it may not fit in the base due to the constraints you had mentioned.

I will try these steps and get it done.

Thanks again.
