### ISSUE TITLE
[FEATURE] Creating Dynamic Sidebar Menu

### ISSUE THREAD

**Issue by bulfaitelo** [jeroennoten/Laravel-AdminLTE#1325]
### Is your request related to a problem? Describe it.
It is not necessarily a problem, but rather a feature.

### Describe the solution you'd like
We have the sidebar menu and the sidebar search, we could create one that integrated the two, for example:
The first search would be in the menu 'sidebar-menu-search', if it does not exist in the menu the search would direct to the custom search like 'sidebar-custom-search'.

### Describe alternatives you've considered
Today, I leave the navbar menu for searches, and the sidebar for menu searches.

### Additional context
This change would generally make it easier to use the menu. And forgive me for my English.

**Comment by dfsmania** [comment]
@bulfaitelo I'm not sure if I understand correctly your proposing, however, the **sidebar menu search** is part of the underlying **AdminLTE v3.2** package, we just created an easy way to use it here, so we can't touch any logic there. Also, it performs the search directly on the client side whitout any interaction with the server. On the other side, the custom search requires a request to the server and wait for a response with the results of the search. They are for different purposes, and I'm not seeing a clean path to integrate both into one. If you find a way, you are free to propose a **PR** for this feature.

Regards!

**Comment by dfsmania** [comment]
Closed, no feedback!
