### ISSUE TITLE
Problem with Custom Filter with the Laratrust module.

### ISSUE THREAD

**Issue by yorkcorpthe** [jeroennoten/Laravel-AdminLTE#1327]
### Describe the bug
I noticed an issue with the custom filter syntax not being correct with the Laratrust module.

### Steps To Reproduce
1.  Go to 
![image](https://github.com/user-attachments/assets/379346bf-7fc9-438d-94e2-d8be299203bd)
2. Go to config/adminlte.php
![image](https://github.com/user-attachments/assets/a86253a7-0ee2-4288-9d13-9c19b06e0924)
3.Go to      /*
    |--------------------------------------------------------------------------
    | Menu Items
    |--------------------------------------------------------------------------
    |
    | Here we can modify the sidebar/top navigation of the admin panel.
    |
    | For detailed instructions you can look here:
    | https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration
    |
    */

            'text' => 'Graficas',
            'url' => 'admin/charts',
            'permission' => 'read-customers',
            'icon' => 'fas fa-fw fa-chart-line',
        ],
        // [
        //     'text' => 'change_password',
        //     'url' => 'admin/settings',
        //     'icon' => 'fas fa-fw fa-lock',
        // ],
        [
            'text' => 'Clientes',
            'url' => 'admin/customers',
            'icon' => 'fas fa-fw fa-user',
            'submenu' => [

                [
                    'text' => 'Listado',
                    'url' => 'admin/customers',
                    'icon' => 'fas fa-fw fa-list',
                   'permission' => 'read-customers',

                ],
                [
                    'text' => 'Crear',
                    'url' => 'admin/customers/create',
                    'icon_color' => 'red',
                    'icon' => 'fas fa-fw fa-plus-circle',
                    'permission' => 'read-customers',

                ],

               ],
           ],
6. See error
Call to undefined method Laratrust\Laratrust::isAbleTo()

### Screenshots
If applicable, add screenshots to help explain your problem or to shown the issue.

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------

        "php": "8.3.10",
        "jeroennoten/laravel-adminlte": "^3.14",
        "laravel-lang/common": "^6.4",
        "laravel/framework": "^11.31",    
        "laravel/ui": "^4.6",
        "santigarcor/laratrust": "^8.3"
    },
![Captura de pantalla 2024-12-14 103643](https://github.com/user-attachments/assets/3111226c-1854-4fb4-a0e2-5b21380bd356)

### Additional context
Add any other context about the problem here. If you already have ideas to solve the issue, add them here or create a Pull Request (PR).

**Comment by dfsmania** [comment]
@yorkcorpthe Laratrust example was just provided as reference on the documentation, maybe that method is now deprecated in that package, if you found which one should be used here, please share so we can update docs.

**Comment by dfsmania** [comment]
No feedback from the author, closed!
