### ISSUE TITLE
AdminLTE v2.4.0

### ISSUE THREAD

**Issue by hackel** [jeroennoten/Laravel-AdminLTE#133]
A new version of AdminLTE is out.  The changes are rather minimal:
https://adminlte.io/docs/2.4/upgrade-guide

I'm mostly pointing this out as a warning, since I use the assets from the adminlte npm package, and had to downgrade it to get them back in sync.

**Comment by jeroennoten** [comment]
Hi! Thanks. I am already busy with upgrading and will publish the new version soon.

**Comment by jeroennoten** [comment]
v1.22.0 of this package is just released and includes AdminLTE v2.4.0!
