### ISSUE TITLE
app.min.js request but only adminlte.min.js available at that path

### ISSUE THREAD

**Issue by judgej** [jeroennoten/Laravel-AdminLTE#134]
Installed on Laravel Spark (based on laravel 5.5).

The AdminLTE pages are calling for:

https://example.co.uk/vendor/adminlte/dist/js/app.min.js

but the script they need is:

https://example.co.uk/vendor/adminlte/dist/js/adminlte.min.js

Is this a general bug, a Spark-related bug, or am I missing some kind of fancy asset building step in the installation?

**Comment by jeroennoten** [comment]
Hi! Thanks for reporting. This is indeed a bug, introduced when I upgraded to AdminLTE v2.4.0.

If you update this package to v1.22.1, it should be fixed.

**Comment by judgej** [comment]
That was super-zippy quick-fast! Thanks, that works now.
