### ISSUE TITLE
QUESTION: Remember open/closed state of the side menu?

### ISSUE THREAD

**Issue by judgej** [jeroennoten/Laravel-AdminLTE#135]
The state of the side menu does not seem to be remembered. If I close it, on the next page it is open again.

Is there a callback to handle remembering the state in the session? Or perhaps there is a front-end plugin that remembers it in the browser (if that is possible)? Or am I just mis-configured?

**Comment by bellwood** [comment]
Take a peak at the following contributions at the official repo for AdminLTE:

https://github.com/almasaeed2010/AdminLTE/issues/896

https://github.com/almasaeed2010/AdminLTE/issues/1240

**Comment by asartz** [comment]
I went server side to resolve this. 

you need to set up an ajax call when sidebar open/close state changes. But you also need some javascript: see

https://github.com/almasaeed2010/AdminLTE/issues/1240#issuecomment-339894053

run this javascript, after your app.js (adminlte.js) has been loaded. EnableRemember enables/disables this functionality.

                var adminLTESidebarTweak = {};

                adminLTESidebarTweak.options = {
                    EnableRemember: true
                };

                $(function () {
                    "use strict";

                    var body = $("body");

                    body.on("collapsed.pushMenu", function () {
                        if (adminLTESidebarTweak.options.EnableRemember) {
                            $.post("{{ url()->route('sidebar-admin-state') }}", {theme_sidebar_toggle_state: 'closed'}, function (data) {
                            });
                        }
                    });

                    body.on("expanded.pushMenu", function () {
                        if (adminLTESidebarTweak.options.EnableRemember) {
                            $.post("{{ url()->route('sidebar-admin-state') }}", {theme_sidebar_toggle_state: 'opened'}, function (data) {
                            });
                        }
                    });
                });

as you see every time state changes a post request is made to sidebar-admin-state route.
on your routes file:

    Route::post('sidebar/admin/state', function (Request $request) {
        $state = $request::get('theme_sidebar_toggle_state', 'opened');

        $request::session()->put('theme_sidebar_toggle_state', $state);

    })->name('sidebar-admin-state');

all this does is saving the sidebar state to session. now the last part is altering your page.blade.php

in the beginning of the file you see 

    @section('body_class', ....

mine, after changing it, looks like

    @section('body_class', 'skin-' . config('adminlte.skin', 'blue') . ' sidebar-mini ' . 
    (config('adminlte.layout') ? [
    'boxed' => 'layout-boxed',
    'fixed' => 'fixed',
    'top-nav' => 'layout-top-nav'
    ][config('adminlte.layout')] : '') . (config('adminlte.collapse_sidebar') || (session()-
    >get('theme_sidebar_toggle_state', '') === 'closed') ? ' sidebar-collapse ' : ''))

as you see,  if session()->get('theme_sidebar_toggle_state', '') === 'closed' then the sidebar-collapse class is being applied

**Comment by lacodimizer** [comment]
Is the issue actual?

**Comment by lacodimizer** [comment]
@REJack a new feature with js cookie?

**Comment by REJack** [comment]
@lacodimizer This issue can closed, we added already a option for this (sidebar_collapse_remember) based on AdmInLTE v3's builtin feature.
