### ISSUE TITLE
QUESTION:How to use multiple admin LTE layouts? 

### ISSUE THREAD

**Issue by randikagit** [jeroennoten/Laravel-AdminLTE#136]
I need to use different AdminLTE layouts for different pages with specific config files for those layouts. How can I do this by using this package?

**Comment by bellwood** [comment]
If you need custom menuing per page, built it at runtime:

https://github.com/jeroennoten/Laravel-AdminLTE#menu-configuration-at-runtime

If you need different layouts per page, fixed, etc then you'll need to adapt your views and the structure of the package so you can set that per-view, example, see how you're able to set the page title per view, you'd need to do the same but for the layout.

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.

**Comment by fdelvals** [comment]
I also need to have 2 config files to be able to set up 2 different menues.. any idea how to do it?

**Comment by dfsmania** [comment]
If your menu needs to be dynamically created, based on some sort of parameter, then you may use [Menu Configuration At Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime) and setup an empty array on the config file.
