### ISSUE TITLE
how to add more plugins in adminlte config file 

### ISSUE THREAD

**Issue by cs-abdulwahab** [jeroennoten/Laravel-AdminLTE#138]
How to add more plugins other than select2 and datatables   like  icheck and others

**Comment by dshoreman** [comment]
It's easiest to add the JS and CSS files yourself from your Blade template.

The plugins are a bit broken - icheck only gets loaded on the login page, and only one skin is included. Meanwhile tablesorter adds the jquery bits so you have to disable the plugin and add the assets manually if you want the Bootstrap functionality.

Luckily the master template yields assets, so we can get it working like this:
```html
@section('css')
<link href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/flat/purple.css" rel="stylesheet">
@stop

@section('js')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script>
    $(function() {
        $('.datatable').DataTable();
        $('input').iCheck({
            checkboxClass: 'icheckbox_square_purple',
            radioClass: 'iradio_square_purple'
        });
    });
</script>
@stop

**Comment by DaniloBenevides** [comment]
Is a good idea to set iCheck as a plugin like select2, chartjs or datatables ?

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
