### ISSUE TITLE
Can Menus have the class="Active"?

### ISSUE THREAD

**Issue by HKGeeks** [jeroennoten/Laravel-AdminLTE#14]
Hi JeroenNoten,

How can I set the menu (anchor class Active) when the URL equal to current URL?

Thanks.

**Comment by JeroenNoten** [comment]
This is not supported yet. A pull request that adds this feature is more than welcome.

**Comment by loekiedepo** [comment]
Interested in this too. If I can find some free time this weekend, I'll look at it.

**Comment by jeroennoten** [comment]
This feature is added in version 1.7.0! Thank you all.
