### ISSUE TITLE
how to translate the side menu

### ISSUE THREAD

**Issue by johnef** [jeroennoten/Laravel-AdminLTE#142]
I saw the translation in the package but I didn't get how to translate the menu
I try to make new translation file under `resources\lang\ar\adminlte.php` and in my `cofig` file I try to do something like this 

```
[
      'header' => 'adminlte.mainnavigation'
 ],
```

but it didn't work as expected
I got `adminlte.mainnavigation`

**Comment by bellwood** [comment]
https://laravel.com/docs/5.5/localization#using-translation-strings-as-keys

**Comment by opnczk** [comment]
Using translator does not work in config files, so you need to publish the adminlte views, and change the line "<span>{{ $item['text'] }}</span>" to "<span>@lang($item['text'])</span>" in views/vendor/adminlte/partials/menu-item.blade.php in order to see translation working in the side menu.

**Comment by CrazyFreeMan** [comment]
see #194

**Comment by lacodimizer** [comment]
Menu translation is coming in the next release.
