### ISSUE TITLE
ISSUE: footer is missing

### ISSUE THREAD

**Issue by bellwood** [jeroennoten/Laravel-AdminLTE#146]
master.blade.php is missing section/output for the footer adminlte includes

```
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright © 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>
```

Could this be added as an option?

**Comment by PaulinPrize** [comment]
I have the same problem but mine occurs when the page contains a lot of elements. Can anyone help me?
![capture](https://user-images.githubusercontent.com/41732884/47354104-18065a80-d6be-11e8-9cb9-251c9070d5b6.PNG)

**Comment by lacodimizer** [comment]
A footer section comes in the coming release.

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
