### ISSUE TITLE
Integration of jeroennoten/Laravel-AdminLTE with Zizaco/entrust

### ISSUE THREAD

**Issue by epalen** [jeroennoten/Laravel-AdminLTE#147]
I am interested in integrating jeroennoten / Laravel-AdminLTE with Zizaco / entrust, for the management of roles and persmisos.

How can I do this without affecting component integrity?

I have used both but I have to build an independent menu assigning the roles and permissions.

**Comment by eniumcriacaodesites** [comment]
Were you able to solve the problem?
