### ISSUE TITLE
User Panel in left side menu

### ISSUE THREAD

**Issue by Piotruni0** [jeroennoten/Laravel-AdminLTE#148]
How to add user panel on left sidebar.
![bez tytulu](https://user-images.githubusercontent.com/15848013/32135377-85c09dc8-bbfe-11e7-9138-6e056ed25a6b.png)

**Comment by ToeiRei** [comment]
Looking at https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/page.blade.php I suspect this implementation doesn't come with batteries - you'd have to do your own page.blade.php

**Comment by bellwood** [comment]
Exactly what I did

**Comment by jeroennoten** [comment]
Indeed. I am planning to add more features when I have time, but have to add it yourself until then. Pull requests are very welcome though.

**Comment by InfoO2** [comment]
Sorry I wanted to this, is this feature available now? Because I can't find it inside the configuration, correct me if I was wrong.

**Comment by beyondscript** [comment]
> Looking at https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/page.blade.php I suspect this implementation doesn't come with batteries - you'd have to do your own page.blade.php
> 
> `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views` should do the trick and you'll find the views in your projects views where you may add something like `@yield('sidebar_top')`

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views is showing: No publishable resources for tag [views]

**Comment by dfsmania** [comment]
@beyondscript I assume that's an old procedure for publishing package views, now you need to proceed as explained in [Views Customization](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization).
