### ISSUE TITLE
HELP : how to foreach loop items into submenu 

### ISSUE THREAD

**Issue by johnef** [jeroennoten/Laravel-AdminLTE#149]
Hi @jeroennoten  and @apisznasdin I need help on this please
I am using configuration at runtime menu

and I have submenu into it

something like this

```
$event->menu->add( 'MEDIA' );
	$event->menu->add(
		[
			'text'       => 'About us',
			'icon_color' => 'green',
			'submenu'    => [
				[ ],
			],
		] ); 
```

now I need to do `foreach` loop inside the `submenu`
how this can be done

thanks a loot

**Comment by Piotruni0** [comment]
$event->menu->add('BRANDS');
            foreach ($brands as $brand) {
                $event->menu->add(
                    [
                        'text' => $brand->Name,
                    ]);
            }

**Comment by johnef** [comment]
@Piotruni0 thanks at last someone is here :) I do understand it can be done like this but it's the `submenu` which I need to loop in not the main menu, thanks again

**Comment by johnef** [comment]
Hi I try to do something like this 

```
//Portal Section
			$event->menu->add( 'MEDIA' );
			$event->menu->add(
				[
					'text'       => 'About us',
					'icon_color' => 'green',
					'submenu'    => [
						$submenu = [],
					],
				] );

			//dd( $event );
			$abouts = About::all();
			foreach ( $abouts as $about ) {
				$event->menu->add(
					$submenu = [
						'text'       => $about->title,
						'icon_color' => "lime",
						'url'        => 'admin/about/1/edit',
					] );
			} 
```

but got an error

> Undefined index: text (View: .....\resources\views\vendor\adminlte\partials\menu-item.blade.php

**Comment by Piotruni0** [comment]
Try this 
`//Portal Section
			$event->menu->add( 'MEDIA' );

			foreach ( $abouts as $about ) {
					$submenu[] = [
						'text'       => $about->title,
						'icon_color' => "lime",
						'url'        => 'admin/about/1/edit',
					] );
			}


			$event->menu->add(
				[
					'text'       => 'About us',
					'icon_color' => 'green',
					'submenu'    =>$submenu,
				] );

			//dd( $event );
			$abouts = About::all();
 `

**Comment by johnef** [comment]
thanks very much @Piotruni0 you saved me another day :)

**Comment by Lipegs** [comment]
Tks @Piotruni0
