### ISSUE TITLE
Fixed layout menu doesnot scroll

### ISSUE THREAD

**Issue by emabusi** [jeroennoten/Laravel-AdminLTE#152]
On AdminLTE fixed layout, when the menu items are many - the menu should be scrollable but while using the plugin the menu is not scrollable

**Comment by bellwood** [comment]
Doesn't look like the author included slimscroll which is used/required for that functionality 😞

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
