### ISSUE TITLE
No wrapping div.container when NOT using top-nav, columns not displaying properly.

### ISSUE THREAD

**Issue by superDuperCyberTechno** [jeroennoten/Laravel-AdminLTE#153]
As far as I can tell, the content of a Bootstrap page is supposed to be wrapped in a `div.container`/`div.container-fluid` element, yet according to your source code, this is only included if the `top-nav` is used: https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/page.blade.php#L106

Also, I tried to emulate [this ](https://getbootstrap.com/docs/4.0/layout/grid/#auto-layout-columns)Bootstrap column behaviour, but the layout always ends up looking like this:

![image](https://user-images.githubusercontent.com/6486383/32779754-36c68bf8-c93f-11e7-993b-9b2843803454.png)

Am I missing something?

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
