### ISSUE TITLE
making separate side menu for admin than user

### ISSUE THREAD

**Issue by aamirkhan37557** [jeroennoten/Laravel-AdminLTE#159]
i want that in multi authentication both admin and user have separate menu not the same menu 
i have copied the code of page.blade.php and named it p1.blade.php this newly create page is just for admin which is for the purpose of distinct side meu of admin from user but it is giving me error

Undefined variable: adminlte (View: C:\xampp\htdocs\singleauth\resources\views\vendor\adminlte\p1.blade.php) (View: C:\xampp\htdocs\singleauth\resources\views\vendor\adminlte\p1.blade.php)

when i remove this code 
 @each('adminlte::partials.menu-item', $adminlte->menu(), 'item') 
from 
<ul class="sidebar-menu" data-widget="tree">
                
                </ul>
then it don,t give me error but it does not show me any thing 

i just want differnt side menu link of admin from user i want to customize the side menu for admin and want to use the defalut side menu for user

**Comment by putrafajarh** [comment]
up, i have same problem'

Undefined variable: adminlte

**Comment by PaulinPrize** [comment]
@aamirkhan37557 how do you do it?

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
