### ISSUE TITLE
QUESTION: help wanted

### ISSUE THREAD

**Issue by aamirkhan37557** [jeroennoten/Laravel-AdminLTE#160]
i want that in multi authentication both admin and user have separate menu not the same menu
i have copied the code of page.blade.php and named it p1.blade.php this newly create page is just for admin which is for the purpose of distinct side meu of admin from user but it is giving me error

Undefined variable: adminlte (View: C:\xampp\htdocs\singleauth\resources\views\vendor\adminlte\p1.blade.php) (View: C:\xampp\htdocs\singleauth\resources\views\vendor\adminlte\p1.blade.php)

when i remove this code
@each('adminlte::partials.menu-item', $adminlte->menu(), 'item')
from

            </ul>
then it don,t give me error but it does not show me any thing

i just want differnt side menu link of admin from user i want to customize the side menu for admin and want to use the defalut side menu for user

**Comment by lacodimizer** [comment]
Is the issue actual?
