### ISSUE TITLE
Possibility for dynamically creating submenus?

### ISSUE THREAD

**Issue by ToeiRei** [jeroennoten/Laravel-AdminLTE#162]
Hi guys,

I'm hooking into my app's main providers boot() to make a menu as shown in the README.md file. How does that work with submenus?

cheers
Rei

**Comment by ToeiRei** [comment]
never mind.

`'submenu' => array([]);` does the trick.

**Comment by jhosepharaujo** [comment]
Hello @ToeiRei , how did you to add the menu and submenu dynamically? Did you use recursion? Would you like to share the form you used?

**Comment by ToeiRei** [comment]
@jhosepharaujo have a look at https://github.com/jeroennoten/Laravel-AdminLTE#menu-configuration-at-runtime

**Comment by jhowbhz** [comment]
### After much research and suffering ... 
I found a solution to assemble your MENU and SUBMENU by the time of execution

Example:

```
// your model Menu
use App\Models\Menu;

class AppServiceProvider extends ServiceProvider{

    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ]
    ];
    public function boot(Dispatcher $events) {

       // ...... your sintaxe

        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {

            $event->menu->add('MENU DE NAVEGAÇÃO');

            $menu = new Menu;
            $menus = $menu->withSubMenus();

            foreach($menus as $menu){

                $arrayMenu = array('text' => '', 'url' => '', 'icon' => '');

                if(count($menu->SubMenu) != NULL){
                    foreach($menu->SubMenu as $submenu){
                        $arrayMenu[] = array(
                            'text' => $submenu->name,
                            'url' => $submenu->url,
                            'icon' => $submenu->icon
                        );

                    };
                    $event->menu->add([
                        'text' => $menu->name,
                        'url' => $menu->url,
                        'icon' => $menu->icon,
                        'submenu' => $arrayMenu,
                    ]);
                }else{
                    $event->menu->add([
                        'text' => $menu->name,
                        'url' => $menu->url,
                        'icon' => $menu->icon,
                    ]);
                }
            }
        });
    }
}
```
**Documentation of  Laravel-AdminLTE:** 
https://github.com/jeroennoten/Laravel-AdminLTE#menu-configuration-at-runtime
_Sorry for my bad english_

**Comment by andersonabreu0606** [comment]
Hello!!!

I solved my problem, with menu and submenu in table on database, with this:

In AppServiceProvider.php

    public function boot(Dispatcher $events){
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add(trans('Menu'));

            $items = Menu::where('fk_menu')->with('menuSubMenu')->get();
            $return = [];
            foreach ($items as $m => $menu) {
                $return[$m] = ['text' => $menu['na_menu'], 'icon' => 'fas fa-fw fa-'. $menu['na_icon']];
                    foreach ($menu['menuSubMenu'] as $s => $menus) {
                    $return[$m]['submenu'][$s] = ['text' => $menus['na_menu'], 'url' => $menus['na_route'], 'icon' => 'fas fa-fw fa-'.$menus['na_icon']];
                }
            }
            $event->menu->add(...$return);
      });
    }
