### ISSUE TITLE
QUESTION: Modifying menu url dynamically

### ISSUE THREAD

**Issue by webspeaks** [jeroennoten/Laravel-AdminLTE#168]
I need to change the URL of a menu item dynamically (based on API response). How can I do that?

If this is not possible, how can I add a submenu to main menu item at runtime. I see that runtime configuration allows me to add all new menu items with submenu but it does not allow to add submenus to existing parent menus. Is it possible?

**Comment by lacodimizer** [comment]
Is the issue actual?
