### ISSUE TITLE
Edit Forms and Messages

### ISSUE THREAD

**Issue by mateushackfaccat** [jeroennoten/Laravel-AdminLTE#172]
I'm trying to edit the messages like, "Register a new membership", "Full Name" and even add an extra field there in register.blade.php.
As I understand it, the messages are pre-set according to an example of the code below:

`<p class =" login-box-msg "> {{trans ('adminlte :: adminlte.register_message')}} </ p>

However there in the config/adminlte.php file there is no "register_message" field.
My question is how is it done, so I can add another field in the register.blade, I need to understand this.

**Comment by jeroennoten** [comment]
Hi! Take a look at https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/README.md#6-translations

**Comment by mateushackfaccat** [comment]
Thanks!
