### ISSUE TITLE
ISSUE: Menus are not shown as permissions when using multi auth

### ISSUE THREAD

**Issue by bigbharatjain** [jeroennoten/Laravel-AdminLTE#173]
I am having two type of users: admin and customers. Both are having different table and model.
So if I logged in admin and then I login customer user, admin menus are hidden. 
This issue occurs only if both users are having same id.
This issue also occurs even when I am logged in both the users in seperate browser.
I see that there is model support, how to use that.
Please show any example.
Should I add complete model path in menu array or just a model name?
@jeroennoten @amnoth

**Comment by PaulinPrize** [comment]
@jeroennoten 

I have the same problem

**Comment by lacodimizer** [comment]
Is the issue actual?
