### ISSUE TITLE
After installing the AdminLTE routes.php are not working

### ISSUE THREAD

**Issue by AqibTeam** [jeroennoten/Laravel-AdminLTE#176]
I have this routes in routes.php.

Route::get('categories', 'CategoriesController@categories');	
Route::get('subcategories', 'SubCategoriesController@subcategories');	

The routes are not wotking after AdminLTE installation.

Thanks

**Comment by loekiedepo** [comment]
Do you have any error messages? "It is not working" has too many reasons to give proper support ;)
