### ISSUE TITLE
Double vertical scrollbar appears when sidemenu has many items

### ISSUE THREAD

**Issue by leonardonogueira94** [jeroennoten/Laravel-AdminLTE#177]
When the height of the side menu items is higher than the screen height, a doubled scroll bar appears. I already tried to put 'overflow-y: hidden' in some contents in AdminLTE.min.css, but it seems not to be effective.

![captura de tela 118](https://user-images.githubusercontent.com/20585942/35305320-11d37932-0080-11e8-97b4-2008cb2dd725.png)

I don't know what else to do.

**Comment by nknguyengl** [comment]
U need to add footer tag below `content-wrapper` 

`<footer class="main-footer">
	<div class="pull-right hidden-xs">
    	<b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights reserved.
</footer>`

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
