### ISSUE TITLE
QUESTION: Question about Resources.

### ISSUE THREAD

**Issue by mateushackfaccat** [jeroennoten/Laravel-AdminLTE#179]
I am using this package in my application.
Everything is ok. However, I use ADMINLTE's official website to get some visuals.
Like the date:
`<div class ="input-group date">
     <div class = "input-group-addon">
        <i class = "fa fa-calendar"> </ i>
     </ div>
     <input type = "text" class = "form-control pull-right" id = "datepicker">
</ div> `

In the example of the official site a calendar appears for the user to choose the referred date.
But when using with this package, it does not have this feature, and it is only as a normal edit.
Is there any package that needs to install or something?

**Comment by loekiedepo** [comment]
As you can see [on the plugin page](https://adminlte.io/docs/2.4/dependencies#plugins) of AdminLTE, there are some dependencies on datepicker plugins. These dependencies don't come with this implementation of AdminLTE, so you can you add them yourself if you need them.

**Comment by chaicai333** [comment]
Anyone know how to include the dependecies ?
On the https://bootstrap-datepicker.readthedocs.io/en/latest/
said need to $ lessc build/build_standalone.less datepicker.css
but in my project it has error saids no such file or directory

**Comment by lacodimizer** [comment]
Is the issue actual?
