### ISSUE TITLE
QUESTION: backpack integration

### ISSUE THREAD

**Issue by ijpatricio** [jeroennoten/Laravel-AdminLTE#182]
Hello @jeroennoten 
Awesome work with all
Gave the project a spin, to try out the permission based menu.
Added functionality to multiple menus, by name
$adminlte->menu('sidebar1') or $adminlte->menu('top1')
with repository pattern, so getting from a colelction within a class, or DB, same implementation.
would you like to see a PR?
also, would you mind i use this in a PR for backpack (despite the MIT licence, wanted to make sure you don't want to do this yourself)?

**Comment by lacodimizer** [comment]
Is the issue actual?
