### ISSUE TITLE
QUESTION: Use bootstrap 4

### ISSUE THREAD

**Issue by Xsur** [jeroennoten/Laravel-AdminLTE#183]
how can i use bosstrap 4 css on this theme u currently in use laravel 5.5 but i put some boostrap 4 component on content section the style is not change

![image](https://user-images.githubusercontent.com/25731857/36192810-d91c1992-1195-11e8-9e25-5f6db378b88c.png)

![image](https://user-images.githubusercontent.com/25731857/36192827-e8ff315a-1195-11e8-804f-fa6534a9a5b4.png)

**Comment by loekiedepo** [comment]
This repo closely follow the official AdminLTE repo. Since that one is still on Bootstrap 3, this is too.

You can however edit the templates and swap out the Bootstrap 3 css imports for your own (in this case, Bootstrap 4!): [Check chapter 7 of the README](https://github.com/jeroennoten/Laravel-AdminLTE#7-customize-views)

**Comment by Xsur** [comment]
ty for the responds,but first sorry im still new in laravel i think i had import boostrap 4 to laravel cause currently in use new laravel version but when i put boostrap 4 element like card its not work the style is not change like boostra4 documentation

**Comment by loekiedepo** [comment]
This has nothing to do with Laravel. Check your HTML / Blade files. In the AdminLTE views, Bootstrap 3 is imported. Just change this to import Bootstrap 4 and you're okay.

**Comment by ErmenegildoCumbe** [comment]
Morning, first of all sorry for my bad inglesh.
I'm trying to use this template for a very first time, so i'm facing a problem whem i try to use it. I have followed all the instructions on de ReadMe file but it doesn't work for me. 

I'm using Laravel 5.5. Would like to know how you implemented it in your projects, if u extracted the files to project or used other way...
Thamks

**Comment by loekiedepo** [comment]
> Morning, first of all sorry for my bad inglesh.
I'm trying to use this template for a very first time, so i'm facing a problem whem i try to use it. I have followed all the instructions on de ReadMe file but it doesn't work for me.
I'm using Laravel 5.5. Would like to know how you implemented it in your projects, if u extracted the files to project or used other way...
Thamks

It seems like you have a different question that what this topic is about. Please open a new question and explain thoroughly what you have done and what issue you're facing. "It doesn't work" isn't helpful enough for us to help you.

**Comment by lacodimizer** [comment]
Please wait for the official AdminLTE3 package. So we make this project compatible with AdminLTE3.

**Comment by marcelogarbin** [comment]
Hi, any news? what's the progress so far? thanks

**Comment by lacodimizer** [comment]
@REJack and I work hard on the new version 3 which include AdminLTE v3 with Bootstrap 4. This will be only available with Laravel 6.

**Comment by marcelogarbin** [comment]
> @REJack and I work hard on the new version 3 which include AdminLTE v3 with Bootstrap 4. This will be only available with Laravel 6.

Very good, thank you for your effort.

AdminLTE is a great admin panel, but I am pending to change it as it is already getting depleted by using Bootstrap 3.

I'm in a new project using Laravel 6, I tried to use the package with this version, but to no avail.

Error occurs when publishing assets.
I made this config in composer:
- "jeroennoten/laravel-adminlte": "dev-laravel6-adminlte3"

When I publish the assets this error occurs:
```bash
Copied Directory [/vendor/jeroennoten/laravel-adminlte/resources/views] To [/resources/views/vendor/adminlte]
Copied Directory [/vendor/jeroennoten/laravel-adminlte/resources/lang] To [/resources/lang/vendor/adminlte]
Can't locate path: </var/www/vendor/jeroennoten/laravel-adminlte/src/../resources/assets>
Publishing complete.
```

![image](https://user-images.githubusercontent.com/9335588/65768530-99087600-e107-11e9-915d-fa30772b4712.png)


Already available for use? How can I proceed?

**Comment by lacodimizer** [comment]
We changed the assets installer, so it's not stable at the moment. We work on it.

**Comment by lacodimizer** [comment]
@marcelogarbin you can try the new install command: adminlte:install
We integrated AdminLTE as composer dependency so we can update faster as actual.

**Comment by marcelogarbin** [comment]
I run the command here, without errors. But the page was not 100%. Not looking properly for assets, so I looked like they were published outside the `public/vendor/admin` folder..

![image](https://user-images.githubusercontent.com/9335588/65770237-0c13eb80-e10c-11e9-8d1e-b49649fabcac.png)

![image](https://user-images.githubusercontent.com/9335588/65770355-4a110f80-e10c-11e9-88d4-6ba6daaddfcc.png)

![image](https://user-images.githubusercontent.com/9335588/65770393-6319c080-e10c-11e9-8c37-1ee20552fb98.png)

**Comment by marcelogarbin** [comment]
I removed the old views and ran the command again: `adminlte:install --force` looks like it went well ...

![image](https://user-images.githubusercontent.com/9335588/65770649-e5a28000-e10c-11e9-8eac-6f6dd434d6da.png)

**Comment by marcelogarbin** [comment]
@lacodimizer Can I use this version for new projects or should I wait longer? Thanks

**Comment by lacodimizer** [comment]
Not for production use, but you can use it on own risk ;)

**Comment by marcelogarbin** [comment]
> Not for production use, but you can use it on own risk ;)

Thanks for the feedback. I really am out of time to help right away. I really liked the project, especially the menu can be added via providers (I currently use AdminLTE, but manually without this package - I found it by chance).. Maybe in the future I can collaborate with the project.

**Comment by lacodimizer** [comment]
I close the issue. Please follow the issue #334 which give updates for AdminLTE v3 with Bootstrap 4 support.
