### ISSUE TITLE
routes for another package not defined in config

### ISSUE THREAD

**Issue by judgej** [jeroennoten/Laravel-AdminLTE#187]
I'm not sure if this is solvable simply or not, but I have not been able to find any references to how to solve it. It depends, I think, on the order in which Laravel boots its packages, and I don't know if that cna be changed.

Basically, I am trying to use `route()` to define URLs for the menu in the config file. The routes I am using are defined in another package. Laravel is halting during the boot of AminLTE with the error:

> Route [myfoo.index] not defined.

It is defined, but I assume the package in which it is defined does not get booted until after AdminLTE. Is there any way to get the AminLTE package to boot later in the process?

**Comment by loekiedepo** [comment]
If you move the service providers for this package to the bottom of `config/app.php`, does that help? Or at least make sure that the provider for the package which routes you're using is above the declaration of this package:

```php
Your/Route/Provider::class,
JeroenNoten\LaravelAdminLte\ServiceProvider::class,
```

Also, which Laravel version are you using?

**Comment by judgej** [comment]
I can give that a go. I've not added any service providers to `app.php` so far, relying on Laravel's auto-discover. But if Laravel reads the explicit providers first, then that may give me all the control I need.

**Comment by judgej** [comment]
According [to this](https://github.com/laravel/framework/pull/19646) it should work, but does not seem to. In `app.php` I've added my depending package first (the one that defines the routes) and AdminLTE immediately afterwards, but still get the same "unknown route" error. According to that PR, putting a provider entry into `app.php` should move it from auto-discovery (which happens after the `Illuminate` packages, but before the remaining `app.php` packages) to the later position. I suspect maybe that PR does not quite do what is described, or maybe once the position is defined in the auto-discovery, then it is set.

However, I can disable auto-discovery for any package I like, so that may be the way to go.

**Comment by judgej** [comment]
Hmm, no, still does not seem to change the order. I think this is a Laravel issue that I need to follow up there.

I added this package to the `dont-discover` list:

```php
    "extra": {
        "laravel": {
            "dont-discover": [
                "jeroennoten/laravel-adminlte"
            ]
        }
    },
```

then refreshed the cache:

    ./artisan package:discover

and confirmed it did not work without an explicit entry in `app.php`. And still the route was not being found. I can only conclude *my* auto-discovered packages are not booting before the `app.php` providers list, as the Laravel docs say they should. That was L5.5 though, and things may have changed for L5.6 that I'm on now.

I'll put this to bed for now and just use the hard-coded URL fragments. It's something I can revisit later/ Hopefully there is something useful in this issue for anyone else hitting this problem. Thanks for your help.

**Comment by loekiedepo** [comment]
Hmm, this is pretty weird indeed. Also a reason why I try to avoid "magic" code like auto-discover (although the trade-off between "magic" and boilerplate is always hard).

I hope you can find a solution, keep us posted!

**Comment by judgej** [comment]
The menu is `adminlte.php` is just the starting point, I guess. It can be modified and rebuilt dynamically once things have started up.
