### ISSUE TITLE
Sidebar menu not changing 

### ISSUE THREAD

**Issue by rafayet-monon** [jeroennoten/Laravel-AdminLTE#188]
I have been working with this package for long but recent changes are applying in the sidemenu even if I'm changing in config/adminlte.php file. Restarting my apache2 didn't do the job. I'm at a loss here. Can anyone help?

[Here is the gist of config/adminlte.php](https://gist.github.com/rafayet-monon/5459068fa19a3f9cec076523c90d119b)

*I had a submenu name 'Upload Customer' which I removed but no changes in sidemenu, It's still there. 'Customer Report' and 'Agent Report' is in the file but not showing in sidemenu.

**Comment by loekiedepo** [comment]
Do you perhaps have your config file cached at `bootstrap/cache/config.php` (name might be different)? This way Laravel reads out of your cached file and ignores the one in `config/adminlte.php`.

**Comment by rafayet-monon** [comment]
Thanks a lot @loekiedepo , That was tge reason.

**Comment by megha-b89** [comment]
can you please send ur code

**Comment by aledc7** [comment]
2024 if you face with this problem, try to add this at the end of  the `config/cache.php` file:
```php
'stores' => [

        ... ahothers,

        'none' => [
            'driver' => 'null',
        ],

**Comment by stzoran1** [comment]
The AdminLte class is registered as a singleton. In Octane's worker mode, it persists across requests — so the menu builder compiles active states once and never rebuilds them. The first page you visit gets highlighted and stays highlighted forever.

Solution: Add AdminLte::class to Octane's flush array in config/octane.php:

```
'flush' => [
    \JeroenNoten\LaravelAdminLte\AdminLte::class,
],

```
Then run php artisan config:cache to pick up the change.
