### ISSUE TITLE
QUESTION: How to use Treeview?!

### ISSUE THREAD

**Issue by gaalves** [jeroennoten/Laravel-AdminLTE#189]
The standard menu only offers the possibility of
```
`'TESTE',
        [
            'text' => 'Groups',
            'url' => '/home',
            'icon' => 'users',
            'permission' => 'read-profile',

        ],`
```
![menu](https://user-images.githubusercontent.com/31774273/37309812-d20cef74-2620-11e8-853e-b8d37e9fde86.PNG)

wanted to use the following menu

![menu2](https://user-images.githubusercontent.com/31774273/37309860-f1795802-2620-11e8-9e60-440509d15a2e.PNG)

**Comment by loekiedepo** [comment]
If you need advanced functionality like this, you can always publish your views and edit them, or create your menu at runtime. The [official AdminLTE docs](https://adminlte.io/docs/2.4/js-tree) describe how you can create a tree menu.
