### ISSUE TITLE
jQuery wrong case

### ISSUE THREAD

**Issue by juliardi** [jeroennoten/Laravel-AdminLTE#19]
In resources/views/master.blade.php line 29, I think it should be 'jquery-2.2.3.min.js' not 'jQuery-2.2.3.min.js' because the jquery file is resources/assets/plugins/jQuery/jquery-2.2.3.min.js with letter 'Q' in small case. I'm using linux and the jquery couldn't be loaded because linux is case-sensitive.

I'm sorry if my english is bad.

**Comment by juliardi** [comment]
ah, it seems that https://github.com/jeroennoten/Laravel-AdminLTE/pull/18 will fix this. Didn't check it first.

**Comment by jeroennoten** [comment]
Fixed in version 1.6.6.
