### ISSUE TITLE
QUESTION: Plans for bootstrap 4?

### ISSUE THREAD

**Issue by IvanRalph** [jeroennoten/Laravel-AdminLTE#190]
Are there any plans on updating bootstrap to version 4? thanks.

**Comment by loekiedepo** [comment]
See the answer for #23 : this repository is basically a mirror of the official Admin-LTE. It looks like they [are already on this](https://github.com/almasaeed2010/AdminLTE/issues/1671).

**Comment by bellwood** [comment]
Correct, v3-dev branch was merged March 17th

**Comment by lacodimizer** [comment]
#183
