### ISSUE TITLE
QUESTION: How to dynamically add title_postfix and title_prefix in Blade file?

### ISSUE THREAD

**Issue by Ali-Shaikh** [jeroennoten/Laravel-AdminLTE#192]
First of all thanks a lot for your hard-work and very useful package.

Could you help me with my query? 

How to dynamically add title_postfix and title_prefix in Blade file? I am generating my menu dynamically and is it also possible to set the title based on the menu item page? or echoing it in the blade from controller?

**Comment by lacodimizer** [comment]
Is the issue actual?
