### ISSUE TITLE
Menu translate sugestion

### ISSUE THREAD

**Issue by r4free** [jeroennoten/Laravel-AdminLTE#194]
i've needed to translate menu and theres was no way to do it, not that i know

what about add a translate method in menu like this

@if (is_string($item))
    <li class="header text-uppercase"> **{{trans($item)}}**</li>
@else
    <li class="{{ $item['class'] }}">
        <a href="{{ $item['href'] }}"
           @if (isset($item['target'])) target="{{ $item['target'] }}" @endif
        class="text-capitalize">
            <i class="fa fa-fw fa-{{ $item['icon'] or 'circle-o' }} {{ isset($item['icon_color']) ? 'text-' . $item['icon_color'] : '' }}"></i>
            {{-- <span>{{ is_string($item['text'])?$item["text"]."é strin":__($item['text']) }}</span> --}}
            <span>**{{trans($item['text']) }}**</span>
            @if (isset($item['label']))
                <span class="pull-right-container">
                    <span class="label label-{{ $item['label_color'] or 'primary' }} pull-right"> {{ __($item['label'])}}</span>
                </span>
            @elseif (isset($item['submenu']))
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
                </span>
            @endif
        </a>
        @if (isset($item['submenu']))
            <ul class="{{ $item['submenu_class'] }}">
                @each('adminlte::partials.menu-item', $item['submenu'], 'item')
            </ul>
        @endif
    </li>
@endif

well sorry if it is not relevant, im a laravel/php begginer

**Comment by CrazyFreeMan** [comment]
Create Filter:
```
<?php

namespace App\Web\MenuFilters;

use JeroenNoten\LaravelAdminLte\Menu\Builder;
use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
use Illuminate\Contracts\Translation\Translator;

class LangFilter implements FilterInterface
{
    protected $langGenerator;

    public function __construct(Translator $langGenerator)
    {
        $this->langGenerator = $langGenerator;
    }

    public function transform($item, Builder $builder)
    {
        if (isset($item['header'])) {
            $item['header'] = $this->langGenerator->trans($item['header']);
        }
        if (isset($item['text'])) {
            $item['text'] = $this->langGenerator->trans($item['text']);
        }
        return $item;
    }
}
```

Add to adminlte.php in filters = [];
Then in menu:
```
 [
            'header' => 'admin.maps'
        ],
        [
            'text' => 'admin.tracking.map',
            'url' => 'maps',
            'icon' => 'map',
            'icon_color' => 'green',
        ],

```
And add translation to you lang file.

Enjoy! :)

**Comment by lacodimizer** [comment]
is coming with new release.
