### ISSUE TITLE
QUESTION: RTL Support

### ISSUE THREAD

**Issue by ahishamali10** [jeroennoten/Laravel-AdminLTE#197]
If it is possible for your perfect work to support RTL (right to left) directions for the admin panel

**Comment by mmcomp** [comment]
yes would you please be kind enough to provide us a Right to Left version of your code?
thanks alot

**Comment by lacodimizer** [comment]
Hi all, please try the pre version of v1.27.0 with a right sidebar, if you mean this with your issue. :)

**Comment by REJack** [comment]
AdminLTE v2 doesn't support out of the box RTL & Bootstrap also has no RTL support.
AdminLTE v3.1.0 will bring this support with an Custom Boostrap v4 for RTL support.

**Comment by Ghassan-Aljaafri** [comment]
So how to make it RTL

**Comment by Krinkle** [comment]
See <https://github.com/mmdsharifi/AdminLTE-RTL> which supports RTL via CSSJanus. Perhaps you can use or collaborate?

Or use CSSJanus directly in this project. See [php-cssjanus](https://github.com/cssjanus/php-cssjanus) or  [node-cssjanus](https://github.com/cssjanus/cssjanus).
