### ISSUE TITLE
QUESTION: How send a var en  'ACCOUNT SETTINGS', menu 

### ISSUE THREAD

**Issue by christiantigre** [jeroennoten/Laravel-AdminLTE#198]
How send var {var}
'ACCOUNT SETTINGS',
        [
            'text' => 'Cuenta',
            'url'  => 'admin/perfil/'{var},
            'icon' => 'user',
        ],
for show info user

**Comment by dlaynes** [comment]
Does \Auth::id() work?

**Comment by MadMikeyB** [comment]
You can't really use a helper such as `auth` inside the configuration files, as the helpers within Laravel depend on the configuration files which you're trying to use them within, creating a sort of infinite dependency loop.

**Comment by dlaynes** [comment]
You are correct.
Perhaps View composers are the correct solution, since the auth object  won't be available inside the library provider.
But I'd suggest adding a custom static route that redirects to the profile of the authenticated user. (If is not too late for this).

**Comment by dlaynes** [comment]
I was thinking on something like this:

`public function index(){
     return \redirect('admin/profile/'.\Auth::id() );
}`

I'm guessing TC is already working on another stuff : (

**Comment by lacodimizer** [comment]
Is the issue actual?
