### ISSUE TITLE
Elements do not work!!!

### ISSUE THREAD

**Issue by santiagoferraz** [jeroennoten/Laravel-AdminLTE#200]
Hello, first of all I would like to commend the great work on the design template.

I'm using the elements (input's, form's and etc) that are shown in the template adminlte template, but some of the elements do not have the same behavior pattern. That is, I put an input calendar that when clicked opens a calendar, however in the project it does not open the calendar. I put an input with mask and it does not generate the mask. It's like missing JS and CSS files. Can you tell me what I should do ???

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
