### ISSUE TITLE
QUESTION: How to use DataTables in view

### ISSUE THREAD

**Issue by luizpatrocinio** [jeroennoten/Laravel-AdminLTE#201]
Hi this not function.
.....
@endsection
<script>

$(function () {

    $('#tabela').DataTable({
  
        'processing': true,
        'serverSide': true,
        'language': {'url': '{{ url('/datatables/pt.br') }}'},
        'ajax': '{{ url('/admin/usuarios/api') }}',
        'columns': [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'rolename', name: 'roles.rolename'},
            {data: 'ativo', name: 'ativo'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
  });
</script>

My plugins all true

'plugins' => [
        'datatables' => true,
        'select2'    => true,
        'chartjs'    => true,
    ],

How to use datatables in view/blade?

Tks

**Comment by luizpatrocinio** [comment]
I got.

Tks

**Comment by sandeshsays** [comment]
how did you do it?please share.

**Comment by tharaka755** [comment]
@section('js')
    <script>
        $(document).ready(function () {
            $('.data-table').dataTable();
        });
    </script>
@stop

put this in your blade file and use 'data-table' class for <table>
and don't forget to specify <thead> and <tbody>

**Comment by luiszarazua** [comment]
hola k tal me podrian ayudar tengo un error al utilizar datatable en la plantilla adminlte me sale mas grande

**Comment by luiszarazua** [comment]
![image](https://user-images.githubusercontent.com/41071589/42523239-ccc4e9fc-8432-11e8-8a37-8d12246e5423.png)

**Comment by AhmadShiddiq** [comment]
Can you please describe how to store data to view, I'm sorry I'm new here I need some tutorial. After googling I didn't find how to make this work.
