### ISSUE TITLE
jquery-ui

### ISSUE THREAD

**Issue by romandf** [jeroennoten/Laravel-AdminLTE#202]
Hi!, I to intent use a jquery-ui datepicker in this version of jeronnoten with laravel 5.5 and, don't function. 
some body help me please. 

app.js
require('./bootstrap');

window.Vue = require('vue');
import $ from 'jquery';

import 'jquery-ui/ui/widgets/datepicker';
import 'jquery-ui/themes/base/datepicker.css';
thank's for your avance..
npm run dev.. works ok, but.. no see nothing.

**Comment by jilcimar** [comment]
I have the same problem :(

**Comment by romandf** [comment]
Hello, my solution..
put it in master.blade.php and remove jquery_ui npm.

<link rel="stylesheet" href="
http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
<script src="{{ asset( 'js/jquery.ui.datepicker-es.js ') }}"></script>

<script>
$(function() {
    $( ".datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      changeMonth: true,
      changeYear: true,
      yearRange: '2013:'+(new Date).getFullYear()
    });
});
</script>

mensaje sin acentos.

Mat. Delibes Flores Roman
RUOA CCA-UNAM
Cto. exterior s/n. cd. universitaria,
coyoacan Mexico D. F.
tel. 52 55 50 67 39

**Comment by jilcimar** [comment]
My problem persists with the following error:
``Uncaught TypeError: $(...).multiDatesPicker is not a function``

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
