### ISSUE TITLE
ISSUE: routing problem with adminlte.php

### ISSUE THREAD

**Issue by Sokan89** [jeroennoten/Laravel-AdminLTE#204]
First of all great package and thanks for that. 

I having some problems with the routing configuration of the menu. 

If i use standard routing like /dashboard or /dashboard/yolo, there is no problem. 
If i want to use route model binding like password.index or /user/{user}/password/edit,
i get: Sorry, the page you are looking for, was not found or an exception. 

What did i wrong? Im nearly new to laravel. But if i had to bet, i would say i have forgot something. 

Hope someone could help me to solve my problem.

**Comment by MadMikeyB** [comment]
You can't really use a helper such as `route` inside the configuration files, as the helpers within Laravel depend on the configuration files which you're trying to use them within, creating a sort of infinite dependency loop.

As such I had to hard code URL's and couldn't use dynamic ones.

**Comment by lacodimizer** [comment]
Is the issue actual?
