### ISSUE TITLE
A compatibility issue with doctrine

### ISSUE THREAD

**Issue by ClearLoveLee** [jeroennoten/Laravel-AdminLTE#205]
Hello，After I executed the    **php artisan make:adminlte**   command, I registered in the registration interface, but it will report an error (as shown below)
![2018-05-03 8 25 58](https://user-images.githubusercontent.com/8563636/39576373-826b163a-4f10-11e8-8161-2d2e20ab9ea3.png)
I found the reason!
Because my php version is 5.6.31
There are some new syntax features (for php7) in the file **vender\doctrine\inflector\lib\Doctrine\Common\Inflector\Inflector.php**, such as hints for return value types.
![2018-05-03 8 32 06](https://user-images.githubusercontent.com/8563636/39576601-42b3a948-4f11-11e8-922e-7ce6da69933d.png)
I deleted the new grammatical features and it works now. Is there any other good way?

**Comment by loekiedepo** [comment]
This has nothing to do with this package (this package doesn't depend on Doctrine), but with how you set up your project. You work with an older PHP version, it helps is you specify this in your `composer.json` file.

```json
{
    "name": ".../...",
    "config": {
        "platform": {
            "php": "5.6.31"
        }
    },
    "require": {
        ...
    }
} 
```

**Comment by ClearLoveLee** [comment]
Thank you very much！
