### ISSUE TITLE
website goes to half of the screen but when i click on the side bar it automatically goes to full screen

### ISSUE THREAD

**Issue by abhishektomer** [jeroennoten/Laravel-AdminLTE#206]
![2018-05-12 2](https://user-images.githubusercontent.com/25544041/39953740-8a230b92-55cf-11e8-89c4-a04ed26db52b.png)
![2018-05-12 3](https://user-images.githubusercontent.com/25544041/39953742-8a5c506e-55cf-11e8-943d-f778c4b90aab.png)
no errors found

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
