### ISSUE TITLE
Laravel 5.3 issue

### ISSUE THREAD

**Issue by dgeyer263** [jeroennoten/Laravel-AdminLTE#21]
When running the command php artisan make:adminlte the following error occurs

[ErrorException]          
  copy(/home/user/Projects/laravel/vendor/laravel/framework/src/Illuminate/Auth/Console/stubs/make/views/auth/emails/password.stub): failed to open stream: No such file or directory

Using the laravel 5.3.x-dev 5cce34b

**Comment by jeroennoten** [comment]
Thanks for reporting this! It's fixed now (v1.8.1).
