### ISSUE TITLE
QUESTION: Menu with 'can'  => 'manage-blog',

### ISSUE THREAD

**Issue by santiagoferraz** [jeroennoten/Laravel-AdminLTE#210]
I'm trying to show the menu just according to the type of user. I have how to do this in other ways, but I would use type reported in the project, using CAN. Someone has a practical example to show me how I should do this. Have I read the documentation several times and can not get a positive result ???

**Comment by PaulinPrize** [comment]
@arifulhb 
Hi, I tested your solution but it does not work for me

**Comment by hawkiq** [comment]
> 
> 
> I was looking for a solution as it wasn't working in my code also. I was using Policy files but Laravel-AdminLTE documentation mention of Gate
> 
> > This integrates with Laravel's Gate functionality.
> 
> So I decided to write a gate for menu only. I added this code in `AuthServiceProvider.php`
> 
> ```
> public function boot()
>    {
>        $this->registerPolicies();
> 
>        Gate::define('browse-teacher', function ($user) {
> 
>            if ($user->role == 'admin'){
>                return true;
>            }
> 
>            return false;
> 
>        });
>    }
> ```
> 
> My menu is:
> 
> ```
>    [
>         'text'      => 'lms.menu.teachers',
>         'url'       => 'admin/teachers',
>         'icon'      => 'users',
>         'can'       => 'browse-teacher',
>     ],
> ```
> 
> And it work fine :)
> 
> I guess its a limitation that it doesn't work with Policy but only gates for the menu is fine with me.

thanks @arifulhp your solution worked on Laravel 5.5

**Comment by gbarcella** [comment]
Dude, thank you very much!!!!!

**Comment by henryq30** [comment]
Thanks @arifulhb, this worked fine in Laravel 8   :)

**Comment by ing-halvarado-7s** [comment]
Saludos, con Laravel 9, basada en este ejemplo y con la documentación en [(https://laravel.com/docs/9.x/authorization)]

En **app->Providers->AuthServiceProvider.php**

En la parte superior del archivo agregar
`use Illuminate\Support\Facades\Gate;
use App\Models\User;`

Luego la funcion boot
` public function boot()
    {
        $this->registerPolicies();
        Gate::define('admin', function (User $user) {

            if ($user->role == 'Administrador'){
                return true;
            }

            return false;

        });

        Gate::define('admin-afiliado', function (User $user) {

            if ($user->role == 'Administrador' or $user->role == 'Afiliado'){
                return true;
            }

            return false;

        });
 }`

Allí agregué  dos permisos, para ser usados en en el Menú de adminLte, de la siguiente manera: 
En **config->AdminLte.php**
` 'menu' => [        
        [
            'text'        => 'Afiliados',
            'url'         => 'afiliado',
            'icon' => 'fas fa-fw fa-user',
            'can'  => 'admin',

        ],
  ],`

Como se puede observar en la propiedad ### **can**, se coloca el nombre del gate al cual queremos darle acceso a cada uno de los items del menú.

**Comment by ruanpepe** [comment]
The package is compatible with Policies already. @dfsmania Do you think this should be at Wiki? Its a great feature.

In policies, we create a policies file that will be attached to our model by Laravel according naming conventions.

Ex: 
Consider the `Post` model policies

```
<?php

namespace App\Policies;

use App\Models\Post;
use App\Models\User;

class PostPolicy
{
    /**
     * Determine whether the user can update the post.
     */
    public function update(User $user, Post $post): bool
    {
        if($user->isAdmin()) {
            return true;
        }

        return $user->id === $post->user_id;
    }

    /**
     * Determine whether the user can delete the post.
     */
    public function delete(User $user, Post $post): bool
    {
        if($user->isAdmin()) {
            return true;
        }

        return $user->id === $post->user_id;
    }
}
```

Then we can check the user permission using the method name and the model instance or model class ([read this](https://laravel.com/docs/11.x/authorization#controller-actions-that-dont-require-models)):

`$user->can('update', $post)`
`Gate::authorize('update', $post);`

I checked the `GateFilter.php` and it already have being done.
All we need is do the following:

```
    [
        'text' => '...',
        'url' => '...',
        'can' => ['update', 'delete'],
        'model' => $post
    ],
```
That will be converted to 
`Gate::any(['update', 'delete'], $post)`

I'm using it and work like a charm.

**Comment by dfsmania** [comment]
@ruanpepe Ok, I will try to add an example on the Wiki when I get some time...

**Comment by dfsmania** [comment]
> The package is compatible with Policies already. @dfsmania Do you think this should be at Wiki? Its a great feature.
> 
> In policies, we create a policies file that will be attached to our model by Laravel according naming conventions.
> 
> Ex: Consider the `Post` model policies
> 
> ```
> <?php
> 
> namespace App\Policies;
> 
> use App\Models\Post;
> use App\Models\User;
> 
> class PostPolicy
> {
>     /**
>      * Determine whether the user can update the post.
>      */
>     public function update(User $user, Post $post): bool
>     {
>         if($user->isAdmin()) {
>             return true;
>         }
> 
>         return $user->id === $post->user_id;
>     }
> 
>     /**
>      * Determine whether the user can delete the post.
>      */
>     public function delete(User $user, Post $post): bool
>     {
>         if($user->isAdmin()) {
>             return true;
>         }
> 
>         return $user->id === $post->user_id;
>     }
> }
> ```
> 
> Then we can check the user permission using the method name and the model instance or model class ([read this](https://laravel.com/docs/11.x/authorization#controller-actions-that-dont-require-models)):
> 
> `$user->can('update', $post)` `Gate::authorize('update', $post);`
> 
> I checked the `GateFilter.php` and it already have being done. All we need is do the following:
> 
> ```
>     [
>         'text' => '...',
>         'url' => '...',
>         'can' => ['update', 'delete'],
>         'model' => $post
>     ],
> ```
> 
> That will be converted to `Gate::any(['update', 'delete'], $post)`
> 
> I'm using it and work like a charm.

@ruanpepe In relation to next code you provided as example:

```php
    [
        'text' => '...',
        'url' => '...',
        'can' => ['update', 'delete'],
        'model' => $post
    ],
```

What is `$post`? Are you using this sort of configuration when defining the menu in `config/adminlte.php` or are you defining your menu dynamically?

**Comment by ruanpepe** [comment]
> > The package is compatible with Policies already. @dfsmania Do you think this should be at Wiki? Its a great feature.
> > 
> > In policies, we create a policies file that will be attached to our model by Laravel according naming conventions.
> > 
> > Ex: Consider the `Post` model policies
> > 
> > ```
> > <?php
> > 
> > namespace App\Policies;
> > 
> > use App\Models\Post;
> > use App\Models\User;
> > 
> > class PostPolicy
> > {
> >     /**
> >      * Determine whether the user can update the post.
> >      */
> >     public function update(User $user, Post $post): bool
> >     {
> >         if($user->isAdmin()) {
> >             return true;
> >         }
> > 
> >         return $user->id === $post->user_id;
> >     }
> > 
> >     /**
> >      * Determine whether the user can delete the post.
> >      */
> >     public function delete(User $user, Post $post): bool
> >     {
> >         if($user->isAdmin()) {
> >             return true;
> >         }
> > 
> >         return $user->id === $post->user_id;
> >     }
> > }
> > ```
> > 
> > Then we can check the user permission using the method name and the model instance or model class ([read this](https://laravel.com/docs/11.x/authorization#controller-actions-that-dont-require-models)):
> > 
> > `$user->can('update', $post)` `Gate::authorize('update', $post);`
> > 
> > I checked the `GateFilter.php` and it already have being done. All we need is do the following:
> > 
> > ```
> >     [
> >         'text' => '...',
> >         'url' => '...',
> >         'can' => ['update', 'delete'],
> >         'model' => $post
> >     ],
> > ```
> > 
> > That will be converted to `Gate::any(['update', 'delete'], $post)`
> > 
> > I'm using it and work like a charm.
> 
> @ruanpepe In relation to next code you provided as example:
> 
> ```php
>     [
>         'text' => '...',
>         'url' => '...',
>         'can' => ['update', 'delete'],
>         'model' => $post
>     ],
> ```
> 
> What is `$post`? Are you using this sort of configuration when defining the menu in `config/adminlte.php` or are you defining your menu dynamically?

I'm doing it dynamically in a service provider. `$post` would be an instance of the Post model, like: 
```
$post = App/Models/Post::find(...);
```

**Comment by dfsmania** [comment]
@ruanpepe Thanks, so then the support to **Policies** only work when generating the menu dynamically...

**Comment by dfsmania** [comment]
@ruanpepe Please review next documentation just in case:

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#side-notes-about-laravel-policies-support

**Comment by ruanpepe** [comment]
It's really well done. Really easy to understand.
👏👏👏
