### ISSUE TITLE
QUESTION: Dynamic menu label by publishing "BuildingMenu" event

### ISSUE THREAD

**Issue by mobilemaster128** [jeroennoten/Laravel-AdminLTE#211]
I am going to add or change label of menu in javascript when receive new event from client.
I have added menu in ServiceProvider.
So I hope to rebuild whenever I need, I am going to publish 'BuildingMenu' event.
But I don't know how I can publish this event from code.
Somebody can help me?
Regards.

**Comment by lacodimizer** [comment]
Is the issue actual?
