### ISSUE TITLE
How to load the CSS of adminlte template correctly

### ISSUE THREAD

**Issue by Donald598** [jeroennoten/Laravel-AdminLTE#214]
Am trying to load the css files for the adminlte jeroennoten package but I have failed. It only loads the html files in the blade .
![capture](https://user-images.githubusercontent.com/38502839/40773627-1d28575c-64cc-11e8-9e49-be6886764d5e.PNG).
Help me resolve the css link possibly

**Comment by loekiedepo** [comment]
Where is the css file located? Normally you would use the [`asset`](https://laravel.com/docs/5.6/helpers#method-asset) helper for this.

**Comment by sameeranees** [comment]
I am having the same problem. Can anyone find a way to load the css of adminlte?

**Comment by Sidibedev** [comment]
Did you resolve it ? i got the same issue here.

**Comment by sameeranees** [comment]
Publish the public assets:

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets

**Comment by romandf** [comment]
Hi!, I need, change the background's body only to home page, but I don't know. Somebody knows like? 
thank's, for advance.

**Comment by Azmeer-crescent** [comment]
I copied the vendor folder to public folder - it fixed it
