### ISSUE TITLE
Active menu doesn't work

### ISSUE THREAD

**Issue by bruno-motacardoso** [jeroennoten/Laravel-AdminLTE#215]
Hello,
I use a menu with routes url and the active class (css) for my items doesn't work correctly.

It's normal, I looked that I don't write the first issue about this.

Thank you

**Comment by gidaban** [comment]
Hi,

have something similar with multi level menu , but without roles.

**Comment by tehuel** [comment]
How are you configuring it?

If you don't define an `active` property for an item, then the menu uses the `url` entry to match against the page url.

You can define your own string to match in the `active` entry, for every item.

An example config

```php

    'menu' => [
        [
            'text'  => 'Admin Home',
            'url'   => '/admin',
            'active' => ['/admin']
        ],
        [
            'text'      => 'Stores (submenu)',
            'submenu'   => [
                [
                    'text'      => 'Stores Index',
                    'url'       => '/admin/stores',
                    'active'    => ['/admin/stores'],
                ],
                [
                    'text'  => 'New Store',
                    'url'   => '/admin/stores/create',
                    'active'    => ['/admin/stores/create'],
                ],
            ],
        ],
    ],

```

**Comment by bruno-motacardoso** [comment]
Hello @tehuel,
I don't know the **active** property.
Thank you for the help this information saves me!

## Issue:
Use **active** property in your config
