### ISSUE TITLE
QUESTION: How to make custom menu

### ISSUE THREAD

**Issue by dinarrhamiya** [jeroennoten/Laravel-AdminLTE#217]
someone please help me to make custom menu, for superadmin and transaction admin. so the menu after login will different. thankyou

**Comment by MadMikeyB** [comment]
Hi,

Simply use the `can` option in your `config/adminlte.php` file once you've run

`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets`

For example:

```
        [
            'text' => 'Site Settings',
            'url'  => 'admin/settings',
            'icon'  => 'cog',
            'can'   => 'view settings'
        ],
```

**Comment by PaulinPrize** [comment]
@MadMikeyB 
Hi, I tried your solution it hides the links but the problem is that it hides the links in all users even those who have the right

**Comment by MadMikeyB** [comment]
@PaulinPrize I'm using that method without issue, are you sure the user in question has the correct permissions?

**Comment by PaulinPrize** [comment]
@MadMikeyB 
hello, I have just tested this solution it works but I still have a problem. When I use 'can' on a tab this, hide this tab for all users while that's not what I want. I would like the tab to be visible to users with the right.

**Comment by lacodimizer** [comment]
Is the issue actual?
