### ISSUE TITLE
Install translation

### ISSUE THREAD

**Issue by ruospo** [jeroennoten/Laravel-AdminLTE#218]
hi, after install with composer require jeroennoten/laravel-adminlte
i not find in vendor/jeroennoten/laravel-adminlte/resource/lang all language.
Can you help me?

**Comment by MadMikeyB** [comment]
Once you have run the publish command:

`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets`

Translations are in `resources/lang/vendor/adminlte`.

![screen shot 2018-07-29 at 16 41 31](https://user-images.githubusercontent.com/831828/43368046-8b0368a6-934e-11e8-9443-e5a2f9299a51.jpg)

**Comment by bretto36** [comment]
Running `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=translations` doesn't cause the tranlations to be copied. to my resources folder
No error messages are seen

**Comment by REJack** [comment]
@bretto36 Which version of Laravel-AdminLTE you use?

**Comment by bretto36** [comment]
@REJack  - Currently using 1.27.2 according to my composer.lock file - I ended up just copying the files manually from the vendor folder for now to get it going

**Comment by bretto36** [comment]
Ah the docs command must be for the latest version. 
 Needs to be `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=translations` When using the Laravel 5 branch.
