### ISSUE TITLE
Auth::user() - Trying to get property of non-object

### ISSUE THREAD

**Issue by rflfl** [jeroennoten/Laravel-AdminLTE#219]
Hi, I am having problems trying to login because it shows the error message "ErrorException (E_ERROR) Trying to get property of non-object" as in the image.
Do you know what it could be?

![try yo get property of non-object](https://user-images.githubusercontent.com/40215566/42090873-87f8f348-7b79-11e8-869f-d7d980444111.png)

**Comment by Lucky-Loek** [comment]
Note that this is a PHP-specific problem that hasn't got anything to do with this package. Please consult other boards like [StackOverflow](https://stackoverflow.com/questions/tagged/php) for stuff like this.

**Comment by rflfl** [comment]
Thanks for the feedback.
