### ISSUE TITLE
Update to Bootstrap 3.3.7 & jQuery 3

### ISSUE THREAD

**Issue by loekiedepo** [jeroennoten/Laravel-AdminLTE#22]
Is it possible to update this template to use Bootstrap 3.3.7 together with jQuery 3?

[Since bootstrap apparently fixed jQuery 3 support](https://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/)

**Comment by jeroennoten** [comment]
You should open an issue at https://github.com/almasaeed2010/AdminLTE.
