### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by bachilli** [jeroennoten/Laravel-AdminLTE#223]
This project is abandoned?

**Comment by jeroennoten** [comment]
No, I just have not much time to maintain this project at the moment. However I will accept PRs with high quality.

**Comment by bachilli** [comment]
Ok, but the styleci is misconfigured. Can you fix this please? @jeroennoten

**Comment by bachilli** [comment]
Config Issue
The provided config option 'linting' was not valid.

**Comment by Lucky-Loek** [comment]
@jeroennoten The package is getting quite big with lots of questions. It can be useful to coordinate with one or two extra maintainers? e.g. one for issues, one for PRs, etc.
