### ISSUE TITLE
QUESTION: Want different menu for different routes (types of users)..( using can option)

### ISSUE THREAD

**Issue by shikhar95** [jeroennoten/Laravel-AdminLTE#227]
i have 3 types of users - admin,hr,users.
on logging in as hr i want an option of visitor panel on menu...so i am doing it through can option.
My problem is I am getting option of visitor panel on menu even if i sign in as admin or normal user.

I have defined a gate in **\app\Providers\AuthServiceProvider.php**  as-

 public function boot()
    {
        $this->registerPolicies();
        Gate::define('hr', function ($users, $guard = 'hr') {
            if (Auth::guard($guard)->check() ){ 
                return true;
            }
            return false;
        });
    }

**And my guards are as-**

   'guards' => [
        'hr' => [
            'driver' => 'session',
            'provider' => 'hrs',
        ],

        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],

        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
**and my menu is-**
'menu' => [
        'MAIN NAVIGATION',
        [
            'text'        => 'Visitor Panel',
            'url'         => 'hr/index2',
            'icon'        => 'user',
            'label_color' => 'success',
            'can'         => 'hr',
        ],

        'ACCOUNT SETTINGS',
        [
            'text' => 'Profile',
            'url'  => 'admin/settings',
            'icon' => 'user',
        ],
        [
            'text' => 'Change Password',
            'url'  => 'admin/settings',
            'icon' => 'lock',
        ],
        [
            'text'    => 'Multilevel',
            'icon'    => 'share',
            'submenu' => [
                [
                    'text' => 'Level One',
                    'url'  => '#',
                ],
                [
                    'text'    => 'Level One',
                    'url'     => '#',
                    'submenu' => [
                        [
                            'text' => 'Level Two',
                            'url'  => '#',
                        ],
                        [
                            'text'    => 'Level Two',
                            'url'     => '#',
                            'submenu' => [
                                [
                                    'text' => 'Level Three',
                                    'url'  => '#',
                                ],
                                [
                                    'text' => 'Level Three',
                                    'url'  => '#',
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'text' => 'Level One',
                    'url'  => '#',
                ],
            ],
        ],
        'LABELS',
        [
            'text'       => 'Important',
            'icon_color' => 'red',
        ],
        [
            'text'       => 'Warning',
            'icon_color' => 'yellow',
        ],
        [
            'text'       => 'Information',
            'icon_color' => 'aqua',
        ],
    ],
Please Help...i am stuck here since three days

**Comment by saberhossain** [comment]
looking for solution to the same thing.

**Comment by cf-git** [comment]
Apparently you need to collect the menu in the dynamics, this is done through providers such as "AppServiceProvider".

It seens like thant:
```php
<?php

namespace App\Providers;

use App\AdminLTE\AccountMenuBuildingEvent;
use App\Models\Handbook;
use Illuminate\Events\Dispatcher;
use Illuminate\Support\ServiceProvider;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
    }

    /**
     * Bootstrap any application services.
     *
     * @param Dispatcher $events
     * @return void
     */
    public function boot(Dispatcher $events)
    {
        app('view')->addNamespace('adminlte', resource_path("views/vendor/adminlte"));
        app('translator')->addNamespace("site", resource_path("lang/vendor/site"));

        $events->listen(AccountMenuBuildingEvent::class, function (AccountMenuBuildingEvent $event) {
            foreach (config("app.account.navigation") as $item) {
                $event->menu->add($item);
            }
        });

        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add(__('SYSTEM CONTROL'));
            $event->menu->add([
                'text' => __('Roles'),
                'icon' => 'user-secret',
                'submenu' => [
                    [
                        'text' => __('List of roles'),
                        'icon' => 'list',
                        'url' => 'admin/role'
                    ],
                    [
                        'text' => __('Create new role'),
                        'icon' => 'plus',
                        'url' => 'admin/role/create'
                    ],
                ],
            ]);
            $event->menu->add([
                'text' => __('Users'),
                'icon' => 'users',
                'submenu' => [
                    [
                        'text' => __('List of users'),
                        'icon' => 'list',
                        'url' => 'admin/user'
                    ],
                    [
                        'text' => __('Create new user'),
                        'icon' => 'user-plus',
                        'url' => 'admin/user/create'
                    ],
                ],
            ]);
        });
    }
}


```

**Comment by lacodimizer** [comment]
Is the issue actual or can we close it?
