### ISSUE TITLE
Logout link showing "adminlte::adminlte.log_out" instead of "Log out"

### ISSUE THREAD

**Issue by niltonssjr** [jeroennoten/Laravel-AdminLTE#230]
I researched here and did't find anything, so I am posting... I was doing tests on localhost and everything was fine. The issue started when I moved the application to the host. Do you have any ideia about what could be happening? Thanks!

**Comment by ahmedalmulki** [comment]
I already do that without any problems .

**Comment by MadMikeyB** [comment]
Can you post your code @niltonssjr

**Comment by niltonssjr** [comment]
Thanks a lot, @Lucky-Loek ! I didnt' find #207 before, it worked perfectly.
