### ISSUE TITLE
How traslate items nav trans('adminlte::adminlte.Profile')

### ISSUE THREAD

**Issue by christiantigre** [jeroennoten/Laravel-AdminLTE#231]
My nav 
 [
            'text' => '{{ trans("adminlte::adminlte.Profile") }}',
            'url'  => 'admin/myprofile',
            'icon' => 'user',
        ],
how traslate items nav

**Comment by MadMikeyB** [comment]
Hi,

You can't really use a helper such as `trans` inside the configuration files, as the helpers within Laravel depend on the configuration files which you're trying to use them within, creating a sort of infinite dependency loop.

Please see here: https://laracasts.com/discuss/channels/laravel/how-to-use-funciton-url-in-config-file/replies/91340

**Comment by CrazyFreeMan** [comment]
see #194

**Comment by lacodimizer** [comment]
Is coming with new release
