### ISSUE TITLE
Change dashboard_url at runtime

### ISSUE THREAD

**Issue by gpressutto5** [jeroennoten/Laravel-AdminLTE#235]
We can change menu at runtime, but it would be great if we could change other options, like `dashboard_url`.

**Comment by Lucky-Loek** [comment]
This sounds a bit like an [X-Y Problem](http://xyproblem.info). Why would you want to change the dashboard uri? The dashboard is always the dashboard right? 

In the meantime, if you must, you can always publish the views and create this functionality yourself.

**Comment by jeroennoten** [comment]
Hey @gpressutto5, you can override the template and add logic to change the dashboard URL at runtime.
