### ISSUE TITLE
Laravel 5.7 incompatibility

### ISSUE THREAD

**Issue by lucaskaiut** [jeroennoten/Laravel-AdminLTE#240]
I can't install this Laravel-AdminLTE on Laravel 5.7. I got an incompatibility issue.

**Comment by bruce2409** [comment]
If it's super-urgent, only thing seemingly stopping you from cursory glance is that composer.json doesn't have 5.7.0 added to requirements.

You can just edit your composer.json to pull from a forked repo that just adds that (#241 comes from just such a repo in fact) and set required version for the package to dev-master.

**Comment by jeroennoten** [comment]
Version 1.24.0 has support for Laravel 5.7
