### ISSUE TITLE
Undefined index: icon  in resources\views\vendor\adminlte\partials\menu-item.blade.php

### ISSUE THREAD

**Issue by vatraiadarsh** [jeroennoten/Laravel-AdminLTE#248]
<i class="fa fa-fw fa-<?php echo e($item['icon'] or 'circle-o'); ?> <?php echo e(isset($item['icon_color']) ? 'text-' . $item['icon_color'] : ''); ?>"></i>

**Comment by consciousnessdev** [comment]
Change 'or' to '??' 

refference: https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/passwords/email.blade.php#L27

**Comment by Lucky-Loek** [comment]
Fixed in #244

**Comment by jeroennoten** [comment]
Fixed in version 1.24.1. Thanks for reporting and sorry for the inconvenience!
