### ISSUE TITLE
Logout is now a POST request

### ISSUE THREAD

**Issue by loekiedepo** [jeroennoten/Laravel-AdminLTE#25]
In Laravel 5.3, the logout route apparently responds to a POST request. I have no problems adding a GET request manually for this package, but the reasons why it was changed to a POST request seem logical.

Is there any way of changing the logout url into a POST request entirely? Or adding an option in the config to define if the logout route should respond to a GET or a POST request?

I've tried looking at it, but I'm afraid I don't know enough php/HTML/Laravel to do it.

![capture](https://cloud.githubusercontent.com/assets/9716643/18027855/a8026b7c-6c6e-11e6-9a82-5cf780bdd41c.PNG)

**Comment by jeroennoten** [comment]
Good point. Fixed in version 1.10.1.

**Comment by loekiedepo** [comment]
Awesome, thanks

**Comment by salamuns** [comment]
In Laravel 8, modify the route as follows :

`Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');`
