### ISSUE TITLE
ISSUE: Publishing views breaks variables

### ISSUE THREAD

**Issue by giobi** [jeroennoten/Laravel-AdminLTE#252]
Publishing views gives an error:
`ErrorException (E_ERROR) Undefined variable: adminlte`

I'm extending the published layout
`@extends('vendor.adminlte.page')`

On line 99 of page.blade.php while building menu calls a $adminlte var that is not defined in the published view.

I'm publishing to add js scripts to every page (apparently the basic page layout is not including my app.js).

Switching back to vendor layouts meanwhile.

**Comment by lacodimizer** [comment]
Is the issue actual?

**Comment by davidpazo** [comment]
I have the same issue, and i looking for a solution

**Comment by lacodimizer** [comment]
Did you try @extends('adminlte::page')?
