### ISSUE TITLE
ISSUE: Error when extending the default template

### ISSUE THREAD

**Issue by guysolamour** [jeroennoten/Laravel-AdminLTE#253]
Morning, sorry for my bad English. When I use the:
@extends('adminlte::page')

I get this error:
ReflectionFunction::__construct() expects parameter 1 to be string, array given (View: /home/user/LABS/LARAVEL/project/resources/views/vendor/adminlte/page.blade.php) (View: /home/guysolamour/LABS/LARAVEL/project/resources/views/vendor/adminlte/page.blade.php).

What 's wrong ?

**Comment by skyosev** [comment]
I have exactly the same issue.

**Comment by stevangoldduck** [comment]
are u using the exact requirements?? like your PHP Version , now only support for >= 7

**Comment by lacodimizer** [comment]
I changed the requirements and added php 5.6.
It will be removed in the next versions.

**Comment by lacodimizer** [comment]
We changed the requirements of PHP to >= 7.0.x and Laravel to >= 5.5.x.
The pre version of v1.27.0 is released.
