### ISSUE TITLE
how to add new inputs on user registration table

### ISSUE THREAD

**Issue by alanpdutra** [jeroennoten/Laravel-AdminLTE#254]
i need add new fields on Users table.
so i created 'birth', 'sex' on User migrations, however, laravel presents this exception
SQLSTATE[HY000]: General error: 1364 Field 'birth' doesn't have a default value (SQL: insert into users (name, email, password, updated_at, created_at) values (test, test@test.com, $2y$10$BUJkxnwzsfxG22u3iyI/lO4esgB4BUtTCX958ICRpUfddB5bxQyhm, 2018-09-26 03:28:18, 2018-09-26 03:28:18))

**Comment by alanpdutra** [comment]
i need add new fields on Users table.
so i created 'birth', 'sex' on User migrations, however, laravel presents this exception
SQLSTATE[HY000]: General error: 1364 Field 'birth' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (test, test@test.com, $2y$10$BUJkxnwzsfxG22u3iyI/lO4esgB4BUtTCX958ICRpUfddB5bxQyhm, 2018-09-26 03:28:18, 2018-09-26 03:28:18))

**Comment by peterooi83** [comment]
In new laravel, every time you save data in new row. you have to insert data of every column. in your script, you didn't insert brith's data. Please check it.

**Comment by andrecaetanov** [comment]
Like @peterooi83 said, you have to insert data in every column, unless the column has a default value.
