### ISSUE TITLE
ISSUE: administration-panel-style

### ISSUE THREAD

**Issue by PaulinPrize** [jeroennoten/Laravel-AdminLTE#257]
Hello, I use the package jeroennoten recently and everything works fine but there I have a problem with the administration panel because when I add content in the body of the page, everything becomes weird as illustrated by the next screenshot.
![capture](https://user-images.githubusercontent.com/41732884/47354616-75e77200-d6bf-11e8-8586-37c108ea394a.PNG)

**Comment by lacodimizer** [comment]
Is the issue actual?

**Comment by PaulinPrize** [comment]
No, i solved it.
