### ISSUE TITLE
QUESTION: Menu Permissions

### ISSUE THREAD

**Issue by PaulinPrize** [jeroennoten/Laravel-AdminLTE#258]
Hi, I'm using the jeroennoten package and I found a Caffeinated \ Shinobi package that allowed me to manage roles and permissions. I would like to hide links to users who do not have rights. I went to the file config / adminlte.php and I added 'can'
[
'text' => 'Manage users',
'url' => 'user /',
'can' => 'user.index',
'icon' => 'users',
]
but that hides this link to all users and I do not know why

**Comment by karthiRam96** [comment]
r u get answer for this question

**Comment by PaulinPrize** [comment]
@karthiRam96  When we use can the link is well hidden but it is hidden for all users, even for those who have the right to access it

**Comment by ronlinet** [comment]
According to docs https://github.com/jeroennoten/Laravel-AdminLTE#51-menu the can option integrates with Laravel's Gate functionality.

**Comment by ronlinet** [comment]
Stick this snippet to the boot function in your AuthServiceProvider.php 

```
        Gate::define('user.index', function ($user) {
            if( in_array( $user->email, array( 'admin@email.com', 'manager@email.com ) ) ) return true;
        });
```
and replace the email values with users who can see the link.

**Comment by PaulinPrize** [comment]
@ronlinet  This solution does not work for me

**Comment by lacodimizer** [comment]
Is this issue actual?

**Comment by PaulinPrize** [comment]
Yes

**Comment by andcarpi** [comment]
What package are you using for the permissions?

**Comment by lacodimizer** [comment]
I recommend https://github.com/spatie/laravel-permission

**Comment by cf-git** [comment]
or https://github.com/jeremykenedy/laravel-roles

**Comment by kubszy** [comment]
Somebody will describe how integrate roles with jeremykenedy/laravel-roles in AdminLTE 2 menu ? thx

**Comment by robertolyra** [comment]
For https://github.com/spatie/laravel-permission

1. On AuthServiceProvider enter the following code ( in this example the role to be checked is ''admin")

\Illuminate\Support\Facades\Gate::define('admin', function ($user) {
            if( $user->hasRole('admin') ) return true;
        });

2. On the config file adminlte.php adjust the menu item with : 
         'can' => 'admin'

3. On the adminlte.php comment out the line : 
/* JeroenNoten\LaravelAdminLte\Menu\Filters\GateFilter::class,*/
