### ISSUE TITLE
How to use fontawesome 5 in current version?

### ISSUE THREAD

**Issue by ahmeng10** [jeroennoten/Laravel-AdminLTE#261]
some icon wont show if I do in this way, what is the best way to use fontawesome 5 icon in current version
```
@section('css')
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
@endsection
```

**Comment by jhowbhz** [comment]
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views
