### ISSUE TITLE
Error on Load DataTable

### ISSUE THREAD

**Issue by cgarrotti** [jeroennoten/Laravel-AdminLTE#265]
When a load Datatable on my view, appear error:

TypeError: $(...).dataTable is not a function;

@section('js')
    <script>
       $(function () {
            $('.data-table').dataTable();
        });
    </script>
@stop

**Comment by nguyentranchung** [comment]
@cgarrotti 
```javascript
$(document).ready( function () {
    $('#myTable').DataTable();
} );
```

**Comment by shadysamir** [comment]
Not working, neither is solution in #66. The DataTables script is not even loaded from CDN, no indication for it in code.
