### ISSUE TITLE
How do view the home page after login

### ISSUE THREAD

**Issue by chisumo2016** [jeroennoten/Laravel-AdminLTE#266]
How do view the logged page? I have logged as normal user and i have been redirected to /home .Which shows the admin pannel .How do u view the content?I have checked inside the HomeController to see what it return itsn;t the same as it display. Please assist.

**Comment by consciousnessdev** [comment]
> How do view the logged page? I have logged as normal user and i have been redirected to /home .Which shows the admin pannel .How do u view the content?I have checked inside the HomeController to see what it return itsn;t the same as it display. Please assist.

How it display?

**Comment by honore237** [comment]
ok if i understand you want to redirect normal user in another page

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
