### ISSUE TITLE
TODO: create a visual tutorial for installation and setup guide

### ISSUE THREAD

**Issue by joshua-darby** [jeroennoten/Laravel-AdminLTE#270]
I think that as a suggestion there could be some sort of visual tutorial made for viewers of interest for the project to help with the setup and installation of the project. Some people can not simply go by what is said unfortunately due to not fully understanding how it is just said by text-like instructions. @jeroennoten

**Comment by lacodimizer** [comment]
We add a wiki and a better readme in the next sprints.
