### ISSUE TITLE
QUESTION: Changing layout per page and Logout showing when not logged in

### ISSUE THREAD

**Issue by dysath** [jeroennoten/Laravel-AdminLTE#272]
Two questions:

1)  How can I change a page to using top-nav when the rest of the site will use the normal null page?

2)  When using extend('adminlte:page'), I always have a 'Logout' option on the upper left, even though I'm not logged in.  Is this something I need to fix outside of adminlte::?  I looked at the page.blade.php and it seems that logout is always displayed regardless of state.

**Comment by LuisOzParr** [comment]
1. You can change the configuration in real time with this:
` config(['adminlte.layout' => 'top-nav']); `

2. You can modify the 'adminlte:page' using:
`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views`
