### ISSUE TITLE
redirect to /js/adminlte.min.js.map after login

### ISSUE THREAD

**Issue by bazuzu931** [jeroennoten/Laravel-AdminLTE#275]
hi, I use laravel 5.6 and "admin-lte": "^3.0.0-alpha.2",
when I login its redirect me to http://127.0.0.1:8000/js/adminlte.min.js.map, and admin pic with logo are not show, but rest of app is render good.
there is not problem after registration of the new user

**Comment by Dola29** [comment]
I'm Having the same problem...

**Comment by eddiemac1902** [comment]
Here's how I solved that problem. Not sure if its the best solution out there. In my LoginController I made the change of `protected $redirectTo = '/home/dashboard';`. Then in AuthenticatesUsers which is located in vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php, I changed the return statement in the `sendLoginResponse` function and replaced it with `return $this->authenticated($request, $this->guard()->user())?: redirect()->to($this->redirectPath());`
After making the change it now redirects to 'home/dashboard', and I created  a Vue Route to handle that page
Hope it helps

**Comment by eddiemac1902** [comment]
> Here's how I solved that problem. Not sure if its the best solution out there. In my LoginController I made the change of `protected $redirectTo = '/home/dashboard';`. Then in AuthenticatesUsers which is located in vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php, I changed the return statement in the `sendLoginResponse` function and replaced it with `return $this->authenticated($request, $this->guard()->user())?: redirect()->to($this->redirectPath());`
> After making the change it now redirects to 'home/dashboard', and I created a Vue Route to handle that page
> Hope it helps

I just changed `protected $redirectTo = '/home/dashboard'` back to `protected $redirectTo = '/home'` and it still works

**Comment by Azimul-Haque** [comment]
I solved it replacing the `intended` to `to` on sendLoginResponse funtion inside AuthenticatesUsers. Just change like this: 

```
return $this->authenticated($request, $this->guard()->user())
                ?: redirect()->instead($this->redirectPath());
```

to

```
return $this->authenticated($request, $this->guard()->user())
                ?: redirect()->to($this->redirectPath()); 
```

**Comment by mhfuad** [comment]
is this good practice? editing Vendor file?

**Comment by Lucky-Loek** [comment]
> Why not? A vendor file can also have bugs, right? I have been using this edited code for about a year now, everything is okay.

![afbeelding](https://user-images.githubusercontent.com/9716643/66551650-2c01d100-eb48-11e9-9565-548be78d86e1.png)

**Comment by Azimul-Haque** [comment]
> > Why not? A vendor file can also have bugs, right? I have been using this edited code for about a year now, everything is okay.
> 
> ![afbeelding](https://user-images.githubusercontent.com/9716643/66551650-2c01d100-eb48-11e9-9565-548be78d86e1.png)

Is composer update necessary always? After adding a package you can just call composer install or require package name from console, right?

**Comment by Lucky-Loek** [comment]
That is, but then you would never be able to install packages: https://stackoverflow.com/questions/33052195/what-are-the-differences-between-composer-update-and-composer-install

**Comment by Azimul-Haque** [comment]
> That is, but then you would never be able to install packages: https://stackoverflow.com/questions/33052195/what-are-the-differences-between-composer-update-and-composer-install

composer install will not update anything; it will just install all the dependencies as specified in the composer.lock file. I have been doing this for about a year.

**Comment by Lucky-Loek** [comment]
I meant, *update*, sorry! If you update a package and install it, it will clear any changes you've made to the package. As such, it's not recommended at all to edit vendor files directly.

**Comment by Azimul-Haque** [comment]
> I meant, _update_, sorry! If you update a package and install it, it will clear any changes you've made to the package. As such, it's not recommended at all to edit vendor files directly.

I did not try to find any other solution after trying this, so if you can find one, please let me know, cheers. :)

**Comment by anouarabdsslm** [comment]
@Azimul-Haque this bad for many reasons. 
First you have to create a PR to the main package so other consumers can get the fix.
Second your fixes will be gone if there is a new release for that package which may contain a fix for a security bug or whatever.
Third it very bad bad bad bad practice to edit packages on the vendor folder because the changes there could be lost at anytime and u may event not notice that if your code is not backed by test.
So what u can do in this cases:
Create PR to main package if not create a fork of it and update it as you like.

**Comment by erubielgzz** [comment]
Just add the method that @Azimul-Haque, mentioned on the LoginController, this will override the Vendor Library and your changes won't go away with composer.

`    /**
     * Send the response after the user was authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user())
            ?: redirect()->to($this->redirectPath());
    }
`

**Comment by fdalcin** [comment]
@Azimul-Haque @erubielgzz 

Instead of editing a vendor file (which is a bad practice) or overriding the whole ```sendLoginResponse``` method you could override the ```authenticated``` method.

```php
    /**
     * The user has been authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @param mixed $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        return redirect()->to($this->redirectPath());
    }
```

**Comment by erubielgzz** [comment]
@fdalcin  both are valid, probably yours is better, the important thing is that changes don't get overwritten.

**Comment by CarlosIvanHuerta** [comment]
**Hello friends, I resolve may problem whit this.**

->where('any', '^(?!js/).*');

in my web.php

`Route::view('/{any}','home')->where('any','^(?!js/).*');`
