### ISSUE TITLE
Feature request: set plugin URL manually

### ISSUE THREAD

**Issue by tgarm** [jeroennoten/Laravel-AdminLTE#281]
Currently, the plugin URLs are hard coded.
Would you please make it configurable? 

For instance:
in config/adminlte.php:
```php
  'plugins'=>[
    'datatables'=>[
      'css'=>'https://some-url-for-datatables-css',
      'js'=>'https://some-url-for-datatables-js'
    ],
   'select2'=>true    // use default URL
  ];
```

So that user may set URL for plugins manually. 
It would be very useful when it difficult to access some remote CDN servers.

Thank you in advance!

**Comment by josegus** [comment]
Wouldn't be better if we could create custom blade directives? @datatable and @select2, like @method or @csrf. This way I can use it only when i need it, instead of loading datatable and select2 cdn in every page. This allow me to define the path to datatable js and css.

**Comment by zhanang19** [comment]
You can check this #330 PR or just update from composer using `composer update jeroennoten/laravel-adminlte` command

**Comment by lacodimizer** [comment]
merged, thank you very much.
