### ISSUE TITLE
Compatibility with Laravel 5.8

### ISSUE THREAD

**Issue by robertogallea** [jeroennoten/Laravel-AdminLTE#282]
Please update composer.json to make it compatible with the current latest laravel release (5.8)

**Comment by Lucky-Loek** [comment]
This needs other changes as well, most notably the menu builder which uses the `fire()` method that has been removed.

**Comment by robertogallea** [comment]
Pull request filed

**Comment by xNaii** [comment]
![adminlte](https://user-images.githubusercontent.com/22669597/53830976-52490800-3f8c-11e9-8a58-7357ba2d86b3.png)

Not possible update to laravel 5.8 nor install it in laravel 5.8 yet

**Comment by robertogallea** [comment]
Unfortunately it is not available on packagist yet. You can still install it adding this GitHub repo to your composer.json file

**Comment by robertogallea** [comment]
In you composer.json:

"require": {
        ...
        "jeroennoten/laravel-adminlte": "dev-master#v1.25.0"
    },
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/jeroennoten/Laravel-AdminLTE.git"
        }
    ],

**Comment by xNaii** [comment]
When should expect to see it on packagist ?

**Comment by jeroennoten** [comment]
Fixed it guys! Sorry for the delay

**Comment by ArthurViniciusE** [comment]
Installation failed, reverting ./composer.json to its original content.
