### ISSUE TITLE
Compatibility with Laravel 5.0

### ISSUE THREAD

**Issue by yusufbayam** [jeroennoten/Laravel-AdminLTE#284]
Hello, it seems like this can not be used with Laravel 5.0 or i might be missing something. It would be great if it can be used with Laravel 5.0.

Thank you

**Comment by Lucky-Loek** [comment]
Just a heads up, Laravel 5.0 hasn't been supported for over three years now. Please consider upgrading to at least 5.5 and preferably 5.8 to get the most recent (security) updates.

**Comment by lvdhoorn** [comment]
@Lucky-Loek FYI Laravel-AdminLTE is not working yet on version 5.8.

jeroennoten/laravel-adminlte v1.24.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev]

**Comment by yusufbayam** [comment]
@Lucky-Loek thank you for answer. I also prefer to upgrade but im not able to change workplace environment.

**Comment by jeroennoten** [comment]
Only Laravel 5.1.12 and higher is supported by this package.

**Comment by lvdhoorn** [comment]
@jeroennoten can you add Laravel 5.8 to the list? I would love to upgrade to the latest version.
