### ISSUE TITLE
QUESTION: Remove /vendor/adminlte subfolder from public directory

### ISSUE THREAD

**Issue by PlanetGamingGG** [jeroennoten/Laravel-AdminLTE#285]
Hi, when I inspected the view-source, I saw that for the bootstrap CSS, it loads it from `http://127.0.0.1:8000/vendor/adminlte/vendor/bootstrap/dist/css/bootstrap.min.css`.
The question is, can this `/vendor/adminlte/` be removed from the URL so it looks like this: `http://127.0.0.1:8000/vendor/bootstrap/dist/css/bootstrap.min.css` Or even better `http://127.0.0.1:8000/css/bootstrap.min.css` ?

I know I can manually move the files but it would be nice if it's done automagically :)

**Comment by lacodimizer** [comment]
Why do you want to change the dirs? You get more problems on updates and integrations as you want. ;)

**Comment by PlanetGamingGG** [comment]
*Sorry for the late reply.

Haha, nice one ;)
But it would be nice if the resource path is shorter. Maybe there's a routing technique that I haven't learned yet?
