### ISSUE TITLE
Bug on sidebar Menu

### ISSUE THREAD

**Issue by nazordz** [jeroennoten/Laravel-AdminLTE#286]
When I am try to use @section('adminlte_js')  in my blade view, 
the submenu from sidebar is cannot open

**Comment by nopalnaxcpm** [comment]
to solve this prolem I need to change the name 'adminlte_js' from yield

**Comment by lacodimizer** [comment]
_Cleanup issue_

If the issue is omnipresent in the coming version 1.26.x, please create a new issue.
