### ISSUE TITLE
MenuBuilder with view composer doubles sidebar menu.

### ISSUE THREAD

**Issue by Sokan89** [jeroennoten/Laravel-AdminLTE#289]
Hi, i want to use the MenuBuilder depending on the guard which is used. The problem is, that i need a view composer to get the guards name. The problem thereby is, i get my sidebarmenu doubled. 

Code in AppServiceProvider:

public function boot(Dispatcher $events) {
        view()->composer('*', function ($view) use ($events) {
            if (Auth::guard('client')->check())
            $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
                $event->menu->add([
                    'text'        => 'Dashboard',
                    'url'         => 'dashboard',
                    'icon'        => 'clipboard',
                ]);
            });
        });
    }

Outcome:
<img width="472" alt="Bildschirmfoto 2019-03-21 um 10 59 50" src="https://user-images.githubusercontent.com/8287611/54744914-7d586c00-4bc8-11e9-914c-06fc973f1f51.png">

**Comment by Sokan89** [comment]
Ok, the view composer calls each blade and attempt the menuBuilder. Thats the reason why its doubled. A cooler approach for the future would be, if i can set the guard in the option like:

$event->menu->add([
                        'text'        => 'Dashboard',
                        'url'          => 'dashboard',
                        'icon'       => 'clipboard',
                        'guard'     => 'client'
                    ]);

I dont really need gates for my application. But currently i would have to write for every route one.

**Comment by sakrancode** [comment]
i had same issue, but i got solution.
the problem are, cause the path on view()->composer('*', function ($view)

in my case, cause all folder i put on pages folder. 
this the original folder "resources/views", i change to "resource/views/pages"

and for general original path use "*.*" i change to "pages.*.*".

this is full code on my serviceprovider 

`$path = "pages.*.*";

         view()->composer($path, function($view) use ($events){
         // View::composer(['*.*.*'], function ($view){
             // $view->with('coba', auth()->user());

            $user = Auth::user();

            if ($user->level=='A') {
                $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
                    // $event->menu->add('MAIN NAVIGATION');
                    // $event->menu->add([
                    //     'text' => 'search',
                    //     'search' => true,
                    //     'topnav' => true,
                    // ]);
                    // $event->menu->add([
                    //     'text' => 'blog',
                    //     'url'  => 'admin/blog',
                    //     'can'  => 'manage-blog',
                    // ]);
                    $event->menu->add([
                       'text'        => 'Dashboard',
                       'url'         => 'home',
                       'icon'        => 'fas fa-fw fa-tachometer-alt',
                       // 'label'       => 4,
                       // 'label_color' => 'success',
                    ]);
                    // $event->menu->add(['header' => 'account_settings']);
                    $event->menu->add('MAIN NAVIGATION');
                    $event->menu->add([
                        'text'        => 'Data Master',
                        'url'         => 'publisher',
                        'icon'        => 'fas fa-fw fa-server',
                        'submenu' => [
                            [
                                'text' => 'Kategori',
                                'url'  => 'category',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                            [
                                'text' => 'Metode',
                                'url'  => 'method',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                            [
                                'text' => 'Langkah Kegiatan',
                                'url'  => 'step',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                            [
                                'text' => 'Data Tahapan',
                                'url'  => 'question',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                            [
                                'text' => 'Anggota',
                                'url'  => 'user',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                            [
                                'text' => 'Penelitian',
                                'url'  => 'research',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                        ],
                    ]);
                    $event->menu->add([
                        'text'    => 'Laporan',
                        'icon'    => 'fas fa-fw fa-file-alt',
                        'submenu' => [
                            // [
                            //     'text' => 'Notula Rapat',
                            //     'url'  => 'notula',
                            //     'icon' => 'fas fa-fw fa-chevron-right',
                            // ],
                            [
                                'text' => 'Input Detail Tahapan',
                                'url'  => 'answer',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                        ],
                    ]);
                    // $event->menu->add([
                    //     'text'        => 'Pengaturan',
                    //     'url'         => 'book',
                    //     'icon'        => 'fas fa-fw fa-cog',
                    //     // 'label'       => 4,
                    //     // 'label_color' => 'success',
                    // ]);
                });
            }else{
                $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
                    $event->menu->add([
                       'text'        => 'Dashboard',
                       'url'         => 'home',
                       'icon'        => 'fas fa-fw fa-tachometer-alt',
                       // 'label'       => 4,
                       // 'label_color' => 'success',
                    ]);
                    // $event->menu->add(['header' => 'account_settings']);
                    $event->menu->add('MAIN NAVIGATION');
                    $event->menu->add([
                        'text'    => 'Laporan',
                        'icon'    => 'fas fa-fw fa-file-alt',
                        'submenu' => [
                            // [
                            //     'text' => 'Notula Rapat',
                            //     'url'  => 'notula',
                            //     'icon' => 'fas fa-fw fa-chevron-right',
                            // ],
                            [
                                'text' => 'Input Detail Tahapan',
                                'url'  => 'answer',
                                'icon' => 'fas fa-fw fa-chevron-right',
                            ],
                        ],
                    ]);
                });
            }

         });`

thanks
