### ISSUE TITLE
ISSUE: can method not working

### ISSUE THREAD

**Issue by drldejacto** [jeroennoten/Laravel-AdminLTE#290]
this is my menu
'ADMINISTRATOR SETTINGS',
         [
            'text' => 'Accounts Settings',
            'url'  => 'accountSettings',
            'icon' => 'users',
            'can'  => 'admin_only'
        ],
        [
            'text'    => 'Libraries',
            'icon'    => 'share',
            'submenu' => [
                [
                    'text' => 'Document Categories',
                    'url'  => 'category',
                    'can'  => 'admin_only'
                ],
           ],
        ],

and my gate in my AuthServiceProvider

public function boot()
    {
        
        $this->registerPolicies();

        Gate::define('admin_only', function ($user) {
            if($user->is_admin == 1){
                return true;
            }
            return false;
        });
        //
    }

but nothing is happening.

**Comment by tusharsinhparmar** [comment]
You have is_admin field in users table? And current login user is set to 1 in is_admin field.

**Comment by lacodimizer** [comment]
Is the issue actual?

**Comment by drldejacto** [comment]
This issue is already fixed.

Thank you.
