### ISSUE TITLE
ISSUE: Select2 missing bootstrap theme

### ISSUE THREAD

**Issue by CrystalShardz** [jeroennoten/Laravel-AdminLTE#293]
The bootstrap theme is missing for the Select2 plugin meaning it does not display properly. Suggest adding a line to include it if using select2.

**Comment by CrystalShardz** [comment]
https://github.com/select2/select2-bootstrap-theme

**Comment by lacodimizer** [comment]
@REJack any idea?

**Comment by REJack** [comment]
This theme isn't included in AdminLTE v2, but I can include it with the next release.
