### ISSUE TITLE
menu item blade Undefined Variable $item

### ISSUE THREAD

**Issue by yogithesymbian** [jeroennoten/Laravel-AdminLTE#295]
**i know , we should'nt edit a vendor script ,**

_https://adminlte.io/docs/2.4/main-header_

i have trying to add code in the `page.blade.php`
                    
<li> tes </li>
//Main Header code From Document Admin LTE
//this line

after i have been add, i got ...

"Undefined variable: item (View: /var/www/html/laravel/laraveladmin/vendor/jeroennoten/laravel-adminlte/resources/views/partials/menu-item.blade.php) (View: /var/www/html/laravel/laraveladmin/vendor/jeroennoten/laravel-adminlte/resources/views/partials/menu-item.blade.php) (View: /var/www/html/laravel/laraveladmin/vendor/jeroennoten/laravel-adminlte/resources/views/partials/menu-item.blade.php) ◀"

when i ctrl + z 
same , still got that .

should i add some code in `config/adminlte.php` ?

Thanks In Advance

**Comment by lacodimizer** [comment]
it was fixed and come with version 1.26.x
