### ISSUE TITLE
please add section in header tag of master.blade.php

### ISSUE THREAD

**Issue by redmagi** [jeroennoten/Laravel-AdminLTE#296]
please add section in header tag of master.blade.php

like

`    
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    @yield('header')

/head>`

in file Laravel-AdminLTE/resources/views/master.blade.php

**Comment by lacodimizer** [comment]
Hi, you can add additional css files on the "adminlte_css" yield.
