### ISSUE TITLE
 integrate with laravel mix

### ISSUE THREAD

**Issue by Helidalto** [jeroennoten/Laravel-AdminLTE#297]
how do I integrate package with laravel mix?

**Comment by ryantxr** [comment]
@Helidalto, you should elaborate on what you mean by this. What are you trying to accomplish?

**Comment by REJack** [comment]
I think he want to compile the AdminLTE assets with Laravel’s [Mix feature](https://laravel.com/docs/5.8/mix).

**Comment by Helidalto** [comment]
that's what my friend said, I've managed to solve it, I've included the assets in require as css and js files and I managed to compile in the mix, thanks for the attention! good night!

**Comment by saquack** [comment]
Can post how you included the assets?
