### ISSUE TITLE
QUESTION: How to use regex to set active URL in menu?

### ISSUE THREAD

**Issue by rpm192** [jeroennoten/Laravel-AdminLTE#299]
The readme says the following:

> To override this behavior, you can specify an active parameter with an array of active URLs, asterisks and **regular expressions** are supported.

So, in my menu I have the following:
```php
[
              'text'    => 'Posts overview',
              'url'     => '/posts',
              'icon'    => 'list',
              'active'  => ['/posts'],
],
```

It matches the `/posts` URL fine, but I need it to also match `/posts/{id}`. I can not use `/posts/*` since that will make it active on `/posts/create` and other pages.

I'm stuck at how to implement the regex, I have tried:
```php
[
              'text'    => 'Posts overview',
              'url'     => '/posts',
              'icon'    => 'list',
              'active'  => ['/posts', '/posts/[^0-9]'],
],
```
But it doesn't work unfortunately: Menu doesn't light up.

The controller is a resource controller, with the normal resource routes.

**Small update:**

I have also tried this: `^\/posts\/[0-9]+$`, which unfortunately also doesn't work.
It does seem to match the correct URL's.

[Regex101 Link](https://regex101.com/r/xeseaH/1)

Any ideas on how to fix it?

**Comment by Shweta-Adya** [comment]
You can try using the below pattern in your code:

/^\/posts(\/[0-9]+)?$/

This will work for the below test scenarios:

/posts
/posts/3829
/posts/921
/posts/1
You can check the requirement with the provided solution on 
(https://regex101.com/r/xeseaH/3)

Hope it works!

**Comment by nguyenhychan** [comment]
It **won't** work. I have tried different types of regex which includes the '/^.*$/' which should work whatever link I click on but it just doesn't. When I look up the `vendor/jeroennoten/laravel-adminlte/src/Menu/ActiveChecker.php` which should be responsible for matching this, I saw that the function `isActive` depends on the `checkPattern` function, which uses the `Str::is` function in the Laravel API. The function definition of `Str::is` contains a `preg_quote` call which would basically **escape out all the regex characters**, so whatever way the pattern is inserted into the config file would still be not working.

**Comment by rpm192** [comment]
> It **won't** work. I have tried different types of regex which includes the `/^.*$/` which should work whatever link I click on but it just doesn't. When I look up the `vendor/jeroennoten/laravel-adminlte/src/Menu/ActiveChecker.php` which should be responsible for matching this, I saw that the function `isActive` depends on the `checkPattern` function, which uses the `Str::is` function in the Laravel API. The function definition of `Str::is` contains a `preg_quote` call which would basically **escape out all the regex characters**, so whatever way the pattern is inserted into the config file would still be not working.

Yes, this is true. There's currently no way of utilising Regex to set a menu item as active.

In the pull request mentioned above, I made it so that you can prefix your regex pattern with `regex:` and it will compare the regex with the request path. [This commit](https://github.com/jeroennoten/Laravel-AdminLTE/pull/301/commits/9cede2ff6e2b0c959d307b10434f4d630234771e).

I've tested it for a number of links and it seems to be working correctly.

**Comment by lacodimizer** [comment]
It was merged and will be released soon.
