### ISSUE TITLE
Highlight active menu items

### ISSUE THREAD

**Issue by 11digitlabs** [JeroenNoten/Laravel-AdminLTE#3]
Hey @JeroenNoten 
Thanks a lot for the wonderful work

Wanted to ask you, is there a way to highlight the active menu item?

Thank you

**Comment by 11digitlabs** [comment]
I think I've got it. I will modify the  menu-item.blade.php and check if the item url is the same as the current page and add class active

Thanks, i'm leaving it open so that I remember to create a pull request :)

**Comment by JeroenNoten** [comment]
Glad you like the package! A PR for this feature is very welcome.

However, I'll close this issue if you don't mind. I like to keep the open issue list clean.
