### ISSUE TITLE
How to make laravelAdminlt to 2 users

### ISSUE THREAD

**Issue by honore237** [jeroennoten/Laravel-AdminLTE#300]
How to make laravelAdminlt to 2 users , Administrator and manager account

**Comment by nguyenhychan** [comment]
Do you mean 
1. restricting access basing on their user groups OR
2. to show different menu items basing on their user groups?

For #1 this cannot be done with the AdminLTE alone, you have to use the Gate functionality in laravel which you can check out the documentations.
For #2, you can use the `'can'` directive in the config for the menu.

**Comment by lacodimizer** [comment]
This is a job for laravel, but you can do this. Take a look to the repo https://github.com/spatie/laravel-permission/.

**Comment by honore237** [comment]
Yes great, i have done it well. Thanks for your help
