### ISSUE TITLE
Fixed layout  : menu scroll back to the top when expand sub-menu

### ISSUE THREAD

**Issue by ibrahimPntr** [jeroennoten/Laravel-AdminLTE#305]
I use a fixed layout, I have a lot of menus in my sidebar, so, some menus need to scroll to open them, when I expand the menu after scrolling down the scroll menu back up and I have to scroll down again to press the menu I want

**Comment by REJack** [comment]
This is an issue from AdminLTE, it will be fixed in v2.4.13.

**Comment by lacodimizer** [comment]
@REJack What is the status of the update? :)

**Comment by REJack** [comment]
@lacodimizer I'll add later some little fixes to v2.4.13 and release it tomorrow.

**Comment by lacodimizer** [comment]
Oh great! So I can merge it in the upcoming release.

**Comment by REJack** [comment]
@lacodimizer v2.4.13 ist auf GitHub released und auch auf npm/packagist verfügbar 😝 

v2.4.13 is released on GitHub and available on npm/packagist too.

**Comment by lacodimizer** [comment]
@REJack nice, it was merged :)

**Comment by ibrahimPntr** [comment]
Thanks @REJack, @lacodimizer
