### ISSUE TITLE
QUESTION: supporting for bootstrap 4?

### ISSUE THREAD

**Issue by karthickshiva18** [jeroennoten/Laravel-AdminLTE#306]
Please guide me for bootstrap 4 how to install

**Comment by MarlonEtiene** [comment]
up

**Comment by yurifoxx** [comment]
up

**Comment by lacodimizer** [comment]
Hi, I will check this in a next sprint to merge an open pr about bootstrap 4.

**Comment by lacodimizer** [comment]
We wait for adminlte 3 with bootstrap 4 support.

**Comment by marcelogarbin** [comment]
How to use version 3 with bootstrap 4?
