### ISSUE TITLE
Question: How to put google analytics on every page

### ISSUE THREAD

**Issue by ryantxr** [jeroennoten/Laravel-AdminLTE#316]
It seems that there isn't a way to inject JavaScript into the master page. Seems like this should be a thing.
I'm thinking something like this:
```
@push('adminlte_master_js')
<script>
whatever
</script>
@endpush
```
Then in the master page:
```
@stack('adminlte_master_js')
```
Can I submit a PR for this?

**Comment by lacodimizer** [comment]
You can add js files in the section "adminlte_js". 
https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/master.blade.php#L79
