### ISSUE TITLE
Undefined index: icon with dev-master

### ISSUE THREAD

**Issue by REJack** [jeroennoten/Laravel-AdminLTE#317]
I've installed Laravel 5.8.28 with Laravel-AdminLTE (dev-master) and I faced this error.

![Screenshot_2019-07-16 Whoops There was an error (1)](https://user-images.githubusercontent.com/1554582/61286945-39672380-a7c4-11e9-9c49-9fcb80ae9909.png)

If I remove the multilevel & labels part of the `config/adminlte.php` the error disappear also the `fa fa-fw fa-`-part should removed to use FontAwesome 5 Icons correctly.

I've also faced this error but I can't reproduce it anymore even after a complete re-install
![Screenshot_2019-07-16 Whoops There was an error ](https://user-images.githubusercontent.com/1554582/61288929-79300a00-a7c8-11e9-864d-088ae71401b8.png)

**Comment by REJack** [comment]
I fixed this error with little changes
```<i class="fa fa-fw fa-{{ $item['icon'] or 'circle-o' }} {{ isset($item['icon_color']) ? 'text-' . $item['icon_color'] : '' }}"></i>``` 
to
```<i class="fa fa-fw fa-{{ $item['icon'] ?? 'circle-o' }} {{ isset($item['icon_color']) ? 'text-' . $item['icon_color'] : '' }}"></i>```

But I also removed the `fa fa-fw fa-` and changed the `circle-o` to `far fa-fw fa-circle`, like this
```
<i class="{{ $item['icon'] ?? 'far fa-fw fa-circle' }} {{ isset($item['icon_color']) ? 'text-' . $item['icon_color'] : '' }}"></i>
```

**Comment by lacodimizer** [comment]
Can you test the master again please? :)

**Comment by REJack** [comment]
Yep, I'll test it later :D

**Comment by REJack** [comment]
Tests done, PR created 😄

**Comment by lacodimizer** [comment]
great!

**Comment by REJack** [comment]
No problem, I'll close this issue.
