### ISSUE TITLE
Sidebar Toggle icon missing in dev-master

### ISSUE THREAD

**Issue by REJack** [jeroennoten/Laravel-AdminLTE#318]
I've found a bug according to the FontAwesome 5 upgrade, the sidebar-toggle display's no icon.
![Screenshot_2019-07-16 AdminLTE](https://user-images.githubusercontent.com/1554582/61291334-8819bb00-a7ce-11e9-9201-222d305cf2e1.png)

It need the extra class `fa5` for this, like this
```
<a href="#" class="sidebar-toggle fa5" data-toggle="push-menu" role="button">
```

**Comment by lacodimizer** [comment]
Do you think, we should work with the adminlte fontawesome v4.7.0, which is included? So we wait for the adminlte v3 with fontawesome 5?

**Comment by REJack** [comment]
No it's not needed to stuck on FA4 you only need to add `.fa5` to the sidebar-toggle like my example, the extra class set the correct unicode, font family & font weight that's needed since FA5 to get the correct style.
