### ISSUE TITLE
[IDEA] composer scripts for easier starts/updates

### ISSUE THREAD

**Issue by REJack** [jeroennoten/Laravel-AdminLTE#326]
Composer has features to run scripts after install/update (Laravel uses them too 😄),
with this we could run the following artisan commands after every update (may with `--force`)

`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets`
`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=config`
`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=translations`

I think this would be a great feature.

EDIT: config/translations only on install but assets on update too.

**Comment by lacodimizer** [comment]
Good idea and we should provide an upgrade guide, for main changes.

**Comment by REJack** [comment]
Sweet, I'll create a PR for this.

**Comment by REJack** [comment]
Ok, idea cancled 😞 We could only accomplish this with an own laravel project template.

> Note: Only scripts defined in the root package's `composer.json` are executed. If a dependency of the root package specifies its own scripts, Composer does not execute those additional scripts.

https://getcomposer.org/doc/articles/scripts.md#defining-scripts
