### ISSUE TITLE
QUESTION: custom menu - Enable can not

### ISSUE THREAD

**Issue by browndemon** [jeroennoten/Laravel-AdminLTE#327]
Can not put in the menu, because I have this problem, my super admin can see everything and everyone there when I use for example normal user super admin can see, if you already have how can I use can not?

**Comment by browndemon** [comment]
Hint use ACL for the GateFilter;: 
protected function isVisible($item)
    {
        if (! isset($item['can'])) {

            return true;
        }

        if (isset($item['model'])) {

            return $this->gate->allows($item['can'], $item['model']);
        }

        return auth()->user()->hasAnyRoles($item['can']);
    }

    protected function notVisible( $item)
    {

        if (! isset($item['cannot'])) {

            return true;
        }
        if (isset($item['model'])) {

            return $this->gate->denies($item['cannot'], $item['model']);
        }

        return !auth()->user()->hasAnyRoles($item['cannot']);
    }

**Comment by lacodimizer** [comment]
You can add a new menu filter to solve your problem. I think it's not important enough to include this in our project.

**Comment by cf-git** [comment]
U cn make custom provider to build dynamically menu. So, on this stage u cn filter items for menu building.
Logic like `AppServiceProvider`:
```php
use Illuminate\Events\Dispatcher;
//...
public function boot(Dispatcher $events) {
    $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
         // your logic -> $myFilteredMenu
        $event->menu->add(__("my menu label"));
        $event->menu->add($myFilteredMenu);
        // ... etc
    });
}
```
