### ISSUE TITLE
QUESTION: How to modify top right bar menu bar?

### ISSUE THREAD

**Issue by jpossetti** [jeroennoten/Laravel-AdminLTE#328]
Hi, I need to add some items before "Logout" option in the top right bar. In the config file I don't see any option. Is that posible or may I need to edit source files?

**Comment by brandonsueur** [comment]
Hello ! 👋 

It's pretty simple. At first you have to recover the partials by making the following command :

```bash
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views
```

Now, you can edit the views in resources/views/vendor/adminlte/page.blade.php

See you soon ! 👌
