### ISSUE TITLE
QUESTION: version beta of AdminLTE

### ISSUE THREAD

**Issue by timoteo7** [jeroennoten/Laravel-AdminLTE#334]
Can make some official branch to test the Beta Version of AdminLTE ?
[AdminLTE v3.0.0-beta.2](https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.0.0-beta.2)

to try to see, what news can already work ?

**Comment by lacodimizer** [comment]
I will make a offical branch in the next days.

**Comment by REJack** [comment]
@lacodimizer I would create a PR for these changes. 😄

**Comment by lacodimizer** [comment]
@REJack <3

**Comment by stepel** [comment]
@lacodimizer I am glad to hear that. I've just used your project and I was wondering if it's worth to change to AdminLTE 3 ? Do you think that AdminLTE3 is ready for production using?

**Comment by lacodimizer** [comment]
@stepel We want to check this project with the current version of adminlte3. A new stable version of this project will be only published if the stable version of adminlte3 is released.

**Comment by lacodimizer** [comment]
Version 1.26.0 was released now. The next focus is on AdminLTE3.

**Comment by lacodimizer** [comment]
@REJack the branch adminlte3 was created, so you can create your pr on this branch :)

**Comment by REJack** [comment]
@lacodimizer Ok sweet 😄

**Comment by lacodimizer** [comment]
@REJack What's the actual state of the project? :D

**Comment by REJack** [comment]
@lacodimizer Sorry I've worked on AdminLTE v3, but I'll commit my changes soon and create a PR draft.

**Comment by lacodimizer** [comment]
@REJack no problem and no stress 👍 :D

**Comment by lacodimizer** [comment]
Please follow the new issue #386 with informations about the integration of AdminLTE v3.

**Comment by agaitan026** [comment]
Hi sir, how i can install adminlte3 in laravel6? i only need to change composer.json file? thank you

**Comment by lacodimizer** [comment]
Please wait for the coming RC in the next days.

**Comment by agaitan026** [comment]
thank you very much
