### ISSUE TITLE
Refresh a @section('content') page without refreshing master page in laravel

### ISSUE THREAD

**Issue by devpacto** [jeroennoten/Laravel-AdminLTE#337]
How to update content only, without reloading the entire page.
I'm starting in Laravel.

**Comment by cf-git** [comment]
Hello. Can you tould more details about your task?

**Comment by devpacto** [comment]
Hello. I am wanting that when you click on link in the menu load only @section ('content') (main content) and not load the master blade and page blade again. It's possible?
Can you understand?

**Comment by lacodimizer** [comment]
It's a good question. In default, you can not use this. You have to change the menu blade template to trigger a ajax action, to change the content.

**Comment by devpacto** [comment]
I'm new to Laravel and using AdminLTE, can you give an example as it would be in my case?

**Comment by lacodimizer** [comment]
Sorry, I don't have a example for this. I think, you have to search for it... ;)
