### ISSUE TITLE
Class 'App\Providers\Page' not found

### ISSUE THREAD

**Issue by wenchang410** [jeroennoten/Laravel-AdminLTE#339]
I have tried to run this project on my local as in the installation.
When I edit AppServiceProvider.php, I found there is a "Page" class.
Like here :

`public function boot(Dispatcher $events)
    {
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add(trans('menu.pages'));
            $items = Page::all()->map(function (Page $page) {
                return [
                    'text' => $page['title'],
                    'url' => route('admin.pages.edit', $page)
                ];
            });
            $event->menu->add(...$items);
        });
    }`

But I couldn't found where the Page is defined.
When I run the code, error as like the Title happened.
I'd like you to help me to run this code, hint me about "Page".
Thank you.

**Comment by lacodimizer** [comment]
@wenchang410  Do you use the example in the readme? delete the content of public function boot.
