### ISSUE TITLE
Issue: Sweet Alert 2 problems

### ISSUE THREAD

**Issue by andcarpi** [jeroennoten/Laravel-AdminLTE#349]
Sweet Alert 2 CDN not working out of the box, as intended...
We can correct this by changing the CDN file, but the fonts get too small because adminlte use bootstrap 3, and sweetalert 2 probably expecting bootstrap 4 bigger font size...

Possible Actions: 
1 - Only change CDN (small sweet alerts)
2 - Change CDN and fix font sizes (but that will require extra css in master or extra CSS file)
3 - Add Sweet alert in plugins as an asset (and add the extra fix css file in the folder)
3 - Remove Sweet Alert 2 plugin from default plugins

What do you think?

**Comment by JuniYadi** [comment]
for now, i'm use like this

```
@section('js')
    <script type="text/javascript">
        swal('Error!', 'Do you want to continue','error')
    </script>
@stop
```

**Comment by lacodimizer** [comment]
If option 1 works, we should do this.
