### ISSUE TITLE
ISSUE: trans does not exist

### ISSUE THREAD

**Issue by intralix** [jeroennoten/Laravel-AdminLTE#354]
In laravel 6:

Method Illuminate\Translation\Translator::trans does not exist. 
(View: /laravel/project/resources/views/vendor/adminlte/page.blade.php)

**Comment by ntqduc** [comment]
I still have this issue. When do you fix this issue @andcarpi ?

**Comment by marcosrocha85** [comment]
Yes it does. Laravel 6.0 changed the [Translation contract](trans-and-trans-choice). I'm working on a solution which can handle both 6.0 and under Laravel versions just right now.

**Comment by ulver2812** [comment]
Same issue here, you will commit this fix on the laravel-6 branch?

I installed the master branch through composer, when you will publish the fix I will install the laravel-6 branch in my project with 
`composer require jeroennoten/laravel-adminlte:dev-laravel-6`
is it correct ?

**Comment by lacodimizer** [comment]
The commit is already merged in laravel-6 branch.

You can try to get the actual branch over composer, but I recommend to work with stable releases. The release of this project for Laravel 6 is coming soon in the next days.

**Comment by myixyt** [comment]
I look forward to seeing the new version for laravel6 as soon,Thanks!

**Comment by LahiruR** [comment]
I got same issue

**Comment by lacodimizer** [comment]
You can test the version v2.0.0.rc1 with this fix.

**Comment by lacodimizer** [comment]
v2.0.0 is released for a few days, so I close the issue.
