### ISSUE TITLE
ISSUE: Make Admintle Command is not definde

### ISSUE THREAD

**Issue by intralix** [jeroennoten/Laravel-AdminLTE#355]
When trying to run **php artisan make:adminlte** in Laravel 6:

Command "make:adminlte" is not defined.  
                                           
  Did you mean one of these?               
      make:channel                         
      make:command                         
      make:controller                      
      make:event                           
      make:exception                       
      make:export                          
      make:factory                         
      make:import                          
      make:job                             
      make:listener                        
      make:mail                            
      make:middleware                      
      make:migration                       
      make:model                           
      make:notification                    
      make:observer                        
      make:policy                          
      make:provider                        
      make:request                         
      make:resource                        
      make:rule                            
      make:seeder                          
      make:test

**Comment by shaan207** [comment]
Facing the same issue? @andcarpi When will you push it?

**Comment by ulver2812** [comment]
Same issue here, I think that the alternative way is to use the Laravel make:auth command and then replace the blade template with the Laravel-Admin LTE ones.

**Comment by andcarpi** [comment]
You guys need to wait @lacodimizer accept the pull request or manually change the installed package with the commit.
@ulver2812 solution is valid too.

**Comment by lacodimizer** [comment]
Hi guys! :) I created a new branch only for laravel 5 and a new branch for laravel 6. So we can support the project for this major versions easier and better.
@andcarpi You can change the branch of your pr's to laravel-6 branch.

**Comment by andcarpi** [comment]
@lacodimizer even with the command now working in laravel-6 branch, i'm rebuilding It to be more like an all-in-one solution for the l6 version. It's adminlte:install and it should install everything needed. What u think? 
You can check an mvp done in my fork. (New-adminlte-install-command).

**Comment by lacodimizer** [comment]
Hi @andcarpi , I think it's a good point of view to refactoring the install command. So we can remove the make:adminlte command in this way.

**Comment by lacodimizer** [comment]
@andcarpi can you add a upgrade guide and fix the trans calls in the blade templates please? :) I think we should work with __ instead of trans in the templates.

**Comment by andcarpi** [comment]
Sure... gonna check the translations on the views...
About the upgrade guide... u mean from adminlte 2 to 3 or laravel 5.8 to 6.0?

**Comment by lacodimizer** [comment]
I mean the upgrade from Laravel 5.x to 6.x :)

**Comment by jodavila** [comment]
hi, I was trying and the new comand ' adminlte:install' doens't work

**Comment by lacodimizer** [comment]
Do you work with v2.0.0.rc1?

**Comment by andcarpi** [comment]
Working fine here on Laravel 6 and RC1 
![image](https://user-images.githubusercontent.com/13441557/64926193-16132180-d7d1-11e9-9091-a19b07902e5a.png)

**Comment by PlanetGamingGG** [comment]
Okay, I've installed the `laravel-6` branch to my Laravel 6 before v2.0.0. was released. Should I switch to v2.0.0. instead of `laravel-6` branch?

**Comment by lacodimizer** [comment]
yes

**Comment by PlanetGamingGG** [comment]
Okay @lacodimizer , can you tell me how to overwrite my existing `laravel-6` branch with `v2.0.0.` properly?

**Comment by lacodimizer** [comment]
do you work with composer?

**Comment by PlanetGamingGG** [comment]
Yes I do work with Composer @lacodimizer

**Comment by lacodimizer** [comment]
You only have to change the version in the composer syntax, like 
"jeroennoten/laravel-adminlte": "^2.0"

**Comment by PlanetGamingGG** [comment]
Oh Nice, thanks @lacodimizer .

**Comment by PiousVenom** [comment]
I've got:

```
        "jeroennoten/laravel-adminlte": "^2.0",
        "laravel/framework": "6.0.*",
```
And the `php artisan make:adminlte` still doesn't work for me. Am I missing something?

**Comment by lacodimizer** [comment]
The command is removed in version 2.x. Please try the new command adminlte:install
We change the readme. Sorry for that.
