### ISSUE TITLE
I cannot Add the service provider to the providers in config/app.php

### ISSUE THREAD

**Issue by sanjayrnath** [jeroennoten/Laravel-AdminLTE#36]
Im using WAMP and 1st step to install : composer require jeroennoten/laravel-adminlte
Is completed. 
But there is not config/app.php file in the folder. So i cannot add the service provider. Please help.

**Comment by jeroennoten** [comment]
This is a Laravel package, make sure you first install Laravel. See laravel.com. Then follow the installation steps for this package.

**Comment by sanjayrnath** [comment]
Thank you so much. I'm new to laravel sorry.
