### ISSUE TITLE
config/adminlte.php not working

### ISSUE THREAD

**Issue by thuram** [jeroennoten/Laravel-AdminLTE#37]
I tried to make some changes in the configuration file / adminlte.php
example:
```
    'menu' => [
    	// CODE
        'MAIN NAVIGATION',
        [
            'text' => 'My Blog', // change name
            'url'  => 'admin/', // remove 'can' 
        ],
        // CODE
    ]
```
But when I update my page menu is not changed.

**Comment by jeroennoten** [comment]
Hmm that's strange. Do you maybe have your config cached? Try running `php artisan config:clear`.

**Comment by thuram** [comment]
Solved !

**Comment by rafael-marques** [comment]
Hi @jeroennoten 

I am having the same problem here.

Is it possible to update config/adminlte.php and change the the settings without clear cache from artisan CLI?

**Comment by lacodimizer** [comment]
@rafael-marques that‘s not possible, because of the default caching system of Laravel.

**Comment by rafael-marques** [comment]
@lacodimizer Thanks man !

**Comment by grab95** [comment]
hi i heave the same problem , config:clear don't work .

**Comment by manusimpson** [comment]
Hi guys, I've same problem that @grab95 , run php artisan config:clear but nothing happen.
I modified 'menu' array, even setting 'menu' = [] but no changes.
Thanks in advance

**Comment by Shidersz** [comment]
Please, review the `bootstrap/cache` folder of your Laravel application. When you run `php artisan config:cache` a file `config.php` is usually created there. Then, if you run `php artisan config:clear` that file should be removed. So, you may check that the mentioned file do not exists.

**Comment by manusimpson** [comment]
The file don't exists, but I did a test and when I generate it with "_php artisan config:cache_" the file content is generated with the default menu, so I think that the system is using another file that I can't found because in my adminlte config file this data was removed.

**Comment by Shidersz** [comment]
@manusimpson That is rare, maybe you can try searching one of the package configuration options, to check if others files exists in your project. For example, on `Linux` you can run next command in the root folder of your project (other ways may exists for other operating systems):
```sh
grep -r "layout_fixed_footer" .
```
That command gives me next output:
```sh
./vendor/jeroennoten/laravel-adminlte/config/adminlte.php:    'layout_fixed_footer' => null,
./config/adminlte.php:    'layout_fixed_footer' => null,
```
On my environment, `./vendor/jeroennoten/laravel-adminlte/config/adminlte.php` is the default package configuration file and `./config/adminlte.php` is the published one, which is ok.

**Comment by manusimpson** [comment]
@Shidersz, well... I found the problem, as you say there are 2 files and I was working on default config and the correct in my enviroment is ./config/adminlte.php. So, was solved.
Thanks a lot. Gracias
