### ISSUE TITLE
ISSUE: Error while extending the default template

### ISSUE THREAD

**Issue by djlimix** [jeroennoten/Laravel-AdminLTE#372]
When I use 

*@extends('adminlte::page')*

I get this error
Argument 1 passed to JeroenNoten\LaravelAdminLte\AdminLte::__construct() must be of the type array, null given, called in D:\gymesweb\vendor\jeroennoten\laravel-adminlte\src\AdminLteServiceProvider.php on line 22

Laravel version: *6.0*
AdminLTE version: *2.0*

What's wrong?

**Comment by lacodimizer** [comment]
Do you have installed the project like the instruction in the readme? The config (file) is missing, that‘s the error.

**Comment by djlimix** [comment]
I did everything like in the readme, but when I try to publish either assets, or views, or config, nothing happens. Console outputs that it was published, but nothing was published

**Comment by lacodimizer** [comment]
I think there are problems with windows setups...

**Comment by djlimix** [comment]
So the error was in your Readme, it is not *JeroenNoten\LaravelAdminLte\ServiceProvider*, it is *JeroenNoten\LaravelAdminLte\AdminLteServiceProvider*. I've changed the publish command provider to this and it was published

**Comment by lacodimizer** [comment]
Do you used the readme of the master branch? Thats for Laravel 5. With Laravel 6 we renamed the service provider. ;)

**Comment by djlimix** [comment]
Yes, I used readme of the master branch. Sorry :)
