### ISSUE TITLE
QUESTION: Can't install AdminLTE

### ISSUE THREAD

**Issue by TD-RA** [jeroennoten/Laravel-AdminLTE#379]
Today I was creating a project with Laravel, all went well, but once I add the

`JeroenNoten\LaravelAdminLte\ServiceProvider::class,`

And try to publish the assests it only returns me:

  Class 'JeroenNoten\LaravelAdminLte\ServiceProvider' not found

I have never found this error, and its setting me and my team quite a bit.

 Thank you in advance for your time.

**Comment by andcarpi** [comment]
Laravel and AdminLTE version?

**Comment by TD-RA** [comment]
> 
> 
> Laravel and AdminLTE version?

I have tried with 

Laravel 5.5.*   5.7.*  and 6.*
I am just using the most current of AdminLTE provided by this project.

**Comment by TD-RA** [comment]
Ok I read the ReadMe update and I tried again and it worked. I guess I was doing it wrong. Thanks to everything.

**Comment by ob1y2k** [comment]
run : composer dump-autoload
