### ISSUE TITLE
INFORMATION about the integration of AdminLTE v3

### ISSUE THREAD

**Issue by lacodimizer** [jeroennoten/Laravel-AdminLTE#386]
Hello friends,

I like to inform you, that @REJack and I work hard for the coming Beta1 with AdminLTE v3 support.

It will be compatible only with Laravel 6.

At the moment, you can test the branch "laravel6-adminlte3" for the actual stand of the development. But please understand, that we can't give support at the moment. The support will be added from the coming Beta1.

Best regards,
Flo

**Comment by agaitan026** [comment]
Hi sir, how i can install adminlte3 in laravel6? i only need to change composer.json file? thank you

**Comment by lacodimizer** [comment]
The version v3.0.0 with AdminLTE v3 support is released. :)
