### ISSUE TITLE
QUESTION: Additional navbar component in main-header

### ISSUE THREAD

**Issue by siljanoskam** [jeroennoten/Laravel-AdminLTE#387]
Hi, I need to add additional navbar component (for example the user dropdown section) in the header next to the `Logout`. Is there a way to do this through the adminlte.php config file or any other way except the manual modification of the vendor files?

**Comment by gbarcella** [comment]
I need to know it too.

**Comment by REJack** [comment]
If you use v1 or v2 you need to modify the master blade, in v3 comes a extra section for both sides.

**Comment by siljanoskam** [comment]
You mean the master blade that comes with the package? That means that I have to touch the vendor files. Correct me if I'm wrong.

**Comment by REJack** [comment]
Correct you need to run `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=views` to publish the package master blade into your project views folder.
