### ISSUE TITLE
Problem to Install Laravel-AdminLTE in Laravel 6.1.0

### ISSUE THREAD

**Issue by vissini** [jeroennoten/Laravel-AdminLTE#389]
I tried to install the Laravel-AdminLTE on my project, but return the errors below:

 Problem 1
    - Conclusion: don't install jeroennoten/laravel-adminlte v2.0.0
    - Conclusion: remove laravel/framework v6.1.0
    - Installation request for jeroennoten/laravel-adminlte ^2 -> satisfiable by jeroennoten/laravel-adminlte[v2.0.0, v2.0.0-rc.1].
    - Conclusion: don't install laravel/framework v6.1.0
    - jeroennoten/laravel-adminlte v2.0.0-rc.1 requires laravel/framework ~6.0.0 -> satisfiable by laravel/framework[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - Can only install one of: laravel/framework[v6.0.0, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.1, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.2, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.3, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.4, v6.1.0].
    - Installation request for laravel/framework (locked at v6.1.0, required as ^6.0) -> satisfiable by laravel/framework[v6.1.0].

**Comment by vladimir-pejic** [comment]
Same here..

**Comment by andcarpi** [comment]
Need to fix composer laravel require... gonna open a pull request

**Comment by lacodimizer** [comment]
Release comes tomorrow. Thanks @andcarpi

**Comment by lacodimizer** [comment]
The new release v2.0.1 is out now.

**Comment by janicesn0w** [comment]
@lacodimizer  still having same issue when i run 'composer require jeroennoten/laravel-adminlte'

**Comment by lacodimizer** [comment]
Please try it again.

**Comment by vissini** [comment]
Works now...many thanks
