### ISSUE TITLE
ISSUE:MENU ITEM IS NOT ACTIVE

### ISSUE THREAD

**Issue by thegreyhatt** [jeroennoten/Laravel-AdminLTE#396]
Menu item is not active even it is a sub-path of the menu url.

**Comment by lacodimizer** [comment]
Can you please give us more details, like the menu config?

**Comment by thegreyhatt** [comment]
> Can you please give us more details, like the menu config?

yes at the menu array at the adminlte config file.

**Comment by lacodimizer** [comment]
I mean a concrete example, how your menu is created.

**Comment by thegreyhatt** [comment]
Here is my sample code:
```
      ['header' => 'main_navigation'],
        [
            'text'        => 'pages',
            'url'         => '#',
            'icon'        => 'fa fa-file',
        ],
        ['header' => 'Records'],
        [
            'text' => 'Department',
            'route'  => 'department.index',
            'icon' => 'fas fa-fw fa-file',
        ],
```

for example at the Department, the url looks like this
`localhost/department`, but when I go to` localhost/department/create`, the Department sidebar menu is not highlighted even its a subpath of `localhost/department`.

**Comment by lacodimizer** [comment]
You have to add the active key, for example:
`
        [
            'text' => 'Department',
            'route'  => 'department.index',
            'icon' => 'fas fa-fw fa-file',
            'active' => ['department/*'],
        ],
`
The highlighting in the sidebar works don't works for subpaths.

**Comment by thegreyhatt** [comment]
> You have to add the active key, for example:
> `[ 'text' => 'Department', 'route' => 'department.index', 'icon' => 'fas fa-fw fa-file', 'active' => ['department/*'], ],`
> The highlighting in the sidebar works don't works for subpaths.

the problem when I add `'active' => 'department/*'` is, the `Department` sidebar menu is always highlighted even if I go/click to other paths like `localhost/other-URL` the `Department` would still be highlighted.

I used this package before and it works well on subpaths without adding the `active` option.

**Comment by rajaduraioec** [comment]
@thegreyhatt Please use * in the url 

[
            'text'        => 'pages*',
            'url'         => '#',
            'icon'        => 'fa fa-file',
        ],

Then it considers whatever comes after pages as part of it and highlights the menu.
