### ISSUE TITLE
QUESTION: How to get adjacent version LESS files?

### ISSUE THREAD

**Issue by Pilskalns** [jeroennoten/Laravel-AdminLTE#398]
I would like compile my own skin based on existing files. To create them in first place, ColorlibHQ/AdminLTE uses a bunch of .less files.

As this project version releases does not match all versions of "parent" project, I am not sure which version should I salvage to get matching .less files? Looking at (not pre) release dates, just latest available?

I can see reasons why versions don't match 1:1, so wouldn't it make sense if .less files were included in with this project? Not forced to use them, maybe with `artisan vendor:publish` or somewhat similarly accessible to expose for user, if one needs to.

P.S. if there is obvious, nice and preffered _Laravel way_ to get those .less files other than downloading ZIP from [/ColorlibHQ/AdminLTE/releases](https://github.com/ColorlibHQ/AdminLTE/releases) and do extortion, you can point direction for me - I am extremely new to learning Laravel 👀.

**Comment by TD-RA** [comment]
I am also having this same issue, I would like to apply a main color do the success class changing it to the color of my company. Thank you for your time!

**Comment by andcarpi** [comment]
The package version 2.x, uses only the adminlte 2.4.18 dist files.
v3 RC is still in development, but i think it installs all the adminlte files in the vendor folder.

**Comment by REJack** [comment]
That‘s correct in the new version it will possible, but it will still only copy the compiled css/js files and no scss files but for this is the Laravel mix option perfect :)

**Comment by Pilskalns** [comment]
@REJack that sounds close. But would the SCSS source files be included under _vendor_?

**Comment by REJack** [comment]
@Pilskalns What excatly you mean?
