### ISSUE TITLE
Cannot make menu dispatcher work

### ISSUE THREAD

**Issue by 11digitlabs** [JeroenNoten/Laravel-AdminLTE#4]
Hey once again :)

I've modified the default EventServiceProvider and added the proposed code into the boot method

```php
    public function boot(DispatcherContract $events)
    {
        parent::boot($events);

        //
	    $events->listen(\JeroenNoten\LaravelAdminLte\Events\BuildingMenu::class, function (BuildingMenu $event) {
		    $event->menu->add('MAIN NAVIGATION');
		    $event->menu->add([
			    'text' => 'Blog',
			    'url'  => 'admin/blog',
		    ]);
	    });
    }
```

But, when I visit the page, I get the following error

```
ErrorException in EventServiceProvider.php line 32:
Type error: Argument 1 passed to 
App\Providers\EventServiceProvider::App\Providers\{closure}() must be an instance of 
App\Providers\BuildingMenu,
 instance of JeroenNoten\LaravelAdminLte\Events\BuildingMenu given
```

Any ideas are appreciated
Thanks!

**Comment by JeroenNoten** [comment]
Hey,

At the top of the file add `use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;`

I will add this to the README soon.

**Comment by 11digitlabs** [comment]
Damn! I thought that by giving the full path in the events->listen I didn't need to do the use on top.

Thanks!

**Comment by JeroenNoten** [comment]
The error came from the typehint in the closure: `function (BuildingMenu $event)`.
