### ISSUE TITLE
Customzie VIEWS - laravel 6

### ISSUE THREAD

**Issue by eblucas** [jeroennoten/Laravel-AdminLTE#401]
Hello,

I ran php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views

to be able to customize the view but I dont get the resources/views/vendor/adminlte. folder.

Nothing changes, how can I customize the login and email sent?

Thanks

**Comment by mikel00per** [comment]
I've got the same problem
