### ISSUE TITLE
Display user profile

### ISSUE THREAD

**Issue by Majidkadi** [jeroennoten/Laravel-AdminLTE#402]
Hello every one,

I'm trying to display the user profile but I get 404 page.
I do not know how to pass the id of the authenticated user.
In config/adminlte.php I have :  
        [
            'url'  => 'admin/settings',
        ]
in the route : 
       Route::get('/users/edit/{userId}', 'UserController@edit')->name('admin.users.edit');

Thanks

**Comment by Majidkadi** [comment]
Hi again,

I finally found the solution.
I added profile function in controller without user id which returns the current logged user, and in the view I've had to display current user info.

controller :  
     public function profile()
     {
          return auth('api')->user();
     }
route: 
Route::get('/profile', 'UserController@profile')->name('admin.users.profile');

**Comment by aledc7** [comment]
Thank you @Majidkadi   !! it worked very well

**Comment by marianozzz** [comment]
You can use Auth::user()->name for example in the view template
