### ISSUE TITLE
ISSUE: publishing views does not create view files (Laraval 6)

### ISSUE THREAD

**Issue by alex-french** [jeroennoten/Laravel-AdminLTE#403]
Running

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views

does not create anything in resource/views/vendor as per docs.

Laravel Framework 6.4.0

 "name": "jeroennoten/laravel-adminlte",
            "version": "v2.0.2",

**Comment by JustinRijsdijk** [comment]
for me this returns the following in red: Unable to locate publishable resources

**Comment by REJack** [comment]
It should be `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=views`

**Comment by alex-french** [comment]
Looks like this was affected by this recent commit:
https://github.com/jeroennoten/Laravel-AdminLTE/pull/400

**Comment by gimtonic** [comment]
Please change readme.MD Now here `php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets --force`

**Comment by REJack** [comment]
The readme.md is correct, look at [here (master)](https://github.com/jeroennoten/Laravel-AdminLTE#22---laravel-6x-package-version-2x) or [here (laravel6-adminlte2)](https://github.com/jeroennoten/Laravel-AdminLTE/tree/laravel6-adminlte2#2-installation) with the new adminlte:install command.

**Comment by gimtonic** [comment]
Why use publish assets in installation for v5 and dont for v6))  
Need add publish assets for v6 in installation  or delete for v5?!
 ```
2. Installation
2.1 - Laravel 5 (Package version 1.x)
Require the package using composer:

composer require jeroennoten/laravel-adminlte "^1"
Publish the public assets:

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets
The make:adminlte artisan command

This package ships with a make:adminlte command that behaves exactly like make:auth (introduced in Laravel 5.2) but replaces the authentication views with AdminLTE style views.

php artisan make:adminlte
This command should be used on fresh applications, just like the make:auth command

2.2 - Laravel 6.x (Package version 2.x)
Require the package using composer:

composer require jeroennoten/laravel-adminlte
Install the package using the command (For fresh laravel installations):

php artisan adminlte:install
You can use --basic to avoid authentication scaffolding installation

You can use --force to overwrite any file

You can also use --interactive to be guided through the process and choose what you want to install 
```

**Comment by gimtonic** [comment]
I need use php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=assets --for for publish assets for v6 when installations

**Comment by lacodimizer** [comment]
In which case do you want publishing the assets?

**Comment by dakshbhatt21** [comment]
> for me this returns the following in red: Unable to locate publishable resources.
> 
> The translations do publish though, so it is not an overall publishing problem.

I am also facing the same issue, did you find the solution?

**Comment by ridwantanjung** [comment]
Same here, I use Laravel 6.4.1,
when I execute the command it returns 
``Unable to locate publishable resources.`` then on the next line ``Publishing complete.``, 
that's weird, I need to change some of them

**Comment by cdr0y** [comment]
If you're using AdminLTE 3 with Laravel 6 you can use:

`php artisan adminlte:install --only=main_views`

**Comment by wpetian** [comment]
> In which case do you want publishing the assets?

Estou com o mesmo problema, não esta publicando nada.
A versão anterior está funcionado corretamente.

**Comment by kiranajudiya** [comment]
is working fine on Laravel 6.4.
create an extended view file in 
`resource\view`
and master file create in 
`vendor\jeroennoten\laravel-adminlte\resources\views`
plz, check that path.
