### ISSUE TITLE
How to Use Top Navigation?

### ISSUE THREAD

**Issue by takielias** [jeroennoten/Laravel-AdminLTE#404]
How to Use Top Navigation?

**Comment by REJack** [comment]
Do you mean with layout topnav only or in combination with the sidebar?
Which Laravel-AdminLTE Version you use? 1.x, 2.x or 3.x?

**Comment by takielias** [comment]
I meant only topnav in v 2/3.

**Comment by REJack** [comment]
For v3.x you only need to change `layout_topnav` to `true` in your config/adminlte.php, in v2.x change `layout` to `top-nav`. After changing the config you should get a complete filled topnav.

**Comment by REJack** [comment]
For questions like this you can look into the readme of your desired version. Also the config file itself gives you infos about the config entries, in v3.x's config you find links to the readme parts with further informations.

**Comment by takielias** [comment]
Thanks a lot.
