### ISSUE TITLE
Installing of admin lte in multi level users

### ISSUE THREAD

**Issue by sarzali07** [jeroennoten/Laravel-AdminLTE#405]
Hi

I have users, managers and admins in laravel application. I want to install admin lte it work fine on users level only. when I add admin lte to managers and admin it give errors and some time just white page.
my view direcotry
![image](https://user-images.githubusercontent.com/10739321/67840802-7efff000-fb18-11e9-8c59-289f6d6d319b.png)

**Comment by REJack** [comment]
What kind of error you recieve?

**Comment by sarzali07** [comment]
> What kind of error you recieve?

I manage to load view in login as adding @extends('adminlte::login') but {{ url('/manager/login') }} not working. as admin lte has one user url to login but not on manager login. how to change login url as per user level like admin manager and user.

login route
for admin {{ url('/admin/login') }} 
for manager {{ url('/manager/login') }} 
for user {{ url('/user/login') }} 

Regards

**Comment by REJack** [comment]
Which version of Laravel-AdminLTE you use?

I understand what you want, actually you would need to modify/duplicate the login.blade.php for this. 
I'll look into the auth views and add a abilty to override the config from blade files like the sidebar_collapse allows already.
