### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by fendipratama** [jeroennoten/Laravel-AdminLTE#409]
when i ran, 
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=config

there is error message like this :
"Unable to locate publishable resources.
Publishing complete."

**Comment by HumbertoSilveira** [comment]
Está usando a [branch da versão 3](https://github.com/jeroennoten/Laravel-AdminLTE/blob/laravel6-adminlte3/README.md)? Esses comandos passaram para o adminlte:install. Da uma olhada no readme da branch que está mais detalhado lá 😉

**Comment by fendipratama** [comment]
obrigada

**Comment by yasir91** [comment]
Any solutions to this?

**Comment by lacodimizer** [comment]
Which package version do you use? If you use v3.x, please use the adminlte:install command for publishing sources.

**Comment by yasir91** [comment]
I used 
php artisan adminlte:install

but when i run

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=translations

i get
Unable to locate publishable resources.
Publishing complete.


why this is important because i need to move translations into laravel resource directory rather than vendor directory.

**Comment by REJack** [comment]
With `php artisan adminlte:install` you should already copied the translations, all the old vendor:publish tags are removed since v3 and not necessary.

**Comment by yasir91** [comment]
yes I have the translations in resources but i need make changes in those translations but it is not reflecting. but if i change in vendor directory it shows the changes.

**Comment by yasir91** [comment]
I think docs are not updated as you said in v3 tags are removed.

**Comment by REJack** [comment]
Sounds like the LangFilter is not updated or replaced, or your lang keys in resources/lang/*/menu.php are not correct.
The LangFilter has a fallback that first load  lang string from the app resources then from the package resources.

**Comment by REJack** [comment]
> I think docs are not updated as you said in v3 tags are removed.

The v3 readme is already updated with the adminlte:install comand instead of vendor:publish.

**Comment by yasir91** [comment]
V3 has this command already

php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=views

That is not the main issue though but thank you for your quick response.

Mainly I am unable to use the lang files in resources. 

Could you kindly shed more light on langFilter thing.

**Comment by yasir91** [comment]
ok turns out
php artisan adminlte:install --only=translations

copy the translations to the resources/lang/ directory while it needs to copy the translations into "resources/lang/vendor/adminlte/"

So now its working for me :) thank you so much guys for your swift replies.

**Comment by yasir91** [comment]
need to change this file:
`vendor/jeroennoten/laravel-adminlte/src/Console/AdminLteInstallCommand.php`

from:
CommandHelper::directoryCopy($this->packagePath('resources/lang'), base_path('**resources/lang**'), $this->option('force'), true);

to: 
CommandHelper::directoryCopy($this->packagePath('resources/lang'), base_path('**resources/lang/vendor/adminlte**'), $this->option('force'), true);

**Comment by fendipratama** [comment]
thanks a lot yasir

**Comment by Dilaksanraj** [comment]
when I run  php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views
it will say Unable to locate publishable resources.
Publishing complete.
what is the problem? How can I solve this?

**Comment by lacodimizer** [comment]
@Dilaksanraj Which package version do you use? In version 3.x, we removed all the --tag commands and replaced it with the adminlte:install command.

**Comment by arthurcvm** [comment]
Please use the command to install all assets and translate files:
`php artisan adminlte:install --type=full`

to verify the status installation, use the command:
`php artisan adminlte:status`

**Comment by SimuliChina** [comment]
@arthurcvm it is still not published. Any ideas on what else I can do...I followed the installation instructions keenly.
![image](https://user-images.githubusercontent.com/25318858/69495661-16ffb800-0ed2-11ea-90d9-5d4048a02896.png)

**Comment by REJack** [comment]
@SimuliChina What exactly is not published? And which version of laravel-adminlte you use?

The AdminLTE v3 Assets status works not correctly, I'll push a fix for this soon.

@arthurcvm `--type=full` option installs also Auth & Main Views. It's not required 😄

**Comment by arthurcvm** [comment]
@REJack to assets for me it's ok, the translations change the --type parameter.

**Comment by REJack** [comment]
> the translations change the --type parameter

@arthurcvm What you mean with this? The translations will published every time with adminlte:install (e.g. without any options, with --type=enhanced (install auth views), --type=full (install auth & basic views) or --only=translations), execpt any othter --only option (like the option say it only install the specific part).

**Comment by nguyentranchung** [comment]
```
Usage:
  adminlte:install [options]

Options:
      --force           Overwrite existing views by default
      --type[=TYPE]     Installation type, Available type: none, enhanced & full.
      --only[=ONLY]     Install only specific part, Available parts: assets, config, translations, auth_views, basic_views, basic_routes & main_views. This option can not used with the with option.
      --with[=WITH]     Install basic assets with specific parts, Available parts: auth_views, basic_views, basic_routes & main_views (multiple values allowed)
```
```
php artisan adminlte:install --only=config --force
```

**Comment by psoliev** [comment]
Please help me with this error: 
**Facade\Ignition\Exceptions\ViewException
Argument 1 passed to JeroenNoten\LaravelAdminLte\AdminLte::__construct() must be of the type array, null given, called in path\vendor\jeroennoten\laravel-adminlte\src\AdminLteServiceProvider.php on line 25 (View: path\resources\views\welcome.blade.php)**

when I run **php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views**
I get this message: 
**Unable to locate publishable resources.
Publishing complete.**
what is the problem?

**Comment by REJack** [comment]
@psoliev Which version of Laravel & Laravel-AdminLTE you use?

**Comment by psoliev** [comment]
> @psoliev Which version of Laravel & Laravel-AdminLTE you use?

Laravel 6.0 and AdminLte 3.0

**Comment by arthurcvm** [comment]
> > the translations change the --type parameter
> 
> @arthurcvm What you mean with this? The translations will published every time with adminlte:install (e.g. without any options, with --type=enhanced (install auth views), --type=full (install auth & basic views) or --only=translations), execpt any othter --only option (like the option say it only install the specific part).

But in Laravel 6+ your tip and the documentation not work, for me it worked as I explained. See below:

> Please use the command to install all assets and translate files:
> `php artisan adminlte:install --type=full`
> 
> to verify the status installation, use the command:
> `php artisan adminlte:status`

after this install missing parts, as the template default and the translations. 
https://github.com/jeroennoten/Laravel-AdminLTE#51-the-adminlteinstall-command

**Comment by naneri** [comment]
How do I change sidebar to sticky sidebar?

**Comment by frankhubrepo** [comment]
I am having the same issue. I followed the installation process as it shows in github. Now, I just created a simple admin_template.blade.php file, and I only put @extends('adminlte::page') in there, and i get this:

Argument 1 passed to JeroenNoten\LaravelAdminLte\AdminLte::__construct() must be of the type array, null given, called in C:\xampp\htdocs\dw_report\vendor\jeroennoten\laravel-adminlte\src\AdminLteServiceProvider.php on line 25 (View: C:\xampp\htdocs\dw_report\resources\views\admin_template.blade.php)

The register function in said file looks like this:
```
public function register()
    {
        $this->app->singleton(AdminLte::class, function (Container $app) {
            return new AdminLte(
                $app['config']['adminlte.filters'],
                $app['events'],
                $app
            );
        });
    }
```

**Comment by frankhubrepo** [comment]
Also, I have tried installing the translations several times now, and it says "translations file installed successfully" everytime, but then when i check status it says it isn't installed

**Comment by web-rider** [comment]
Hi. Try
`php artisan config:clear`
It helps me

**Comment by paajake** [comment]
@frankhubrepo  try publishing the Main Views with this command :
`php artisan adminlte:install --only=main_views`

and for the translations checkout @yasir91  tip 

> need to change this file:
> `vendor/jeroennoten/laravel-adminlte/src/Console/AdminLteInstallCommand.php`
> 
> from:
> CommandHelper::directoryCopy($this->packagePath('resources/lang'), base_path('**resources/lang**'), $this->option('force'), true);
> 
> to:
> CommandHelper::directoryCopy($this->packagePath('resources/lang'), base_path('**resources/lang/vendor/adminlte**'), $this->option('force'), true);

**Comment by Zgarc** [comment]
With newer versions of Laravel, this should already be published to your vendor folder. You need to run "php artisan cache clear && php artisan config:cache" for it to work.

**Comment by KNobHack** [comment]
@web-rider 

Thanks a lot. That help me

**Comment by Naveenp99** [comment]
> Any solutions to this?
did you solved this

**Comment by hernandoglobal** [comment]
I need to edit the main layout of adminlte, because I need a script method to run in all views.
but I can't find the main layout to add my script methods. 
"@extends ('adminlte :: page')"

when i run the command
"php artisan vendor: publish --provider =" JeroenNoten\LaravelAdminLte\ServiceProvider " 
![Captura](https://user-images.githubusercontent.com/79588523/109398287-f959a380-7909-11eb-9ac8-343f562002f6.PNG)
--tag = views"

this shows me:
"Unable to locate publishable resources."

I tried running the command:
php artisan adminlte: install --type = full

and I select all the options to overwrite all "yes", "yes", "yes" ...
but when I run the command:
php artisan adminlte: status

everything installed, except what I think I need:
![Captura](https://user-images.githubusercontent.com/79588523/109398294-037ba200-790a-11eb-8761-97eb225194fd.PNG)


main_views | The default package main views | Not Installed | false |

I need to add 3 js methods in all the views, and I don't want to repeat them for each view, this is how I would like to add it in the main layout "@extends ('adminlte :: page')" This means  in the "page", so that these methods work in all views.

example of my methods:

```
<script>
    @if (session('update'))
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'updade ok xxxxx',
            showConfirmButton: false,
            timer: 1500
        })
@endif
</script>

<script>
    @if (session('delete'))
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'Delete ok  xxxx',
            showConfirmButton: false,
            timer: 1500
        })
        @endif
</script>
```

What could I do? Thank you very much to anyone who can help me.

**Comment by Shidersz** [comment]
@hernandoglobal To install **main_views** you need to use `php artisan adminlte:install --only=main_views`, read the [Artisan Commands Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Artisan-Console-Commands) to check how use the commands.

However it will be better if you include your custom `js` file as a plugin, see the [Plugins Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration#plugins) for that...

```php
'plugins' => [
    /* Other plugins definition... */
    ...
    'MyCustomFiles' => [
        'active' => true,
        'files' => [
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/custom-files/my-script-1.js',
            ],
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/custom-files/my-script-2.js',
            ],
        ],
    ],
]
```

Then you can place your custom script file into `public/vendor/custom-files/` folder...
