### ISSUE TITLE
how can i add if statement in the navigation menu? 

### ISSUE THREAD

**Issue by joannesnoel** [jeroennoten/Laravel-AdminLTE#41]
how can i add if statement in the navigation menu? like admin can see that particular menu.

**Comment by loekiedepo** [comment]
Take a look at the "menu filters" in the readme. Define a gate and use that gate in the menu config.

**Comment by joannesnoel** [comment]
Thanks @loekiedepo  i will take a look.

**Comment by joannesnoel** [comment]
Hello @loekiedepo where can i add this 
namespace MyApp;

use JeroenNoten\LaravelAdminLte\Menu\Builder;
use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
use Laratrust;

class MyMenuFilter implements FilterInterface
{
    public function transform($item, Builder $builder)
    {
        if (isset($item['permission'] && Laratrust::can($item['permission'])) {
            return false;
        }

        if (isset($item['header'])) {
            $item = $item['header'];
        }

        return $item;
    }
}

**Comment by joannesnoel** [comment]
Hello @loekiedepo i am confused with the docs. can u help me? in my case i have a users table is_admin field i want to display particular menu for the admin if is_admin = 1.

**Comment by loekiedepo** [comment]
Define a function in your user model

```php
public function isAdmin()
{
    return $this->is_admin;
}
```

And create a Gate (look at the laravel docs, they are really clear) that implements the isAdmin(). Then you can use the name of that Gate in your menu config in `adminlte.php`

**Comment by jeroennoten** [comment]
In your `AuthServiceProvider` (see `app/providers/AuthServiceProvider.php`), add this to the `boot()` method:

```php
    Gate::define('admin', function ($user) {
        return $user['is_admin'] == 1;
    });
```

Then, in any menu item, you can use the `'can'` attribute with `'admin'` to show it only for admins:

```php
[
    'text' => 'Admin Menu Item'
    'url' => 'admin/only-for-admins'
    'can' => 'admin'
]
```

**Comment by kardusimajinasi** [comment]
how to implement custom menu for user with level =1 can access all menu but user with level =2 only access particular menu
