### ISSUE TITLE
QUESTION: UPDATING existing menu item realtime via ajax

### ISSUE THREAD

**Issue by JustinRijsdijk** [jeroennoten/Laravel-AdminLTE#411]
Hello, In my menu I have some labeld. I want to change the colors and value's of the labels in realtime trough ajax, but I don't know how. I kinda understand how you build the menu, but rebuilding the whole menu is not what I want to do. 

Can I just assign an ['id' => 'server_status'] to my menu item, and add that into the menu builder so that it puts the id in just like the label color class?

**Comment by REJack** [comment]
For adding the 'id'-attribute on menu item's you would need to modify the menu-item.blade.php and add `@if (isset($item['id'])) id="{{ $item['id'] }}" @endif` to the `<li>`s.

**Comment by JustinRijsdijk** [comment]
I thought something like that would be the solution. Thanks for the quick response!

**Comment by REJack** [comment]
No problem 😄 I've added this ability also to my PR for v3.x.

**Comment by JustinRijsdijk** [comment]
ah, that is nice to hear. But, v3 is going to be Laravel 6 only right?

**Comment by REJack** [comment]
Correct v3 is Laravel 6 only
