### ISSUE TITLE
Issue with 'php artisan adminlte:install'

### ISSUE THREAD

**Issue by adriancampanaro** [jeroennoten/Laravel-AdminLTE#413]
I ran the following command 

php artisan adminlte:install
and got error 
"There are no commands defined in the "adminlte" namespace."

**Comment by NicolasDepoilly** [comment]
I ve got same issue on laravel 6.2, I might need help here too!

**Comment by lacodimizer** [comment]
Which project version is used?

**Comment by adriancampanaro** [comment]
first I created new project..
Installing laravel/laravel (v6.4.0)

- Ran
composer require jeroennoten/laravel-adminlte
- Then
php artisan adminlte:install

What I did to get it working is change Laravel version
composer create-project laravel/laravel adminLte60 6.0.*

**Comment by REJack** [comment]
Please post your composer.json content, this can give us more informations 😄

**Comment by brunnoandrade** [comment]
I have the same problem. =(

**Comment by parbhez** [comment]
I got the same problem when i am using laravel version 6.2.
"There are no commands defined in the "adminlte" namespace."

**Comment by superelite123** [comment]
I got same problem in laravel 5.8

**Comment by REJack** [comment]
@brunnoandrade @parbhez Please post your composer.json content

@superelite123 Laravel-AdminLTE v3 (`adminlte:install`) will work only with Laravel 6.x+.

**Comment by MascHman** [comment]
HI @REJack 
I've got the same Problem. Can you give me any suggestion what to do ?

This is the contents of my composer.json file:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.0",
        "jeroennoten/laravel-adminlte": "^1.25",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^5.8",
        "yajra/laravel-datatables-oracle": "~9.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laravel/telescope": "^2.0",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5",
        "xethron/migrations-generator": "^2.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by REJack** [comment]
@MascHman The `adminlte:install` command is only available in v2 & v3 not in v1.

**Comment by MiguelRosaPT** [comment]
First run "composer require..." insido of your laravel project. After run "php artisan adminlte:install"

**Comment by Apfelwurm** [comment]
for all that experiencing that issue, you might want to clear your bootstrap/cache folder :)
