### ISSUE TITLE
Issue with installing using laravel/framework v6.5.0

### ISSUE THREAD

**Issue by adriancampanaro** [jeroennoten/Laravel-AdminLTE#414]
In composer.json I added

"jeroennoten/laravel-adminlte": "^1.22"

And when I ran the update I get

D:\xampp\htdocs\adminLte>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.4.1
    - Conclusion: don't install laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.3.0
    - Conclusion: don't install laravel/framework v6.2.0
    - jeroennoten/laravel-adminlte v1.27.0 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~5.8.0|~6.0.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.27.1 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~

**Comment by andcarpi** [comment]
Change
"jeroennoten/laravel-adminlte": "^1.22"
To
"jeroennoten/laravel-adminlte": "^3.0"

**Comment by adriancampanaro** [comment]
I still get the same error:

D:\xampp\htdocs\adminLte>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.4.1
    - Conclusion: don't install laravel/framework v6.4.0
    - Conclusion: don't install laravel/framework v6.3.0
    - Conclusion: don't install laravel/framework v6.2.0
    - jeroennoten/laravel-adminlte v1.27.0 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~5.8.0|~6.0.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.27.1 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~5.8.0|~6.0.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.27.2 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.22.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev].
    - jeroennoten/laravel-adminlte v1.22.1 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev].
    - jeroennoten/laravel-adminlte v1.23.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev].
    - jeroennoten/laravel-adminlte v1.23.1 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev].
    - jeroennoten/laravel-adminlte v1.23.2 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev].
    - jeroennoten/laravel-adminlte v1.24.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - jeroennoten/laravel-adminlte v1.24.1 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - jeroennoten/laravel-adminlte v1.24.2 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - jeroennoten/laravel-adminlte v1.25.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.25.1 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.26.0 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - jeroennoten/laravel-adminlte v1.26.0-beta1 requires laravel/framework ~5.1.12|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.6.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.1.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.2.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.3.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, 5.4.x-dev].
    - Installation request for laravel/framework ^6.2 -> satisfiable by laravel/framework[6.x-dev, v6.2.0, v6.3.0, v6.4.0, v6.4.1, v6.5.0].
    - Installation request for jeroennoten/laravel-adminlte ^1.22 -> satisfiable by jeroennoten/laravel-adminlte[v1.22.0, v1.22.1, v1.23.0, v1.23.1, v1.23.2, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.25.1, v1.26.0, v1.26.0-beta1, v1.27.0, v1.27.1, v1.27.2].

**Comment by lacodimizer** [comment]
What is your composer config?

**Comment by adriancampanaro** [comment]
Sorry, what do you mean by "composer config"

**Comment by lacodimizer** [comment]
how looks your composer.json file?

**Comment by adriancampanaro** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "almasaeed2010/adminlte": "~3.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^1.0",         
         "jeroennoten/laravel-adminlte": "^3.0"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by lacodimizer** [comment]
Ok, thats sounds good. But you can remove "almasaeed2010/adminlte": "~3.0", it will be included with this package.

**Comment by REJack** [comment]
@adriancampanaro If this still appears, the error looks like a composer cache bug try to flush the composer cache with `composer clearcache`.

**Comment by adriancampanaro** [comment]
Not sure why this is closed.

I still get error after clearing cache.

D:\xampp\htdocs\Laravel-AdminLTE>composer update jeroennoten/laravel-adminlte
Package "jeroennoten/laravel-adminlte" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Comment by REJack** [comment]
@adriancampanaro Did you tried it again in last days? It should update to v3.0.7. Also could you post me result of`composer show -i`.

**Comment by bigzooooz** [comment]
I have the same issue but with laravel 6.9

any solution to this? cuz it's preventing me from installing other packages :/

**Comment by REJack** [comment]
This issue seems to be related with your local cache from composer, take a look at this [old issue](https://github.com/composer/composer/issues/6720) from composer github repo.

**Comment by bigzooooz** [comment]
@REJack I have looked into the link you posted and tried doing composer clear-cache and got me no where.

keep in mind that i was able to install the package like 4 days ago but today when i try to install new packages adminlte throws the error.
i tried removing it and that did fix installing new packages but now i'm not able to reinstall laravel-adminlte package lol

here's the error when i try `composer require jeroennoten/laravel-adminlte` or `composer require jeroennoten/laravel-adminlte="^3.0`:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework == 5.8.36.0 -> satisfiable by laravel/framework[v5.8.36].
    - jeroennoten/laravel-adminlte v3.0.0 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.3 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.4 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.5 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.6 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.7 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.8 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - Conclusion: don't install laravel/framework 6.x-dev
    - Installation request for jeroennoten/laravel-adminlte ^3.0 -> satisfiable by jeroennoten/laravel-adminlte[v3.0.0, v3.0.0-rc.1, v3.0.0-rc.2, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8].`

**Comment by schonhose** [comment]
Have you tried it with the development version ("dev-master")?

**Comment by bigzooooz** [comment]
i tried it just now and this is the output.
it's not really different from the previous ones
```
Problem 1
    - Can only install one of: laravel/framework[v5.8.36, 6.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.36].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.36].
    - jeroennoten/laravel-adminlte dev-master requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - Installation request for jeroennoten/laravel-adminlte dev-master -> satisfiable by jeroennoten/laravel-adminlte[dev-master].
    - Installation request for laravel/framework == 5.8.36.0 -> satisfiable by laravel/framework[v5.8.36].
```

**Comment by bigzooooz** [comment]
now it's been a week and i still get the same error.
i kept trying thinking that this might be one of those things that would fix itself but i had no success.

it keeps telling me this...

```
 Problem 1
    - The requested package laravel/framework == 6.9.0.0 could not be found.
  Problem 2
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev, v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.15, v5.8.16, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.21, v5.8.22, v5.8.23, v5.8.24, v5.8.25, v5.8.26, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9].
    - jeroennoten/laravel-adminlte v3.0.0 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.3 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.4 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.5 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.6 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.7 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.8 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.8 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - Conclusion: don't install laravel/framework 6.x-dev
    - Installation request for jeroennoten/laravel-adminlte ^3.0 -> satisfiable by jeroennoten/laravel-adminlte[v3.0.0, v3.0.0-rc.1, v3.0.0-rc.2, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

any ideas?

**Comment by melangi** [comment]
1st make sure that you are on the right directory (eg C:xammp/htdocs/name of your project here )
2nd write the command without the version number (composer require jeroennoten/laravel-adminlte)

**Comment by bigzooooz** [comment]
@melangi done and done. same results.
this issue is really bugging me. i really do like using this package it make life alot easier and i really don't want to redo the whole frontend part again but i keep hitting this wall with no clear clue on how to get this fixed.

**Comment by andcarpi** [comment]
you probably have wrong laravel/adminlte versions...
Laravel 5.8- and adminlte v2 - Use package version 1
Laravel 5.8- and adminlte v3 - No package version available
Laravel 6+ and adminlte v2 - Use package version 2
Laravel 6+ and adminlte v3 - Use package version 3

**Comment by bigzooooz** [comment]
@andcarpi oh man this feels so stupid!
i don't know what caused this but your reply regarding laravel version made me see what was wrong exactly.
as i said earlier, my laravel version is `6.9` (`6.11` now that i fixed this issue) but the problem was that the `required` laravel version in composer.json somehow got changed from `6.*` to `5.8.*` !!!
i feel so stupid i spent so much time trying to tweak the file to find a solution i NEVER saw this! :)

once i replaced `5.8.*` with `6.*` everything worked like a charm :)

any idea what could've caused this? i'm fairly new to composer but my guess is some package somehow changed the `required` version of laravel and threw me in a loop.

thanks to all of you for trying to help.
and i'm sorry if gave you guys a hard time
