### ISSUE TITLE
Updating Adminlte 1 to 3

### ISSUE THREAD

**Issue by TD-RA** [jeroennoten/Laravel-AdminLTE#416]
I am having trouble updating my Adminlte version 1 to 3, the only way I could do it is creating a new project with adminlte 3 and migrating the files one by one. even though everything seems kinda out of place in the new version. Is there an easy way I can do this?

**Comment by REJack** [comment]
Overall you not need to create a new project for this, but you need to update laravel, laravel-adminlte, adminlte and update also all existing views to adminlte 3/bootstrap 4 standard. There is no easy way for this.
