### ISSUE TITLE
QUESTION: development

### ISSUE THREAD

**Issue by JustinRijsdijk** [jeroennoten/Laravel-AdminLTE#418]
Hello, I was wondering if there are any features that you would want to see in this package, but don't have the time for to work on. Because I find this package really useful, and would love to contribute.

**Comment by lacodimizer** [comment]
Feel free for contribution :)

**Comment by JustinRijsdijk** [comment]
What would be a useful addon for this package? a form helper or something?

**Comment by JustinRijsdijk** [comment]
usage:
{{form()}}
@csrf
$this->adminlte->input($name&id, $options(array());

Then we could easily render form elements for adminlte. Options could be; 
- type (default=text)
- class (custom classes, default class form-control),
- inputaddon (default false, options: append, prepend)
etc. I will make a full list of options I think could be useful when i'm home. So you can give a opinion.
