### ISSUE TITLE
How to add a Dashboard home link without making it active globally?

### ISSUE THREAD

**Issue by dragonfire1119** [jeroennoten/Laravel-AdminLTE#42]
When I add a Dashboard home link it works perfect with the active class but I went to ``admin/users`` & both the ``Dashboard`` link & the ``/admin/users`` link is active.

How would I go about not making the Dashboard active when the user is not on the dashboard.

**Comment by jeroennoten** [comment]
You have two possibilities to solve this:

- Change the dashboard URL to something like `admin/dashboard` (with an additional redirect from `admin` to `admin/dashboard` if you want).
- Or explicitly indicate the active URL for the dashboard:
```
[
    'text' => 'Dashboard'
    'url' => 'admin',
    'active' => ['admin']
]
```

Refer to the section **Active menu items** in the readme: https://github.com/jeroennoten/Laravel-AdminLTE#active-menu-items

**Comment by jeroennoten** [comment]
There was indeed a bug related to overriding the active menu items. It is fixed now. Running `composer update jeroennoten/laravel-adminlte` will fix it for you.

Thanks for the bug report!
