### ISSUE TITLE
AdminLTE 2 - 11 Error 200's /vendor/.......

### ISSUE THREAD

**Issue by digitalight** [jeroennoten/Laravel-AdminLTE#422]
Running latest version of Laravel-AdminLTE (using AdminLTE 2 in config)
Latest version of Laravel 6

The pages look ok but in the console there are 11 Error 200's every time a page is loaded.

`[Wed Nov 13 15:56:37 2019] 127.0.0.1:52026 [200]: /vendor/bootstrap/dist/css/bootstrap.min.css
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52029 [200]: /vendor/font-awesome/css/all.min.css
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52030 [200]: /vendor/Ionicons/css/ionicons.min.css
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52031 [200]: /vendor/adminlte/dist/css/AdminLTE.min.css
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52032 [200]: /vendor/adminlte/dist/css/skins/skin-purple.min.css
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52033 [200]: /vendor/jquery/dist/jquery.min.js
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52034 [200]: /vendor/jquery/dist/jquery.slimscroll.min.js
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52035 [200]: /vendor/bootstrap/dist/js/bootstrap.min.js
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52036 [200]: /vendor/adminlte/dist/js/adminlte.min.js
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52037 [200]: /vendor/font-awesome/webfonts/fa-solid-900.woff2
[Wed Nov 13 15:56:37 2019] 127.0.0.1:52038 [200]: /vendor/font-awesome/webfonts/fa-regular-400.woff2`

Have done vendor:publish and select Laravel-AdminLTE and that doesn't resolve it.
The files do not exist in the installation so the error is correct. But I'm not sure what is suppose to be generating those files as it doesn't seem to be working.
I'm fairly new to Laravel and this is the first time using Laravel-AdminLTE.

**Comment by lacodimizer** [comment]
The status 200 is not a error status, it's says that everything is ok.

**Comment by digitalight** [comment]
Oh. lol. ok my bad then. Everything is fine then :D
