### ISSUE TITLE
There was a problem with jeroennoten / Laravel-AdminLTE + VueJS

### ISSUE THREAD

**Issue by sergdsv** [jeroennoten/Laravel-AdminLTE#423]
Good afternoon!

There was a problem with jeroennoten / Laravel-AdminLTE + VueJS
The code does not provide for adding a tag with ID for Vuejs.
Or maybe I didn’t find it.
Solved the issue using the code in the file vendor / jeroennoten / laravel-adminlte / resources / views / master.blade.php

Added by
<div id = "app">
@yield ('body')
</div>

Tell me, maybe there is another way not to get into the code vendor / jeroennoten / laravel-adminlte / resources / views / master.blade.php
Or it can be solved through the template engine or config / adminlte.php config?

**Comment by REJack** [comment]
What kind of tag you want to modify?

If you want to add some stuff on the `body`-tag you can add any attribute to body, 
like this id-attribute example:
```php
@section('body_data', 'id="someIdForThis"')
```

**Comment by sung1asses** [comment]
Hello, using Adminlte templates I cannot create a vue object. Bootstrap styles do not work either. I added an Element with id "app" in the file vendor / jeroennoten / laravel-adminlte / resources / views / master.blade.php, but that did not help ...

Here is by app.js file:

require('./bootstrap');
window.Vue = require('vue');
const app = new Vue({
    el: '#app'
});


And here is one of my views, which extends AdminLTE layout.

@extends('adminlte::page')
@section('content_header')
....
@stop
@section('content')
...
@stop

**Comment by oplan-hebibulla** [comment]
> Hello, using Adminlte templates I cannot create a vue object. Bootstrap styles do not work either. I added an Element with id "app" in the file vendor / jeroennoten / laravel-adminlte / resources / views / master.blade.php, but that did not help ...
> 
> Here is by app.js file:
> 
> require('./bootstrap');
> window.Vue = require('vue');
> const app = new Vue({
> el: '#app'
> });
> 
> And here is one of my views, which extends AdminLTE layout.
> 
> @extends('adminlte::page')
> @section('content_header')
> ....
> @Stop
> @section('content')
> ...
> @Stop

`php artisan adminlte:install --only=main_views`

and then open `resources/views/vendor/adminlte/master.blade.php`
add 
```
<div id="app">
    @yield('body')
</div>
```
and refresh browser,booom!!
