### ISSUE TITLE
menu classes 

### ISSUE THREAD

**Issue by wiiwilasinee** [jeroennoten/Laravel-AdminLTE#425]
I would like to add more class for menu on nav bar 

for example (I want to hide menu when become to mobile layout size ):
'menu' => [
        [
            'text' => 'Home',
            'url'  => '/home',
            **'classes' => 'd-none d-sm-inline-block',**
            'icon' => 'fas fa-home',
            'topnav' => true,
        ],
] 

Is it possible to do ?
Thank you for helping :)

**Comment by andcarpi** [comment]
The best option fo this, is creating a new Menu Filter for this, as in the docs
https://github.com/jeroennoten/Laravel-AdminLTE#692-custom-menu-filters
