### ISSUE TITLE
skin issue

### ISSUE THREAD

**Issue by nahuelmellusso** [jeroennoten/Laravel-AdminLTE#426]
Hi , i want to change the skin , but i cant find it on  config/adminlte.php ... 
where i can do that ?

**Comment by REJack** [comment]
Which version you use (v1, v2 or v3)?

**Comment by nahuelmellusso** [comment]
v3

**Comment by REJack** [comment]
The skins was removed with AdminLTE v3, you can change the look of your sidebar, navbar, brand & link accent color individually.

Here are example config entries for a Light Purple Version of AdminLTE v3:
- Sidebar Light with Purple Nav Item Background 
    ```
    'classes_sidebar' => 'sidebar-light-purple elevation-4',
    ```
- Navbar in Purple with Light Text Color
    ```
    'classes_topnav' => 'navbar-purple navbar-dark',
    ```
- Brand in Purple
    ```
    'classes_brand' => 'bg-purple',
    ```
- Link Accents in Purple
    ```
    'classes_body' => 'accent-purple',
    ```

All color variations are listed in the [AdminLTE v3 Docs](https://adminlte.io/docs/3.0/layout.html).

**Comment by nahuelmellusso** [comment]
I see , thanks !
