### ISSUE TITLE
Menu active when using route()

### ISSUE THREAD

**Issue by markdegrootnl** [jeroennoten/Laravel-AdminLTE#43]
Laravel (5.3) returns the full URL when using the route(...) helper function. The ActiveChecker class only checks for the path() section of the current route. 

So when using 'url' => route(...) in the menu config the ActiveChecker never marks the menu item as active.

**Comment by jeroennoten** [comment]
True. You should actually never use function calls in your config files, because you can get into trouble when you enable config caching. However, I can add a possibility to specify the route instead of the URL. Will do that later today.

Thanks for your issue.

**Comment by markdegrootnl** [comment]
I agree with you on using function calls in config files. When adding menu configuration at runtime however, it would make sense to use function calls right?

**Comment by jeroennoten** [comment]
You're right. I will make sure that full URLs are supported for active item checking.

**Comment by jeroennoten** [comment]
Full URL support added in version 1.16 and also the possibility to specify `route` instead of `url`.

**Comment by catalinivan15** [comment]
thats v nice! :) thanks!

**Comment by markdegrootnl** [comment]
Great fix, only the activechecker does not work with the new 'route' config option?

**Comment by jeroennoten** [comment]
Damn it, you're right ;-)

It is fixed now. But pay attention to the filter order in the config, see release notes: https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v1.16.2
