### ISSUE TITLE
Help using plugins

### ISSUE THREAD

**Issue by okitupadmin** [jeroennoten/Laravel-AdminLTE#433]
I'm relative new in web development.
Apologies if this is not the place for a question, I'm not sure if it is an issue or is my misunderstanding.

I installed all plugins with artisan:
`php artisan adminlte:plugins install`

Then I want to use Chart.js plugin on a specific page, so I read documentation and I activated like this:
`@section('plugins.Chartjs', true)`

So when I see the html I can see that is loading the javascript file via CDN with version 2.7.0:
`<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>`

The downloaded version by artisan is 2.9.2, so I'm interested to use the newest one.
I understand that I can change also the version on config/adminte.php, but I prefer to user local files .js and .css

So, here we have to ways to use plugins:
- Downloaded via artisan
- Injected via CDN
That's right?

My question is:
How I can use downloaded plugins?
Have I to write like this:
```
<link href="vendor/chart.js/Chart.min.css" rel="stylesheet">
<script src="/vendor/chart.js/Chart.min.js"></script>
```

Or via config/adminlte.php I can choose a localhost location?

**Comment by andcarpi** [comment]
You did almost everything all right, except the configuration.
When you use `@section('plugins.Chartjs', true)` the package still uses the `adminlte.php` config file to see what kind of injection you want and then load the files into your view, so you need to edit it to do not use assets, and change the location to the local files...

**Comment by okitupadmin** [comment]
Thanks so much, I only needed some of light!
