### ISSUE TITLE
Not working wind Laravel 6.2

### ISSUE THREAD

**Issue by helderam** [jeroennoten/Laravel-AdminLTE#434]
Hi,
I install Laravel using composer command
after that, I install UI

`composer require laravel/ui`
`php artisan ui vue --auth`
`npm install && npm run dev`

After thats i install AdminLTE:

`composer require jeroennoten/laravel-adminlte`
`php artisan adminlte:install`

But nothing happens! The login page still like before

What I fogot to do ?

**Comment by andcarpi** [comment]
Laravel 6 comes with the auth controllers and so on... you just need the views and the routes.
add
`Auth::routes();` to your web routes and install adminlte...
