### ISSUE TITLE
how to set favicon?

### ISSUE THREAD

**Issue by bbdangar** [jeroennoten/Laravel-AdminLTE#436]

**Comment by REJack** [comment]
Simply place the favicon.ico in your public folder.

**Comment by bbdangar** [comment]
not working, I have placed favicon.ico in public folder, looking at the page source there, `<link rel="icon" href="favicon.ico" type='image/x-icon'>` tag is missing.

**Comment by abasjo** [comment]
I've got the same problem, @bbdangar. I hope my pull request helps and will be accepted.

**Comment by lacodimizer** [comment]
I will check this PR, but I think we should add more Blade sections to define meta-tags and so one and not only config options to set them. This only limits the adaptability and allows fewer individual adjustments.

**Comment by REJack** [comment]
I would prefer blade sections too, but we can combine the blade section with the PR added tags. 
We could change the two options to one single option with 3 variable types like `simple`, `extended` & `blade` or we change `simple` & `extended` to an array like I've done it with the fixed options, with this we give the users the ability to decide which icon they want to show.

Like this array (all posibile icons): 
```php
[
    "favicon": "/favicon/favicon.ico",
    "apple-57": "/favicon/apple-icon-57x57.png",
    "apple-60": "/favicon/apple-icon-60x60.png",
    "apple-72": "/favicon/apple-icon-72x72.png",
    "apple-76": "/favicon/apple-icon-76x76.png",
    "apple-114": "/favicon/apple-icon-114x114.png",
    "apple-120": "/favicon/apple-icon-120x120.png",
    "apple-144": "/favicon/apple-icon-144x144.png",
    "apple-152": "/favicon/apple-icon-152x152.png",
    "apple-180": "/favicon/apple-icon-180x180.png",
    "generic-16": "/favicon/favicon-16x16.png", 
    "generic-32": "/favicon/favicon-32x32.png", 
    "generic-96": "/favicon/favicon-96x96.png", 
    "generic-192": "/favicon/android-icon-192x192.png", 
    "manifest": "/favicon/manifest.json", 
    "msapplication-color":"#ffffff",
    "msapplication-image":"/favicon/ms-icon-144x144.png",
]
```

Or like this array (only simple favicon): 
```php
[
    "favicon": "/favicon/favicon.ico",
]
```

Also we can place this config option in the logo section too 😄 not as a seperate section.

**Comment by joaopaulopvillela** [comment]
I would like to request the reopening of this issue, since the platform I am developing will be used by several customers, and each one will have their own, in this format I am stuck to just one, @REJack suggestion would be ideal, so I could do the necessary adjustments.

**Comment by Shidersz** [comment]
@joaopaulopvillela Please, open a new **feature request** explaining your needs with some details and examples.
