### ISSUE TITLE
role-based menu

### ISSUE THREAD

**Issue by kubszy** [jeroennoten/Laravel-AdminLTE#438]
Somebody will describe how integrate roles with jeremykenedy/laravel-roles in AdminLTE 2 menu ? thx

**Comment by REJack** [comment]
For this you will need to create a custom MenuFilter, as a good startpoint you can use the GateFilter.

**Comment by kubszy** [comment]
Can you get me example ?

**Comment by miskin1702** [comment]
Yes, i have same question. But i dont know how to make a Gate filter? Can you make a demo for us?

**Comment by kubszy** [comment]
I've found a solution, just add in the file in boot method App\Providers\AuthServiceProvider for example: 
`Gate::define('ordersAdmin', function ($user) {
          return $user->hasRole('admin');
        });` 
and then in the file config\adminlte.php in section Menu for item menu: 
`'text'        => 'Orders',
            'url'         => 'orders',
            'icon'        => 'fas fa-fw fa-chart-pie',
            'can'  => 'ordersAdmin',`
