### ISSUE TITLE
Custom file input error

### ISSUE THREAD

**Issue by AhmadShiddiq** [jeroennoten/Laravel-AdminLTE#439]
I just found little error when I want to upload it with the type file e.g .png
when I check console here what it says :
![image](https://user-images.githubusercontent.com/53107961/70528392-b4b8df80-1b80-11ea-8e8c-ee1938984bb9.png)

here the results on my web :
![Screenshot_20191215_163240](https://user-images.githubusercontent.com/53107961/70860822-100c1880-1f59-11ea-90ba-ddd3058a5262.png)

These results from .zip download :
![Screenshot_20191215_163449](https://user-images.githubusercontent.com/53107961/70860829-2d40e700-1f59-11ea-882d-35e1ac1e412a.png)

**Comment by lacodimizer** [comment]
The field or var csCustomFileInput is not defined, but that's not a error in adminlte.
