### ISSUE TITLE
ISSUE: Active menu not working exactly

### ISSUE THREAD

**Issue by nguyentranchung** [jeroennoten/Laravel-AdminLTE#442]
![image](https://user-images.githubusercontent.com/9611224/70758938-df28b980-1d87-11ea-9e17-fbc57cf487c9.png)

> By default, a menu item is considered active if any of the following holds:
> 
> The current path matches the url parameter
> The current path is a sub-path of the url parameter
> If it has a submenu containing an active menu item

But not active xxx.com/admin/permission is a sub-path of the xxx.com/admin/permission?page=2

**Comment by BbgnsurfTech** [comment]
Bro i want to know how you achieve to build roles and permissions

**Comment by schonhose** [comment]
Several laravel packages exist who are able to help you with this. The permission package by [Spatie](https://github.com/spatie/laravel-permission) is one of them.
