### ISSUE TITLE
sidebar menu icon not centered when collapsed

### ISSUE THREAD

**Issue by buddyy93** [jeroennoten/Laravel-AdminLTE#443]
Here's how it looks like on my local development

![Snipaste_2019-12-13_12-13-03](https://user-images.githubusercontent.com/22981271/70768833-f1175600-1da1-11ea-884c-943be6f0f9a0.png)

i haven't modified any css files, anyone knows how to fix it ?

**Comment by fajarsulaksono** [comment]
you can add `nav-icon` class before the font class (fonteawesome)

![Screen Shot 2019-12-13 at 13 16 52](https://user-images.githubusercontent.com/202346/70773747-de554f00-1daa-11ea-8c51-7eb9e1a48876.png)

**Comment by fajarsulaksono** [comment]
edit the `resources/views/vendor/adminlte/partials/menu-item.blade.php
![Screen Shot 2019-12-13 at 13 18 48](https://user-images.githubusercontent.com/202346/70773898-4c017b00-1dab-11ea-8da0-5ccb428393a8.png)
`

**Comment by buddyy93** [comment]
thanks man! that helped!
