### ISSUE TITLE
active menu item for urls having parameters

### ISSUE THREAD

**Issue by BahodurSaidov** [jeroennoten/Laravel-AdminLTE#445]
Hi, 
Great project, very helpful to systematically create sites based on adminlte and laravel.

When a submenu is displaying some table data that has many pages like 20 rows per page then the menu (and submenu) does not get active:
http://domain.com/page1/page2?page=3

So, after looking inside project's source files i am using a simple solution by editing checkPattern() function:
From
`Str::is($fullUrlPattern, $fullUrl);`
to
`Str::is($fullUrlPattern . '*', $fullUrl);`

and then everything works fine.

You could update your package like so.

**Comment by kubszy** [comment]
You can add active links in the submenu by section active:
`['header' => 'Main manu'],
        [
            'text'        => 'Orders',
            'url'         => 'orders',

            'submenu' => [
                [
                    'text' => 'Pending orders',
                    'url'  => 'pending-orders',
                    'can'  => 'ordersAdmin',
                    'active' => ['pending-orders', 'details-order/*'],
                ],
`
