### ISSUE TITLE
QUESTIONS: add more sections and possibility to include global CSS

### ISSUE THREAD

**Issue by schonhose** [jeroennoten/Laravel-AdminLTE#446]
Thanks for making this available. I have two questions that I would like to ask:

1) Is it possible to add more sections where HTML can be injected using blade template files? For example, the default layout consists of a top menu with a search form and a log out button. It would be great if we could add some more content there. The same goes for the sidebar (a section on top of the menu, and one at the bottom of the menu). I know I can add these myself, by publishing the template files and editing them. However, those changes are lost when updating (and republishing) the templates. If there is any other idea on how to handle this, I would love to hear it.

2) How to include a global CSS file? I guess I can add it to the plugin section of the config file, defining a new plugin with only a link to the CSS and set active=TRUE. However, perhaps there might be a better way?

**Comment by schonhose** [comment]
In answer to my questions:
1) The top menu bar with search form and log out button can be reached using `@section('content_top_nav_right')`. As for the other options in the sidebar I added some sections, as well as the user panel, starting from line 141:

```
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="URL_TO_IMAGE" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
        <a href="#" class="d-block">{{$user->name}}</a>
    </div>
</div>
@yield('main_sidebar_top_nav')
```
The following is added after the `<nav>` section: `@yield('main_sidebar_bottom_nav')`. This allows for inclusion of code after the user panel, but before the navigation and after the navigation.

2) including global CSS files works best as described.

**Comment by REJack** [comment]
1. It's funny this is one of my next implementation for Laravel-AdminLTE, I've planned to add the user panel with menu and multiple sections.

But I need to find a way to add the user image via config, I need this also for the lockscreen 😄.

2. Yep that's the easiest way like in your first comment.

**Comment by schonhose** [comment]
Adding the user image through config is indeed a bit tricky as the user image often is stored in the database for each user.

As denoted in the documentation over at:  https://laravel.com/docs/6.x/configuration

```
To set configuration values at runtime, pass an array to the config helper:

config(['app.timezone' => 'America/Chicago']);
```
This allows you to set configuration values, but I am not sure if those changes are made persistent by writing them into the configuration file.
