### ISSUE TITLE
class in page.blade.php

### ISSUE THREAD

**Issue by hendralin** [jeroennoten/Laravel-AdminLTE#447]
Line 58, maybe can be change like this for the config :
`<nav class="main-header navbar {{config('adminlte.classes_topnav_nav', 'navbar-expand')}} {{config('adminlte.classes_topnav', 'navbar-white navbar-light')}}">`

**Comment by REJack** [comment]
Oh dang 🤦‍♂, I'll create a PR soon to fix this.

**Comment by REJack** [comment]
@lacodimizer Assign it to me bro 😄
