### ISSUE TITLE
How to align right in topnav?

### ISSUE THREAD

**Issue by rasyidialwee** [jeroennoten/Laravel-AdminLTE#450]
How can i create an item and make it align right on the topnav.

**Comment by triastanto** [comment]
I do it manually by adding after this [line 82](https://github.com/jeroennoten/Laravel-AdminLTE/blob/4830f877e090480c6a7469d492bd5b7d2d9ce8e9/resources/views/page.blade.php#L82). And then try to copy paste this entire `ul` from [this line](https://github.com/ColorlibHQ/AdminLTE/blob/05f23cb8c3fed7b079249f322378419dddc2615b/pages/layout/fixed-topnav.html#L48).
