### ISSUE TITLE
ISSUE: href key for search menu doesn't work

### ISSUE THREAD

**Issue by zdzc** [jeroennoten/Laravel-AdminLTE#459]
In the documentation, to change the `form action` you should change the `href` in the menu item. For whatever value I use for `href`, the value is automatically set to `#`. But if I use `url` instead, it works as expected.

Sample menu:
```php
[
    'text' => 'search',
    'href' => '/search',
    'search' => true,
    'topnav' => true,
    'method' => 'get',
],
```

**Comment by zdzc** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/blob/890b188e0cfbd9c066a5752b9d96dab53b91af41/src/Menu/Filters/HrefFilter.php#L19

This might be the cause, but I'm not sure about that.

**Comment by Kalpeshpatelbyk** [comment]
u can use url feature that will solve purpose

 'url'  => 'admin/blog',

**Comment by zdzc** [comment]
Yes, I am aware of that. My point is, the possible bug should be fixed or the documentation should be updated.
