### ISSUE TITLE
Menu side-bar push button not responding to sidebar-collapse & sidebar-open state

### ISSUE THREAD

**Issue by BbgnsurfTech** [jeroennoten/Laravel-AdminLTE#462]
Just installed laravel admin lte but when on small screen or even large pressing on menu bars does not toggle sidebar to sidebar-collapse or sidebar-open

**Comment by REJack** [comment]
`sidebar-open` will only toggled on certain viewport sizes (adjusted by the autoCollapseSize setting of AdminLTE, by default under 992px). It's used to show the overlay while open sidebar on mobiles/old tablets.
