### ISSUE TITLE
ISSUE: using dataTables

### ISSUE THREAD

**Issue by EmanuelM** [jeroennoten/Laravel-AdminLTE#463]
Hi!

I'm trying to implement dataTablse plugin, but at the moment to init on a table the error is always the same 
```
VM2705:1 Uncaught TypeError: $(...).dataTable is not a function <anonymous>:1:22
```

The plugin from CDN is loading well, I can't find an other issue related to this.

![config/adminlte.php](https://imgur.com/JPcDEXv.jpg)

![Plugin loading well](https://imgur.com/3b40CeD.jpg)

![Error](https://imgur.com/7DYLA1u.jpg)

**Comment by andcarpi** [comment]
You are setting asset to true in the files while using the cdn location, set asset to false and it should work.

**Comment by EmanuelM** [comment]
> You are setting asset to true in the files while using the cdn location, set asset to false and it should work.

No, still not working. Why you said that? DataTables files are fetched, but not loaded in DOM.

**Comment by EmanuelM** [comment]
Disabling DataTables from Plugins sections and loading in the blade on "js" section works well
