### ISSUE TITLE
Change sidebar colors

### ISSUE THREAD

**Issue by andersonabreu0606** [jeroennoten/Laravel-AdminLTE#466]
Hello everybody,

How I change sidebar color?

**Comment by REJack** [comment]
Just change the `classes_sidebar` in `config/adminlte.php`, if you use Laravel-AdminLTE v3 (AdminLTE v3).

**Comment by andersonabreu0606** [comment]
Thank You REJack!!! I will test new version.

I alter color in css files, because My client request a specific color that not exists in AdminLTE

**Comment by miguel1441** [comment]
> classes_sidebar

Hello friend, you could change it to another color that is not what it comes by default as green, red
