### ISSUE TITLE
specific arrangement in dynamic menu

### ISSUE THREAD

**Issue by rasyidialwee** [jeroennoten/Laravel-AdminLTE#468]
Hello,

I created my menu using the configuration in adminlte.php file, and for dynamic menu item I manage to create it by using BuilingMenu in the AppServiceProvider.php. By default it will add my dynamic content at the bottom of the menu.

Is there any method to set the position of the dynamic menu item? or I just need to create the whole menu using the BuildingMenu in AppServiceProvider.php.

my code are as below :

**AppserviceProvider.php**
`$schools->listen(BuildingMenu::class, function (BuildingMenu $school) {
            $school->menu->add([
                'text'        => 'Manage School',
                'icon'        => 'fas fa-school',
                'label'       => School::count(),
                'label_color' => 'success',
                'align' => 'right',
                'submenu' => [
                    [
                        'text' => 'List',
                        'url'  => 'school',
                        'icon'        => 'fas fa-th-list',
                    ],
                    [
                        'text'    => 'Add New',
                        'url'     => 'school/create',
                        'icon'        => 'fas fa-plus',
                    ]
                ]
            ]);
        });
`

**adminlte.php**
`
'menu' => [
        [
            'text' => 'search',
            'search' => true,
            'topnav' => true,
        ],
        [
            'text'        => 'Dashboard',
            'url'         => 'dashboard',
            'icon'        => 'fas fa-tachometer-alt',
        ],
]
`

thank you in advance

**Comment by REJack** [comment]
Checkout my PR #477, I've added there a example that works with my changes.
