### ISSUE TITLE
Deploing install: variables not seted

### ISSUE THREAD

**Issue by trivoweb** [jeroennoten/Laravel-AdminLTE#473]
I have a trouble when deploy  my app to server.
I run compose install but variables apears invalid.

Take a look. jpg attached.
What is missing?
Laravel 5.8/AdminLTE 1.25.1

![image](https://user-images.githubusercontent.com/60224855/73276091-e59fb300-41c6-11ea-9437-b9c63de09908.png)

**Comment by REJack** [comment]
Is your Laravel installation a fresh copy, or did you migrated from older Laravel to 5.8? May the ServiceProvider needs to loaded if you run old configs.
