### ISSUE TITLE
Dynamic Right navbar links

### ISSUE THREAD

**Issue by Majidkadi** [jeroennoten/Laravel-AdminLTE#474]
Hi everybody,

Is it possible to add a Right navbar links in the dynamic menu.

Thanks
![right navbar links](https://user-images.githubusercontent.com/31285669/73547952-fa21bc80-440d-11ea-98c2-bb7b754747b8.JPG)

**Comment by REJack** [comment]
for custom menus like notification and messages you will need to add the `content_top_nav_right`-blade section.

**Comment by Majidkadi** [comment]
Thanks too much
