### ISSUE TITLE
QUESTION: Is it possible to group menu entries

### ISSUE THREAD

**Issue by KyleMassacre** [jeroennoten/Laravel-AdminLTE#475]
Hello,
I was wondering if it is possible to add menu entries during runtime to a menu group (if that makes sense)? Let's say I have a modular system and want to add a menu to a particular menu group through various modules, for example:
```php
// Profile Module
$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
  $event->menu->add('Account Settings');
  $event->menu->add([
    'text' => 'Profile',
    'url' => 'account/edit/profile',
  ]);
});
```

```php
// Notifications Module
$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
  $event->menu->add('Account Settings');
  $event->menu->add([
    'text' => 'Notifications',
     'url' => 'account/edit/notifications',
  ]);
});
```
Current Result:
<img width="173" alt="Screen Shot 2020-02-01 at 7 00 47 AM" src="https://user-images.githubusercontent.com/4021612/73594178-a6bc7680-44c0-11ea-93fd-d41239c680e3.png">
Desired Result:
<img width="205" alt="Screen Shot 2020-02-01 at 7 03 46 AM" src="https://user-images.githubusercontent.com/4021612/73594251-8c36cd00-44c1-11ea-92ba-a8e28a5f48e6.png">

**Comment by lacodimizer** [comment]
Not at the moment, but this is a nice feature!

**Comment by REJack** [comment]
I prefer to add array key's to the menu items, then it should be easier to achieve this 😄

**Comment by yagrasdemonde** [comment]
Can you give us an example how do you do this @REJack please ?

**Comment by REJack** [comment]
Checkout my PR #477, I've added there a example that works with my changes.
