### ISSUE TITLE
Installation of older version

### ISSUE THREAD

**Issue by davidrichart** [jeroennoten/Laravel-AdminLTE#480]
Hello,
I have tried to install an older version of the package (with Admin LTE 2, because I find it more pretty). But when I launched update with the package version "^2.0.2" into my composer file (I think it's the last version with my favorite admin design), a big error has occured : 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jeroennoten/laravel6-adminlte2 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

How can I avoid the problem please ?

**Comment by REJack** [comment]
the package name is not correct, it's still `jeroennoten/laravel-adminlte` but you need to target the version 2 but this has not the new features that the v3 has. You can change the style of the AdminLTE v3 sidebar to get a more AdminLTE v2 look.

**Comment by davidrichart** [comment]
Effectively I was wrong with my syntax, thank you for your reactivity ! :) 
Concerning Admin LTE, I really prefer the version 2 in its entirety (sidebar, boxes, tables...), I use it for years, and it bothers me that the top navigation layout has been deleted :( (it was useful for really smart admin access)
https://adminlte.io/themes/AdminLTE/pages/layout/top-nav.html
