### ISSUE TITLE
Insert 'adminlte_js' with laravel_mix enabled

### ISSUE THREAD

**Issue by eliasrosa** [jeroennoten/Laravel-AdminLTE#481]
Hello! 

First I would like to thank you for sharing this project, thank you very much!

I'm using the 'laravel_mix' option and I'm looking to add the package https://github.com/tjgazel/laravel-toastr, but the 'adminlte_js' section is not rederized.

```
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/css/app.css">
</head>
<body>
    <div id="app"></div>
    <script type="text/javascript" src="js/app.js"></script>
    {!! toastr()->render() !!}
</body>
</html>
```

How can I proceed?
Thanks

**Comment by eliasrosa** [comment]
Hi, I was able to install the package.

I had forgotten to publish the views of AdminLTE.
`php artisan adminlte: install --only = main_views`

After publishing, I adjusted the view 'master.blade.php'

Thank you very much

**Comment by rodrigompais** [comment]
@eliasrosa How did you go about including Toastr in the master to use in the view?
