### ISSUE TITLE
Sidebar Padding Left

### ISSUE THREAD

**Issue by rodrigompais** [jeroennoten/Laravel-AdminLTE#482]
Good afternoon Guys, I would like to know where I include the padding-left in the sidebar according to the attached model?
![image](https://user-images.githubusercontent.com/59613110/74371961-8d68d380-4db8-11ea-9e84-ad07d802f2e8.png)
Grateful for everyone's attention.
Rodrigo Pais

**Comment by REJack** [comment]
Just add `nav-child-indent` to `classes_sidebar_nav` in config/adminlte.php.

**Comment by rodrigompais** [comment]
Thank you very much, it worked!
