### ISSUE TITLE
Role Based Menu problem with Laratrust

### ISSUE THREAD

**Issue by dgvai** [jeroennoten/Laravel-AdminLTE#485]
added inside adminlte.php, like 
```
[
...
'can' => 'manage-posts',
...
]
```
still the menu is visible to all users. 
I have checked manually inside blade, that if permission is granted to the user, 
```
@permission('manage-posts')
//check here the permission, it is ok
@endpermission
```

I have created a custom GateFilter for Laratrust, according to the readme.

**Comment by lacodimizer** [comment]
Have you tried the @can syntax in the blade file:

**Comment by dgvai-git** [comment]
@lacodimizer yes, I check ```@can``` syntax in blade to test, if laratrust been working perfectly, indeed it was working, but in the ```adminlte.php``` config file, I did set ```can : 'user-perm'``` but, the user without that permission, still can see the menu.

**Comment by lacodimizer** [comment]
@dgvai is the issue actual or solved?

**Comment by dgvai** [comment]
@lacodimizer i think the problem was with Laratrust, or may be I was not able to configure the custome Gate class, so I changed with another package of role-permission, and there was no problem.

**Comment by lacodimizer** [comment]
@dgvai thanks for feedback!
