### ISSUE TITLE
Is it possible to combine this with a crud generator?

### ISSUE THREAD

**Issue by BooJoe** [jeroennoten/Laravel-AdminLTE#486]
Looking to combine this with  appzcoder/laravel-admin crud generator. Seems to cause issues during installation, has anyone done something similar? or can anybody recommend a crud generator package that will just install and work along with adminlte without having to change much.

**Comment by honorezemagho** [comment]
First  of all install "laravel/ui" package and generate auth files  and use adminlte.
You install the composer package "composer require jeroennoten/laravel-adminlte" and run the command "php artisan adminlte:install" 
after this you run the command "php artisan adminlte:install --only=auth_views" , afterwards you run the command "php artisan adminlte:install --only=config" to publish config files and if you want to customize views run the command "php artisan adminlte:install --only=main_views"
