### ISSUE TITLE
How can i add background image to login page only.

### ISSUE THREAD

**Issue by rasyidialwee** [jeroennoten/Laravel-AdminLTE#487]
I already run the command to customize the view, but i cant seem to find ways to change/add background image to the login page.

**Comment by lacodimizer** [comment]
You can customize the login blade template, to add a css class. In this css class, you can define a background image now.

**Comment by honorezemagho** [comment]
you can customize the adminlte login blade file, adding css class. In this css class, you can define your image and customize it as you want
