### ISSUE TITLE
Change bars color.

### ISSUE THREAD

**Issue by MiguelRosaPT** [jeroennoten/Laravel-AdminLTE#488]
Hi guys.

I've two questions:
- Can I change the **sidebar** and **top** bar colors?
- Can I add a seperator on left menu? like <hr> in html

Thanks.

**Comment by REJack** [comment]
In v3: 
1. Just change the `classes_sidebar` & `classes_topnav` option like this:
```php
     'classes_sidebar' => 'sidebar-dark-purple elevation-4',
    'classes_topnav' => 'navbar-purple navbar-light',
```

2. You could add a empty nav header but a real seperator isn't available.

**Comment by MiguelRosaPT** [comment]
REJack, thank you.

One more question: It's possible create menu like this:

Option 1
Option 1.1
Option 1.1.1
Option 1.2

Option 2
(....)

I try, but I only can create one sub-menu... I want create a sub-menu inside another sub-menu.
