### ISSUE TITLE
Sem acesso ao Painel

### ISSUE THREAD

**Issue by marcionavarro** [jeroennoten/Laravel-AdminLTE#489]
Fiz tudo como descrito, mas não consigo acessar o painel e não aparece os links de Login e Register.
quando uso o php artisan adminlte:status esta tudo ok. Só o translations aparece como Not Installed
meus arquivos auth estao ok. e tbm publiquei a pasta vendor\adminlte na views. Mas não consigo acessar o painel meu laravel é 6.12.

**Comment by lacodimizer** [comment]
Do you have any error message or log details for us?

**Comment by marcelcunha** [comment]
@marcionavarro Se postar em português acredito que vai ser mais dificil ter uma resposta decente. Conseguiu resolver seu problema? Se não, explica melhor que eu tento te ajudar.

**Comment by marcionavarro** [comment]
Consegui o obrigado , mudaram a forma de criar o auth

Em qua, 11 de mar de 2020 10:06, Marcel Cunha <notifications@github.com>
escreveu:
