### ISSUE TITLE
 Failed to load plugins (datatable and select2) after integration with laravel mix

### ISSUE THREAD

**Issue by wtccosta** [jeroennoten/Laravel-AdminLTE#490]
Hello, first, thanks for sharing this project, very nice.
It turns out that after I performed the procedure to activate the laravel mix (I did it step by step, as described), the plugins (which were working well) do not want to load.
I activated the laravel mix directive in config / adminlte.php, but nothing. Someone has been there and can help.

**Comment by Eddy16391** [comment]
Hi, I solved this problem by first publishing the main views (php artisan adminlte:install --only=main_views), and then editing the master view in this way:
1. Under the line where you see <link rel="stylesheet" href="{{ mix('css/app.css') }}"> add this line @include('adminlte::plugins', ['type' => 'css'])
2. Under the line where you see <script src="{{ mix('js/app.js') }}"></script> add this line @include('adminlte::plugins', ['type' => 'js']) and, if you want to load js section in child views, add @stack('js') and @yield('js')
Obviously in the AdminLTE configuration file you must activate both the plugins and the related js and css files that you want.

**Comment by REJack** [comment]
That's only a workaround, if you want to use Laravel's Mix feature you need to import the plugins in the js/app.js. Laravel-AdminLTE's plugin feature doesn't work with Laravel Mix and it's not how laravel itself describe to accomplish this.

**Comment by stoneC0der** [comment]
Hi @Shidersz, thanks this how I solved it:

Extend the adminlte::page from layout/dashboard.blade.php in my case (or app.blade.php)
add this
   `@extends('adminlte::page')
    @push('css')
    {{-- Configured CSS --}}
    @include('adminlte::plugins', ['type' => 'css'])
    @endpush
    @push('js')
    {{-- Configured Scripts --}}
    @include('adminlte::plugins', ['type' => 'js'])
    @endpush`

Then extend all your view from the dashboard or app template
