### ISSUE TITLE
php artisan adminlte:install --type=full not working 

### ISSUE THREAD

**Issue by furqee** [jeroennoten/Laravel-AdminLTE#492]
$ php artisan adminlte:install --type=full

  Command "adminlte:install --type=full" is not defined.

  Did you mean one of these?
      adminlte:install
      adminlte:plugins
      adminlte:status{--include-images
      adminlte:update

**Comment by marchershey** [comment]
Try `php artisan adminlte` and if it gives you an error, you need to run this command: `composer require jeroennoten/laravel-adminlte`.

Make sure you're in the correct directory when running this command.
