### ISSUE TITLE
Not work in laravel 7.0

### ISSUE THREAD

**Issue by bonzinho** [jeroennoten/Laravel-AdminLTE#494]
I can not install in laravel 7.0, any solution to install it?

**Comment by qurgh** [comment]
It should work, it just needs the composer file updated to include Laravel 7. I just don't know the composer command to tell it to ignore requirements like that.

**Comment by fajarsulaksono** [comment]
Wait for this PR (https://github.com/jeroennoten/Laravel-AdminLTE/pull/495) to be accepted

**Comment by jakubthedeveloper** [comment]
I see that the PR was merged, but I'm still getting errors:

```
 Problem 1
    - Installation request for laravel/framework (locked at v7.0.2, required as ^7.0) -> satisfiable by laravel/framework[v7.0.2].
    - jeroennoten/laravel-adminlte v3.0.0 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.0-rc.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.1 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.2 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.3 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.4 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.5 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.6 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.7 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - jeroennoten/laravel-adminlte v3.0.8 requires laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev].
    - Conclusion: don't install laravel/framework 6.x-dev
    - Installation request for jeroennoten/laravel-adminlte ^3.0 -> satisfiable by jeroennoten/laravel-adminlte[v3.0.0, v3.0.0-rc.1, v3.0.0-rc.2, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8].
```

BTW: the PR doesn't update README

**Comment by lacodimizer** [comment]
I released v3.0.9 with the current changes in master branch

**Comment by fajarsulaksono** [comment]
Thx @lacodimizer :

`λ composer require jeroennoten/laravel-adminlte                              
Using version ^3.0 for jeroennoten/laravel-adminlte
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing almasaeed2010/adminlte (v3.0.2): Loading from cache
  - Installing jeroennoten/laravel-adminlte (v3.0.9): Downloading (100%)         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: jeroennoten/laravel-adminlte
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.`

**Comment by jakubthedeveloper** [comment]
It works, thanks.

**Comment by karlerss** [comment]
If you're using the included authentication views, make sure to add `composer require laravel/ui "^2.0"`. Otherwise `Auth::routes();` will not work. It might make sense to add laravel/ui to this project's composer.json.

**Comment by REJack** [comment]
> If you're using the included authentication views, make sure to add composer require laravel/ui "^2.0". Otherwise Auth::routes(); will not work. It might make sense to add laravel/ui to this project's composer.json.

I would rather add a note for this in the readme instead of adding `laravel/ui` to the composer.json as long as this works for laravel 6 & 7.

**Comment by REJack** [comment]
I've added a note to the installation section in the README.md, it's also published already 😄

**Comment by Walt-H** [comment]
@REJack adding `laravel/ui` is a required for all Laravel 7 apps, and isn't just a caveat here (see https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades).

**Comment by REJack** [comment]
Sure but the v3 respectively the master branch is not only for Laravel 7 it works also for Laravel 6 and that's why I've added a note for this, also it's not required only you want to use the auth feature.

![grafik](https://user-images.githubusercontent.com/1554582/77063352-d4606f00-69dd-11ea-951d-14e596dc7732.png)
