### ISSUE TITLE
QUESTION: Including extra JavaScript with mix()

### ISSUE THREAD

**Issue by siljanoskam** [jeroennoten/Laravel-AdminLTE#497]
Hi guys!

I have a problem when I try to include extra JavaScript with `mix()`. 
So, basically when I include it this way:

`<script src="{{ mix('/js/cms/blog-posts/create.js') }}"></script>`

I have no JS error, but the execution of the script I'm trying to use never starts.

By the way, this doesn't happen when I add the code from the script directly into a `<script>` tag and include it that way.

I'm not sure if the problem lies in my webpack configuration or this is a real issue of the package, that's why I'm submitting this as a `QUESTION`.

**Comment by REJack** [comment]
The mix() is only to display the generated js files, you can take a look in the [Laravel Mix Docs](https://laravel.com/docs/6.x/mix) for this.

**Comment by siljanoskam** [comment]
It was my bad. I'm sorry. I didn't have the following scripts included in my master file properly.

```
  <script src="{{ mix('/js/manifest.js') }}"></script>
  <script src="{{ mix('/js/vendor.js') }}"></script>
  <script src="{{ mix('/js/app.js') }}"></script>
```
