### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by dem02312** [jeroennoten/Laravel-AdminLTE#498]
Why after some time in login page expired error occurs.

**Comment by REJack** [comment]
Please post the exact error message. 
Laravel-AdminLTE itself doesn't has any login expiry this come only from Laravel itself.

**Comment by JustinRijsdijk** [comment]
This means that your CSRF token isn't valid anymore.
 please take a look here: https://laracasts.com/discuss/channels/laravel/auth-login-shows-419-page-expired-on-post-request?page=1

**Comment by lacodimizer** [comment]
It's not a problem with this project.
