### ISSUE TITLE
usermenu_enabled not working

### ISSUE THREAD

**Issue by kennysinkeler** [jeroennoten/Laravel-AdminLTE#499]
Hi, 

I change in my config\adminlte.php 

   'usermenu_enabled' => true,

Only there is no effect. 
I see only log out in the header.

I use laravel 6.18.0.
Adminlte 3.10

**Comment by REJack** [comment]
If you updated it recently you will need to regenerate the views too.

**Comment by kennysinkeler** [comment]
I already did this 


php artisan adminlte:update

Basic Assets Installation complete.
 php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=views

Unable to locate publishable resources.
Publishing complete.

**Comment by kennysinkeler** [comment]
Others setting will change

**Comment by REJack** [comment]
`adminlte:update` is only shortcut for updating the assets you need to run `adminlte:install —only=main_views —force`.

**Comment by kennysinkeler** [comment]
That was the problem, Thank you!

**Comment by REJack** [comment]
👍 I hope you like my new implementation of the usermenu 😄

**Comment by yagrasdemonde** [comment]
Amazing @REJack !!!!
addBefore, addAfter .. working like a charm !!! Thank you very much

**Comment by kennysinkeler** [comment]
Yeas @REJack . It is very nice!!

**Comment by BoGnY** [comment]
I've the same problem, fresh installation, and assets are updates..
Nothing works

**Comment by REJack** [comment]
@BoGnY Please post the require/require-dev section of you composer.json or the whole composer.lock file.

**Comment by BoGnY** [comment]
@REJack sorry my fault..
I have not removed `<script src="{{ mix('js/app.js') }}"></script>` from blade, in this file was loaded jquery, bootstrap, and other library again, and this make app crashing 🤕 
I have removed duplicated library from `resources/js/app.js` and now works 👍

**Comment by REJack** [comment]
@BoGnY Ok 😄

**Comment by siljanoskam** [comment]
Hi guys! Isn't there a way to use the `usermenu` without publishing the main views?

**Comment by lacodimizer** [comment]
Hi @siljanoskam! you can copy the html of the views into your project.
