### ISSUE TITLE
Customizing FontAwesome version

### ISSUE THREAD

**Issue by LBreda** [jeroennoten/Laravel-AdminLTE#500]
Hi, 

I have a FontAwesome Pro license, and I'd like to use it in my Laravel-AdminLTE project. Is it possible to customize the FontAwesome-related URIs? I checked out the solution on #261, but the solution seems to be no longer available.
Thanks!

**Comment by andcarpi** [comment]
run adminlte:install —only=main_views
this will publish the master views, edit then and replace fontawesome includes
please note that if the views get updated in future releases you will need to do that again
