### ISSUE TITLE
Logo at the upper left corner

### ISSUE THREAD

**Issue by jczwo** [jeroennoten/Laravel-AdminLTE#501]
The Readme says: "The logo is displayed at the upper left corner of your admin panel." But there's none even if I add some own pngs. What's the trick?

**Comment by jczwo** [comment]
Seems like the problem only exists in Safari on Mac.

**Comment by lacodimizer** [comment]
@REJack

**Comment by lacodimizer** [comment]
@jczwo can you give as more details, like the exact logo config? It works with the infos in the readme, on Mac and Safari too.

**Comment by REJack** [comment]
May its related to this https://github.com/ColorlibHQ/AdminLTE/issues/2412

**Comment by jczwo** [comment]
Tested again today. Everything ok now. I don’t know why, but my content blocker was the problem.

**Comment by REJack** [comment]
XD these bad blockers 😄 but better than too much ads.
