### ISSUE TITLE
how to customize scss?

### ISSUE THREAD

**Issue by port22** [jeroennoten/Laravel-AdminLTE#502]
As the scss build files are installed by composer within the vendor folder, I can't figure how to customize these build files.
Let's say I want to customize the `grid_columns` (`_bootstrap_variables.scss` - line 201)
How'd you do that? (despite the fact that you perhaps wouldn't customize the grid_columns in a clean way; just see it as an example, please). It's about hooking in there.

How are they designed to be built actually?

I am used to use `compass`. My idea was to use the `resources/sass/app.scss` to `@include` the first build file (`vendor/almasaeed2010/adminlte/build/scss/AdminLTE.scss` ?) and then modify the value by overwriting like this:

```
@import '../../vendor/almasaeed2010/adminlte/build/scss/AdminLTE.scss';
$grid-columns:                15 !default;
``` 
but I get problems resolving the `~` aliases.
I think I'm doing it wrong ...

**Comment by REJack** [comment]
Try this without `!default` and place the overrides before the import.

**Comment by port22** [comment]
thanks for your answer!
I get the following error:

```    error sass/app.scss (Line 9 of /www/vendor/almasaeed2010/adminlte/build/scss/AdminLTE.scss: File to import not found or unreadable: ~bootstrap/scss/functions.
```

I am not sure what exactly the tilde `~` is doing; seems like an alias to the vendor package and
compass does not find it. I suppose, at least, this is a reference to a composer package, not a node_module, right? Neither in compose.json nor in package.json is bootstrap defined as a dependency.

**Comment by port22** [comment]
I would consider using npm css stuff if that works better. I just ain't used to it.
There is no css build script in package.json, that's my first hurdle

**Comment by port22** [comment]
Running `npm run dev` produces the following:

``` 
DONE  Compiled successfully in 6996ms                                                                                                                         10:40:27 AM

       Asset     Size   Chunks             Chunk Names
/css/app.css  727 KiB  /js/app  [emitted]  /js/app
  /js/app.js  592 KiB  /js/app  [emitted]  /js/app
```

where are the sources for that?

**Comment by REJack** [comment]
> where are the sources for that?

That's Laravel Mix css/js generation, you can find the files in resources/ e.g. resoruces/js/app.js or resources/sass/app.scss, the compiled files are in public/css or public/js 😄. 

To modify the AdminLTE scss variables you should add AdminLTE as dependecy in your package.json and then point the `build/scss/AdminLTE.scss` to the npm package otherwise you need to recreate the AdminLTE.scss with absoulte paths instead of the tilde (the tilde scopes to a npm package without any absolute path).

**Comment by port22** [comment]
> point the build/scss/AdminLTE.scss to the npm package

how would you do that? you mean `node_modules/admin-lte/build/scss/AdminLTE.scss`, right?

Your suggestion with placing the override before the import and without !default did now produce a valid css how I wanted (the grid is now indeed 15), but the referenced stylesheet is 

```
    <link rel="stylesheet" href="/vendor/adminlte/dist/css/adminlte.min.css">
```

and I cant find a way to configure to use `public/css/app.css`

I can append stylesheets, but this one is injected somewhere deeper in the core ...

**Comment by REJack** [comment]
For this set `enabled_laravel_mix` to true and you should automatically use the laravel mix generated files.

**Comment by port22** [comment]
yess, that worked! thank you very much !

**Comment by anthony0506** [comment]
thank you.
