### ISSUE TITLE
top_nav_class error when enabled

### ISSUE THREAD

**Issue by ivex001** [jeroennoten/Laravel-AdminLTE#503]
Hi there how are you? By the way  thank you for making this, it saves me a lot of time.
Im getting this error when i set top_nav_class= true

Undefined index: top_nav_class (View: /opt/lampp/htdocs/kazadmin/vendor/jeroennoten/laravel-adminlte/resources/views/partials/menu-item-top-nav.blade.php) on line 13

Here and image if it could help:
[https://drive.google.com/file/d/1y5A1t3V-iRkdGQb2G7rpcvxoYBPzjS0C/view?usp=sharing](url)

**Comment by REJack** [comment]
You should not set `top_nav_class` to true, it's used by the MenuBuilder to set the right css classes e.g. for the active state, dropdown identifier or the nav-item style.

**Comment by ivex001** [comment]
Oh ok.  With that i went read the docs again and i saw what i was doing wrong. i needed to add 'topnav' => true.
Sorry for this and thanks

**Comment by REJack** [comment]
No problem 👍 Please close this issue 😄

**Comment by ivex001** [comment]
right +1
