### ISSUE TITLE
Adminlte DataTable export buttons in laravel

### ISSUE THREAD

**Issue by Mhongo31** [jeroennoten/Laravel-AdminLTE#505]
I am having difficulties projecting the pdf, excel and csv export buttons on my datatables.. I have added all the neccesary links. I dont know what I am missing, kindly assist

**Comment by REJack** [comment]
Did you imported/loaded the DataTables Plugin for this? You need to load various CSS/JS files for the export functions, they are not bundled to the DataTable Core.

**Comment by Mhongo31** [comment]
Thank you for the response.. I noticed in the adminlte.php has plugins for datatables like below
'plugins' => [
        [
            'name' => 'Datatables',
            'active' => true,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => false,
                     'location' => '//cdn.datatables.net/v/bs/dt-1.10.18/datatables.min.js',  
               ]
               [
                    'type' => 'css',
                    'asset' => true,
                     'location' => '//cdn.datatables.net/v/bs/dt-1.10.18/datatables.min.css',
             
                ],

**Comment by Mhongo31** [comment]
my assumption is that it is imported like that
