### ISSUE TITLE
Top Bar user menu

### ISSUE THREAD

**Issue by alsahlawi** [jeroennoten/Laravel-AdminLTE#506]
Dear friend,
First, thanks for the great update, with the new features. Great package and great implementation. 

Sorry this is silly, but I would like to ask about the user menu above. How can I set the lablel/icon for the anchor link? it appears empty, but when you hover with the mouse it is clickable, and it shows the menu. but the span inside has empty string.

Is there a way to set this from the config?

![image](https://user-images.githubusercontent.com/36734055/77246098-06b7d980-6c35-11ea-92ae-0956cafb9928.png)

thanks,
Ahmed

**Comment by JustinRijsdijk** [comment]
Could you share the part for the user menu of the configuration file ?

Also What type of layout are you using?

**Comment by REJack** [comment]
The usermenu label should be your username, it’s not definable by config.

**Comment by alsahlawi** [comment]
> Could you share the part for the user menu of the configuration file ?
> 
> Also What type of layout are you using?

Thanks for replying, these are my configs:

`  
    'usermenu_enabled' => true,
    'usermenu_header' => false,
    'usermenu_header_class' => 'bg-primary',
    'usermenu_image' => false,
    'usermenu_desc' => false,

    'layout_topnav' => null,
    'layout_boxed' => null,
    'layout_fixed_sidebar' => null,
    'layout_fixed_navbar' => null,
    'layout_fixed_footer' => null,
`
Menu:

`
'menu' => [
        
        ['header' => 'Main Menu'],
        [
            'text'        => ' Restaurants',
            'url'         => '#',
            'icon'        => 'fas fa-utensils',
            'label_color' => 'success',
            'roles' => [
                'admin',
            ],
            'submenu' => [
                [
                    'text' => 'Add Restaurant',
                    'route' => 'restaurants.create', 
                    'icon'  => '',
                ],
                [
                    'text' => 'View Restaurants',
                    'route' => 'restaurants.index', 
                    'icon'  => '',  
                ],
            ],
        ],
        [
            'text'        => ' Bookings',
            'url'         => 'admin/pages',
            'icon'        => 'far fa-calendar-alt',
            'label_color' => 'success',
            'submenu' => [
                [
                    'text' => 'Add Booking',
                    'route' => 'tablebookings.create', 
                    'icon'  => '',
                ],
                [
                    'text' => 'View Bookings',
                    'route' => 'tablebookings.index', 
                    'icon'  => '',  
                ],
            ],
        ],
        [
            'text'        => ' Users',
            'url'         => 'admin/pages',
            'icon'        => 'fas fa-users',
            'label_color' => 'success',
            'submenu' => [
                [
                    'text' => 'Add User',
                    'route' => 'users.create', 
                    'icon'  => '',
                ],
                [
                    'text' => 'View Users',
                    'route' => 'users.index', 
                    'icon'  => '',  
                ],
            ],
        ],
        [
            'text' => 'My Profile',
            'route' => 'users.profile', 
            'icon' => 'fas fa-fw fa-user',
        ],
       
        
    ],
`



> The usermenu label should be your username, it’s not definable by config.

This makes sense, but I am using the default Auth for Laravel, with no username. How can I customize what is displayed?

**Comment by REJack** [comment]
Which Laravel Version do you use? V6 oder V7? Laravel's User Class comes with the "name" field and Laravel-AdminLTE use this field.

**Comment by alsahlawi** [comment]
Hey, I am using Laravel 6.

**Comment by alsahlawi** [comment]
> Which Laravel Version do you use? V6 oder V7? Laravel's User Class comes with the "name" field and Laravel-AdminLTE use this field.

Ok. thanks for the hint, I have updated the package with my custom method, as I don't have the 'name' field, and reinstalled the views again :

```
 public function getFullName(){

        return $this->first_name." ".$this->last_name;
 }
```
![image](https://user-images.githubusercontent.com/36734055/77351437-d19faa00-6d4e-11ea-8535-39f86c0ba4cd.png)

Thanks for the hint, if there is a better way to do it please let me know.

**Comment by JustinRijsdijk** [comment]
No, this seems like a good way, I don't see any problems here.

**Comment by alsahlawi** [comment]
Thanks for your reply, case is solved.
