### ISSUE TITLE
404 not found cant make menu work

### ISSUE THREAD

**Issue by ClaudeTheRed** [jeroennoten/Laravel-AdminLTE#507]
I'm having trouble with the Menu items, i don't seem to be able to make them work and point to my blades.
My menu:
'menu' => [
        'CLAUDETE',
          [
            'text'    => 'Administrar Apiarios',
            'icon'    => 'share',
            'submenu' => [
                [
                    'text' => 'Ingresar Apiario Nuevo',
                    'url'  => 'apiario',
                ],
                [
                    'text' => 'AQUI VA REQUERIMIENTO',
                    'url'  => 'colmena',
                ],
            ],
        ],

web.php 

Route::resource('apiario', 'ApiarioController');
Route::resource('colmena','ColmenaController');

controller:

public function index()
    {
        return view('Colmenas.index');
    }

I might be doing things wrong, i'm fairly new to working with laravel, sorry if it seems like a foolish error

**Comment by yaleksandr89** [comment]
![image](https://user-images.githubusercontent.com/44297420/77304622-c6745c00-6d05-11ea-94cc-3f4b31dc0479.png)

**Comment by JustinRijsdijk** [comment]
@yaleksandr89 That is incorrect, he is using resource mapping.

@ClaudeTheRed Could you run `php artisan routes:list` and paste the result?

**Comment by ClaudeTheRed** [comment]
@yaleksandr89 
@JustinRijsdijk 
![rutas](https://user-images.githubusercontent.com/44554072/77319131-0da22300-6ced-11ea-8708-42363819d08a.png)

**Comment by JustinRijsdijk** [comment]
can you show me the contents of `resources/views/`

**Comment by ClaudeTheRed** [comment]
![views](https://user-images.githubusercontent.com/44554072/77319676-00396880-6cee-11ea-9875-a97f7d845eef.png)

**Comment by JustinRijsdijk** [comment]
in your function, you call the foldername with an uppercase C. Please change Colmenas.index to colmenas.index.

**Comment by ClaudeTheRed** [comment]
I did, when i press the button with the 'url' => 'colmena', it goes to "http://localhost/public/colmena" and gives a 404

**Comment by JustinRijsdijk** [comment]
how do you serve the application? `php artisan serve` ? `Wamp` or `Xampp` or?

**Comment by ClaudeTheRed** [comment]
I'm Using docker with a Debian:Buster image

**Comment by JustinRijsdijk** [comment]
In side that I think you have an apache or an nginx server running?

**Comment by ClaudeTheRed** [comment]
Apache2 sorry

**Comment by JustinRijsdijk** [comment]
can you show me your apache configuration?

**Comment by JustinRijsdijk** [comment]
I need the Vhost file, my bad

**Comment by ClaudeTheRed** [comment]
This one?

[Nuevo documento de texto.txt](https://github.com/jeroennoten/Laravel-AdminLTE/files/4369932/Nuevo.documento.de.texto.txt)

**Comment by JustinRijsdijk** [comment]
yes, can you do an `ls` on the folder `/var/www/html`?

**Comment by ClaudeTheRed** [comment]
-rwxrwxrwx 1 1000 staff   1545 Mar 22 12:13 Dockerfile
-rwxrwxrwx 1 1000 staff   4497 Mar 20 14:41 README.md
drwxrwxrwx 1 1000 staff   4096 Mar 20 18:24 app
-rwxrwxrwx 1 1000 staff   1686 Mar 20 14:41 artisan
drwxrwxrwx 1 1000 staff      0 Mar 20 14:41 bootstrap
-rwxrwxrwx 1 1000 staff   1702 Mar 20 16:24 composer.json
-rwxrwxrwx 1 1000 staff 212174 Mar 20 16:26 composer.lock
drwxrwxrwx 1 1000 staff   4096 Mar 20 16:33 config
drwxrwxrwx 1 1000 staff   4096 Mar 20 14:41 database
-rwxrwxrwx 1 1000 staff 456641 Mar 20 14:41 package-lock.json
-rwxrwxrwx 1 1000 staff   1013 Mar 20 14:41 package.json
-rwxrwxrwx 1 1000 staff   1139 Mar 20 14:41 phpunit.xml
drwxrwxrwx 1 1000 staff      0 Mar 20 14:56 public
drwxrwxrwx 1 1000 staff      0 Mar 20 14:41 resources
drwxrwxrwx 1 1000 staff      0 Mar 20 14:41 routes
-rwxrwxrwx 1 1000 staff    563 Mar 20 14:41 server.php
drwxrwxrwx 1 1000 staff      0 Mar 20 14:41 storage
drwxrwxrwx 1 1000 staff      0 Mar 20 14:41 tests
drwxrwxrwx 1 1000 staff   8192 Mar 20 16:26 vendor
-rwxrwxrwx 1 1000 staff    538 Mar 20 14:41 webpack.mix.js

**Comment by JustinRijsdijk** [comment]
Okay, replace the vhost file with this:

`<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/public

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>
`

**Comment by andcarpi** [comment]
I would attempt to modify the menu, replacing the urls to route names
`
[
    'text' => 'Ingresar Apiario Nuevo',
    'route' => 'apiario.index',
],
`

**Comment by ClaudeTheRed** [comment]
I did, now localhost it's on my main page and not in the folder, but it still has the same problem :c 
Still 404 on http://localhost/colmena

**Comment by ClaudeTheRed** [comment]
> I would attempt to modify the menu, replacing the urls to route names
> `[ 'text' => 'Ingresar Apiario Nuevo', 'route' => 'apiario.index', ],`

It didn't work

**Comment by JustinRijsdijk** [comment]
> I did, now localhost it's on my main page and not in the folder, but it still has the same problem :c
> Still 404 on http://localhost/colmena

well, then I wouldn't know it anymore

**Comment by ClaudeTheRed** [comment]
@JustinRijsdijk thank you for trying to help me, i appreciate it, i'll just keep trying, something has to work
