### ISSUE TITLE
ISSUE: Logo is not displayed in the sidebar (top left)

### ISSUE THREAD

**Issue by yaleksandr89** [jeroennoten/Laravel-AdminLTE#508]
Hello.
 I can 't figure out how to fix the logo display error in the left sidebar (where the menu is ).
HTML markup is available
```html
<a href="http://l-blog.loc/limbo/blog" class="brand-link ">
    <img src="http://l-blog.loc/images/circle-logotype.png" alt="logotype Aleksandr Yurchenko" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light ">
        <strong>Limbo</strong>zone
    </span>
</a>
```
![image](https://user-images.githubusercontent.com/44297420/77307837-0c7fee80-6d0b-11ea-90b9-48d938e3dfce.png)
, but it does not appear in the sidebar itself.

**Comment by JustinRijsdijk** [comment]
Did you change it in one of teh views or did you set it inside the configuration file?

**Comment by yaleksandr89** [comment]
> Did you change it in one of teh views

I don 't quite understand. You mean did I extend `@extends('adminlte:: page')`? If Yes, I'm in the `/resources/view/admin/dashboard.blade.php`  and added an example from guides

```
@extends('adminlte::page')

@section('title', __('adminlte::dashboard.title'))

@section('meta_tags')
    <meta name="description" content="{{ __('adminlte::dashboard.description') }}">
    <meta name="keywords" content="{{ __('adminlte::dashboard.keywords') }}">
@endsection

@section('content_header')
    <h1>{{ __('adminlte::dashboard.title' }}</h1>
@stop

@section('content')
    // custom content
@stop
```

**Comment by JustinRijsdijk** [comment]
What i meant was; did you publish the assets, and hardcoded it in the master.blade file, or did you set the url inside config/adminlte.php

**Comment by yaleksandr89** [comment]
`config/adminlte.php` — almost default. in the file I changed only the paths in logo: 
```
'logo' => '<strong>Admin</strong>lte',
    'logo_img' => '/images/circle-logotype.png',
    'logo_img_class' => 'brand-image img-circle elevation-3',
    'logo_img_xl' => null,
    'logo_img_xl_class' => 'brand-image-xs',
    'logo_img_alt' => 'logotype',
```
and configured menu.

> ...and hardcoded it in the master.blade file
No, file `master.blade.php` didn't make any change

**Comment by yaleksandr89** [comment]
It turns out that there is html markup. Paths are displayed correctly ( the image is loaded). But the block itself picture/ image papdis not outputting in top-left  sidebar

**Comment by JustinRijsdijk** [comment]
Hmm, Interesting. I cannot replicate this issue myself...

**Comment by yaleksandr89** [comment]
I noticed an oddity. HTML markup that does not display the logo:

```html
<a href="http://l-blog.loc/limbo/blog" class="brand-link">
            <img src="http://l-blog.loc/images/circle-logotype.png" alt="logotype Aleksandr Yurchenko"
                 class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light ">
            <strong>Limbo</strong>zone
        </span>
</a>
```

but if the delete link `.brand-link` - the logo starts to appear(crooked, but visible). Where else is it used class="brand-link".

maybe it's because of him...

**Comment by yaleksandr89** [comment]
You are using the latest version?

**Comment by JustinRijsdijk** [comment]
I am on the latest version, Laravel 6 and Adminlte 3

**Comment by yaleksandr89** [comment]
strange, performed a clean install of version 6 ( I had 7). The same thing...

![image](https://user-images.githubusercontent.com/44297420/77316606-c5015e80-6d1a-11ea-84e3-ea6fc3e7ed72.png)

**Comment by JustinRijsdijk** [comment]
hmm, strange. It shouldn't be the problem, but what browser are you on?

**Comment by yaleksandr89** [comment]
I'm very surprised myself. I do everything exactly according to the instructions and the problem is only in this moment:/ 

I use chrome Version 80.0.3987.149 and firefox 74.0 (64-bit). OS: ubuntu 18.04.4
problem in all browsers ...

**Comment by yaleksandr89** [comment]
The problem was solved accidentally (when transferring from a local server to hosting).

Google Chrome extension: [AdGuard](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=ru) blocked the output of this block (there was no warning).

So consider this point :)
