### ISSUE TITLE
Error publish Laravel 7

### ISSUE THREAD

**Issue by rmirandadev** [jeroennoten/Laravel-AdminLTE#511]
I installed the Package, but it fails when I try to publish the files. I am using version 7.0. Anyone also with this error?

**Comment by REJack** [comment]
Which command you use to publish the files and whats the error?

**Comment by dewelooper** [comment]
php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\AdminLteServiceProvider" --tag=views
Unable to locate publishable resources.

**Comment by REJack** [comment]
@dewelooper that's the v1/Laravel 5.x command, you need only to run [adminlte:install](https://github.com/jeroennoten/Laravel-AdminLTE#2-installation) like its documented in the readme.
