### ISSUE TITLE
Popper or Tooltip function is not defined

### ISSUE THREAD

**Issue by buddyy93** [jeroennoten/Laravel-AdminLTE#513]
i tried to create tooltip with popper, but it says that popper is not defined

![Snipaste_2020-03-27_11-40-13](https://user-images.githubusercontent.com/22981271/77715764-c931c280-701f-11ea-9ccb-50d3b9cc318a.png)

![Snipaste_2020-03-27_11-40-27](https://user-images.githubusercontent.com/22981271/77715766-c9ca5900-701f-11ea-8657-0e326ad7fa8f.png)

these are the codes i tried
`
var tooltip = new Tooltip(info.el, {
      title: info.event.extendedProps.description,
      placement: 'top',
      trigger: 'hover',
      container: 'body'
    });
`

**Comment by REJack** [comment]
It look like that you run this code before th pooper & bootstrap isn't loaded.

**Comment by tiagofrancafernandes** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/issues/472#issue-555962144
