### ISSUE TITLE
How to use datatables?

### ISSUE THREAD

**Issue by yudhaputra77** [jeroennoten/Laravel-AdminLTE#514]

**Comment by REJack** [comment]
Checkout the docs from Datatables, https://datatables.net/examples/index.

**Comment by honorezemagho** [comment]
With adminlte first of all you have to unlock datatables assets in config/adminlte.php  'plugins' => [
       ```
 [
            'name' => 'Datatables',
            'active' => false,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => false,
                    'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
                ],
                [
                    'type' => 'js',
                    'asset' => false,
                    'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
                ],
                [
                    'type' => 'css',
                    'asset' => false,
                    'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
                ],
            ],
        ],
```

by default asset => false but you have to set it to true like  asset=> true and then you can checkout the  docs from Datatables, https://datatables.net/examples/index.

**Comment by yudhaputra77** [comment]
> With adminlte first of all you have to unlock datatables assets in config/adminlte.php
> By default asset => false but you have to set it to true like asset=> true and then you can checkout the docs from Datatables, https://datatables.net/examples/index.
> 
> By default it's looks like this in config/adminlte.php:
> 'plugins' => [
> ```
> [
> 'name' => 'Datatables',
> 'active' => false,
> 'files' => [
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
> ],
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
> ],
> [
> 'type' => 'css',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
> ],
> ],
> ],
> 
> ```
> 
> But after changing it's will look like this :
>  'plugins' => [
>        ```
>  [
>             'name' => 'Datatables',
>             'active' => true,
>             'files' => [
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
>                 ],
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
>                 ],
>                 [
>                     'type' => 'css',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
>                 ],
>             ],
>         ],
> ```

I was do that, change the plugins and then call the datatables but does'nt work. This my code, I was tried used the datatables like this.

`@extends('adminlte::page')
    @section('content')  
                <div class="right_col" role="main">
                    <div class="">
                        <div class="page-title">
                        <div class="title_left">
                            <h3>Manajemen User</h3>
                        </div>
                        <div class="title_right">
                        </div>
                            </div>
                        </div>
                        @if (session('success'))
                            @alert(['type' => 'success'])
                                {!! session('success') !!}
                            @endalert
                        @endif
                             
                        </div>
                            
                        <div class="card">
                            <div class="card-header">
                            <a href="{{ route('user.create') }}" 
                                 class="btn btn-primary btn-sm">
                                    <i class="fa fa-edit"></i> Tambah Akun
                                    </a>   
                                </div>
                                    
                                    <div class="card-body">
                                        <table id="Datatable" class="table table-bordered table-striped responsive">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Created at</th>
                                            <th>Last Update</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $no = $users->firstItem() ; @endphp
                                        @forelse ($users as $row)
                                        <tr>
                                            <td>{{ $no++ }} </td>
                                            <td>{{ $row->name }} </td>
                                            <td>{{ $row->email }} </td>
                                            <td>{{ $row->created_at }} </td>
                                            <td>{{ $row->updated_at }}</td>
                                            <td>
                                                <form action=" {{ route ('user.destroy', $row->id) }} " method="POST">
                                                @csrf   
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <a href=" {{ route('user.edit', $row->id) }} " class="btn btn-warning btn-xs">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                    <button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7" class="text-center">Tidak ada data</td> 
                                        </tr>
                                        @endforelse
                                    </tbody>
                                    <script>
                                    $(document).ready(function() {
                                        $('Datatable').DataTable();
                                    });
                                    </script>
                                </table>
                            </div>
                        </body>
                            @slot('footer')
                            @endslot
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
`

**Comment by yudhaputra77** [comment]
> With adminlte first of all you have to unlock datatables assets in config/adminlte.php
> By default asset => false but you have to set it to true like asset=> true and then you can checkout the docs from Datatables, https://datatables.net/examples/index.
> 
> By default it's looks like this in config/adminlte.php:
> 'plugins' => [
> ```
> [
> 'name' => 'Datatables',
> 'active' => false,
> 'files' => [
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
> ],
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
> ],
> [
> 'type' => 'css',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
> ],
> ],
> ],
> 
> ```
> 
> But after changing it's will look like this :
>  'plugins' => [
>        ```
>  [
>             'name' => 'Datatables',
>             'active' => true,
>             'files' => [
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
>                 ],
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
>                 ],
>                 [
>                     'type' => 'css',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
>                 ],
>             ],
>         ],
> ```

I was do that, but does'nt work. This my code I try to use the datatables like this, but does'nt work.
![Capture](https://user-images.githubusercontent.com/41959731/77812970-0bbad400-70e0-11ea-9203-c630a33f2703.JPG)

![capture 2](https://user-images.githubusercontent.com/41959731/77812888-70296380-70df-11ea-900e-0eb96b729634.JPG)
![capture 2](https://user-images.githubusercontent.com/41959731/77812965-09f11080-70e0-11ea-9ddd-7a5f5078c178.JPG)

**Comment by yudhaputra77** [comment]
> With adminlte first of all you have to unlock datatables assets in config/adminlte.php
> By default asset => false but you have to set it to true like asset=> true and then you can checkout the docs from Datatables, https://datatables.net/examples/index.
> 
> By default it's looks like this in config/adminlte.php:
> 'plugins' => [
> ```
> [
> 'name' => 'Datatables',
> 'active' => false,
> 'files' => [
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
> ],
> [
> 'type' => 'js',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
> ],
> [
> 'type' => 'css',
> 'asset' => false,
> 'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
> ],
> ],
> ],
> 
> ```
> 
> But after changing it's will look like this :
>  'plugins' => [
>        ```
>  [
>             'name' => 'Datatables',
>             'active' => true,
>             'files' => [
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js',
>                 ],
>                 [
>                     'type' => 'js',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js',
>                 ],
>                 [
>                     'type' => 'css',
>                     'asset' => true,
>                     'location' => '//cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css',
>                 ],
>             ],
>         ],
> ```

I was do that, I got an error "Uncaught ReferenceError: $ is not defined". What should I do?

**Comment by REJack** [comment]
@yudhaputra77  You try to use a jQuery script before you load jQuery.

**Comment by yudhaputra77** [comment]
> @yudhaputra77 You try to use a jQuery script before you load jQuery.

@REJack So, how to solve that? I use the jQuery script on my content section, and I was extended the 'adminlte::page'.

**Comment by REJack** [comment]
You can also place your custom script in the js section like this
```php
@section('js')
    <script> console.log('Hi!'); </script>
@stop
```

**Comment by yudhaputra77** [comment]
> You can also place your custom script in the js section like this
> 
> ```
> @section('js')
>     <script> console.log('Hi!'); </script>
> @stop
> ```

It's works! Thank you so much 👍

**Comment by Jaoponeis** [comment]
depois de ajustar no adminlte os true, o que fazer para ajustar os plugins?
estou endoidando...

**Comment by irfanyazid-13032000** [comment]
i don't know how to solve this bug, i almost cry

**Comment by R1NEJ0** [comment]
> i don't know how to solve this bug, i almost cry

what is your problem?

Thats pretty easy to use.

First of all you have to install plugins with php artisan adminlte:plugins install  --plugin:*whatereveryouwant*

Then you have to activate actions on confing/adminlte

And if you put active plugin you dont need use     @section('plugins.Datatables', true)
    @section('plugins.DatatablesPlugin', true) on each page that you want a table.

And finally you need use config variable to set data and other config stuff, you can check this documentation -> https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables

**Comment by irfanyazid-13032000** [comment]
the javascript is conflicting, it was resolved by removing the javascript default by the LTE admin
