### ISSUE TITLE
How can reduce query.?

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [jeroennoten/Laravel-AdminLTE#515]
![query](https://user-images.githubusercontent.com/48278861/77750194-943c6480-704d-11ea-8829-b91e2d6ac7ab.PNG)

My every comment gets two queries...

**Comment by lacodimizer** [comment]
Thats not an issue by this package, we don't have any queries...

**Comment by ShekhSaifuddin007** [comment]
![query2](https://user-images.githubusercontent.com/48278861/77750800-a36fe200-704e-11ea-837f-73212fb8dd9c.PNG)


Then where it's come from.?

**Comment by lacodimizer** [comment]
from your app logic, we don't know it ;)
