### ISSUE TITLE
Where are the auth controllers?

### ISSUE THREAD

**Issue by kejojedi** [jeroennoten/Laravel-AdminLTE#517]
I have required `laravel/ui` and ran `php artisan adminlte:install --type=full` but it does not appear to have created the auth controllers.

What am I missing? Do I need to run `php artisan ui bootstrap --auth` first?

**Comment by REJack** [comment]
`adminlte:install` never created the auth controllers, in Laravel 6 it was created by default only since Laravel 7 you need to run `php artisan ui:controllers` after or before `php artisan adminlte:install --type=full`.

**Comment by REJack** [comment]
@lacodimizer We need a info for this in the readme 😄

**Comment by REJack** [comment]
@lacodimizer You can close it, since you merged my last PR 😄

**Comment by bareyes-anc** [comment]
Please add this in the read files.
I spent a whole day looking for the controllers xD

**Comment by Shidersz** [comment]
@bareyes-anc the **step 3** of the [Installation Guide](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation) mention how to install the `laravel/ui` authentication scaffolding. If you suggest how we should modify it, I will add it to the documentation later...

However, note that laravel offers multiple authentication scaffolding and the controllers may not be all on the same place.
