### ISSUE TITLE
Failed to load resource: vendor/icheck-bootstrap/icheck-bootstrap.min.css

### ISSUE THREAD

**Issue by CrazyFreeMan** [jeroennoten/Laravel-AdminLTE#518]
https://github.com/jeroennoten/Laravel-AdminLTE/blob/c26da685dbab426162bd921a9b6813dba74b9d82/resources/views/login.blade.php#L4

Asset not found in published files (from old version, maybe legacy)

**Comment by REJack** [comment]
You need to publish this resource with the `adminlte:plugins` command like this `php artisan adminlte:plugins install --plugin=icheckBootstrap`
