### ISSUE TITLE
How to create new data attributes in menu item?

### ISSUE THREAD

**Issue by fhariano** [jeroennoten/Laravel-AdminLTE#519]
Creating a new data-attribute in menu item to use in my controls.

Example:

['header' => 'account_settings'],
[
	'text' => 'profile',
	'url'  => 'admin/settings',
	'icon' => 'fas fa-fw fa-user',
	**'my-data' => 'new-data-attribute'**
],

**Comment by REJack** [comment]
There is actually no way to add custom data attributes.

**Comment by fhariano** [comment]
I am altering the menu-item.blade.php file to this.
But, the better would be on config file of adminlte.

**Comment by dubinfo** [comment]
> There is actually no way to add custom data attributes.

I don't understand, no possible to add input or change menu ?  Thank you

**Comment by lacodimizer** [comment]
@REJack we can add this as a new feature to the menu 👍

**Comment by REJack** [comment]
@lacodimizer sure :D assign me on it, I'll create a PR for it and may other issues too.

**Comment by REJack** [comment]
@lacodimizer I wait until #558 is merged and then I implement my prebuild code 😄.

I build a Menu Filter called DataFilter and it generate from this code
```php
[
    'text'        => 'pages',
    'url'         => 'admin/pages',
    'icon'        => 'far fa-fw fa-file',
    'label'       => 4,
    'label_color' => 'success',
    'data'        => [
        'test' => 'tesa',
        'fest' => 'fesa',
    ],
],
```

this data tags 😄 
```html
data-test="tesa" data-fest="fesa"
```

**Comment by lacodimizer** [comment]
@REJack done. :D
