### ISSUE TITLE
Issue with adminlte.php config file

### ISSUE THREAD

**Issue by sachinwng** [jeroennoten/Laravel-AdminLTE#52]
Anything I am updating in adminlte.php config file I am not able to see the changes. What are the possible reasons

**Comment by jeroennoten** [comment]
Maybe you have the config cached? Try running `php artisan config:clear`.

If that does not help, can you be more specific? What exactly did you change and what did you expect to see?

**Comment by sachinwng** [comment]
Thanks it worked this time, I tried this before but it was not working. Actually i was just trying to change the color of theme

**Comment by grab95** [comment]
hi i have the same problem , config:clear don't work .

**Comment by lacodimizer** [comment]
@grab95 please write on the open issue #601 .
