### ISSUE TITLE
Copy / Paste is not a same look

### ISSUE THREAD

**Issue by flemzord** [jeroennoten/Laravel-AdminLTE#522]
Hello,
https://adminlte.io/themes/AdminLTE/index2.html
Why when we copy / paste blocks from the theme site, we do not have the same behavior at all?
It lacks background-color etc
Regards,
Maxence

**Comment by REJack** [comment]
Which Laravel-AdminLTE version you use?

**Comment by flemzord** [comment]
I use v3.1.1 cc @REJack

**Comment by REJack** [comment]
Then you try the wrong theme demo, (https://adminlte.io/themes/AdminLTE/) is for v2.4 you need to look over (https://adminlte.io/themes/v3).

**Comment by flemzord** [comment]
Thanks you so much !
