### ISSUE TITLE
Undefined variable adminlte, after publish view

### ISSUE THREAD

**Issue by Alfian5229** [jeroennoten/Laravel-AdminLTE#523]
i need full control over the provided views, so im doing this

`php artisan adminlte:install --only=main_views
`

but i got an error `undefined variable: adminlte` in page.blade.php when i open dashboard.blade.php

![Screenshot_20200409_132018](https://user-images.githubusercontent.com/28615224/78863946-e83f4400-7a64-11ea-9cf3-eca2a9cf28c0.png)

this is my dasboard.blade.php
```
@extends('vendor.adminlte.page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop
```

**Comment by REJack** [comment]
Your extend should look like this `@extends('adminlte::page')`, if this not works you have may disabled the Auto-Discovery feature from Laravel.

**Comment by Alfian5229** [comment]
so if i use that, i cannot use my custom page?

**Comment by REJack** [comment]
Oh the error comes from your custom page, it would be helpful to see the content of the custom page instead of your dashboard page.

**Comment by Alfian5229** [comment]
ah nevermind, i got an idea how to handle this, thanks

**Comment by gdias1992** [comment]
How did you solve this ? 

I am facing the same problem.

I create a copy of page.blade.php with no changes in the content but i am not able to extend this new view.
