### ISSUE TITLE
Can't modify path of mix compiled css/js

### ISSUE THREAD

**Issue by mrshoikot** [jeroennoten/Laravel-AdminLTE#525]
I'm compiling my assets using laravel mix. But, instead of putting my compiled code in "public/js" or "public/css", I'm trying to put them in something like "public/assets/admin/{css, js}".

But, I can't find any option in the config to do that. The only way I can do it now is to do the modification in "vendor\jeroennoten\laravel-adminlte\resources\views\master.blade.php".

Need a better way to do it. Something like having an option for mix asset location in the config would be great.

**Comment by lacodimizer** [comment]
Can you tell me please, why this change is necessary?

**Comment by mrshoikot** [comment]
Actually, I am working on an app where I'm trying to build the admin area using AdminLTE and the main app using different front-end. So, I'm using separated assets for the two parts and stored them inside resources/assets/admin and resources/assets/app. But, I'm not being able to point to the resources/assets/admin directory for laravel mix assets as there is no option to do that in the config.

So, I think it'd be helpful for this kind of case if there is an option in the config where the directory for mix assets can be modified.

Thank you.

**Comment by Shidersz** [comment]
@mrshoikot Can you describe exactly what changes you did to the `master.blade.php` to get it work on you local project? So, I can confirm the planed modifications are in a good direction.

**Comment by mrshoikot** [comment]
@Shidersz 

I've changed

`<link rel="stylesheet" href="{{ mix('css/app.css') }}">`
to
`<link rel="stylesheet" href="{{ mix('assets/admin/css/app.css') }}">`

and

`<script src="{{ mix('js/app.js') }}"></script>`
to
`<script src="{{ mix('assets/admin/js/app.js') }}"></script>`

I'm just expecting an option to modify the path of mix generated css and js files in the config.

**Comment by Shidersz** [comment]
@mrshoikot Thanks you, and all those paths are relative to the `public` folder right?

**Comment by mrshoikot** [comment]
@Shidersz 
Yup. all paths are relative to the public folder.
And, the PR looks fine for me. Thank you very much.
