### ISSUE TITLE
Active submenu not working

### ISSUE THREAD

**Issue by pooriamo** [jeroennoten/Laravel-AdminLTE#526]
Hi

This is my config:

```
'menu' => [
        [
            'text'        => 'Settings',
            'icon'        => 'fa fa-cog',
            'submenu'   => [
                [
                    'text'        => 'General',
                    'route'         => 'settings/general',
                    'active'      => ['settings/general']
                ]
            ]
        ],
]
```

But when I click on it, the parent menu is closed and also the item itself has no active class.

**Comment by REJack** [comment]
Try to remove the active atribute, it's only needed if your use a wildcard for active states.

**Comment by pooriamo** [comment]
@REJack I added it later to test if it's its fault. It also doesn't work without it.

**Comment by lacodimizer** [comment]
Please try this one:

```
'menu' => [
        [
            'text'        => 'Settings',
            'icon'        => 'fa fa-cog',
            'active'        => ['settings/*'],
            'submenu'   => [
                [
                    'text'        => 'General',
                    'route'         => 'settings/general',
                    'active'      => ['settings/general']
                ]
            ]
        ],
]
```

**Comment by pooriamo** [comment]
@lacodimizer Thanks but it still doesn't work.

**Comment by lacodimizer** [comment]
@pooriamo I will check this.

**Comment by lacodimizer** [comment]
It works on my dev env. 
Please provide us with the following infos:
* Which Laravel version is used?
* Which release of this project is used?
* Did you install the views of this project?

**Comment by lacodimizer** [comment]
@pooriamo  can you test the changes in the linked pr please?

**Comment by pooriamo** [comment]
@lacodimizer I'm sorry that I'm responding late. I tested it but It doesn't work.

I'm using Laravel 7.1.0 and version ^3.1 of this package

**Comment by lacodimizer** [comment]
@pooriamo the changes are only in master branch. A release will be available in the next days.

**Comment by pooriamo** [comment]
@lacodimizer I copied the changes to `ActiveChecker.php` manually. But didn't work.

**Comment by lacodimizer** [comment]
@pooriamo I‘m confused, I have test your example. Before this fix, it doesn‘t work and with the fix, it works now...

**Comment by pooriamo** [comment]
@lacodimizer I checked the code and I can see that `$this->request->fullUrl()` is returning the current url with additional redundant query string.

in `checkPattern()`:

This is the actual url:
`/settings/general`

This is what `$this->request->fullUrl()` returns:
`/settings/general?%2Fsettings%2Fgeneral=`

So they don't match

**Comment by pooriamo** [comment]
@lacodimizer I manually changed `fullUrl()` to `url()` in the source code and it's working now.
Why should we check query strings to make sure the link is active, isn't the path enough?

P.S.: I still don't know why the path is being added to `$_SESSION['QUERY_STRING']`

**Comment by lacodimizer** [comment]
@pooriamo crazy... can you send me the route setting of this route from your web.php route config? But we should check, that urls with parameters work too with a valid active state. I will check this and will fix the issue.

**Comment by pooriamo** [comment]
@lacodimizer It's a resource. 
`Route::resource('settings/general', '\App\Http\Controllers\Admin\SettingsController');`

**Comment by REJack** [comment]
https://github.com/jeroennoten/Laravel-AdminLTE/blob/28008baf94f9be387fd134003f2b5cf589bf0dde/src/Menu/ActiveChecker.php#L47

@lacodimizer we could change the line to the following code lines 😄 

```php
        $fullUrlArray = explode('?', $this->request->fullUrl());
        $fullUrl = $fullUrlArray[0];
```

With this change we would get avoid of the query string limitation and it should close this issue too.

**Comment by pooriamo** [comment]
@REJack Why not just use laravel's `url()` method instead?

As said in [docs](https://laravel.com/docs/7.x/requests#request-path-and-method):
> To retrieve the full URL for the incoming request you may use the url or fullUrl methods. The url method will return the URL without the query string, while the fullUrl method includes the query string

**Comment by REJack** [comment]
Oh yeah that's a good way too :P I didn't checked the docs 🤦‍♂️

**Comment by lacodimizer** [comment]
@pooriamo PR is related to this issue.
