### ISSUE TITLE
Right sidebar does not stick to end of page

### ISSUE THREAD

**Issue by Busuzima** [jeroennoten/Laravel-AdminLTE#527]
Hi,

i've made a fresh installation from this repo and i'm trying to get the right sidebar as it was in adminlte2, i've set adminlte.php
`    'right_sidebar' => true,
    'right_sidebar_icon' => 'fas fa-cogs',
    'right_sidebar_theme' => 'dark',
    'right_sidebar_slide' => true,
    'right_sidebar_push' => false,
    'right_sidebar_scrollbar_theme' => 'os-theme-light',
    'right_sidebar_scrollbar_auto_hide' => 'l',`

put this code as mentioned here https://adminlte.io/docs/3.0/components/control-sidebar.html into right-sidebar section, but it does not stick to the end of the page even if there is no footer, can someone please give me some hints? 

![rightsidebar](https://user-images.githubusercontent.com/35733232/79273286-0a8cf380-7ea3-11ea-8863-89b05de26afd.JPG)

p.s. how can i get the tabs in the right sidebar old adminlte2 code seems to not work anymore

**Comment by REJack** [comment]
I would guess you don't use the footer, as workaround you can use set `layout_fixed_sidebar` to `true`.

**Comment by Busuzima** [comment]
yes i don't use the footer i've tried just now and seems to work fine for now, thanks
