### ISSUE TITLE
$event->menu->addIn() generates Undefined index: text (View: .../resources/views/partials/menu-item.blade.php)

### ISSUE THREAD

**Issue by peyobr** [jeroennoten/Laravel-AdminLTE#536]
Facade\Ignition\Exceptions\ViewException when i try to add a submenu via ServiceProvider. Below is my code.

    public function boot(Dispatcher $events)
    {
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add(
                ['key' => 'profile', 'icon' => 'fas fa-home', 'text' => __('profilo'), 'url' => 'sso', 'icon_color' => 'blue'],
                ['key' => 'passport', 'icon' => 'fas fa-key', 'text' => __('passport'), 'url' => 'sso/passport', 'can' => 'a3-perform', 'model' => 'a3-auditing-system-audit'],
                ['key' => 'users', 'icon' => 'fas fa-users-cog', 'text' => __('utenti'), 'url' => 'sso/utenti', 'can' => 'index', 'model' => Utente::class],
                ['key' => 'subnets', 'icon' => 'fas fa-network-wired', 'text' => __('subnets'), 'url' => 'sso/subnets', 'can' => 'index', 'model' => Subnet::class],
                ['key' => 'events', 'icon' => 'fas fa-calendar-check', 'text' => __('eventi'), 'url' => 'sso/eventi', 'can' => 'index', 'model' => Evento::class],
                ['key' => 'translations', 'icon' => 'fas fa-globe-europe', 'text' => __('traduzioni'), 'url' => 'sso/languages', 'can' => 'a3-perform', 'model' => 'a3-translation-update'],
                ['key' => 'auditing', 'icon' => 'fas fa-stream', 'text' => __('auditing'), 'url' => 'sso/ulogs', 'can' => 'a3-perform', 'model' => 'a3-auditing-system-audit']
            );
            $event->menu->addIn('events', [
                'key' => 'guests', 'icon' => 'fas fa-user-friends', 'text' => __('ospiti'), 'url' => 'sso/ospiti', 'can' => 'index', 'model' => Ospite::class
            ]);
        });
    }

**Comment by lacodimizer** [comment]
In master is a change to blade template. I will revert this change. I prefer to don‘t use the master branch...
