### ISSUE TITLE
Unable to publish views.

### ISSUE THREAD

**Issue by Nardusgc** [jeroennoten/Laravel-AdminLTE#537]
Hi, 

When running ```php artisan adminlte:install --force``` everything runs successfully 
```Basic Assets Installation complete.
Configuration Files installed successfully.
Translation files installed successfully.
AdminLTE Installation complete.
```

But I cannot find how to publish the views?

**Comment by REJack** [comment]
To publish the package views you need to add `--with=main_views`  or run seperatly `php artisan adminlte:install --only=main_views`.

**Comment by Nardusgc** [comment]
@REJack apologies I just saw this under ```Customize views``` section. Thanks you for the quick response.
