### ISSUE TITLE
Skin colours

### ISSUE THREAD

**Issue by abacram** [jeroennoten/Laravel-AdminLTE#54]
Hi, I really appreciate your work. 
I'm trying to change the skin colours, but when I change and set 'skin' => 'purple' into my adminlte.php config file, it doesn't work. In fact, in my login page where i have your code: @extends('adminlte::login'), it remains the blue for the buttons and links, directly from AdminLTE.min.css.
Can you help me?

Thanks, 

Antonio

**Comment by jeroennoten** [comment]
Unfortunately, the AdminLTE login screen is not affected by the skin settings, I am not going to change this, because it is determined by the original AdminLTE.

**Comment by abacram** [comment]
I suspected this because later, i saw the skin css imported in page.blade, but not in master.blade.
I really appreciate your help and time jeroennoten. Thanks!

**Comment by jeroennoten** [comment]
No problem, you're welcome!
