### ISSUE TITLE
QUESTION: how can adminlte_image in User model use variable?

### ISSUE THREAD

**Issue by schonhose** [jeroennoten/Laravel-AdminLTE#542]
According to the documentation we need to add a static function called `adminlte_image` to provide a user defined image.

However, my image url is located at `$user->avatar` in which `$user` contains information about the current logged in user. How can I access this variable in the model (or override the static function somewhere where I can access this variable)?

**Comment by lacodimizer** [comment]
You can add methods into the user model, like the following:

App\User class:
```php
class User extends Authenticatable
{
    …

    public static function adminlte_image()
    {
        return 'https://picsum.photos/300/300';
    }

    public static function adminlte_desc()
    {
        return 'That\'s a nice guy';
    }
}
```

More details on the PR desc:
https://github.com/jeroennoten/Laravel-AdminLTE/pull/477

**Comment by schonhose** [comment]
Yes, I know. But in the App\User class I don't have access to the variable `$user` which contains my user image.

For example, I use Gravatar, which uses my email address. The email address for every user is different. Hence I need to inject some variable in the `adminlte_image` function to get the correct image.

**Comment by schonhose** [comment]
@REJack Yes, I do. Only for eloquent models. I have never added functions to a model, let alone trying to pass variables to them.

**Comment by lacodimizer** [comment]
@schonhose that's total easy in eloquent model, to add functions. In this way, you can create a string with model data. In your usecase, you can create the gravatar link in this method with the exact email of a user. 

You can try this one for example:

```php
class User extends Authenticatable
{
    …

    public function adminlte_image()
    {
        $gravatarEmail = md5( strtolower( trim( $this->email ) ) );
        return 'https://www.gravatar.com/avatar/'.$gravatarEmail.'?s=200';
    }
}
```

Within the methods (i have changed it to non static function), you can work with $this and all the columns of your model what you want.

@REJack With static functions, we can not work with model data. I will update the readme for that.
