### ISSUE TITLE
QUESTION: How to show submenu active when url is not listed in submenu items?

### ISSUE THREAD

**Issue by schonhose** [jeroennoten/Laravel-AdminLTE#546]
So, I have read https://github.com/jeroennoten/Laravel-AdminLTE#6114-active-menu%E2%80%93items but I have got some questions about the active items.

Say I have the following menu structure:

```
main menu
|- submenu
    |- sub item 1 => url: /sub/item1
    |- sub item 2 => url: /sub/item2
```
This is defined using the following basic array:

```
[
    [
        'text'    => 'main menu',
        'submenu' => [
            [
                'text'    => 'sub menu',
                'submenu' => [
                    [
                        'text' => 'sub item 1',
                        'url'  => 'sub/item1',
                    ],
                    [
                        'text' => 'sub item 2',
                        'url'  => 'sub/item2',
                    ],
                ],
            ],
        ],
    ],
]
```

So when I head to `/sub/item1` I get to see items main, submenu and sub item 1 as active. So far so good, and no additional `active` statements are needed. But now I have an url `/sub/not_in_the_list`. Nothing is active at this point.

However, I want to make at least main and submenu active, since the url is related to this part (although not related to the items in the sub menu). After reading the docs I figured I had to use an `active` statement for the sub menu as shown below.

```
[
    [
        'text'    => 'main menu',
        'submenu' => [
            [
                'text'    => 'sub menu',
                'active'    => ['sub/*'],
                'submenu' => [
                    [
                        'text' => 'sub item 1',
                        'url'  => 'sub/item1',
                    ],
                    [
                        'text' => 'sub item 2',
                        'url'  => 'sub/item2',
                    ],
                ],
            ],
        ],
    ],
]
```
By setting `'active'    => ['sub/*'],` I figured that the sub menu will become active with any url starting with `sub`. Alas, no dice.

What I am doing wrong or what am I missing here?

**Comment by lacodimizer** [comment]
@schonhose I will check this. related to #526

**Comment by schonhose** [comment]
@lacodimizer Thanks, please find the answers to your questions below.

**Which Laravel version is used?** Laravel Framework 6.18.8
**Which release of this project is used?** dev-master from Github, last commit: https://github.com/jeroennoten/Laravel-AdminLTE/commit/eb9e1399765272d008d1b8b02f201cc4c7b32328
**Did you install the views of this project?** Yes. and I made sure they matched the versions on the latest commit by going over them one by one using Winmerge.

**Comment by lacodimizer** [comment]
@schonhose can you test the changes in the linked pr please?

**Comment by schonhose** [comment]
@lacodimizer https://github.com/jeroennoten/Laravel-AdminLTE/pull/547#issuecomment-617567851
