### ISSUE TITLE
Class 'JeroenNoten\LaravelAdminLte\ServiceProvider' not found

### ISSUE THREAD

**Issue by senthu1994** [jeroennoten/Laravel-AdminLTE#548]
When i upgrade `laravel 5.8 to ^6.0`. According to the requirement i upgrade `jeroennoten/laravel-adminlte ^1.23 to ^2.0`. But after upgrade i got Class `'JeroenNoten\LaravelAdminLte\ServiceProvider' `not found error how to solve this?

**Comment by REJack** [comment]
It was renamed to AdminlteServiceProvider

**Comment by senthu1994** [comment]
> It was renamed to AdminlteServiceProvider

How? Where?

**Comment by senthu1994** [comment]
I rename `JeroenNoten\LaravelAdminLte\ServiceProvider::class` to `JeroenNoten\LaravelAdminLte\AdminLteServiceProvider::class` . But now also i got same error `JeroenNoten\LaravelAdminLte\ServiceProvider` . Please anyone help me. Thanks.

**Comment by lacodimizer** [comment]
@senthu1994 The versions are updated in the composer file and composer update was called, correct?
With Laravel 5.5, it used plugin discovery, so you can delete the line in config/app.php.

**Comment by senthu1994** [comment]
> @senthu1994 The versions are updated in the composer file and composer update was called, correct?
> With Laravel 5.5, it used plugin discovery, so you can delete the line in config/app.php.

Yes versions are correct. I am not using laravel 5.5. I upgrade laravel 5.8 to 6.0.

**Comment by lacodimizer** [comment]
> Yes versions are correct. I am not using laravel 5.5. I upgrade laravel 5.8 to 6.0.

I mean, the manual adding of an package in the config/app.php is not needed since Laravel 5.5 and higher. Please remove this line in the config/app.php and try it again.

A other idea is, something can be wrong with the cache on our system. The JeroenNoten\LaravelAdminLte\ServiceProvider exists with package v2.x anymore. So you can try run composer clearcache.

**Comment by lacodimizer** [comment]
@senthu1994 is the issue solved?

**Comment by senthu1994** [comment]
> > Yes versions are correct. I am not using laravel 5.5. I upgrade laravel 5.8 to 6.0.
> 
> I mean, the manual adding of an package in the config/app.php is not needed since Laravel 5.5 and higher. Please remove this line in the config/app.php and try it again.
> 
> A other idea is, something can be wrong with the cache on our system. The JeroenNoten\LaravelAdminLte\ServiceProvider exists with package v2.x anymore. So you can try run composer clearcache.

Yes exactly cache is the problem I solved. Thanks

**Comment by senthu1994** [comment]
> @senthu1994 is the issue solved?

Solved thanks
