### ISSUE TITLE
usermenu_image and usermenu_desc from database

### ISSUE THREAD

**Issue by eraporsmk** [jeroennoten/Laravel-AdminLTE#553]
how to use usermenu_image form field photo in users table, and use usermenu_desc from user role?

**Comment by lacodimizer** [comment]
@eraporsmk could it help you with this? https://github.com/jeroennoten/Laravel-AdminLTE/issues/542

**Comment by REJack** [comment]
You can extend your App\User like the code below.

```php
class User extends Authenticatable
{
    …

    public function adminlte_image()
    {
        return $this->photo; //photo can be replaced with any other field name
    }
}
```

**Comment by eraporsmk** [comment]
error: Using $this when not in object context (View: C:\xampp\myapp\resources\views\vendor\adminlte\page.blade.php)

**Comment by REJack** [comment]
@eraporsmk Where you added the code?

**Comment by eraporsmk** [comment]
the code
![the-code](https://user-images.githubusercontent.com/53444184/80125891-7f0b1500-85bc-11ea-9f36-37503ad9d74c.jpg)

**Comment by eraporsmk** [comment]
the field
![the-field](https://user-images.githubusercontent.com/53444184/80126053-bb3e7580-85bc-11ea-9325-91ec9223c7e1.jpg)

**Comment by lacodimizer** [comment]
@eraporsmk I have changed the readme for this error. The methods should not be a static function, so you have to change it from "public static function adminlte_image" to "public function adminlte_image". And then it works. :)

**Comment by eraporsmk** [comment]
@lacodimizer Thank you very much, its work!

**Comment by lacodimizer** [comment]
great!

**Comment by aledc7** [comment]
in my case this works well on Laravel 8 and Adminlte3


<img width="1106" alt="Screen Shot 2020-11-18 at 15 40 05" src="https://user-images.githubusercontent.com/29775143/99573055-59a88300-29b4-11eb-8296-4079714638b3.png">
