### ISSUE TITLE
Assign Multiple Gates to 'can' field in sidebar menu

### ISSUE THREAD

**Issue by hkpanchani** [jeroennoten/Laravel-AdminLTE#554]
I tried something like this didnt work out is there any other way?

'menu' => [
        // For central_admin, super_admin
        [
            'text' => 'Dashboard',
            'url' => '#',
            'icon' => 'fas fa-fw fa-file',
            'can'=> ['admin','user']
        ],
]

**Comment by hkpanchani** [comment]
Issue already there at #98

**Comment by lacodimizer** [comment]
@hkpanchani you can check the related pr for this improvment.

**Comment by hkpanchani** [comment]
I don't have src/Menu/Filters/GateFilter.php in my project how to proceed can you please explain?

**Comment by lacodimizer** [comment]
@hkpanchani you can find the file in the your laravel project in this path:
./vendor/jeroennoten/laravel-adminlte/src/Menu/Filters/GateFilter.php
