### ISSUE TITLE
Add profile_url dynamically

### ISSUE THREAD

**Issue by hkpanchani** [jeroennoten/Laravel-AdminLTE#560]
As i have role based redirection i would like to redirect profile link to different URL based on role so how to pass profile_ url dynamically in usermenu

**Comment by lacodimizer** [comment]
@hkpanchani let me check that, but good idea!

**Comment by REJack** [comment]
You can pass it with the `config()`-function via a middleman.

**Comment by hkpanchani** [comment]
How can you pass the function can you plase help me out?? And what is middleman?

**Comment by REJack** [comment]
In this example I override AdminLTE's Logo text to `AdminLTE CMS` with this simple code: `config(['adminlte.logo' => 'AdminLTE CMS']);`, you can place this line in any active ServiceProvider, Middleware (not Middleman 🤦‍♂️)  or Controller.

Here my example AppServiceProvider content.

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        config(['adminlte.logo' => 'AdminLTE CMS']);
    }
}
```

**Comment by hkpanchani** [comment]
Not working I tried it in LoginController to override but it isn't working.
Tried in Middleware but in middleware user is not authenticated and there for unable to fetch role of authenticated use
