### ISSUE TITLE
Not supporting multiple auth guards

### ISSUE THREAD

**Issue by tanmay27vats** [jeroennoten/Laravel-AdminLTE#562]
I am using multiple auth guard (User & Admin) on my website. `adminlte::page` has `Auth::user()`, `Auth::user()->adminlte_image()`, etc. This is working fine for my User auth guard but not for Admin auth guard since both table are different. I tried to copy `adminlte::page` to my view but it throws. 

`Facade\Ignition\Exceptions\ViewException
Undefined variable: adminlte (View: /resources/views/admin/page.blade.php)`

Please suggest me what should I do?

**Comment by lacodimizer** [comment]
@tanmay27vats can you please post the content of your admin/page.blade.php?
