### ISSUE TITLE
Sidebar not full

### ISSUE THREAD

**Issue by eraporsmk** [jeroennoten/Laravel-AdminLTE#567]
if the content is small, the sidebar is not full

![adminlte](https://user-images.githubusercontent.com/53444184/80481839-68c6d580-897d-11ea-99a5-e027eeb45b6d.png)

**Comment by REJack** [comment]
That's a bug from AdminLTE itself and will fixed with the next release (v3.0.5).

**Comment by REJack** [comment]
I've published a new version of AdminLTE with this bug fixed, you can simply update it via composer and then run `php artisan adminlte:update`.

**Comment by Shidersz** [comment]
@REJack After follow updating procedure, I can confirm that bug is fixed (at least on my local environment). However, I have noted that the **user menu** or any **dropdown menu** on the navbar don't work when `boxed_layout` option is enabled (I really don't know if this previously existed).
