### ISSUE TITLE
Problem with Custom Filter

### ISSUE THREAD

**Issue by darylgeyerii** [jeroennoten/Laravel-AdminLTE#57]
I noticed an issue with the custom filter syntax not being correct with the Laratrust module.

```
<?php

namespace MyApp;

use JeroenNoten\LaravelAdminLte\Menu\Builder;
use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
use Laratrust;

class MyMenuFilter implements FilterInterface
{
    public function transform($item, Builder $builder)
    {
        if (isset($item['permission'] && Laratrust::can($item['permission'])) {
            return false;
        }

        if (isset($item['header'])) {
            $item = $item['header'];
        }

        return $item;
    }
}
```

needs to be

```
<?php

namespace MyApp;

use JeroenNoten\LaravelAdminLte\Menu\Builder;
use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
use Laratrust;

class MyMenuFilter implements FilterInterface
{
    public function transform($item, Builder $builder)
    {
        if (isset($item['permission']) && !Laratrust::can($item['permission'])) {
            return false;
        }

        if (isset($item['header'])) {
            $item = $item['header'];
        }

        return $item;
    }
}
```

**Comment by jeroennoten** [comment]
You're right. Fixed.

Thanks! 👍

**Comment by darylgeyerii** [comment]
Don't forget the right parentheses after the first isset as described in
three ticket.

Daryl

**Comment by jeroennoten** [comment]
Thanks ;-)

**Comment by eniumcriacaodesites** [comment]
Would you kindly help me to implement with https://github.com/Zizaco/entrust

**Comment by sadhan47** [comment]
Pls help me to implement with jeroennoen laravel roles.

**Comment by dewimah** [comment]
help me to implement with jeroannoten auth guard

**Comment by dewimah** [comment]
Thank You , Sir

Jum, 13 Jan 2023 pukul 19.45 Roberto Lyra ***@***.***>
menulis:

**Comment by robertolyra** [comment]
After implementing Spatie with Admin Lte it seems that it also works by seeting up the adminlte.php with ( I am still testing it) : 

[
            'text' => 'blog2',
            'url'  => 'admin/blog',
            'role'  => 'writer',
        ],

it is important that the User model is defined with the spatie trait HasRoles

_____________________________________________________________

**Comment by robertolyra** [comment]
Best solution I could find so far is to adjust the EventServiceProvider.php (Note that the hasRole is from the Spatie package)

public function boot()
    {
        Event::listen(BuildingMenu::class, function (BuildingMenu $event) {
            // Add some items to the menu...
            $event->menu->add('MAIN NAVIGATION');
            if(Auth::user()->hasRole('admin'))
            {
                $event->menu->add([
                    'text' => 'Blog',
                    'url' => 'admin/blog',
                ]);
            }

        });
    }
