### ISSUE TITLE
Profile Link override not working I tried it in LoginController to override but it isn't working.

### ISSUE THREAD

**Issue by hkpanchani** [jeroennoten/Laravel-AdminLTE#570]
Not working I tried it in LoginController to override but it isn't working.
Tried in Middleware but in middleware user is not authenticated and there for unable to fetch role of authenticated use

_Originally posted by @hkpanchani in https://github.com/jeroennoten/Laravel-AdminLTE/issues/560#issuecomment-620744027_

**Comment by REJack** [comment]
If you override it via the LoginController, then the override is only while you are on the LoginController. You should override it in the "Controller"-Controller.

But you not need to override the profile_url, you can set one generic profile url (like /user/profile) and add the user id through the routes.

**Comment by hkpanchani** [comment]
There is a situation where each users type role has its own resource methods and their different views so need to override profile_url..

I tried it in constructor of "controller" didn't work out..

Here is the code i tried..

public function __construct(){
        if(Auth::check()){
            switch(Auth::user()->role){
                case 1:
                    config(['adminlte.profile_url' => 'super/profile']);
                    break;
                case 2:
                    config(['adminlte.profile_url' => 'tpo/profile']);
                    break;
                case 3:
                    config(['adminlte.profile_url' => 'admin/profile']);
                    break;
                case 4:
                    config(['adminlte.profile_url' => 'student/profile']);
                    break;
                default:
                    config(['adminlte.profile_url' => 'profile']);
                    break;
            }
        }
    }

**Comment by lacodimizer** [comment]
@REJack I think we should generate a method for the profile url like the methods for profile image or profile desc.

**Comment by REJack** [comment]
Yeah this would be a good method too.

**Comment by lacodimizer** [comment]
@REJack I have opened the linked PR for that issue :) Can you test it please?
