### ISSUE TITLE
QUESTION: Mobile view on top nav seems to be broken. 

### ISSUE THREAD

**Issue by Nardusgc** [jeroennoten/Laravel-AdminLTE#572]
Hi, 

The mobile view when on top_nav = true seems to be broken when using topnav_right = true? Or I might be missing some config? 
![Selection_010](https://user-images.githubusercontent.com/3862600/80860431-d9187400-8c67-11ea-9513-f77cd6b7fc75.png)

**Comment by Shidersz** [comment]
I'm not really sure what is your problem, but if you are expecting that the links with the configuration attribute `topnav_right=true` get collapsed into the dropdown menu, that will not happen. Actually, only **topnav left** links gets collapsed into the dropdown menu.

**Comment by lacodimizer** [comment]
Closed. No new response.
