### ISSUE TITLE
Argument 1 passed to JeroenNoten\LaravelAdminLte\AdminLte::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by ddubois2** [jeroennoten/Laravel-AdminLTE#576]
Hi,

I'm under Laravel 7.9.2 and I would like to user AdminLTE 3.

I have this error :

> Facade\Ignition\Exceptions\ViewException
Argument 1 passed to JeroenNoten\LaravelAdminLte\AdminLte::__construct() must be of the type array, null given, called in /Applications/MAMP/htdocs/hedrinenew/vendor/jeroennoten/laravel-adminlte/src/AdminLteServiceProvider.php on line 23 (View: /Applications/MAMP/htdocs/hedrinenew/resources/views/adminlte.blade.php) 

I have the config file under config 

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Title
    |--------------------------------------------------------------------------
    |
    | Here you can change the default title of your admin panel.
    |
    | For more detailed instructions you can look here:
    | https://github.com/jeroennoten/Laravel-AdminLTE/#61-title
    |
    */

    'title' => 'AdminLTE 3',
    'title_prefix' => '',
    'title_postfix' => '',`
...

any idea please ? 

Thank you in advance.

**Comment by lacodimizer** [comment]
Do you have included the menu filters in the config? This caused the error, because the menu filters have to set.

**Comment by ddubois2** [comment]
Thank you for your reply.

For you information, I just created a new laravel project (test) and I tried to install adminlte, it wors great.

On my projetct, it doesn't.

Where can I see if I included the menu filtrers ?

Thank you for your help.

**Comment by ddubois2** [comment]
Hi,

Problem resolved with this (hope it will help other people) 👍 
`php artisan config:clear
php artisan cache:clear
php artisan config:cache`
