### ISSUE TITLE
Error: the fixed layout requires the slimscroll plugin!

### ISSUE THREAD

**Issue by arturcesarmelo** [jeroennoten/Laravel-AdminLTE#58]
I'm a new bye guy with webpack and its stuffs.

I just want to know how to add this pligin via webpack or other way.

i'm using the fixed layout (changed in config/adminlte.php ) and now, i'm just trying to execute npm run dev and it is giving another error like "app.scss doesn't export content".

Could you help me explaing to me how to understand and solve problems arround webpack n'stuffs?

**Comment by jeroennoten** [comment]
This is currently not supported. You are welcome to submit a PR to add this feature.
