### ISSUE TITLE
VueJS Integration Issue (Possible Bug)?

### ISSUE THREAD

**Issue by LasanthaSudeera** [jeroennoten/Laravel-AdminLTE#582]
![ezgif com-optimize](https://user-images.githubusercontent.com/19815215/81466666-f8c41500-91f0-11ea-8809-d879285a32a5.gif)

Hi,

I tried this on a fresh installation of Laravel. If I add app.js to home.balde.php as

@section('js')
<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>
@stop

usermenu will not open, no matter what I do. There are no errors in the console to debug it. I have attached a GIF with the issue. However if I remove app.js everything will work fine, as usual, the usermenu will show up with the log out button.

Is there a way to overcome this issue.

Thanks.

**Comment by Paton7** [comment]
Have you tried loading it as a plugin within the `adminlte.php` config like so 

```
[
     'name' => 'Vue',
     'active' => true,
     'files' => [
         [
             'type' => 'js',
             'asset' => true,
             'location' => 'js/app.js',
         ],
      ],
],
```

**Comment by LasanthaSudeera** [comment]
> Have you tried loading it as a plugin within the `adminlte.php` config like so
> 
> ```
> [
>      'name' => 'Vue',
>      'active' => true,
>      'files' => [
>          [
>              'type' => 'js',
>              'asset' => true,
>              'location' => 'js/app.js',
>          ],
>       ],
> ],
> ```

Hi, I tried it, the same issue persists.

**Comment by LasanthaSudeera** [comment]
![2020-05-16_12h58_56](https://user-images.githubusercontent.com/19815215/82113673-60d8a500-9775-11ea-8a9b-04e264cf1ecc.png)

Solved the issue by commenting "require('bootstrap');" in bootstrap.js.

Don't know if this will cause any issues, for the moment bootstrap seems to work fine with smooth animations.
