### ISSUE TITLE
datetimepicker plugin

### ISSUE THREAD

**Issue by eraporsmk** [jeroennoten/Laravel-AdminLTE#583]
datetimepicker plugin is available on the demo, i searched for this plugin, it was not found
![timepicker](https://user-images.githubusercontent.com/53444184/81508756-48f5c100-9330-11ea-8876-764c420d1099.png)
thanks for answer

**Comment by REJack** [comment]
You need to install the plugin files with the adminlte:plugins command or load them from a cdn.
