### ISSUE TITLE
Change color sidebar menu?

### ISSUE THREAD

**Issue by rodrigompais** [jeroennoten/Laravel-AdminLTE#587]
Guys, how do I change the color of the sidebar menu?
![image](https://user-images.githubusercontent.com/59613110/81953572-36a0af00-95de-11ea-9e7a-c8cf0df687ed.png)

**Comment by eraporsmk** [comment]
change class in 
`<aside class="main-sidebar elevation-4 sidebar-light-primary"> <== light`
`<aside class="main-sidebar elevation-4 sidebar-dark-primary"> <== dark`

**Comment by Shidersz** [comment]
Hello, there is a configuration option on the **config/adminlte.php** file. The default value is the next one:

`'classes_sidebar' => 'sidebar-dark-primary elevation-4',`

You can replace the class `sidebar-dark-primary` by `sidebar-dark-<color>` or `sidebar-light-<color>` where `<color>` is one of the next:


1. `primary, secondary, success, info, warning, danger`
2. `blue, gray, green, cyan, yellow, red`
3. `black, gray-dark, indigo, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive`

These set of colors are documented on the [AminLTE / Layout](https://adminlte.io/docs/3.0/layout.html) page.

Also, if you need to play with the background color, you can add an extra class `bg-<color>` where `<color>` can take one of the previously mentioned values:

# Example

`'classes_sidebar' => 'sidebar-light-lime elevation-4 bg-olive',`

will give next look:

![Screenshot_2020-05-14 Laradmin Dashboard](https://user-images.githubusercontent.com/63609705/81973875-2ba84780-95fb-11ea-8cf4-864ff0893505.png)

**Comment by rodrigompais** [comment]
@eraporsmk and @Shidersz. Thanks a lot for the help!
