### ISSUE TITLE
iCheck background images missing

### ISSUE THREAD

**Issue by sudden-break** [jeroennoten/Laravel-AdminLTE#59]
With the standard installation the images for the iCheck checkboxes are in the public vendor folder but the reference in the css isn't correct.

![image](https://cloud.githubusercontent.com/assets/1845379/23063762/7a0bf46e-f50c-11e6-8d89-541a1330772a.png)

**Comment by jeroennoten** [comment]
Why not? That css file is in the same folder as the images.

**Comment by jeroennoten** [comment]
I close this because of no response. Let me know if you think that this should be reopened.
