### ISSUE TITLE
QUESTION about sidebar menu links

### ISSUE THREAD

**Issue by fermevc** [jeroennoten/Laravel-AdminLTE#597]
I can't understand how to achieve the following:
When I click top level menu item, I would like to open a specific page and at the same time expand the accordion to see sub-menu items (sub-menu items shouldn't point to any page, I just use their "data-" attribute in ajax.
Currently, I can implement sub-menu logic, but can't solve "dual" function on top-level menu item.
Is this possible?

**Comment by Shidersz** [comment]
Hi @fermevc , The collapsible `treeview` menu of the sidebar is not designed for that purposes. However, you can do some changes to make it work as you want:

**Step 1)**
Make sure to publish the package views to have full access to customize they: [Publish Views Documentation](https://github.com/jeroennoten/Laravel-AdminLTE#8-customize-views).

**Step 2)**
On the configuration file, add `id` and `url` keys to the item representing the `treeview` menu, example:

```php
[
    'text'    => 'multilevel',
    'icon'    => 'fas fa-fw fa-share',
    'id'      => 'itemId',
    'url'     => 'itemUrl',
    'submenu' => [...],
]
```
**Step 3)**
Customize the `resources/views/vendor/adminlte/partials/sidebar/menu-item-treeview-menu.blade.php` file on your local laravel project. So we can add the `url` option into the `href` attribute. Basically we change `href=""` by `href="{{ $item['url'] ? url($item['url']) : '' }}"`. File should look like this:

```blade
<li @if(isset($item['id'])) id="{{ $item['id'] }}" @endif class="nav-item {{ $item['submenu_class'] }}">

    {{-- Menu toggler --}}
    <a class="nav-link {{ $item['class'] }} @if(isset($item['shift'])) {{ $item['shift'] }} @endif"
       href="{{ $item['url'] ? url($item['url']) : '' }}" {!! $item['data-compiled'] ?? '' !!}>

        <i class="{{ $item['icon'] ?? 'far fa-fw fa-circle' }} {{
            isset($item['icon_color']) ? 'text-'.$item['icon_color'] : ''
        }}"></i>

        <p>
            {{ $item['text'] }}
            <i class="fas fa-angle-left right"></i>

            @if(isset($item['label']))
                <span class="badge badge-{{ $item['label_color'] ?? 'primary' }} right">
                    {{ $item['label'] }}
                </span>
            @endif
        </p>

    </a>

    {{-- Menu items --}}
    <ul class="nav nav-treeview">
        @each('adminlte::partials.sidebar.menu-item', $item['submenu'], 'item')
    </ul>

</li>
```
**Step 4)**
Customize the `resources/views/vendor/adminlte/page.blade.php` file on your local laravel project to inject some `Javascript/JQuery` code that capture the `click` event on the desired item. Just replace the previous `adminlte_js` section:

```blade
@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop
```
by next one:

```blade
@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>

    <script>
        $("li#itemId.nav-item").click(function()
        {
            let url = $(this).find('a.nav-link').attr('href');

            // Load content from the link's "href" attribute.

            $.get(url, function(data)
            {
                // Replace "content_header" section.
                $(".content-header > div").html(data.content_header);

                // Replace "content" section.
                $(".content > div").html(data.content);
            });
        });
    </script>

    @stack('js')
    @yield('js')
@stop
```
You can, if you want, put that logic on separated file. Also this is an example of how to reload a section without having to reloading the entire page.

**Step 5)**
Finally, we need to create a route for the `itemUrl` that returns an array with the rendered sections of the page you wanted to show. A basic example will be this one (add the logic in `routes/web.php` laravel file):

```php
Route::get('itemUrl', function()
{
    return View::make('item.view')->renderSections();
});
```
In this particular case, `item.view` is a blade layout that extends the `adminlte::page` view.

**Comment by fermevc** [comment]
Thanx for the response and sugestion. I'll take a look at it
