### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by zKoz210** [jeroennoten/Laravel-AdminLTE#599]
![image](https://user-images.githubusercontent.com/28255085/82768875-4cae3b00-9e3a-11ea-91f6-2e75995c6ddf.png)

**Comment by Shidersz** [comment]
Have you follow the [Installation](https://github.com/jeroennoten/Laravel-AdminLTE#2-installation) steps, in particular the execution of `php artisan adminlte:install` command? That should install the `AdminLTELogo.png` image on the **Laravel's `public` folder**

Anyway, check also if the image exists inside the `public` folder, for example, on a Linux environment, you can run the next command inside your Laravel Project root folder:

```sh
find public/ -name "AdminLTELogo.png"
```
In my local environment, that will output:

`public/vendor/adminlte/dist/img/AdminLTELogo.png`
