### ISSUE TITLE
'dashboard_url' setting not working

### ISSUE THREAD

**Issue by DrewNeon** [jeroennoten/Laravel-AdminLTE#60]
The default value of 'dashboard_url' is 'home', and it works at http://domain.com/home. When I change it to say 'admin', http://domain.com/home still works, but http://domain.com/admin returns 404.

My Laravel version is 5.4.14

**Comment by loekiedepo** [comment]
Might be a silly question, but have you added a route and view to return a page if you hit `/admin`?

**Comment by DrewNeon** [comment]
I followed all the steps of installation and settings, including generating auth stuff. The http://domain.com/home is accessed after logging in, and it has "Dashboard" as the title of the body. When checking the config file, 'dashboard_url' => 'home' looks like the setting pointing to this URL to me.

**Comment by jeroennoten** [comment]
The `dashboard_url` setting only determines the link that is attached to the logo (top left) on each admin page. You will always have to change your routes files as well when you want to change the url of your dashboard page.

**Comment by jeroennoten** [comment]
I guess this solved your problem? If not, please let me know and I will reopen this issue.
