### ISSUE TITLE
adminlte.php inside config file not updating

### ISSUE THREAD

**Issue by ubisales-bradley** [jeroennoten/Laravel-AdminLTE#601]
Normally I'd put this on StackOverflow but it's too specific to adminLTE for a larval query, I have added details to adminlte.php and saved them when I launch it the platform hasn't updated. I have tried to 

```
php artisan adminlte:update
php artisan config:clear
php artisan cache:clear
php artisan view:clear
composer dump-autoload
```

![notupdated](https://user-images.githubusercontent.com/54758671/82849704-2b8a3f00-9f4d-11ea-8880-d24dc5caf287.PNG)
![page](https://user-images.githubusercontent.com/54758671/82849706-2d540280-9f4d-11ea-927b-33b88a52768d.PNG)

I can see in the bootstrap/cache/config it is showing the updated one but not on screen. Any ideas to fix this issue?

**Comment by REJack** [comment]
Did you tried a other browser or clear the browser cache?

**Comment by ubisales-bradley** [comment]
> Did you tried a other browser or clear the browser cache?

Good suggestion but didn't work :/

**Comment by REJack** [comment]
Do you use `php artisan serve`?

**Comment by ubisales-bradley** [comment]
Yes I do

**Comment by REJack** [comment]
Ok, do you run `php artisan config:clear` while your artisan dev server is running?

**Comment by ubisales-bradley** [comment]
I use PHPStorm and it wont let me do that

**Comment by REJack** [comment]
Mmh that's sounds like a Laravel related issue

**Comment by Bradley-Kirkland** [comment]
Would you be willing to take a look?

**Comment by ubisales-bradley** [comment]
If someone wants to teamviewer/Anydesk and take a look I would welcome it, I am still facing the issue.

**Comment by grab95** [comment]
hi i have the same problem, somebody will help?

**Comment by lacodimizer** [comment]
We need more infos, like the following:
* Laravel version
* version of the AdminLTE project
* PHP version
* environment (mac, windows)
* local test environment (artisan serve, herokus, ...)

**Comment by lacodimizer** [comment]
Please provide us with more infos, like the post before. Thank you.

**Comment by lacodimizer** [comment]
closed, because no response

**Comment by Bradley-Kirkland** [comment]
I ended up rebuilding the application and it worked, it's caused by using
packages which conflict with AdminLTE

**Comment by Shidersz** [comment]
Hi @Bradley-Kirkland , could you provide the name of the packages that was generating the conflict. So we can help other readers...

**Comment by ubisales-bradley** [comment]
No idea sorry I just did a complete rebuild and installed all packages I
used before.
