### ISSUE TITLE
Laravel 7 AdminTLE ?

### ISSUE THREAD

**Issue by iPhonePKAndroid** [jeroennoten/Laravel-AdminLTE#602]
Laravel 7 AdminTLE ?

**Comment by lacodimizer** [comment]
Works.

**Comment by iPhonePKAndroid** [comment]
what?doc&nbsp;





------------------ Original ------------------

**Comment by lacodimizer** [comment]
Whats your question, please more details what do you want.

**Comment by iPhonePKAndroid** [comment]
有没有 laravel 7 的 admintle

------------------ Original ------------------

**Comment by lacodimizer** [comment]
This project is available for Laravel >= 7 with AdminLTE v3.

**Comment by iPhonePKAndroid** [comment]
不是很会弄，我试试吧，你这个没有更详细的说明吗，针对于Laravel7，




很感谢你及时的答复！

**Comment by lacodimizer** [comment]
Please follow the infos in the readme to install the project for Laravel 7. It‘s the same like Laravel 6.

**Comment by lacodimizer** [comment]
If you have any questions or problems, please ask again.
