### ISSUE TITLE
@section('js') and @section('css') are not working

### ISSUE THREAD

**Issue by claytongf** [jeroennoten/Laravel-AdminLTE#606]
After configuring the Laravel mix, the @section('js') and @section('css') are not working.
However, when I use @section('load_js') and @section('load_css') instead, they work.
Is the documentation wrong or it should have another configuration that it is missing?

**Comment by Shidersz** [comment]
What version of the package you are using? Sections `load_js` and `load_css` will be discarded and sections `js` and `css` should work on the next release. Any previous version will work as you describe. Take a look to the issue #590 and the PR #591

**Comment by claytongf** [comment]
I've installed the 3.2 version. But, I realized that it's getting an older version. My config file does not have the laravel_mix_css_path' and  'laravel_mix_js_path' options. 
I've cleared the cache of the composer and installed again. And I'm still getting the older version with @yield( 'load_js')
All blade files have @extends('adminlte::page')

**Comment by lacodimizer** [comment]
I think I know what the issue is. The readme in the master branch is newer then the included functions in v3.2. So you have the older configs / blades as the readme.

Please use the following readme:
https://github.com/jeroennoten/Laravel-AdminLTE/blob/v3.2.0/README.md

**Comment by Shidersz** [comment]
@claytongf as @lacodimizer says, the master is already [17 commits upward](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.2.0) in comparison with the [release 3.2.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.2.0). You are reading the documentation of the master. And as I previously says, take in consideration that in the next release, sections `load_js` and `load_css` won't exists anymore.

**Comment by claytongf** [comment]
Got it. So, I should wait until the next version or I should import the master dev version, right?

**Comment by Shidersz** [comment]
That is up to you, maybe you can import the master dev while waiting for a new release. I believe a new release will come soon.

**Comment by lacodimizer** [comment]
The release v3.3.0 was published.
