### ISSUE TITLE
User top menu nav link is invisible

### ISSUE THREAD

**Issue by buddyy93** [jeroennoten/Laravel-AdminLTE#607]
how could i fix it ? thank you

![Snipaste_2020-05-28_16-28-16](https://user-images.githubusercontent.com/22981271/83111916-4ea92000-a100-11ea-9957-f26c2e724ca4.png)

Here are the adminlte config codes for the user top menu

`  'usermenu_enabled'      => true,
    'usermenu_header'       => true,
    'usermenu_header_class' => 'bg-primary',
    'usermenu_image'        => true,
    'menu'                  => [
        [
            'topnav_user' => true,
            'text'        => '個人情報の設定',
            'url'         => 'user/setting',
            'icon'        => 'fas fa-fw fa-lock',
        ],
        [
            'topnav_user' => true,
            'text'        => 'パスワード変更',
            'url'         => 'user/password_setting',
            'icon'        => 'fas fa-fw fa-lock',
        ],`

**Comment by Shidersz** [comment]
Please, provide the code (or config) you have used to add the link to the user dropdown menu. Also, what version of the package you are using?

**Comment by buddyy93** [comment]
> Please, provide the code (or config) you have used to add the link to the user dropdown menu. Also, what version of the package you are using?

My apology, i've added the codes.

**Comment by Shidersz** [comment]
It is working fine on my local environment, could you inspect the element with the browser inspector and see what you are getting there. On my case I'm getting this `html` code for one of the items:

```html
<li class="nav-item ">
    <a class="nav-link" href="http://localhost/public/user/setting">
      <i class="fas fa-fw fa-lock "></i>
      個人情報の設定
    </a>
</li>
```

**Comment by buddyy93** [comment]
> It is working fine on my local environment, could you inspect the element with the browser inspector and see what you are getting there. On my case I'm getting this `html` code for one of the items:
> 
> ```
> <li class="nav-item ">
>     <a class="nav-link" href="http://localhost/public/user/setting">
>       <i class="fas fa-fw fa-lock "></i>
>       個人情報の設定
>     </a>
> </li>
> ```

i think i found the problem, when i add navbar dark to topnav classes, the nav item on usermenu will be invicible

`'classes_topnav'           => 'navbar-dark',`

the problem is how could i keep the dark navbar and make sure the nav item shows as it should be ?

**Comment by Shidersz** [comment]
Yeah, actually the nav items are not invisible, but the that `navbar-dark` class affects they adding a white color on the texts (and the default background is also white).

```css
.navbar-dark .navbar-nav .nav-link {
    color: rgba(255,255,255,.75);
}
```
Give me some time in order to check for a solution to this, ok?

**Comment by Shidersz** [comment]
The PR #611 solves this issue, please refer to it to see the changes and implement it on your local environment until a new release is available.

**Comment by lacodimizer** [comment]
The release v3.3.0 was published.
