### ISSUE TITLE
Select2 plugin not working

### ISSUE THREAD

**Issue by Piazzi** [jeroennoten/Laravel-AdminLTE#609]
The css and js are loading but the multiple select don't work. I tried the CDN version and even installed the plugin using the `artisan adminlte:plugins install --plugin=paceProgress --plugin=select2
` . I changed the config file but it's not working so far. Any idea what is happening?

![image](https://user-images.githubusercontent.com/40416044/83176734-59f64e80-a0f4-11ea-8e02-9e15b4f1b539.png)

![image](https://user-images.githubusercontent.com/40416044/83176903-99bd3600-a0f4-11ea-8a81-f47a6dfda7d1.png)

**Comment by Serge3d** [comment]
From the [https://select2.org/getting-started/basic-usage](https://select2.org/getting-started/basic-usage)
```js
// In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('select.select2').select2();
});
```

**Comment by Piazzi** [comment]
@Serge3d i already did that, does not work :/

**Comment by REJack** [comment]
@Piazzi is the second image from your html markup inside the blade file?

**Comment by Piazzi** [comment]
> @Piazzi is the second image from your html markup inside the blade file?

Actually i load the plugin in every page as suggested in the docs

> You can activate them with changing the config file to load it on every page or add a section in specific blade files, this will automatically injecting their CDN files.

**Comment by REJack** [comment]
I mean this code:
![img](https://user-images.githubusercontent.com/40416044/83176903-99bd3600-a0f4-11ea-8a81-f47a6dfda7d1.png)

Is this your actual html markup in your blade file?

**Comment by Piazzi** [comment]
> I mean this code:
> ![img](https://user-images.githubusercontent.com/40416044/83176903-99bd3600-a0f4-11ea-8a81-f47a6dfda7d1.png)
> 
> Is this your actual html markup in your blade file?

Yes. But i figured out the problem, it seems that the select2 was loading before the jquery,  so i could not use the jquery query selector 

`$(document).ready(function() {
    $('select.select2').select2();
});`
Anyway, thank you for the help!
