### ISSUE TITLE
Method adminlte_profile_url() not overwrites profile_url config option

### ISSUE THREAD

**Issue by vsilva472** [jeroennoten/Laravel-AdminLTE#616]
Following the documentation at https://github.com/jeroennoten/Laravel-AdminLTE/#641-user-image--description-example-code the code bellow should be placed inside user model.

```php
public function adminlte_profile_url()
{
   return route('/users/{user}/profile', $this->id);
}
```

But with `profile_url=false` the profile buttons is not generated.

If i set  `profile_url=/profile` the button appears with this value not with the value returned from `adminlte_profile_url` model.

My config:

```php
'usermenu_enabled' => true,
'usermenu_header' => true,
'usermenu_header_class' => 'bg-primary'',
'usermenu_image' => true,
'usermenu_desc' => true,
'usermenu_profile_url' => true,

...
'profile_url' => false,
```

User model
```php
    public function adminlte_image()
    {
        return asset('/img/profiles/' . $this->image_url);
    }
  
    public function adminlte_profile_url()
    {
        return route('/users/{user}/profile', $this->id);
    }

    public function adminlte_desc()
    {
        return $this->slogan;
    }
```

Is there some other configuration that i miss?

Thanks in advance for this awesome implementation of AdminLTE!!!!

**Comment by lacodimizer** [comment]
@vsilva472 The infos in the readme are for the coming release of this project.

**Comment by vsilva472** [comment]
@lacodimizer my version is 3.2.0, this options is not applied for this version?

**Comment by lacodimizer** [comment]
@vsilva472 the release 3.3.0 is published, have fun :)
