### ISSUE TITLE
Call to undefined method getBodyClasses (v3.3.0)

### ISSUE THREAD

**Issue by vfj-tuanlm** [jeroennoten/Laravel-AdminLTE#618]
| Question                | Answer
| ----------------------- | ---
| Issue or Enhancement    | Issue|Enhancement
| Larvel Version          | v6.18.18
| Project Version         | v3.3.0

My project use AdminLTE v3.2.0 is usualy, but after update AdminLTE v3.3.0 i get an error:
`Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses() (View: /work/resources/views/vendor/adminlte/page.blade.php)`

I has down to version v3.2.0 and it working, let me know what configuration I need when using v3.3.0

**Comment by rino7** [comment]
Same issue here

**Comment by lacodimizer** [comment]
You have to update the main views, see infos in the readme.

**Comment by Shidersz** [comment]
@rino7 The `getBodyClasses()` method was moved and renamed on the **version 3.3.0**. I believe this problem is caused because yo have not published the new views. Be sure to follow the [Update Procedure](https://github.com/jeroennoten/Laravel-AdminLTE#3-updating), in particular the **step 3**.

**Comment by rino7** [comment]
Nice. These tips fix the issue.
Thanks for the help @lacodimizer @Shidersz
