### ISSUE TITLE
Problem with route and save register in BD (form-adminlte)

### ISSUE THREAD

**Issue by ragna30** [jeroennoten/Laravel-AdminLTE#62]
Good I have a problem with the adminlte and the routes .. I create my controller, I create my route, I convert the url en route so that in the blade the form picks up the information to save in the database but when registration is not stored in The database has tried everything and I do not know what to do if someone please help me

blade.php:
```
{!! Form::open(['route' => 'UsersLogincontroller.store', 'method' => 'post', 'novalidate']) !!}
```

routes:
```
Route::post('users',['as'=> 'UsersLogincontroller.store', 'uses'=>'UsersLogincontroller@store ']);
```

PS: this same I did a form without the adminlte and I keep it lso perfectly register in the DB

**Comment by jeroennoten** [comment]
You need to provide more information/code, I cannot see what you are doing wrong.

**Comment by ragna30** [comment]
Good morning, ok I segi trying to solve the problem and nothing based on url, but I happen something curious, on the routes I have this.
`<?php



Route::get('/', function () {
    return view('welcome');
});


Auth::routes();


Route::get('acudiente', 'pruebakattaController@store');
Route::post('acudiente', 'pruebakattaController@store');`

In my controller i have this
`use Illuminate\Http\Request;
use App\Colegios\UsersLogica\UsersRepo;
class pruebakattaController extends Controller
{
    protected  $UsersRepo;
    
    
    public function __construct(UsersRepo $UsersRepo) {
        $this->UsersRepo=$UsersRepo;
    }
    public function index()
    {
        
    
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return view('acudiente');
       
    $users= $this->UsersRepo->crearUser($request);
    
    }`

And on my blade i have this
`
 <section  class="content">
      <div class="row">
        
        <div class="col-md-8">
          <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">REGISTRO <div class="fa fa-child text-maroon "></h3>        
                
            
      
                     
            </div>            
                       
            
            
            <form class="form-horizontal">
              <div class="box-body">
                <div class="form-group">                    

		       
              
                 
             
             
             
              {!! Form::open(['url' => 'acudiente@store', 'method' => 'post', 'novalidate']) !!}
		       
              
                                
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('name', 'Nombre') !!}</div>
                      
                      <div class="col-sm-5">{!! Form::text('name', null, ['class' => 'form-control',"placeholder"=>'Nombre', 'required' => 'required']) !!}</div> 
                  </div>
              
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('apellido', 'Apellido') !!}</div>
                      
                      <div class="col-sm-5">{!! Form::text('apellido', null, ['class' => 'form-control',"placeholder"=>'Apellido', 'required' => 'required']) !!}</div> 
                  </div>
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('direccion', 'dir') !!}</div>
                      
                      <div class="col-sm-3">{!! Form::text('direccion', null, ['class' => 'form-control',"placeholder"=>'tel', 'required' => 'required']) !!}</div> 
                  </div>
              
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('telefono', 'tel') !!}</div>
                      
                      <div class="col-sm-3">{!! Form::text('telefono', null, ['class' => 'form-control',"placeholder"=>'tel', 'required' => 'required']) !!}</div> 
                  </div>
            
                  
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('email', 'Email') !!}</div>
                      
                      <div class="col-sm-6">{!! Form::text('email', null, ['class' => 'form-control',"placeholder"=>'Direccion', 'required' => 'required']) !!}</div> 
                  </div>
              
              
                  
                  <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation">

                                @if ($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>   
              
              <div class="form-group">
                      <div class="col-sm-3 control-label ">{!! Form::label('roles', 'Role') !!}</div>
                      
                      <div class="col-sm-5">{!! Form::text('roles_id', null, ['class' => 'form-control',"placeholder"=>'roles', 'required' => 'required']) !!}</div> 
                  </div>
              
              
            
              
              
              
              
           </div>
                  
             <div class="box-footer">        
                                    
              {!! Form::submit('Guardar',[ 'class' => 'btn btn-primary pull-right']) !!}
              
             
                  
              </div>
                  
                  
        </div>
         

{{ Form::close() }}

            </form>
            
            </section>
 
           <div class="top-left box-header ">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>

              <h3 class="box-title">Atencion</h3>
            </div>
            
            <div class="box-body">
              
              <div class="callout callout-info">
                <h4>Es un Tips Informativo!</h4>

                <p></p>
              </div>
                            
            </div>
            
          </div>
 
 
@stop`


Then I tried to solve the problem I started playing with the routes and I made em save once I looked as if the route and the post did not work, after that I continued to give error, what I did to keep that one time was : The routa in post I put it as a comment or legend just leave the get, after that when I fill out the form and save I put in method of legend the method get and activate the method post en route and there is if I save, then try to do it again And I could not every time I save in the form I get this in the link
`http://localhost:3008/acudiente?_token=rElPEhpUjiIyAY7keT9ANRD49qXCL9AiqZnAKmmG&name=jhon&apellido=loney&direccion=country&telefono=999999&email=kattia%40live.com&password=12345678&password_confirmation=12345678&roles_id=2`


y ese es mi problema nose si en el controller o en routas estoy haciendo algo malo llevo ya 1 mes en lo mismo y nose que hacer, igual soy principiante en laravel y adminlte

**Comment by jeroennoten** [comment]
Both routes reference the same controller method:

```
Route::get('acudiente', 'pruebakattaController@store');
Route::post('acudiente', 'pruebakattaController@store');
```

**Comment by ragna30** [comment]
`Route::get('acudiente', 'pruebakattaController@index');
Route::post('acudiente', 'pruebakattaController@store');`

Same problem although I changed it

**Comment by jeroennoten** [comment]
Now you are referencing the `index` method which is empty:

```
    public function index()
    {
 
    }
```

**Comment by loekiedepo** [comment]
Kinda hooking in here, but if your `store` method is still what you've described in your 2nd post, it's no wonder it doesn't do anything. The first line is `return view` which exits your method and then shows a view to the user. Nothing happens.

**Comment by ragna30** [comment]
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Colegios\UsersLogica\UsersRepo;
class pruebakattaController extends Controller
{
    protected  $UsersRepo;
    
    
    public function __construct(UsersRepo $UsersRepo) {
        $this->UsersRepo=$UsersRepo;
    }
    public function index()
    {
        
      return view('acudiente');
    
    }

 
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
               
    $users= $this->UsersRepo->crearUser($request);
   return redirect('home');
    }`

**Comment by jeroennoten** [comment]
This is clearly not a problem related to AdminLTE. I suggest that you start learning Laravel a bit more, because there is a lot wrong with your code. This is not the right place to ask such questions. As a a learning source I recommend [laracasts.com](http://laracasts.com). It has a forum as wel.
