### ISSUE TITLE
Toggle navigation button misplaced on small screens

### ISSUE THREAD

**Issue by samuelm77** [jeroennoten/Laravel-AdminLTE#623]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | Laravel 7
| Project Version         | AdminLTE 3.2

### Current Behavior

The toggle navigation button is not placed correctly when reducing the screen size :
Full screen : OK
![1](https://user-images.githubusercontent.com/2292089/83967375-0c7e9c00-a8c1-11ea-8e03-7ef23727f9bf.PNG)

Medium screen : OK
![2](https://user-images.githubusercontent.com/2292089/83967379-11435000-a8c1-11ea-94bd-b001ac775b26.PNG)

Small screen : Not OK
![3](https://user-images.githubusercontent.com/2292089/83967474-1785fc00-a8c2-11ea-9be1-6f5f7896e88c.PNG)

Same behaviour on Chrome, Firefox and Microsoft Edge.

### Expected Behavior

I would like the toggle navigation button on the small screens to be placed a little on the right (like in the full and medium size screens).

Note: Commenting the search bar in config/admintle.php  does not help.

### Steps to Reproduce

Simply reduce the size of the browser.

**Comment by lacodimizer** [comment]
@REJack

**Comment by REJack** [comment]
This come from `classes_topnav_nav`'s default value it should be `navbar-expand` not `navbar-expand-md`.

**Comment by Shidersz** [comment]
@REJack @lacodimizer We can change the default values with minor fixes, I can do that if no one else wants...

**Comment by lacodimizer** [comment]
solved with v3.3.1
