### ISSUE TITLE
Cannot use PHP code to construct an URL in the sidebar menu items

### ISSUE THREAD

**Issue by samuelm77** [jeroennoten/Laravel-AdminLTE#624]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement/Question
| Laravel Version         | Laravel 7
| Project Version         | AdminLTE 3.2

### Current Behavior

I cannot use the _route_ command or any PHP code to construct a menu item URL for the sidebar in config/adminlte.php.

### Steps to Reproduce

![screenshot](https://user-images.githubusercontent.com/2292089/84030949-29849f00-a995-11ea-8f35-30f96b2fb50d.PNG)

**Comment by lacodimizer** [comment]
To work with Auth in config is not possible. You have to work with the menu builder on runtime to set menu entries like this.
