### ISSUE TITLE
Multiple select makes the content section slide

### ISSUE THREAD

**Issue by samuelm77** [jeroennoten/Laravel-AdminLTE#631]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue / Enhancement
| Laravel Version         | Laravel 7
| Project Version         | AdminLTE 3.2

Spotted on Chrome and Microsoft Edge. Cannot reproduce on Firefox.

### Current Behavior

Using a form with a **multiple** select makes the whole content section slide from left to right on page load. Note that the sidebar is not affected. Also, **simple** select works without any issue.

### Expected Behavior

No sliding with multiple select.

### Steps to Reproduce

Code to reproduce:
![code_to_reproduce](https://user-images.githubusercontent.com/2292089/84264584-bc524480-ab21-11ea-897f-849cd0ad67ca.PNG)

Important note: It is sometimes hard to reproduce since the issue does not show at every page load.

**Comment by lacodimizer** [comment]
@REJack any idea?

**Comment by REJack** [comment]
No, but I will check it out in the next days

**Comment by lacodimizer** [comment]
@REJack any news?

**Comment by REJack** [comment]
I found no bug related to AdminLTE itself :/

**Comment by lacodimizer** [comment]
Closed, not error reproduction possible.
