### ISSUE TITLE
Laravel LogViewer package with not show sidebar menu

### ISSUE THREAD

**Issue by Nikhilchudasama** [jeroennoten/Laravel-AdminLTE#633]
specially thank for this great package, come to my point
i have integrate Laravel LogViewer package and add LogViewer routes in config file but i looked strange thing on my system is all sidebar menus disappear when click on LogViewer routes.

**Comment by REJack** [comment]
This sounds like you not use the Laravel-AdminLTE page views in your LogViewer views.

**Comment by Nikhilchudasama** [comment]
i have use inherit layout @extends('adminlte::page')
