### ISSUE TITLE
Using @stack to add scripts and stylesheets in master.blade.php?

### ISSUE THREAD

**Issue by satyakresna** [jeroennoten/Laravel-AdminLTE#634]
Hi, I see in the [Laravel documentation that `@stack` is good](https://laravel.com/docs/7.x/blade#stacks) too add scripts and stylesheets libraries required in another view or layout.

In [SO discussion](https://stackoverflow.com/questions/35672485/what-is-the-difference-between-section-and-stack-in-blade) also mentions that `@stack` is good too add scripts.

In [Laracasts forum](https://laracasts.com/discuss/channels/laravel/blade-at-stackscripts-and-at-pushscripts-am-i-doing-it-right) also discuss the same thing.

I saw in `master.blade.php` uses [`@yield('adminlte_css')`](https://github.com/jeroennoten/Laravel-AdminLTE/blob/8fdf912f3bb7d365c50f069524e03dcfe20c28ce/resources/views/master.blade.php#L40) and [`@yield('adminlte_js')`](https://github.com/jeroennoten/Laravel-AdminLTE/blob/8fdf912f3bb7d365c50f069524e03dcfe20c28ce/resources/views/master.blade.php#L87). I think it will be good if use `@stack('css')` and `@stack('js')`.

Is that any reasons why use `@yield` instead of `@stack`?

**Comment by Shidersz** [comment]
Actually, the [adminlte_css](https://github.com/jeroennoten/Laravel-AdminLTE/blob/8fdf912f3bb7d365c50f069524e03dcfe20c28ce/resources/views/page.blade.php#L11) and [adminlte_js](https://github.com/jeroennoten/Laravel-AdminLTE/blob/8fdf912f3bb7d365c50f069524e03dcfe20c28ce/resources/views/page.blade.php#L67) sections are define like next on the [page.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/8fdf912f3bb7d365c50f069524e03dcfe20c28ce/resources/views/page.blade.php) (and this is the one you usually will `@extends()`):

```blade
@section('adminlte_css')
    @stack('css')
    @yield('css')
@stop

@section('adminlte_js')
    @stack('js')
    @yield('js')
@stop
```
So you will have the chance to use `@section('js')`, `@push('js')` or `@prepend('js')` on your views extending the `page.blade.php` layout.

**Comment by satyakresna** [comment]
Hi @Shidersz, thanks for your explaination. I will close the issue now.
