### ISSUE TITLE
config parameter classes_content_wrapper not present in page.blade.php

### ISSUE THREAD

**Issue by sdonchez** [jeroennoten/Laravel-AdminLTE#639]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 7.14.1
| Project Version         | 3.3.1

### Current Behavior

Classes specified in the 'classes_content_wrapper' parameter of config/adminlte.php are not echoed in the AdminLTE blade assets generated by `php artisan adminlte:update`. Said classes are not applied to any views that extend this template.

### Expected Behavior

Classes specified in the 'classes_content_wrapper' parameter of config/adminlte.php should be echoed into the classes parameter of the content-wrapper div on line 201 of resources/views/vendor/adminlte/page.blade.php, causing them to appear on all blades that extend the adminlte template. This behavior is outlined in the [admin panel classes](https://github.com/jeroennoten/Laravel-AdminLTE#662-admin-panel-classes) section of this repository's README.md file.

### Steps to Reproduce

1. Specify classes to be applied to the content_wrapper by defining a 'classes content_wrapper' value in adminlte.php. For example, `classes_content_wrapper' => 'bg-gradient-dark text-light',`.

1. Browse to any AdminLTE-based page on the site (using `php artisan serve` or another server of choice) and confirm that the changes have not been applied.

### Possible Solutions

Modify line 201 of resources/views/vendor/adminlte/page.blade.php to include the classes specified in config/adminlte.php

A pull request is forthcoming to incorporate this change

**Comment by Shidersz** [comment]
@sdonchez What is your current source code for the `page.blade.php` file? Have you followed the [UPDATE PROCEDURE](https://github.com/jeroennoten/Laravel-AdminLTE#3-updating), particularly the **step 3** of it. I mean, the current `page.blade.php` does not have a line `201`, it have less than `100` lines. I believe you have forgotten to publish the views again as explained on the **step 3**.

**Comment by sdonchez** [comment]
I'm seeing now that this file is dynamically generated. The line number listed was in reference to the copy in my project - it's actually line 36 in the file in this repository (I'll update my prior comment), which does not have the ~error~ I outlined above.

Additionally, issuing `php artisan adminlte:install --only=main_views --force` specifically resolved my problem, while the other `php artisan adminlte:update` command listed elsewhere in the readme did not. Thanks for pointing this out!
