### ISSUE TITLE
Please, support htpps

### ISSUE THREAD

**Issue by williamdunbar** [jeroennoten/Laravel-AdminLTE#64]
My website http update to secure htpps and have something errors

Mixed Content: The page at 'https://example.com' was loaded over HTTPS, but requested an insecure stylesheet 'http://example.com/public/vendor/adminlte/bootstrap/css/bootstrap.min.css'. This request has been blocked; the content must be served over HTTPS.

Please support it! Thanks you!

**Comment by jeroennoten** [comment]
It should automatically detect what protocol you are using. It just uses Laravel's `asset()` function. So if that does not work, then something else is wrong, and it has nothing to with this package.
