### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by thiagoromera** [jeroennoten/Laravel-AdminLTE#642]
Hello guys,

I have a question in this version 3.0 The config skin has been removed. How do I change the default blue skin for another one now?

Thanks advanced

**Comment by Shidersz** [comment]
Hi, there is no skin on the [AdminLTE v3](https://adminlte.io/themes/v3/), instead you can customize `navbar`, `sidebar`, etc, to get your own theme. I suggest to give a read to next documentation first:

- [AdminLTE V3 Layout](https://adminlte.io/docs/3.0/layout.html), particularly the `Color Variations` section.
- [Configuration - Classes](https://github.com/jeroennoten/Laravel-AdminLTE#66-classes) section of this package.

Then, you can play with the configuration options of this package to get your own style.

**Comment by thiagoromera** [comment]
Thanks Diego.

I did anythig.

But I cant chage primary color from buttons.

My buttons has btn-primary class, but I cant change the blue.

Thanks if can help me.



________________________________
De: Diego Smania <notifications@github.com>
Enviado: sexta-feira, 19 de junho de 2020 11:16
Para: jeroennoten/Laravel-AdminLTE <Laravel-AdminLTE@noreply.github.com>
Cc: thiagoromera <thiago.romera@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [jeroennoten/Laravel-AdminLTE] skins (#642)


Hi, there is no skin on the AdminLTE v3<https://adminlte.io/themes/v3/>, instead you can customize navbar, sidebar, etc, to get your own theme. I suggest to give a read to next documentation first:

  *   AdminLTE V3 Layout<https://adminlte.io/docs/3.0/layout.html>, particularly the Color Variations section.
  *   Configuration - Classes<https://github.com/jeroennoten/Laravel-AdminLTE#66-classes> section of this package.

Then, you can play with the configuration options of this package to get your own style.

**Comment by Shidersz** [comment]
What buttons, the ones on the login and register pages?

If yes, try to use the configuration option: `classes_auth_btn`. The current default value is:

`'classes_auth_btn' => 'btn-flat btn-primary'`

But you can change `btn-primary` by `btn-<color>` where `<color>` is one of the available on the [AdminLTE Framework Colors](https://adminlte.io/themes/v3/pages/UI/general.html). For example:

`'classes_auth_btn' => 'btn-flat btn-danger`
or
`'classes_auth_btn' => 'btn-flat btn-lime`

**Comment by thiagoromera** [comment]
Hello there.

Any button in any page.

I tried use btn-lime but not work. But works using  'btn  bg-teal'

Thank so much ur help

________________________________
De: Diego Smania <notifications@github.com>
Enviado: segunda-feira, 22 de junho de 2020 19:21
Para: jeroennoten/Laravel-AdminLTE <Laravel-AdminLTE@noreply.github.com>
Cc: thiagoromera <thiago.romera@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [jeroennoten/Laravel-AdminLTE] skins (#642)


What buttons, the ones on the login and register pages?

If yes, try to use the configuration option: classes_auth_btn. The current default value is:

'classes_auth_btn' => 'btn-flat btn-primary'

But you can change btn-primary by btn-<color> where <color> is one of the available on the AdminLTE Framework Colors<https://adminlte.io/themes/v3/pages/UI/general.html>. For example:

'classes_auth_btn' => 'btn-flat btn-danger
or
'classes_auth_btn' => 'btn-flat btn-lime

**Comment by Shidersz** [comment]
@thiagoromera Yea, sorry about that, not all colors are available with `btn-*` classes. I believe only **theme colors** are available with they. You can check the [AdminLTE / UI Buttons Section](https://adminlte.io/themes/v3/pages/UI/buttons.html) to see all about buttons. Just use the browser's inspector tool to see how a particular button is implemented.

**Comment by REJack** [comment]
The `btn-*` classes are only with default classes (primary, secondary, info, success, danger, warning and default), you can only get the other colors via `bg-*` otherwise it would even more lines in the stylesheet and it's already too much 🤣

**Comment by thiagoromera** [comment]
Thanks friends.

________________________________
De: REJack <notifications@github.com>
Enviado: terça-feira, 23 de junho de 2020 19:22
Para: jeroennoten/Laravel-AdminLTE <Laravel-AdminLTE@noreply.github.com>
Cc: thiagoromera <thiago.romera@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [jeroennoten/Laravel-AdminLTE] skins (#642)


The btn-* classes are only with default classes (primary, secondary, info, success, danger, warning and default), you can only get the other colors via bg-* otherwise it would even more lines in the stylesheet and it's already too much 🤣
