### ISSUE TITLE
50 Gigabytes of project storage

### ISSUE THREAD

**Issue by santiagoferraz** [jeroennoten/Laravel-AdminLTE#647]
I developed 1 project with this framework and after going into production I realized I have 50 Gigabytes of storage. Is it more or less that?

**Comment by lacodimizer** [comment]
That's very much. But I don't think it's an issue of this project. I think a other resource of your project is the issue.

**Comment by reymaro0** [comment]
take a look at the logs and if you have media support in your app, check if files are deleted from storage when you delete from you app or database (if you have, of course)
you can check the folders size with this command inside of you app path 
`find ./ -maxdepth 1 -type d -exec du -sh {} \;`
