### ISSUE TITLE
Sidebar menu - do not collapse automatically

### ISSUE THREAD

**Issue by jagyossarian** [jeroennoten/Laravel-AdminLTE#65]
Hi, 

The default functionality for the sidebar multi-level menus is to collapse automatically when another menu is clicked. Is it possible to keep multiple menus open and only close a menu if you click on that same menu again?  What I have in mind is something like what's at the link below. 

http://www.bootply.com/90JfjI2Q7n

Thanks for any help/suggestions you can provide.

**Comment by jeroennoten** [comment]
Hi,

I think that you should request this in the official AdminLTE repository: https://github.com/almasaeed2010/AdminLTE

Note that this package just provides a way to integrate AdminLTE with Laravel and does not modifying functionality of AdminLTE in any way.

**Comment by jagyossarian** [comment]
Appreciate the response and suggestion. Thanks!

**Comment by jeroennoten** [comment]
No problem, you're welcome! Thanks for the interest in this package. 😄
