### ISSUE TITLE
Box component not rendered properly

### ISSUE THREAD

**Issue by fabioi** [jeroennoten/Laravel-AdminLTE#650]
Boxes are not showing as expected ( https://adminlte.io/docs/2.4/boxes) eg: white background.

I attached the style I am getting.

Do you have any idea if I am missing something?

![2020-07-01_19-00-03](https://user-images.githubusercontent.com/4541083/86271515-48a9d180-bbcd-11ea-827e-a8df21947125.png)

**Comment by REJack** [comment]
You try the AdminLT **v2** boxes example, but you need to use the AdminLTE **v3** card examples from [here](https://adminlte.io/docs/3.0/components/cards.html)

**Comment by fabioi** [comment]
Thank you a lot! I am sorry, had the previous version bookmarked and did not notice I was not looking at the latest version.

Thank you a lot for the quick and kind help and for maintaining this great package!.  I really like it a lot, keep up the great work!

Thank you again to you and all the maintainers :D
