### ISSUE TITLE
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist

### ISSUE THREAD

**Issue by kastony** [jeroennoten/Laravel-AdminLTE#652]
| Question 

| Issue 
| Laravel Version       7.18.0
| Project Version        3.3

### Current Behavior

Facade\Ignition\Exceptions\ViewException
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist. (View: /Users/xxx/code/xxx/resources/views/vendor/adminlte/partials/navbar/navbar.blade.php)

### Expected Behavior

Well it was working great but without any new composer update, never did anything with filters it pop up this error

**Comment by lacodimizer** [comment]
We removed the SubmenuFilter class in the release v3.4.0.

Please go into the config.php and remove the class in the menu filter array.

**Comment by kastony** [comment]
Thanks,
it's working now :)
