### ISSUE TITLE
is: Undefined variable

### ISSUE THREAD

**Issue by hitcklife** [jeroennoten/Laravel-AdminLTE#653]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Undefined variable: type
| Laravel Version         | Laravel 7.*
| Project Version         | last version fresh installation with laravel

Facade\Ignition\Exceptions\ViewException
Undefined variable: type (View: ...\resources\views\vendor\adminlte\plugins.blade.php)

$type is undefined
Make the variable optional in the blade template. Replace {{ $type }} with {{ $type ?? '' }}

```

@foreach(config('adminlte.plugins') as $plugin)
    @if($plugin['active'] || View::getSection('plugins.' . $plugin['name']))
        @foreach($plugin['files'] as $file)
            {{-- Check requested file type --}}
            @if($file['type'] == $type && $type == 'css')
                <link rel="stylesheet" href="{{ $file['asset'] ? asset($file['location']) : $file['location'] }}">
            @elseif($file['type'] == $type && $type == 'js')
                <script src="{{ $file['asset'] ? asset($file['location']) : $file['location'] }}"></script>
            @endif

        @endforeach
    @endif
@endforeach


```
![image](https://user-images.githubusercontent.com/45523128/86505637-66c22e00-bd95-11ea-8108-2e460ba31f07.png)

**Comment by lacodimizer** [comment]
The type is needed and will be called to the plugins.blade.php, like the following lines in the master.blade.php:
        @include('adminlte::plugins', ['type' => 'css'])
or 
        @include('adminlte::plugins', ['type' => 'js'])

Please check the lines in your master.blade.php

**Comment by lacodimizer** [comment]
I see, you have published the views into your resources directory. So I think the blade files not up to date.
