### ISSUE TITLE
Menu Builder : Submenu

### ISSUE THREAD

**Issue by Lisendra** [jeroennoten/Laravel-AdminLTE#657]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 7.18.0
| Project Version         | 3.4.1

### Current Behavior

When building menu, if i use the method addIn() it return me:
`Facade\Ignition\Exceptions\ViewException
Undefined index: submenu_class (View: /var/www/mice/resources/views/vendor/adminlte/partials/sidebar/menu-item-treeview-menu.blade.php)`

### Expected Behavior

Expected Behavior is to get a submenu

### Steps to Reproduce

```
public function boot(Dispatcher $events)
    {
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add(
                ['text' => 'MENU PRINCIPAL', 'url' => '/home', 'icon' => 'fas fa-fw fa-home',]);
            $event->menu->add(
                ['text' => 'Devis', 'url' => '/queries', 'icon' => 'fas fa-fw fa-clipboard-list',]);
            $event->menu->add(
                ['text' => 'Clients', 'url' => '/clients', 'icon' => 'fas fa-address-book',]);
            $event->menu->add(
                ['text' => 'DMC', 'url' => '/clients', 'icon' => 'fas fa-passport',]);
            $event->menu->add(
                ['text' => 'Raports', 'url' => '/reports/index', 'icon' => 'fas fa-fw fa-chart-line',]);
            $event->menu->add(
                ['text' => 'Notifications', 'url' => '/notifications', 'icon' => 'fas fa-fw fa-bell',
                    'label' => auth()->user()->unreadNotifications()->groupBy('notifiable_type')->count(),]);
            $event->menu->add(
                ['key' => 'Admin', 'text' => 'Admin', 'url' => '/notifications', 'icon' => 'fas fa-fw fa-cogs',]);
            $event->menu->addIn('Admin',
                ['text' => 'profile', 'url' => 'profile', 'icon' => 'fas fa-fw fa-id-badge', 'icon_color' => 'red',]);
            $event->menu->addIn('Admin',
                ['text' => 'Utilisateurs', 'url' => 'users', 'icon' => 'fas fa-fw fa-users',]);
            $event->menu->addIn('Admin',
                ['text' => 'Roles', 'url' => 'roles', 'icon' => 'fas fa-fw fa-user-shield',]);

        });
    }
```

downgrading to 3.3.1 fix the issue 
already did:
- [composer update jeroennoten/laravel-adminlte ]
- [php artisan adminlte:update ]
- [php artisan adminlte:install --only=main_views --force ]
 
- [commentout in config\adminlte.php : //JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class,]

**Comment by Shidersz** [comment]
@Lisendra thanks for your detailed explanation. Try to use the next **workaround** while we find a way to resolve this issue.

Edit the file `vendor/jeroennoten/laravel-adminlte/src/Menu/Builder.php` on your local project, and replace the function `addIn()` by the **new version**:

### OLD VERSION

```php
/**
 * Add new submenu items inside a specific menu item.
 *
 * @param mixed $itemKey The key that represents the specific menu item
 * @param mixed $newItems Items to be added
 */
public function addIn($itemKey, ...$newItems)
{
    $this->addItem($itemKey, self::ADD_INSIDE, ...$newItems);
}
```

### NEW VERSION

```php
/**
 * Add new submenu items inside a specific menu item.
 *
 * @param mixed $itemKey The key that represents the specific menu item
 * @param mixed $newItems Items to be added
 */
public function addIn($itemKey, ...$newItems)
{
    $this->addItem($itemKey, self::ADD_INSIDE, ...$newItems);
    $this->menu = $this->transformItems($this->menu);
}
```
Tell me if that solves the issue...

**Comment by Lisendra** [comment]
I have made the modifications as requested and it does indeed fix the issue.

**Comment by Shidersz** [comment]
Ok, thanks @Lisendra , if you found any other issue related to this let me know. I'm going to check if there is a better way to make a fix for this issue.

**Comment by lacodimizer** [comment]
Released with v3.4.2

**Comment by mateusjunges** [comment]
@lacodimizer I've updated to `v3.4.2` and still getting this error. I fixed it with your previous suggestion. Any thougths on this?

**Comment by lacodimizer** [comment]
@mateusjunges Which error?

**Comment by Shidersz** [comment]
@mateusjunges That's rare because I have created a test for that issue, and the fix is similar to the one I have suggested. Maybe I missed something more... Can you provide and example of how are you creating the menu items that expose the failure?

**Comment by mateusjunges** [comment]
Sorry, here's a screenshot:
![image](https://user-images.githubusercontent.com/19756164/86629255-84fc7980-bfa1-11ea-8402-91fde38d572a.png)

This is what i did:
- composer update jeroennoten/laravel-adminlte
- php artisan adminlte:update

If i comment the following line in `config/adminlte.php`, this error disappears, but my submenus are not generated.
```php
JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class,
```

**Comment by mateusjunges** [comment]
I thik that `php artisan adminlte:update` did not have installed the right config file, since this filter does not exist anymore and the line above should not be there. I fixed this issue using `php artisan adminlte:insatll --only=config`, and now everything works fine. Thank you @lacodimizer and @Shidersz for your time!

**Comment by Shidersz** [comment]
The [adminlte:update](https://github.com/jeroennoten/Laravel-AdminLTE#53-the-adminlteupdate-command) is just a shortcut for `adminlte:install --force --only=assets` as explained on the **README**. It will only update the `assets` needed by `AdminLte` template on the `public/vendor` folder of your Laravel project. To update other resources, you need to execute other commands, as you have done (that is explained on the [Updating Procedure](https://github.com/jeroennoten/Laravel-AdminLTE#3-updating)).

**Comment by mateusjunges** [comment]
@Shidersz so it was my mistake. Sorry about that :confused:

**Comment by Shidersz** [comment]
@mateusjunges Not a problem, just wanted to clarify it for future readers...
