### ISSUE TITLE
Problem when running composer update

### ISSUE THREAD

**Issue by fagnerfjas** [jeroennoten/Laravel-AdminLTE#661]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 7
| Project Version         | 3.0

When executing the command "composer update" my system broke. showing this error message.

**Comment by REJack** [comment]
You need to update your views, `getBodyClasses()` was removed with v3.3.0.

**Comment by publicentro** [comment]
Sorry, what You mean with update your views?

**Comment by Shidersz** [comment]
Hi, please give a read to [Updating Section](https://github.com/jeroennoten/Laravel-AdminLTE#3-updating). Probably, you have [published the main views](https://github.com/jeroennoten/Laravel-AdminLTE#8-customize-views) and now are not compatible with the new package version. Be sure to backup the views you have published (those on `resources/views/vendor/adminlte` folder) if you have applied changes to these views.

**Comment by fagnerfjas** [comment]
@Shidersz Thanks for the tip, I ran the update procedure, but now I have a ViewException:

Facade\Ignition\Exceptions\ViewException
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist. (View: /home/fjas/Projetos/sgedu-2/resources/views/vendor/adminlte/partials/navbar/navbar.blade.php)

**Comment by Shidersz** [comment]
Review the `config/adminlte.php` file and remove `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class` from the list of filters, since that filter no longer exists on the new version. Take a look to [release of version 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0). Updating the config, or be aware of the changes it includes (if any) is also part of the update procedure. I hope that helps...

**Comment by tiagofrancafernandes** [comment]
the metod is deprecated, you have to replace "isSearchBar" with "isLegacySearch" in this files:

`resources\views\vendor\adminlte\partials\navbar\menu-item.blade.php`

`resources\views\vendor\adminlte\partials\sidebar\menu-item.blade.php`

**Comment by dfsmania** [comment]
> > Review the `config/adminlte.php` file and remove `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class` from the list of filters, since that filter no longer exists on the new version. Take a look to [release of version 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0). Updating the config, or be aware of the changes it includes (if any) is also part of the update procedure. I hope that helps...
> 
> hello, I managed to get rid of the error by removing FillterSubmenu::class but my collapse submenu became not working

@rifkimaulana54 Please provide details of your updating procedure, what's the previous version and to what version are you updating. Also, be sure to read the [Updating Guide](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) and to check all the middle releases information between the two versions on [Releases Page](https://github.com/jeroennoten/Laravel-AdminLTE/releases) to verify if any additional task is needed.

**Comment by rifkimaulana54** [comment]
> > > Review the `config/adminlte.php` file and remove `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class` from the list of filters, since that filter no longer exists on the new version. Take a look to [release of version 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0). Updating the config, or be aware of the changes it includes (if any) is also part of the update procedure. I hope that helps...
> > 
> > 
> > hello, I managed to get rid of the error by removing FillterSubmenu::class but my collapse submenu became not working
> 
> @rifkimaulana54 Please provide details of your updating procedure, what's the previous version and to what version are you updating. Also, be sure to read the [Updating Guide](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) and to check all the middle releases information between the two versions on [Releases Page](https://github.com/jeroennoten/Laravel-AdminLTE/releases) to verify if any additional task is needed.

Previously I used v2.*

**Comment by rifkimaulana54** [comment]
> > > Review the `config/adminlte.php` file and remove `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class` from the list of filters, since that filter no longer exists on the new version. Take a look to [release of version 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0). Updating the config, or be aware of the changes it includes (if any) is also part of the update procedure. I hope that helps...
> > 
> > 
> > hello, I managed to get rid of the error by removing FillterSubmenu::class but my collapse submenu became not working
> 
> @rifkimaulana54 Please provide details of your updating procedure, what's the previous version and to what version are you updating. Also, be sure to read the [Updating Guide](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) and to check all the middle releases information between the two versions on [Releases Page](https://github.com/jeroennoten/Laravel-AdminLTE/releases) to verify if any additional task is needed.

Previously I used v2.* and upgraded to v3.9

**Comment by dfsmania** [comment]
> > > > Review the `config/adminlte.php` file and remove `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class` from the list of filters, since that filter no longer exists on the new version. Take a look to [release of version 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0). Updating the config, or be aware of the changes it includes (if any) is also part of the update procedure. I hope that helps...
> > > 
> > > 
> > > hello, I managed to get rid of the error by removing FillterSubmenu::class but my collapse submenu became not working
> > 
> > 
> > @rifkimaulana54 Please provide details of your updating procedure, what's the previous version and to what version are you updating. Also, be sure to read the [Updating Guide](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) and to check all the middle releases information between the two versions on [Releases Page](https://github.com/jeroennoten/Laravel-AdminLTE/releases) to verify if any additional task is needed.
> 
> Previously I used v2.* and upgraded to v3.9 ![image](https://user-images.githubusercontent.com/57777693/274347147-4abee71b-9399-4beb-afbb-78544484081e.png)

Wow, that's a huge jump since `v2.*` was based on `AdminLTE v2` and `v3.*` is based on `AdminLTE v3`. Also, `v2.*` versions only supported until `Laravel 6` and some things from `v3` may not work on `Laravel 6`. I'm not really sure how to proceed in your case, but for sure you will be facing a lot of issues and conflicts. I would rather start a new project with latest `Laravel` and `AdminLTE` in this case and migrate your old admin panel slowly to the new project (but this is only my opinion).

**Comment by rifkimaulana54** [comment]
> > > > > Tinjau `config/adminlte.php`file dan hapus `JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class`dari daftar filter, karena filter tersebut tidak ada lagi di versi baru. Lihatlah [rilis versi 3.4.0](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.4.0) . Memperbarui konfigurasi, atau mengetahui perubahan yang ada di dalamnya (jika ada) juga merupakan bagian dari prosedur pembaruan. Saya harap itu membantu...
> > > > 
> > > > 
> > > > halo, saya berhasil menghilangkan kesalahan dengan menghapus FillterSubmenu::class tetapi submenu ciutkan saya tidak berfungsi
> > > 
> > > 
> > > @rifkimaulana54Harap berikan rincian prosedur pembaruan Anda, versi apa sebelumnya, dan ke versi apa yang Anda perbarui. Selain itu, pastikan untuk membaca [Panduan Pembaruan](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) dan memeriksa semua informasi rilis tengah antara kedua versi di [Halaman Rilis](https://github.com/jeroennoten/Laravel-AdminLTE/releases) untuk memverifikasi apakah ada tugas tambahan yang diperlukan.
> > 
> > 
> > Sebelumnya saya menggunakan v2.* dan mengupgrade ke v3.9![gambar](https://user-images.githubusercontent.com/57777693/274347147-4abee71b-9399-4beb-afbb-78544484081e.png)
> 
> Wow, itu lompatan besar sejak `v2.*`didasarkan pada `AdminLTE v2`dan `v3.*`didasarkan pada `AdminLTE v3`. Selain itu, `v2.*`versi hanya didukung hingga `Laravel 6`dan beberapa hal darinya `v3`mungkin tidak berfungsi `Laravel 6`. Saya tidak begitu yakin bagaimana melanjutkan kasus Anda, tetapi yang pasti Anda akan menghadapi banyak masalah dan konflik. Saya lebih suka memulai proyek baru dengan yang terbaru `Laravel`dan `AdminLTE`dalam hal ini dan memigrasikan panel admin lama Anda secara perlahan ke proyek baru (tapi ini hanya pendapat saya).

Hmm, thank you for your response and suggestions
