### ISSUE TITLE
View Error

### ISSUE THREAD

**Issue by srealm** [jeroennoten/Laravel-AdminLTE#662]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 6.18.24
| Project Version         | 3.4.2

### Current Behavior

When navigating to a view using the extending the adminlte:page view the following error is thrown. I've checked the source code and the class no longer exists (did in previous versions). The functionality seems to have been moved to a helper file but perhaps there is still some reference to the old location.
Facade\Ignition\Exceptions\ViewException
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist. (View: /home/srds/Projects/myacbl-laravel/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php)

**Comment by Shidersz** [comment]
Hi @srealm , please check if #652 helps... I believe the adminlte.php config file need an update...
