### ISSUE TITLE
Dashboard page has not good look

### ISSUE THREAD

**Issue by Yarandi** [jeroennoten/Laravel-AdminLTE#666]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 6.x
| Project Version         | ^3.4

### Current Behavior

After installing  adminlte package Dashboard page is not render as well as expected, this is my view:

![Screen Shot 2020-07-12 at 08 33 24](https://user-images.githubusercontent.com/1158575/87238640-87842680-c41a-11ea-85e1-58e860761ae5.png)

![Screen Shot 2020-07-12 at 08 38 31](https://user-images.githubusercontent.com/1158575/87238697-198c2f00-c41b-11ea-962c-c0528b66b6d5.png)

**Comment by Shidersz** [comment]
Hi @Yarandi  try running `php artisan adminlte:update`, when executing `adminlte:status` you should read **Installed** keyword for the `AdminLTE v3` asset. For some reason, it appears that the adminlte stylesheets where not installed. Also check that the structure of the `public/vendor/adminlte` folder is like next one:

```
public/vendor/adminlte/
└── dist
    ├── css
    │   ├── adminlte.css
    │   ├── adminlte.css.map
    │   ├── adminlte.min.css
    │   └── adminlte.min.css.map
    ├── img
    │   └── AdminLTELogo.png
    └── js
        ├── adminlte.js
        ├── adminlte.js.map
        ├── adminlte.min.js
        └── adminlte.min.js.map
```

**Comment by Yarandi** [comment]
Hi @Shidersz  Thank for response,
