### ISSUE TITLE
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist.

### ISSUE THREAD

**Issue by EvanSchleret** [jeroennoten/Laravel-AdminLTE#669]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 7.20.0
| Project Version         | 3.4.3

### Current Behavior
Target class [JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter] does not exist.

### Expected Behavior
It should work fine.

### Steps to Reproduce
I just updated my app to the latest version. Then I refreshed my tab and the error shows up.
I tried to clear cache of application and follow the instructions on https://github.com/jeroennoten/Laravel-AdminLTE#3-updating but it still not working.

### Possible Solutions
No idea.

Thanks in advance!

**Comment by lacodimizer** [comment]
Please read the release infos of v3.4.0 to solve the issue.

**Comment by EvanSchleret** [comment]
Oops, sorry ! I havent see this release info.
Thank you !
