### ISSUE TITLE
ISSUE: [Symfony\Component\Console\Exception\InvalidArgumentException] The "force" option does not exist.  

### ISSUE THREAD

**Issue by gdfox** [jeroennoten/Laravel-AdminLTE#67]
When I run: php artisan make:adminlte
I get:                                                                
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "force" option does not exist.                              

Running Laravel 5.4

**Comment by jeroennoten** [comment]
Fixed in v1.19.2
