### ISSUE TITLE
Search on side menu didn't hide entirely when minimize?

### ISSUE THREAD

**Issue by seirralanzce** [jeroennoten/Laravel-AdminLTE#674]
![image](https://user-images.githubusercontent.com/1050583/88027085-5ec20680-cb69-11ea-9896-216d54220d78.png)

in the image above is when the side menu is expanded,
when minimize, it became like this

![image](https://user-images.githubusercontent.com/1050583/88027185-77322100-cb69-11ea-9226-fba7b453964b.png)

**Comment by lacodimizer** [comment]
@REJack Can you check this please?

**Comment by REJack** [comment]
@lacodimizer Yep, I'll check it later this day

**Comment by lacodimizer** [comment]
@REJack any news?

**Comment by REJack** [comment]
This is fix in master branch and will released with v3.1.0 soon.

**Comment by resslinger** [comment]
@REJack

**Comment by REJack** [comment]
This will be fixed with AdminLTE v3.1.0.
