### ISSUE TITLE
ISSUE: Hebrew language support (RTL)

### ISSUE THREAD

**Issue by bennyadar** [jeroennoten/Laravel-AdminLTE#676]
QUESTION: 
Is there a RTL support ?
I can provide hebrew lang file if needed.
Of course, I would be glad to help in other things also as possible.
Thanks

**Comment by REJack** [comment]
There is no RTL Support in AdminLTE & Laravel-AdminLTE

**Comment by lacodimizer** [comment]
Duplicate to #197
