### ISSUE TITLE
Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses()

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#678]
| Question                       | Answer
| ------------------------   | -----------------------
| Issue or Enhancement   | Issue
| Laravel Version              | 6.2
| Project Version              | 3.4.2
            
### Current Behavior

After running composer update, the application no longer works, spitting out the exception:
[https://i.imgur.com/MfqxkSf.png](url)

### Expected Behavior

Well, the expected behavior would be showing the page without the error.

### Steps to Reproduce

Ran composer update and application now errors out.

Note: already tried to delete the vendor folder and run composer install again, didn't work.

**Comment by lacodimizer** [comment]
@MathiasOliveira Please check the update infos in the readme:
https://github.com/jeroennoten/laravel-adminlte#3-updating

I think you use the old main views and you have to update this (point 3.3).

Why do you not use the actual version v3.4.4?

**Comment by MathiasOliveira** [comment]
There was a mistake in the original issue, the version used was 3.4.2 not 3.0.4.

The issue was fixed by downgrading to v3.2.0, thank you for the help.

**Comment by lacodimizer** [comment]
You can use 3.4.4 or 3.4.2 too, but you have to update your local main views. That's all.
