### ISSUE TITLE
Undefined variable: adminlte

### ISSUE THREAD

**Issue by gdias1992** [jeroennoten/Laravel-AdminLTE#681]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 7.22.4
| Project Version         | 3.4

**Description**
I created a copy of "page.blade.php" called "pagefull.blade.php" with no changes in the file content.

But i am receiving the error "Undefined variable: adminlte" when trying to extend the new file.

Does anyone know how to fix this ?

**Images**
![image](https://user-images.githubusercontent.com/25283876/89141394-e705bb80-d51a-11ea-9276-28e8f7a86709.png)
![image](https://user-images.githubusercontent.com/25283876/89141567-4bc11600-d51b-11ea-8263-5487d58983d9.png)
![image](https://user-images.githubusercontent.com/25283876/89141346-b9b90d80-d51a-11ea-918d-377e9b8cb0b0.png)

**Comment by Shidersz** [comment]
Hi @gdias1992 in that case you will need to register a new **view composer**. Try editing the file: `vendor/jeroennoten/laravel-adminlte/src/AdminLteServiceProvider.php` and change method `registerViewComposers()` like this:

```php
/**
 * Register the package's view composers.
 *
 * @return void
 */
private function registerViewComposers(Factory $view)
{
    $view->composer('adminlte::page', AdminLteComposer::class);

    // Add next new line...
    $view->composer('adminlte::pagefull', AdminLteComposer::class);
}
```

Tell me if that works...

**Comment by gdias1992** [comment]
@Shidersz Thank you!

**Comment by KillerShaw** [comment]
making change on vendor is a good idea ? i am facing the same issue but i am confused,,,,..

**Comment by Shidersz** [comment]
@KillerShaw Personally, I don't consider it a good idea. In this particular case, every package update will overwrite the file and you will need to redo the change again. The package was designed with the idea that you extends the `page.blade.php` file ([Usage](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/4.-Usage)) and the `adminlte` variable is internal to the package. You can also edit all the package blade view files if you first [Publish the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/11.-Customize-Views). I`m not really sure why you will need a new copy of the mentioned file, but in that case I can't think another idea to make it work.

**Comment by KillerShaw** [comment]
Yes offcourse i actually extended the master file for my views which was my mistake. But generally its not a good advice/idea to change anything in vendor subfolders just pointing it out. Thanks by the way

**Comment by thalesbarbosab** [comment]
Create a new blade layout file extends admin lte layout "@extends('adminlte::page')" and use create any things inside this file and use it on your views.

**Comment by oyepez003** [comment]
You can add the AdminLteComposer in a new Provider or inside the AppServiceProvider:

```
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Contracts\View\Factory;
use JeroenNoten\LaravelAdminLte\Http\ViewComposers\AdminLteComposer;

class AppServiceProvider extends ServiceProvider
{
    ...
    public function boot(Factory $view)
    {
        $view->composer('layouts.page', AdminLteComposer::class);
    }
   ...
}
```
