### ISSUE TITLE
how to configure vuejs in this project please

### ISSUE THREAD

**Issue by temesgenmhr** [jeroennoten/Laravel-AdminLTE#682]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

**Comment by lacodimizer** [comment]
have you check the issue #423 ?

**Comment by lacodimizer** [comment]
Closed, no new response.
