### ISSUE TITLE
Call to a member function compileColumnListing() on null (View: /Users/anang.maruf/Documents/codes/amelia-profile/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php)

### ISSUE THREAD

**Issue by anangmaruf** [jeroennoten/Laravel-AdminLTE#684]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 6.18.35
| Project Version         | 3.4

after i'm install adminlte version 3.4, i have some issue
Call to a member function compileColumnListing() on null (View: /Users/anang.maruf/Documents/codes/amelia-profile/vendor/jeroennoten/laravel-adminlte/resources/views/partials/navbar/navbar.blade.php)

how i solve this problem

**Comment by REJack** [comment]
Did you upgraded Laravel-AdminLTE from 3.X to 3.4 or it is a complete fresh installation?

**Comment by anangmaruf** [comment]
it is a complete fresh installation, how can i resolve this ?

**Comment by Shidersz** [comment]
Hi @anangmaruf , can you add more details about the error, for example, the line where the error occurs. On the other hand, have you created the user's table and respective model (`app/User.php`)?

**Comment by lacodimizer** [comment]
Closed, no new response.
