### ISSUE TITLE
usermenu_enabled is set to true,but the user menu does not display on top nav

### ISSUE THREAD

**Issue by ChunhaoXiao** [jeroennoten/Laravel-AdminLTE#685]
I have set the  'usermenu_enabled' => true, in the config file, But the user menu does not display on the top right of the nav

**Comment by alibaba258** [comment]
Same Problem here. Any efforts?

**Comment by lacodimizer** [comment]
You have to update the main views, please take a look into the readme.

**Comment by alibaba258** [comment]
Thanks for your quick reply. I use a fresh installation of the package. Anyway i updated the views with no luck. Still same error.
