### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by iHeartBard** [jeroennoten/Laravel-AdminLTE#690]
Hey,

Is there a safe way to change the colors for adminlte 3 (eg. primary color)?

I read somewhere that you have to change the bootstrap colors to achieve this but I've tried and it doesn't do anything.

**Comment by REJack** [comment]
You want to replace the default primary color?

**Comment by iHeartBard** [comment]
Yes, and the only way I found how to do this is by overwriting classes.

**Comment by MarekMaz** [comment]
That would be awesome if we could set the colour variables in the config file

**Comment by REJack** [comment]
> That would be awesome if we could set the colour variables in the config file

That would not work, you need to recompile the existing css files and replace them otherwise your won't get custom colors.
Laravel-AdminLTE comes not with own CSS files it uses the AdminLTE CSS files.
