### ISSUE TITLE
QUESTION: remove repository and use adminlte views

### ISSUE THREAD

**Issue by Barmunksu** [jeroennoten/Laravel-AdminLTE#692]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 6
| Project Version         | laravel6-adminlte2

Hello! i want remove package and use only adminlte views. I edited all dependency from config file, like settings, names, lang and etc. but I don't know what to do with "filters" and menu items

```php
// config/adminlte.php

'filters' => [
    JeroenNoten\LaravelAdminLte\Menu\Filters\HrefFilter::class,
    JeroenNoten\LaravelAdminLte\Menu\Filters\ActiveFilter::class,
    JeroenNoten\LaravelAdminLte\Menu\Filters\SubmenuFilter::class,
    JeroenNoten\LaravelAdminLte\Menu\Filters\ClassesFilter::class,
    JeroenNoten\LaravelAdminLte\Menu\Filters\GateFilter::class,
]
```

```php
// AppServiceProvider.php

$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
     $event->menu->add('MAIN NAVIGATION');
     $event->menu->add([
          'text' => 'Blog',
           'url' => 'admin/blog',
      ]);
});
```

Can you help me transfer this code?

**Comment by lacodimizer** [comment]
That's not a good idea, we don't recommend this.
