### ISSUE TITLE
Dynamic Menu By Controller Example

### ISSUE THREAD

**Issue by Sameer911** [jeroennoten/Laravel-AdminLTE#694]
$this->dynamicMenu(); what to pass in parameter . ??

function dynamicMenu(Dispatcher $events){
// some conditions
$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
$event->menu->remove('dashboard');
$event->menu->remove('users');
$event->menu->remove('users');
// or add any other menu here
});
}

**Comment by Shidersz** [comment]
Hi @Sameer911 , first it will be nice to have some overview or explanation of what are your goals. Otherwise it is hard to understand what are you trying to achieve. On the other hand, you can use the **Event Facade** to access the `Laravel's Dispatcher Service Provider` from a controller, for example:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;

// Note next two lines:
use Illuminate\Support\Facades\Event;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;

class TestController extends Controller
{
    ...
    ...
    public function dynamicMenu()
    {
        Event::listen(BuildingMenu::class, function(BuildingMenu $event)
        {
            $event->menu->remove('dashboard');
            $event->menu->remove('users');
            $event->menu->remove('users');
            // or add any other menu here
        }); 
    }
    ...
}
```

**Comment by Sameer911** [comment]
Thankyou for no Replying solved it :)

Incase for future readers, no need to create a function just use Dispatcher Inside constructer laravel will auto understand what is dispatcher; 

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Dispatcher $events)
    {
//        $this->middleware('auth');
         $events->listen(BuildingMenu::class, function (BuildingMenu $event)
   { 
          $event->menu->add([ 'text' => 'Blog', 'url' => 'admin/blog', ]); });
    }

}

**Comment by Sameer911** [comment]
Thankyou Dear, 

I was missing that use Illuminate\Support\Facades\Event;

but for now I used dispatcher inside Constructer and it works for me. 

Thanks Again!.

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Dispatcher $events)
    {
         $events->listen(BuildingMenu::class, function (BuildingMenu $event)
        { 
          $event->menu->add([ 'text' => 'Blog', 'url' => 'admin/blog', ]); });
         }

}

**Comment by Shidersz** [comment]
@Sameer911 Yea, that is called **Dependency Injection** and is a feature available in `Laravel`. In that case, if you need to use the `Dispatcher` outside the constructor, you need to save it into a controller's variable. Example:

```php
class HomeController extends Controller
{
    protected $events;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Dispatcher $events)
    {
        $this->events = $events;
    }

    public dynamicMenu()
    {
        $this->events->listen(BuildingMenu::class, function (BuildingMenu $event)
        {
            $event->menu->add([ 'text' => 'Blog', 'url' => 'admin/blog', ]); });
        }
    }
}
````
