### ISSUE TITLE
Select2 css is not working properly

### ISSUE THREAD

**Issue by Tropicalista** [jeroennoten/Laravel-AdminLTE#70]
This is probably due to the fact that this [line ](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/master.blade.php#L25) should be inserted before of adminlte css is inserted.

**Comment by Lvkz** [comment]
Hello, I'm facing the same problem, @Tropicalista did you found a way to fix it or a workaround while they fix this issue?

**Comment by Lvkz** [comment]
@Tropicalista, @jeroennoten  I think that we could add it as a plugin like the 'DataTable plugin' is set - before the AdminLTE CSS.

**Comment by jeroennoten** [comment]
Seems like a plan. Could you submit a PR for this? That would be awesome!
