### ISSUE TITLE
array_replace_recursive(): Expected parameter 2 to be an array, int given

### ISSUE THREAD

**Issue by mateusjunges** [jeroennoten/Laravel-AdminLTE#704]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|
| Laravel Version         | 8.4.0
| Project Version         | 3.4.4

### Current Behavior

When i have any item in `config/adminlte.php` `menu` array, the error in the screenshot appears. If i remove my menu items from the config file, this error disappears.
![image](https://user-images.githubusercontent.com/19756164/93371069-20269080-f828-11ea-9c03-fa9bb3b90f2f.png)

**Comment by mateusjunges** [comment]
While debugging it, i  found out that if i commend the `LangFilter` in adminlte configuration file the menu works fine.

**Comment by Shidersz** [comment]
@mateusjunges Thanks for your feedback. Are you using the default `menu` configuration that comes with the package or you have added some custom menu items? In the latest case, can you provide an example of the menu configuration?

**Comment by mateusjunges** [comment]
@Shidersz This is my menu configuration:
```php
    'menu' => [
        [
            'text' => 'Home',
            'url' => 'home',
            'icon' => 'fas fa-fw fa-home',
            'class' => '',
        ],
        [
            'text' => 'My route groups',
            'route' => 'route-groups.index',
            'icon' => 'fas fa-fw fa-route'
        ]
    ],
```

**Comment by Shidersz** [comment]
@mateusjunges Appears to be a problem when trying to load a locale file for translations.
- What locale are you using in your application?
- Have you published the package translations files (i.e did you see the folder: `resources/lang/vendor/adminlte/`)?

**Comment by mateusjunges** [comment]
I was using `en` and `pt-br`, depending on the authenticated user locale. I checked the file you specified and the `pt-br/menu.php` file was empty. I added the key/value pairs and now it works fine. 
Thank you @Shidersz :smile:

**Comment by kerimtim** [comment]
God bless you man! There is no way I could have figured that out myself.
Today in the morning, I added /resources/lang/ru/validation.php,
Just removed it, and everything works.
