### ISSUE TITLE
Pass param to text attributes

### ISSUE THREAD

**Issue by alr2413** [jeroennoten/Laravel-AdminLTE#708]
is it possible to pass parameters to text/header field attributes like "trans" method?
thanks

**Comment by Shidersz** [comment]
Can you give a better explanation of what you need? In the case you need to translate `text` and `header` attributes, please refer to [Menu Translation](https://github.com/jeroennoten/Laravel-AdminLTE#101-menu-translations) documentation.

**Comment by alr2413** [comment]
Yea,
In "trans" method you can pass extra parameters to the translated string, for example:
`trans(str_key, ['foo' => 'sth', 'bar' => '...'])` where str_key is "`bla bla bla :foo and :bar`" in the language file.

**Comment by Shidersz** [comment]
I believe it is not supported right now, but this will be a nice feature to be included. I will work on it later...

**Comment by alr2413** [comment]
Thanks @Shidersz.
I've done that already in PR #710. 
Waiting for merge...

**Comment by lacodimizer** [comment]
Thank you for your merge request. It will be published with the next release.
