### ISSUE TITLE
Verify Email with Auth

### ISSUE THREAD

**Issue by lalanankit** [jeroennoten/Laravel-AdminLTE#711]
Laravel Version 8 and Admin LTE as from the repository.

###Current behavior
Unable to send emails for reset password or user registration.

### Expected Behavior
Sending emails and Verified At timestamp populated to users table.

![Screen Shot 2020-09-23 at 12 42 05 AM](https://user-images.githubusercontent.com/71725903/93925334-b6314e00-fd35-11ea-81d9-cb9f3002b60a.png)

Changes done to RegisterController
![Screen Shot 2020-09-23 at 12 43 45 AM](https://user-images.githubusercontent.com/71725903/93925475-ea0c7380-fd35-11ea-910a-8a65fff34e04.png)

Changes to user model:

```
class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

```

Changes to routes, web.php

`Auth::routes(['verify' => true]);`

**Comment by lacodimizer** [comment]
Please create an issue on the Laravel project. This is not an issue on this package.
