### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by lalanankit** [jeroennoten/Laravel-AdminLTE#715]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 8.0
| Project Version         | 3.4

### Current Behavior

I have the auth from this package. But Form validation on the signup does not seems to be responsive to text. Example: I have a failed validation for "required" First Name. When I enter any value to it, the form still shows the validation error.

### Expected Behavior

If the validation criteria is met and form is not submitted, the error message should not be displayed. As reference from AdminLTE version 3 Validation. Here is the link to reference - https://adminlte.io/themes/v3/pages/forms/validation.html

### Steps to Reproduce

1. Install the package in Laravel 8
2. Click to Register
3. Enter No values to the Register and click Submit.
4. Validation fails error will be displayed.
5. Put the value to any required text box.

BINGO: You will see the error messaging still displayed.

### Possible Solutions
Calling Adminlte AJAX for form validation.

### Screenshot
![Screen Shot 2020-09-25 at 12 43 50 PM](https://user-images.githubusercontent.com/71725903/94236347-cb240200-ff2c-11ea-9e99-7c2ed35f697c.png)

**Comment by REJack** [comment]
The Form Validation is correct that's simply the expected behavior, it only checks the fields on submit there are no AJAX functions included.

> As reference from AdminLTE version 3 Validation. 

Thats not a reference its only a way to do it, also the demo is intended to test without any backend framework like Laravel or other that's why there is a simple JS Validation script built in the demo.
