### ISSUE TITLE
Show/hide menus in sidebars depending on the user roles

### ISSUE THREAD

**Issue by sweggggg** [jeroennoten/Laravel-AdminLTE#72]
Is it possible to this? How?

**Comment by jeroennoten** [comment]
Yes, see section 5.1 of the README: https://github.com/jeroennoten/Laravel-AdminLTE#51-menu

**Comment by sweggggg** [comment]
so i go through the README, the '@can' works fine, but is it possible to use '@role' to define which role that can view the sidebar links

for example

```
[
            'text'        => 'Users',
            'url'         => 'users',
            'icon'        => 'file',
            'label_color' => 'success',
            'can'         => 'manage-blog',
            'role'        => 'User',
 ],
```

**Comment by jeroennoten** [comment]
Yes, you could implement this with a custom menu filter: https://github.com/jeroennoten/Laravel-AdminLTE#custom-menu-filters

Please reopen this issue if you're not able to figure out how to do it.

**Comment by sarowerj** [comment]
Can anyone please tell me, in which directory i will create `MyMenuFilter` Class

**Comment by SyedSohail** [comment]
is this possible to assign menu to different user base on auth guard

**Comment by theshook** [comment]
> 
> 
> Can anyone please tell me, in which directory i will create `MyMenuFilter` Class

hey there! where did you put your MyMenuFilter Class?

**Comment by dbvgonezoren** [comment]
> Can anyone please tell me, in which directory i will create `MyMenuFilter` Class



> > Can anyone please tell me, in which directory i will create `MyMenuFilter` Class
> 
> hey there! where did you put your MyMenuFilter Class?

inside `JeroenNoten\LaravelAdminLte\Menu\Filters`

**Comment by xmush** [comment]
> is this possible to assign menu to different user base on auth guard?

just define the gate, then configure it in menu with key 'can',

this is my example in AuthServiceProvider.php  :
`
    public function boot() {
        $this->registerPolicies();

        Gate::define('user', function () {
            return Auth::user()->role->type == 'user';
        });

        Gate::define('admin', function () {
            return Auth::user()->role->type == 'admin';
        });

        Gate::define('root', function () {
            return Auth::user()->role->type == 'root';
        });
    }
`
then in config/adminlte.php :
`
        ['header' => 'CLASS'],
        [
            'text' => 'Class',
            // 'url'  => 'class/',
            'icon' => 'fas fa-fw fa-university',
            'submenu' => [
                [
                    'text' => 'My Class',
                    'url'  => '#',
                    'can' => ['user', 'admin']
                ],
                [
                    'text' => 'Pick Class',
                    'url'  => '#',
                    'can'  => ['admin'],
                ],
            ],
        ],
`

**Comment by xmush** [comment]
> is this possible to assign menu to different user base on auth guard?

just defini your auth guard in AuthServiceProvider.php as a gate, then use it in menu with key can
