### ISSUE TITLE
Can we add display condition for each item in the left sidebar?

### ISSUE THREAD

**Issue by jaysonhubt** [jeroennoten/Laravel-AdminLTE#725]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | 8.6.0
| Project Version         | 3.0.5

Can we add display condition for each item in the left menu?
Example: I want to have 2 menus for 2 different types of users. 1 for normal user, 1 for admin.

Thanks for reading!

**Comment by Shidersz** [comment]
@jaysonhubt Yes, take a read to the `can` attribute on the [Menu Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration) documentation. Also, you will need to be familiar with [Laravel's Gate](https://laravel.com/docs/8.x/authorization#gates).

**Comment by jaysonhubt** [comment]
> @jaysonhubt Yes, take a read to the `can` attribute on the [Menu Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration) documentation. Also, you will need to be familiar with [Laravel's Gate](https://laravel.com/docs/8.x/authorization#gates).

Many thanks, Shidersz!
