### ISSUE TITLE
How to show count variable in menu ?

### ISSUE THREAD

**Issue by thuram** [jeroennoten/Laravel-AdminLTE#73]
How to pass an variable in label for adminlte.php

`'menu' => [
    'MAIN NAVIGATION',
    [
        'text'        => 'Pages',
        'url'         => 'admin/pages',
        'icon'        => 'file',
        'label'       => count($all_pages) // How to pass variable here,
        'label_color' => 'success',
    ],
];`

**Comment by jeroennoten** [comment]
Hi, you should use 'Menu configuration at runtime', as described in the README: https://github.com/jeroennoten/Laravel-AdminLTE#menu-configuration-at-runtime
