### ISSUE TITLE
Adding logo saved in database and update it accordingly

### ISSUE THREAD

**Issue by Nipace** [jeroennoten/Laravel-AdminLTE#731]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

### Current Behavior

I am able to get a static logo from public folder and display it

### Expected Behavior

I want to add a logo. But my logo is dynamic i.e it may change and i want to display the dynamic logo in my view.

**Comment by Shidersz** [comment]
You can change [configuration at runtime](https://laravel.com/docs/8.x/configuration#accessing-configuration-values) on Laravel. So you can update the `logo` configuration before loading (rendering) your view, for example:

```php
config([
    'adminlte.logo' => 'newLogoText',
    'adminlte.logo_img' => 'new/logo/img.png',
]);
```

If you going to apply this logic on all the routes, maybe a [middleware](https://laravel.com/docs/8.x/middleware) will be adequate for you.
