### ISSUE TITLE
LINK HREF

### ISSUE THREAD

**Issue by KenntLao** [jeroennoten/Laravel-AdminLTE#734]
How can i change my link to root path, from <a href="http//domain.com/folder/file to"> to <a href="/folder/file to"> ? thanks!

**Comment by Shidersz** [comment]
Hi @KenntLao , can you give an example of what you need?

**Comment by KenntLao** [comment]
from <   a  href ="http://sample.com/folder/file" > to <   a  href ="folder/file" >  on the sidebar nav links

**Comment by Shidersz** [comment]
I'm not really sure if you can do that right now. The `href`attribute for menu links is generated using the Laravel [UrlGenerator.to()](https://laravel.com/api/8.x/Illuminate/Contracts/Routing/UrlGenerator.html#method_to) method. The idea is that you define the `url` attribute for the menu item and then capture the request with a route definition (read [Routing](https://laravel.com/docs/8.x/routing)):

```php
Route::get('/folder/file', function () {
   /* Return or do what you want here */
});
```

Anyway, if you want you can edit file `vendor/jeroennoten/laravel-adminlte/src/Menu/Filters/HrefFilter.php` and change method `transform()` like this:

```php
/**
 * Transforms a menu item. Make the href attribute when situable.
 *
 * @param array $item A menu item
 * @return array The transformed menu item
 */
public function transform($item)
{
    if (! MenuItemHelper::isHeader($item)) {
        $item['href'] = isset($item['forceCustomUrl']) ? $item['url'] : $this->makeHref($item);
    }

    return $item;
}
```

Then you can define your menu item like this on configuration:

```php
[
    'text' => 'Custom link',
    'url' => 'folder/file',
    'forceCustomUrl' => true,
],
```

**Comment by lacodimizer** [comment]
@Shidersz we can add a config option to generate nav links without url global. What do you think about this?

**Comment by Shidersz** [comment]
@lacodimizer I don't know, I can't see a situation (or a general scenario) where this will be useful. In my opinion the package already have a lot of options, and we should try to avoid adding options for very particular situations. But this is only my opinion, I may be wrong...

@KenntLao can you explain what's the reason behind your requirement?
