### ISSUE TITLE
Is it possible to add other options to the user menu?

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#743]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | 8.10.0
| Project Version         | 3.5.0

### Current Behavior

![image](https://user-images.githubusercontent.com/67007152/96505355-5f337180-122c-11eb-801e-2e0a241f8c33.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/67007152/96505262-41660c80-122c-11eb-90a1-53325517116e.png)

### Possible Solutions

Maybe adding an array of options like for the user menu would help, something like:
```
/*
|--------------------------------------------------------------------------
| User Menu
|--------------------------------------------------------------------------
|
| Here you can activate and change the user menu.
|
| For more detailed instructions you can look here:
| https://github.com/jeroennoten/Laravel-AdminLTE/#64-user-menu
|
*/

'usermenu_enabled' => true,
'usermenu_header' => true,
'usermenu_header_class' => 'bg-primary',
'usermenu_image' => false,
'usermenu_desc' => false,
'usermenu_profile_url' => false,
'usermenu_options' => [
	[
		'text'    => 'Settings',
		'icon'    => 'nav-icon fas fa-cogs',
		'submenu' => [
			[
				'text'  => 'Profile',
				'route' => 'admin.profile',
				'icon'  => 'nav-icon fas fa-user-cog',
			],
			[
				'text'  => 'Help',
				'route' => 'admin.support',
				'icon'  => 'nav-icon fas fa-question-circle',
			],
		],
	],
	[
		'text'        => 'About',
		'route'       => 'admin.about',
		'icon'        => 'nav-icon fas fa-info-circle',
	],
],
```

**Comment by Shidersz** [comment]
You can use `topnav_user` option on the menu configuration (read [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#the-topnav-topnav_right-and-topnav_user-attributes)), for example:

```php
[
    'text' => 'Settings',
    'icon' => 'fas fa-user-cog',
    'icon_color' => 'info',
    'topnav_user' => true,
    'url' => 'some/url',
],
```

**Comment by MathiasOliveira** [comment]
I see, thanks for the help!
