### ISSUE TITLE
QUESTION: Usage in multi-auth application

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#744]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | 6.18.43
| Project Version         | 3.5.0

I am creating a multi-auth application that uses different guards for different type of users. Eg. Admin User has admin guard, Partner users have `partner`, Customers have the default `web` guard.

### Current Behavior
I have tried using Laravel's Gate (can-xxxx attributes) to show different menu items to different type of users, which while not being elegant, works correctly. However, changing other options like urls (profile, dashboard, logout) , logos, or layout depending on the user guard doesn't seem to be possible.

### Possible Solutions
The solution in my mind is to load different adminlte config files depending on some parameter like the auth guard of the logged in user. The guard is set when the Controller is created using auth middleware.

What would be the right way to do this?

**Comment by Shidersz** [comment]
I believe you need to generate the menu dynamically at run time. Please, take a look to section [Menu Configuration At Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime). Also, search on the closed issues, I'm sure there are multiple discussions about this with some ideas that can help you.

**Comment by Shidersz** [comment]
@lacodimizer Consider closing this, there is no feedback after long time.
