### ISSUE TITLE
Intractive installation doesn't work

### ISSUE THREAD

**Issue by cupcodei** [jeroennoten/Laravel-AdminLTE#745]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.10
| Project Version         | 3.5

### Current Behavior

C:\Laravel>php artisan adminlte:install --interactive

 Install the basic package assets? (yes/no) [no]:
 > The installation is complete.

### Expected Behavior

It should let me choose the answer but after printing first question it says 
The installation is complete.
and actually nothing being installed

### Steps to Reproduce

composer require jeroennoten/laravel-adminlte
php artisan adminlte:status

All resources checked succesfully!

+------------------+------------------------------------------+---------------+----------+
| Package Resource | Description                              | Status        | Required |
+------------------+------------------------------------------+---------------+----------+
| assets           | The AdminLTE required assets             | Not Installed | true     |
| config           | The default package configuration file   | Not Installed | true     |
| translations     | The default package translations files   | Not Installed | true     |
| main_views       | The default package main views           | Not Installed | false    |
| auth_views       | The default package authentication views | Mismatch      | false    |
| basic_views      | The default package basic views          | Mismatch      | false    |
| basic_routes     | The package routes                       | Not Installed | false    |
+------------------+------------------------------------------+---------------+----------+

Status legends:
+---------------+----------------------------------------------------------------------------------------------+
| Status        | Description                                                                                  |
+---------------+----------------------------------------------------------------------------------------------+
| Installed     | The resource is installed and matches with the default package resource                      |
| Mismatch      | The installed resource mismatch the package resource (update available or resource modified) |
| Not Installed | The package resource is not installed                                                        |
+---------------+----------------------------------------------------------------------------------------------+

php artisan adminlte:install --interactive

**Comment by Shidersz** [comment]
What **Operating System** you are using? Also, what is your **php** version?
On my Linux distribution all works nicely, these are the steps I have follow for install Laravel and package:
```sh
composer create-project --prefer-dist laravel/laravel <app_name>
cd <app_name>
composer require jeroennoten/laravel-adminlte
php artisan adminlte:install --interactive
```

where `<app_name>` is the name of your application...

**Comment by cupcodei** [comment]
I'm using Windows 10  and my PHP version is 7.3.12

**Comment by cupcodei** [comment]
> 
> 
> What **Operating System** you are using? Also, what is your **php** version?
> On my Linux distribution all works nicely, these are the steps I have follow for install Laravel and package:
> 
> ```shell
> composer create-project --prefer-dist laravel/laravel <app_name>
> cd <app_name>
> composer require jeroennoten/laravel-adminlte
> php artisan adminlte:install --interactive
> ```
> 
> where `<app_name>` is the name of your application...
I'm using Windows 10 and my PHP version is 7.3.12

**Comment by cupcodei** [comment]
> 
> 
> What **Operating System** you are using? Also, what is your **php** version?
> On my Linux distribution all works nicely, these are the steps I have follow for install Laravel and package:
> 
> ```shell
> composer create-project --prefer-dist laravel/laravel <app_name>
> cd <app_name>
> composer require jeroennoten/laravel-adminlte
> php artisan adminlte:install --interactive
> ```
> 
> where `<app_name>` is the name of your application...

I'm using Windows 10 and my PHP version is 7.3.12

**Comment by Shidersz** [comment]
Did you try to update dependencies with `composer update`? We just use the [confirm()](https://laravel.com/docs/8.x/artisan#asking-for-confirmation) method from the **Laravel's Command Class** as explained on the documentation. Also check the `storage/logs/laravel.log` file to see if you find any error related to the command execution.

**Comment by Shidersz** [comment]
@cupcodei Have you found a solution for your problem? If yes, consider sharing it here, it may be useful for other readers.

**Comment by Shidersz** [comment]
@lacodimizer I believe you can close this issue (no response and appears to be some particular situation).
