### ISSUE TITLE
@livewireStyles shown as a text in Laravel 8

### ISSUE THREAD

**Issue by sadeghim** [jeroennoten/Laravel-AdminLTE#752]
The code in this line:
 https://github.com/jeroennoten/Laravel-AdminLTE/blob/3f7d41cb46cfe4093815f7492c071acad8e90c83/resources/views/master.blade.php#L42

should change to `@livewireStyles()`.

**Comment by lacodimizer** [comment]
That's wrong. According to the docu of livewire, the syntax is correct:
https://laravel-livewire.com/docs/2.x/quickstart

**Comment by RafaelKr** [comment]
I had a running Laravel project and implemented Livewire later on.

There was the problem that the `@livewire*`-directives were not processed and `@livewireStyles` and `@livewireScripts` were literally printed on the webpage instead.

I could fix this problem by running `php artisan view:clear`
