### ISSUE TITLE
Laravel 8 with jetstream

### ISSUE THREAD

**Issue by abedputra** [jeroennoten/Laravel-AdminLTE#762]
Thanks for this awesome packaged
I have a question about installing Laravel-AdminLTE with Laravel v8, and using jetstream for the auth, how do it?

Thank you

**Comment by SandunHerath** [comment]
i also have that problem

**Comment by Shidersz** [comment]
Hi @abedputra , @SandunHerath for what I know, the set of authentication views that are available on this package was developed as a replacement for the views provided with the **laravel/ui** authentication scaffolding package. However, I believe you can use the **Jetstream** scaffolding for all the authentication procedure (without any view replacement), and after login you may display a view with the `AdminLTE` template as documented on [Usage Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/4.-Usage). I had no time to give this a try, so any feedback about this can be useful for future readers.

**Comment by abedputra** [comment]
@Shidersz Thanks for your answer.

**Comment by wafiqamrillah** [comment]
Hi @abedputra, I also have this problem too. In this case, I edit the jetstream auth blade files in resources. Here the example of the profile settings view in resources\update-profile-information-form.blade.php.
`
{{-- ADMIN LTE --}}
    <form wire:submit.prevent="updateProfileInformation">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ __('Profile Information') }}</h3>&nbsp;
                <small class="text-muted">{{ __('Update your account\'s profile information and email address.') }}</small>
            </div>
            <div class="card-body">
                <div class="row">
                    @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                        <div class="col-md-6 col-xs-12">
                            <div class="d-flex align-item-center justify-content-center">
                                
                                <div x-data="{photoName: null, photoPreview: null}">
                                    <div class="d-flex align-item-center justify-content-center">
                                        <label for="photo">{{ __('Photo') }}</label>
                                    </div>

                                    <div class="d-flex align-item-center justify-content-center">
                                        
                                        <div x-show="! photoPreview">
                                            <img src="{{ $this->user->profile_photo_url }}" alt="{{ $this->user->name }}" class="img-circle elevation-2" style="height: 5rem; width: 5rem;">
                                        </div>

                                        
                                        <div x-show="photoPreview">
                                            <img :src="photoPreview" alt="" class="img-circle elevation-2" style="height: 5rem; width: 5rem;">
                                            <span class="block rounded-full w-20 h-20"
                                                x-bind:style="'background-size: cover; background-repeat: no-repeat; background-position: center center; background-image: url(\'' + photoPreview + '\');'">
                                            </span>
                                        </div>
                                    </div>
                                    <br>
                                    
                                    <input type="file"
                                                wire:model="photo"
                                                x-ref="photo"
                                                x-on:change="
                                                        photoName = $refs.photo.files[0].name;
                                                        const reader = new FileReader();
                                                        reader.onload = (e) => {
                                                            photoPreview = e.target.result;
                                                        };
                                                        reader.readAsDataURL($refs.photo.files[0]);
                                                " hidden />

                                    <button class="btn btn-sm btn-primary" type="button" x-on:click.prevent="$refs.photo.click()">
                                        {{ __('Select A New Photo') }}
                                    </button>

                                    @if ($this->user->profile_photo_path)
                                        <button type="button" class="btn btn-sm btn-danger" wire:click="deleteProfilePhoto">
                                            {{ __('Remove Photo') }}
                                        </button>
                                    @endif
                                </div>
                            </div>
                        </div>
                    @endif
                    <div class="col-md-6 col-xs-12">
                        
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input type="text" class="form-control" id="name" type="text" wire:model.defer="state.name" autocomplete="name"/>
                            <x-jet-input-error for="name" class="mt-2" />
                        </div>

                        
                        <div class="form-group">
                            <label for="name">{{ __('Email') }}</label>
                            <input type="text" class="form-control" id="email" type="email" wire:model.defer="state.email" />
                            <x-jet-input-error for="email" class="mt-2" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <span class="text-success" on="saved" x-data="{ shown: false, timeout: null }" x-init="@this.on('saved', () => { clearTimeout(timeout); shown = true; timeout = setTimeout(() => { shown = false }, 2000);  })" x-show.transition.opacity.out.duration.1500ms="shown">
                    {{ __('Saved.') }}
                </span>
                <button class="btn btn-sm btn-success float-right" type="submit" wire:loading.attr="disabled" wire:target="photo">
                    <i class="fas fa-save"></i> {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
{{-- / ADMIN LTE --}}
`

I'm edit this file manually. And every file with tailwind.css, I convert it to AdminLTE layouts.
So, in this case, you can find the files in every <x-jet-(file_name)> tags in vendor/jetstream/components, and you can edit like in my example. You'll figure it out.
(sorry for my bad english).

**Comment by abedputra** [comment]
@wafiqamrillah Thank you, let me try.
