### ISSUE TITLE
How to Add menu from database value in array menu ?

### ISSUE THREAD

**Issue by finalcode21** [jeroennoten/Laravel-AdminLTE#764]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

### Current Behavior

Hi, Please Help me, how to add menu into array menu adminlte.php get from database value ? please Help ... 
Thanks You

**Comment by Shidersz** [comment]
If you are looking to build your menu at runtime, please read [Menu At Runtime Dcoumentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime). Also, I'm sure you will find more examples if you search on the [CLOSED ISSUES](https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+is%3Aclosed)

**Comment by finalcode21** [comment]
> If you are looking to build your menu at runtime, please read [Menu At Runtime Dcoumentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime). Also, I'm sure you will find more examples if you search on the [CLOSED ISSUES](https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+is%3Aclosed)

Thanks for your help and information

**Comment by Shidersz** [comment]
@finalcode21 Please, consider closing this issue if you have found a solution for your problem. Also, you can share a summary of your solution for future readers (if you have the time).
