### ISSUE TITLE
How do you pass parameters in routes?

### ISSUE THREAD

**Issue by fbc** [jeroennoten/Laravel-AdminLTE#765]
What is the methods we are supposed to use for passing parameters to routes?
```
        [
            'text' => 'Bidding',
            'icon'    => 'fa fa-gavel',
            'route'  => 'bid.index',
            // 'can'  => 'manage-blog',
            'submenu' => [
                [
                    'text' => 'Tracking Phase',
                    'route'  => 'bid.index',
                ],
                [
                    'text' => 'Submitted Phase',
                    'route'  => ['bid.index', [$filter = 'onlysubmitted']],
                ],
            ]
        ],
```

**Comment by Shidersz** [comment]
You can always check the closed issues:

https://github.com/jeroennoten/Laravel-AdminLTE/issues/697

Or the wiki documentation:

[Wiki - The route attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#the-route-attribute)

**Comment by fbc** [comment]
> You can always check the closed issues:
> 
> #697
> 
> Or the wiki documentation:
> 
> [Wiki - The route attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#the-route-attribute)

OK I followed the same nomenclature as the example in the wiki changing my code to read:
```
                [
                    'text' => 'Submitted Phase',
                    'route'  => ['bid.index', ['filter' => 'onlysubmitted']],
                ],
```
however how do you query it in the controller function? dd($filter) results in error.

**Comment by Shidersz** [comment]
Usually, you catch the parameter on the route definition:

https://laravel.com/docs/8.x/routing#route-parameters

For example, something like this:

```php
Route::get('some_url/{filter}', function ($filter) {
    // Call the controller method here using the $filter variable.
})->name('bid.index');
```

**Comment by fbc** [comment]
@Shidersz Awesome thanks! that worked!
