### ISSUE TITLE
Can you help me with setting Up Dashboard2 As Default Page

### ISSUE THREAD

**Issue by raysultan** [jeroennoten/Laravel-AdminLTE#770]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

**Comment by Shidersz** [comment]
Hi @raysultan , are you talking about the next demo page:

https://adminlte.io/themes/v3/index2.html

If you are new, first you need to understand this packages provides an integration of the **AdminLTE v3** template with **Laravel** framework. The integration provides a starting point with the template ready layout (sidebar, navbar, footer, etc) and easy menu configuration.  I recommend to start by reading the [Wiki Pages](https://github.com/jeroennoten/Laravel-AdminLTE/wiki), specially next ones:

- [Installation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/2.-Installation)
- [Usage](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/4.-Usage)
- [Basic Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/6.-Basic-Configuration)
- [Layout Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/7.-Layout-and-Styling-Configuration)
- [Menu Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration)

Once you have a started page working (see **Usage** section), you can see how all that demo page is implemented by inspecting next code:

https://github.com/ColorlibHQ/AdminLTE/blob/master/index2.html

In particular the one wrapped inside next block:

```html
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
   <!-- Here is all the page implementation -->
</div>
```

Also, a solid knowledge about the [Laravel Framework](https://laravel.com/) is required.

**Comment by raysultan** [comment]
Hey Mate! Thank you for replying, I just wondered to include the whole layout and then modify it later, I've gone through components and all the documentation of AdminLte.
