### ISSUE TITLE
Not working on laravel 8

### ISSUE THREAD

**Issue by nicolicioiul** [jeroennoten/Laravel-AdminLTE#778]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         |  8.17.0
| Project Version         | latest
root@ff9afddcf0b0:/var/www/html# php artisan --version
Laravel Framework 8.17.0

### Current Behavior

After installing the laravel and running all documentation steps, the UI did not load the adminlte interface, see:
![image](https://user-images.githubusercontent.com/7777900/100928821-61f1d980-34ef-11eb-9924-aaba7750c64f.png)

### Expected Behavior
To show the adminlte UI.
Adminlte artisan status
 php artisan adminlte:status
Checking the resources installation ...
 7/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
All resources checked succesfully!

+------------------+------------------------------------------+---------------+----------+
| Package Resource | Description                              | Status        | Required |
+------------------+------------------------------------------+---------------+----------+
| assets           | The AdminLTE required assets             | Installed     | true     |
| config           | The default package configuration file   | Installed     | true     |
| translations     | The default package translations files   | Installed     | true     |
| main_views       | The default package main views           | Installed     | false    |
| auth_views       | The default package authentication views | Mismatch      | false    |
| basic_views      | The default package basic views          | Mismatch      | false    |
| basic_routes     | The package routes                       | Not Installed | false    |
+------------------+------------------------------------------+---------------+----------+

Status legends:
+---------------+----------------------------------------------------------------------------------------------+
| Status        | Description                                                                                  |
+---------------+----------------------------------------------------------------------------------------------+
| Installed     | The resource is installed and matches with the default package resource                      |
| Mismatch      | The installed resource mismatch the package resource (update available or resource modified) |
| Not Installed | The package resource is not installed                                                        |
+---------------+----------------------------------------------------------------------------------------------+

### Steps to Reproduce
Fresh laravel installation

**Comment by Shidersz** [comment]
Hi @nicolicioiul , give a read to [Usage Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/4.-Usage), then be sure that the default loaded blade view by **Laravel** (the one after the login process) implements the code you see on the usage section. I'm not sure witch one is used on the **Laravel 8 framework**, maybe `home.blade.php` or `welcome.blade.php`.

**Comment by Shidersz** [comment]
@resslinger You can close this one, no feedback or extra information from the user.

**Comment by nicolicioiul** [comment]
Yes,
 it was working after changed the templates and override the content on home.blade.php or welcome.blade.php
Thank you.
