### ISSUE TITLE
enable laravel mix

### ISSUE THREAD

**Issue by victorJaramilloC** [jeroennoten/Laravel-AdminLTE#779]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 7.29.3
| Node Version         | 14.15.0
| NPM Version         | 6.14.9

### Current Behavior

when i enable laravel-mix in adminlte.php my sidebar style gets out of frame  and icons get very big

**Comment by Shidersz** [comment]
Hi @victorJaramilloC , honestly I have no experience with **Laravel Mix** feature, but it sound like a plugin conflict or something that is missed. However, be sure to review the documentation and the closed issues:
- [Laravel Mix Documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#92-laravel-mix)
- [Closed Issues for Laravel Mix](https://github.com/jeroennoten/Laravel-AdminLTE/issues?q=is%3Aissue+is%3Aclosed+laravel+mix)

If you found a solution, please explain it for future readers.

**Comment by victorJaramilloC** [comment]
I was forgetting to import a css file, thank you very much, your answer helped me
