### ISSUE TITLE
Configuring Navbar and Sidebar

### ISSUE THREAD

**Issue by growdeuno** [jeroennoten/Laravel-AdminLTE#78]
1. How to configure navbar? (For example : Profile Navbar)
2. How to configure role & permission on sidebar?

**Comment by webstractions** [comment]
> 1. How to configure navbar? (For example : Profile Navbar)

Was wondering that myself. I looked at the `page.blade.php` file and there is no way to configure the right side of the top-nav bar for that purpose. It is hard-coded for login/logout purposes. You can customize the right side of the top-nav, only if you go with the `'layout' => 'top-nav'` option in the config file (but you will lose the side menu altogether.)

@jeroennoten Perhaps you could enhance the menu to allow for the right side area in top-nav ???

> 2. How to configure role & permission on sidebar?

This package does not come with roles and permissions. There are other projects that handle that, and once installed and set up, you can add the links in the config file for your menu.

**Comment by carlosadames** [comment]
If i want to use a package in order to manage role & permissions, how can i integrate it? Could i just comment menu Items in config/adminlte.php ?

**Comment by jeroennoten** [comment]
@carlosadames there is an example of integrating the Laratrust package in the README. Integrating other packages should be doable in a similar way.

**Comment by vatraiadarsh** [comment]
How to configure navbar? (For example : Profile Navbar)
How to configure role & permission on sidebar?

**Comment by masete** [comment]
chech out laravel-roles-permissions-manager on github. its a plug and play
 https://github.com/masete/laravel-roles-permissions-manager

**Comment by nihadatakishiyev** [comment]
Any progress about how to configure the navbar or how to add some links to the right part next to username?

**Comment by Shidersz** [comment]
@nihadatakishiyev Maybe you looking for [topnav, topnav_right and topnav_user](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#the-topnav-topnav_right-and-topnav_user-attributes) attributes of the [menu configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration)

**Comment by subdesign** [comment]
My implementation for top right profile dropdown. In your `/config/adminlte.php` file add a new array item after the two defaults:

```php
'menu' => [
        // Navbar items:
        [
            'type'         => 'navbar-search',
            'text'         => 'search',
            'topnav_right' => true,
        ],
        [
            'type'         => 'fullscreen-widget',
            'topnav_right' => true,
        ],
        [
            'text'         => '',
            'url'          => '#',
            'icon'         => 'fas fa-fw fa-user',
            'topnav_right' => true,
            'topnav_user'  => true,
            'submenu' => [
                [
                    'text' => 'Profile',
                    'url'  => '/profile'
                ],
                [
                    'text' => 'Log out',
                    'url'  => '/logout',
                    'icon' => 'fas fa-sign-out-alt'
                ]
            ],
        ],
        ...
```
Looks like:
<img width="172" alt="Screenshot 2022-09-28 at 15 09 47" src="https://user-images.githubusercontent.com/691695/192786565-4f301188-5559-4894-9fac-4a941b562e14.png">
