### ISSUE TITLE
Menu Filter using Policies rather than Gate

### ISSUE THREAD

**Issue by bitzs-alex** [jeroennoten/Laravel-AdminLTE#781]
| Issue |Enhancement

### Current Behavior

The Menu Filter is configured to use Laravel's Gate but I rather prefer Policies. Is there anyone who can help me with how to write a new MenuFilter using Policies?

**Comment by Shidersz** [comment]
Have you read the example on the documentation, just in case: [Custom Menu Filter](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#83-custom-menu-filters)

**Comment by bitzs-alex** [comment]
@Shidersz Thanks for your quick response but yes I have checked it but the example there is using Laratrust Package as an example.
What I want is, I already have permissions in place and I want the menu filter to use the already coded Policies. Is there any possible way to achieve this?

**Comment by resslinger** [comment]
@bitzs-alex You can use the Laratrust menu filter as example to create your own filter. In this example, there is a call to Laratrust::isAbleTo(). This should be changed to your coded policy checker.

**Comment by Shidersz** [comment]
As @resslinger says, you need to create your own logic for the filter (using the policies). Once you have the logic, just setup `$item['restricted'] = true;` when the menu item is not allowed (or restricted by your policies). I'm not familiar with Laravel's policies, so I can't give you a better example.

**Comment by ruanpepe** [comment]
The package is compatible with Policies already. This should be at Wiki also. Its a great feature.

In policies, we create a policies file that will be attached to our model by Laravel according naming conventions. Then we can use the Gate facade to check the user access.

Ex: 
Consider the `Post` model policies

```
<?php

namespace App\Policies;

use App\Models\Post;
use App\Models\User;

class PostPolicy
{
    /**
     * Determine whether the user can update the post.
     */
    public function update(User $user, Post $post): bool
    {
        if($user->isAdmin()) {
            return true;
        }

        return $user->id === $post->user_id;
    }

    /**
     * Determine whether the user can delete the post.
     */
    public function delete(User $user, Post $post): bool
    {
        if($user->isAdmin()) {
            return true;
        }

        return $user->id === $post->user_id;
    }
}
```

Then we can check the user permission using the method name and the model instance or model class ([read this](https://laravel.com/docs/11.x/authorization#controller-actions-that-dont-require-models)):

`$user->can('update', $post)`
`Gate::authorize('update', $post);`

I checked the `GateFilter.php` and it already have being done.
All we need is do the following:

```
    [
        'text' => '...',
        'url' => '...',
        'can' => ['update', 'delete'],
        'model' => $post
    ],
```
That will be converted to 
`Gate::any(['update', 'delete'], $post)`

I'm using it and work like a charm.

**Comment by ruanpepe** [comment]
#210
