### ISSUE TITLE
'brand classes' are not added when using a 'logo_img_xl'

### ISSUE THREAD

**Issue by vhood** [jeroennoten/Laravel-AdminLTE#783]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | v8.17.2
| Project Version         | v3.5.0

### Current Behavior

`a.brand_link` don't have classes from the 'classes_brand' config if the 'logo_img_xl' isn't NULL

**Comment by Shidersz** [comment]
@vhood Thanks for reporting this issue, a PR is already on his way.

**Comment by Shidersz** [comment]
@resslinger This is now included in the new version **3.5.1**. You can close this issue.
