### ISSUE TITLE
ISSUE : topnav_right & topnav & topnav_user didn't work

### ISSUE THREAD

**Issue by BIhab** [jeroennoten/Laravel-AdminLTE#784]
Hi,
Please I have an issue with adding menu items in topnav and topnav_right, it just didn't work, here is the code `adminlte.php`
```
'menu' => [
        [
            'text' => 'dashboard',
            'topnav_user' => true,
            'active' => ['/'],
        ],
        [
            'text' => 'contact',
            'topnav_right' => true,
        ],
        [
            'text' => 'search',
            'search' => true,
            'topnav' => true,
        ],
...
```
Only the search appear, and if I add 'search' => true to one of the two items without, it'll appear as a search box in the exact specified location - left or right in the topnav-

**Comment by Shidersz** [comment]
Hi  @BIhab , take a look to [Menu Configuration Documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration), there says that:

> You can specify the set of menu items to display in the left sidebar and/or the top navbar. A menu item representing a link should have a **text** attribute and an **url** (or **route**) attribute.

You are missing the **url** and/or **route** attribute.

**Comment by BIhab** [comment]
Thanks a lot
