### ISSUE TITLE
Where to enable login button?

### ISSUE THREAD

**Issue by LinardsLiepenieks** [jeroennoten/Laravel-AdminLTE#788]
I set up the template as written in docs and everything works fine, but the login button is missing,
Can I enable it through the config file or if not to which file then can I add the code for it.
![unknown](https://user-images.githubusercontent.com/49512889/101975192-b4e43300-3c4b-11eb-8456-d0e03a4e350c.png)

**Comment by Shidersz** [comment]
Hi @LinardsLiepenieks , these buttons will be visible if you install an **authentication scaffolding** (`laravel/ui` on Laravel 7.x or `jetstream` on Laravel 8+) and setup the related routes. For the `laravel/ui ` authentication scaffolding, read step 2 of the [Installation Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/2.-Installation) and the related Laravel documentation. The package also includes a set of views in replacement of the `laravel/ui` views (more info on [Auth Views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/5.-Artisan-Console-Commands#55-authentication-views)). If you going use `Jetstream` you will need to create customs authentication views that replaces the ones that the package provides (only if you don't like they), take a look on discussion #762 .

**Comment by LinardsLiepenieks** [comment]
> Hi @LinardsLiepenieks , these buttons will be visible if you install an **authentication scaffolding** (`laravel/ui` on Laravel 7.x or `jetstream` on Laravel 8+) and setup the related routes. For the `laravel/ui ` authentication scaffolding, read step 2 of the [Installation Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/2.-Installation) and the related Laravel documentation. The package also includes a set of views in replacement of the `laravel/ui` views (more info on [Auth Views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/5.-Artisan-Console-Commands#55-authentication-views)). If you going use `Jetstream` you will need to create customs authentication views that replaces the ones that the package provides (only if you don't like they), take a look on discussion #762 .

Hi,
I had already auth scaffolding installed, that's why I was confused.
I fixed this by adding buttons in config file and then creating a gate to check if user is logged in.

Added this in adminlte.php

```
`[
            'text' => 'login',
            'topnav' => true,
            'url'=> 'login',
            'can'=> 'logged-in',
        ],
        [
            'text' => 'register',
            'topnav' => true,
            'url'=> 'register',
            'can'=> 'logged-in',

        `],``
```
And this in AuthServiceProvider.php

```
Gate::define('logged-in', function ($user = null) {
            return $user == null;
        });
```

**Comment by Shidersz** [comment]
@LinardsLiepenieks shouldn't be needed, usually (after installing the `laravel/ui` authentication scaffolding) you need to include the authentication routes in the `routes/web.php` files (I think the package do that automatically but I do not remember now), and then use the authentication middleware to require authentication before accessing your pages, something like this:

```php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authentication routes.

Auth::routes();

// Next group of routes requires authentication. If the user is not
// authenticated, it will be redirected to the login screen.

Route::middleware('auth')->group(function()
{
    /* Define your routes here... */
});
```

If you are using other authentication scaffolding, read the documentation. Also, you need to setup the HOME view on the `app/Providers/RouteServiceProvider.php`:

```php
/**
 * The path to the "home" route for your application.
 *
 * This is used by Laravel authentication to redirect users after login.
 *
 * @var string
 */
public const HOME = '/home';
```

In my particular situation, I usually define the `home` view (`resources/views/home.blade.php`), or the one you have setup, as explained on [Usage Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/4.-Usage). Then, this package will automatically detect if the user have login, and display the logout button or a customized [User Menu](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/6.-Basic-Configuration#64-user-menu) if you have enabled it.

**Comment by LinardsLiepenieks** [comment]
Thank you added the Login button in navbar.blade.php
