### ISSUE TITLE
Vue.js overrides adminlte

### ISSUE THREAD

**Issue by LinardsLiepenieks** [jeroennoten/Laravel-AdminLTE#789]
Hello, I'm trying to add an Vue component, but when I add the links adminlte logout usermenu (and sometimes left sidebar too, but only sometimes) stops working.
My component itself is working fine and if I remove links to the app.css/app.js files adminlte is working fine again.

This is how I add the files 

```
@section('css')
    <link rel="stylesheet" href="{{ asset('css/app.css') }}"/>
@stop

@section('js')
    <script defer src="{{ asset('js/app.js') }}"></script>
@stop
```

Did I miss something in the docs, or is there something I should add so that it does not override the main script/stylesheet?

**Comment by Shidersz** [comment]
Hi @LinardsLiepenieks , I never experimented with `Vue`. However, what `app.css` and `app.js` is supossed to contain? For what you have described, appears to be some conflict with the `adminlte` template (You should review the browser's developer console or use any tool to inspect for problems/warnings).  Now, and particularly, I will include `Vue.js` and your components as plugins in the configuration file (See [Plugins Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#91-plugins)), that is how plugins or extra tools are managed whitin this package. You may add something like this on the plugins configuration section:

```php
'Vue' => [
    'active' => false,
    'files' => [
        [
            'type' => 'js',
            'asset' => false,
            'location' => 'https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js',
        ],
    ],
],
'MyVueComponents' =>
    'active' => false,
    'files' => [
        [
            'type' => 'js',
            'asset' => true,
            'location' => 'path/to/components.js',
        ],
        [
            'type' => 'css',
            'asset' => true,
            'location' => 'path/to/components.css',
        ],
    ],
],
```

And then include the `Vue.js` and your `Vue.js` components in your blade views using:

```blade
@section('plugins.Vue', true)
@section('plugins.MyVueComponents', true)
...
```

All this procedure is explained on the documentation...
