### ISSUE TITLE
Sidebar and Navbar

### ISSUE THREAD

**Issue by kcrad100** [jeroennoten/Laravel-AdminLTE#79]
How to create two menus, one on the sidebar and another on the navbar each diferent but both from the database that are loaded according to the profile?

**Comment by jeroennoten** [comment]
Hi! Thanks for your question. A Configurable topbar is not supported yet. However, you can [publish the views](https://github.com/jeroennoten/Laravel-AdminLTE#7-customize-views) and add your custom topbar logic there. Refer to the [AdminLTE docs](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#component-main-header) on how to use the topbar.

A pull request that makes this functionality configurable via this package is more than welcome.
