### ISSUE TITLE
JS dont work on adminlte 3 with laravel 8

### ISSUE THREAD

**Issue by nicolasprimo** [jeroennoten/Laravel-AdminLTE#790]
All css style work fine, but js component like timepicker dont work

**Comment by Shidersz** [comment]
Hi @nicolasprimo , I doubt you can receive any help with so little explanation of your problem. You need to add more details, and explain what **Timepicker** is (a plugin maybe?) and how you integrate it on the package.

**Comment by Shidersz** [comment]
@resslinger You can close this one, there was no feedback from the user.
