### ISSUE TITLE
When I use Select 2 and collapsed-card with Livewire it's not working properly?

### ISSUE THREAD

**Issue by tmgomas** [jeroennoten/Laravel-AdminLTE#792]
| When I use Select 2 and collapsed-card with Livewire it's not working properly?

when I use the input field after select 2 is not working.

when I use collapsed card with Livewire I put some value on input field card is auto collapsed 

> <div class="col-12 col-lg-6 col-sm-12">
     <div class="input-group mb-3">
        <select wire:model="stu_gender" class="form-control form-control-sm select2" style="width: 100%;">
            <option selected="selected">Gender</option>
               @foreach ($Genders as $key=>$Gender)
                     <option value="{{ $Gender->gen_id }}">{{ $Gender->gen_name }}</option>
               @endforeach
        /select>      
    </div>
 </div>

**Comment by tmgomas** [comment]
> 

<div class="card card-primary collapsed-card">
--
  | <div class="card-header">
  | <h3 class="card-title">Expandable</h3>
  |  
  | <div class="card-tools">
  | <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
  | </button>
  | </div>
  | 
  | </div>
  | 
  | <div class="card-body">
  | The body of the card
  | </div>
  | 
  | </div>

**Comment by tmgomas** [comment]
> <div class="card card-primary collapsed-card">
              <div class="card-header">
                <h3 class="card-title">Expandable</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
                  </button>
                </div>
                
              </div>
              
              <div class="card-body">
                The body of the card
              </div>
              
            </div>

**Comment by resslinger** [comment]
@tmgomas is the issue actual?

**Comment by setiawanjoko** [comment]
@resslinger my Datatables doesn't work properly with livewire. Here is my project structure

```
+-- Main views
|   +-- Table livewire
|   |   + Action button livewire
```

I used Action Button Livewire to destroy a User (for example), and then calling a listener from parent livewire using `emitUp()`. The User already deleted but the table order is messed up. 

Should I use a package focused on Datatables in livewire or somebody have a solution?

**Comment by Shidersz** [comment]
@setiawanjoko I'm not familiarized with Livewire, but If you are deleting elements from the Datatable, I believe you have to do it using the [API](https://datatables.net/reference/api/) they provide. The documentation to remove is here: [remove()](https://datatables.net/reference/api/row().remove()). If you are only deleting the html code associated with a row, it will conflict with the information that Datatables is handling in memory.
