### ISSUE TITLE
I get de following message Failed to clone https://github.com/ColorlibHQ/AdminLTE.git

### ISSUE THREAD

**Issue by jatmar** [jeroennoten/Laravel-AdminLTE#793]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    |I get de following message Failed to clone https://github.com/ColorlibHQ/AdminLTE.git
| Laravel Version         | 8
| Project Version         | 
### Steps to Reproduce

after run the command composer require jeroennoten/laravel-adminlte, after to try to download the package almasaeed2010/adminlte (v3.0.5) I get a message:
Failed to download almasaeed2010/adminlte from dist: curl error 28 while downloading https://codeload.github.com/ColorlibHQ/AdminLTE/legacy.zip/6b8b69261f1aacbb4be037c934f3c3652e6dff27: Operation timed out after 300000 milliseconds with 5435161 bytes received
    Now trying to download from source
  - Installing almasaeed2010/adminlte (v3.0.5): Cloning 6b8b69261f
    Install of almasaeed2010/adminlte failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [RuntimeException]
  Failed to clone https://github.com/ColorlibHQ/AdminLTE.git, git was not found, check that it is installed and in yo
  ur PATH env.

  "git" it is not recognized as an internal or external command,
  program or executable batch file. 
![image](https://user-images.githubusercontent.com/76924101/103495177-3fb1eb00-4e10-11eb-96d9-67679b384017.png)

**Comment by Shidersz** [comment]
Note the next:

> "git" it is not recognized as an internal or external command.

Have you [Git](http://git-scm.com/) installed on your Operating System?

**Comment by Shidersz** [comment]
@resslinger You can close this issue, appears to be related to development environment setup and there is no feedback from the user.

**Comment by jatmar** [comment]
Thanks for you Answer... all was solved
