### ISSUE TITLE
Error on rendering view when the route is declared in a Laravel's Route::resource

### ISSUE THREAD

**Issue by arthurmr96** [jeroennoten/Laravel-AdminLTE#799]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.23.1
| Project Version         | 3.5.2

### Current Behavior

$adminlte is undefined

![image](https://user-images.githubusercontent.com/10486154/105416904-90e81a00-5c19-11eb-8f9c-794370b3fc7d.png)

### Expected Behavior

The view to load normally

![image](https://user-images.githubusercontent.com/10486154/105416929-99d8eb80-5c19-11eb-97c9-b6cb55156c93.png)

### Steps to Reproduce

Create a Resource Controller and return the view from one of its routes

**routes.php**

`Route::resource('regions', \App\Http\Controllers\RegionsController::class);`

**RegionsController**

```php

class RegionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $regions = Region::query()->paginate();

        return response()->view('regions.index', ['regions' => $regions]);
    }

    ...

```

**views/regions/index.php**

```html

@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Dashboard</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <p class="mb-0">You are logged in!</p>
                </div>
            </div>
        </div>
    </div>
@stop

```

### Possible Solutions

I found out that declarating those routes separatedly worked normal

`Route::get('regions/index', [\App\Http\Controllers\RegionsController::class, 'index']);`

**Comment by Shidersz** [comment]
Hi @arthurmr96 , I can't reproduce the issue on my local environment with `laravel/framework (v8.24.0)`. Please try next:

1) Update the Laravel framework with `composer update laravel/framework`. Maybe it was a problem related to that version.
2) Try to just `return view('regions.index', ['regions' => $regions]);` from the controller.
