### ISSUE TITLE
Compatibility with Laravel 5.1?

### ISSUE THREAD

**Issue by jesusvpct** [JeroenNoten/Laravel-AdminLTE#8]
It seems that requires Laravel 5.2. It would be great if it has compatibility with Laravel 5.1 (because this is a LTS version).

Thanks!

**Comment by JeroenNoten** [comment]
Sure! Done: https://github.com/JeroenNoten/Laravel-AdminLTE/releases/tag/v1.6.3

Note that the `php artisan make:adminlte` command only works for Laravel 5.2 and higher, because of the dependency on `php artisan make:auth`. Other functionality should work in Laravel 5.1 now.
