### ISSUE TITLE
Different Menus for Different Pages

### ISSUE THREAD

**Issue by CordMarston** [jeroennoten/Laravel-AdminLTE#801]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 8
| Project Version         | 3.5.2

### Current Behavior

Currently there is one menu that is pulled from the config/adminlte.php file as an array of 'menu' 

I am trying to implement different menus for different pages. For example /home would show the home 'menu' and maybe user would show the user menu. Both completely different with different links, class, etc.

**Comment by Shidersz** [comment]
Hello @CordMarston , check the next link:

- [Menu Config at Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime) to know how you can implement a logic to built the menu at runtime (and not from the configuration file).

**Comment by CordMarston** [comment]
> Hello @CordMarston , check the next link:
> 
> * [Menu Config at Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime) to know how you can implement a logic to built the menu at runtime (and not from the configuration file).

This just seems over complicated. Is there a way to disable to menu builder completely? That way I could just use switch statements for different blades. Could be me, but is the menu builder really sluggish the more you add to it?

**Comment by Shidersz** [comment]
@CordMarston The configuration of the menu at runtime is good when you want to store the menu on a Database, for example. I'm not sure if there is a alternative

>  Is there a way to disable to menu builder completely?

I don't think so. Menu builder is in charge of adding the active class to menu items, creating the `href` urls, among a lot of other things.

> is the menu builder really sluggish the more you add to it?

I have never tested it with a really lot of menu items. Maybe someone can answer this question. We can try to improve it, if this is the case.

**Comment by Vincent11110** [comment]
> Question	Answer
> Issue or Enhancement	Enhancement
> Laravel Version	8
> Project Version	3.5.2
> ### Current Behavior
> Currently there is one menu that is pulled from the config/adminlte.php file as an array of 'menu'
> 
> I am trying to implement different menus for different pages. For example /home would show the home 'menu' and maybe user would show the user menu. Both completely different with different links, class, etc.

I am searching for the exact same thing.

**Comment by Cloudxyz** [comment]
For futures references is very easy with permissions, the next code show option "can" in the array this will hide or show the menu item according to role and permissions for the user, so you need construct a single menu with all the options and show or hide the items with "can" is the only way i find to make that

`'menu' => [
		// Navbar items:
		[
			'type'         => 'navbar-search',
			'text'         => 'search',
			'topnav_right' => true,
		],
		[
			'type'         => 'fullscreen-widget',
			'topnav_right' => true,
		],
		// Sidebar items:
		[
			'text'    => 'Control de Usuarios',
			'icon'    => 'fas fa-fw fa-user',
			'can'     => 'Users',
			'submenu' => [
				[
					'text'  => 'Usuarios',
					'route' => 'users',
					'icon'  => 'fas fa-fw fa-list',
					'shift' => 'ml-3',
					'can'   => 'Users',
				],
				[
					'text'  => 'Roles',
					'route' => 'roles',
					'icon'  => 'fas fa-fw fa-mask',
					'shift' => 'ml-3',
					'can'   => 'Roles',
				],
				[
					'text'  => 'Permisos',
					'route' => 'permissions',
					'icon'  => 'fas fa-fw fa-lock',
					'shift' => 'ml-3',
					'can'   => 'Permissions',
				],
				[
					'text'  => 'Posiciones',
					'route' => 'positions',
					'icon'  => 'fas fa-fw fa-pencil-alt',
					'shift' => 'ml-3',
					'can'   => 'Positions',
				],
			],
		],
		[
			'text'    => 'Control de Regiones',
			'icon'    => 'fas fa-fw fa-map',
			'can'     => 'Regions',
			'submenu' => [
				[
					'text'  => 'Regiones',
					'route' => 'regions',
					'icon'  => 'fas fa-fw fa-list',
					'shift' => 'ml-3',
					'can'   => 'Regions',
				],
				[
					'text'  => 'Zonas',
					'route' => 'zones',
					'icon'  => 'fas fa-fw fa-map-pin',
					'shift' => 'ml-3',
					'can'   => 'Zones',
				],
			],
		],
	]`
