### ISSUE TITLE
The Mix manifest does not exist when it does exist [Shared Hosting]

### ISSUE THREAD

**Issue by jonasmarco** [jeroennoten/Laravel-AdminLTE#802]
Hello everyone. I deployed the admin on a shared hosting. And when I try to access it I get an error message from Mix.

'The Mix manifest does not exist when it does exist.'

With ssh I do NOT have the option to run '`npm run dev`'.

The file 'manifest-json.js' is at /home1/public_html/manifest-json.js

Can someone help me?

**Comment by Shidersz** [comment]
@jonasmarco I have no experience with `Mix`, so I can't help you much. However, this is more a deployment issue than a package issue. Maybe you can search/ask on `Stackoverflow`:
- https://stackoverflow.com/search?q=The+Mix+manifest+does+not+exist+when+it+does+exist

I hope you can found a solution out there...

**Comment by resslinger** [comment]
@jonasmarco on shared hosting npm is not available in the most cases.
