### ISSUE TITLE
QUESTION: how can I add my custom chart ?

### ISSUE THREAD

**Issue by mohafiz** [jeroennoten/Laravel-AdminLTE#804]
I want to add custom charts, how can I do it? is there is a feature like that?

**Comment by Shidersz** [comment]
Hello @mohafiz , what custom chart? If the chart is provided as a plugin, then read [Plugins Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/9.-Other-Configuration#91-plugins) to see how you can include the files of the plugins on the package.

**Comment by mohafiz** [comment]
ok nice, i missed this section of the documentaion
