### ISSUE TITLE
How to Pass Dynamic Id to the route value of Menu attribute

### ISSUE THREAD

**Issue by bitzs-alex** [jeroennoten/Laravel-AdminLTE#807]
| Question               
| ----------------------- | -----------------------
| Laravel Version         | 8.12
| Project Version         | 3.5

### Current Behavior

Cant pass dynamic Id value to the route value

### Expected Behavior

I wanted the menu link to redirect to a specific school that is assigned to the user.

### Steps to Reproduce

```
[
    'text'  => 'My School',
    'route' => ['school.show', [Auth::user()->principal->id]], // I am trying to make it Dynamic, specific to each user
    'can'   => ['isUserPrincipal']
 ],
```

**Comment by Shidersz** [comment]
@bitzs-alex Take a look to [Menu Configuration At Runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#84-menu-configuration-at-runtime). You can't do that using the `adminlte.php` configuration file.
