### ISSUE TITLE
Keep menu item active based on url

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#808]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | v8.21.0
| Project Version         | v3.5.1

This is probably impossible but I would like to see if there is a way.

### Current Behavior

Currently a menu item only stays active based on the current URL, example:

The item is active if the url is http://localhost/admin/tools/supre/clients
![image](https://user-images.githubusercontent.com/67007152/107985388-c7ab1900-6fa8-11eb-8552-d89b66abc5ce.png)

However if the url is http://localhost/admin/tools/supre/clients/create the item will not be active
![image](https://user-images.githubusercontent.com/67007152/107985463-e01b3380-6fa8-11eb-8a09-7fea44e3ae71.png)

### Desired Behavior

For the item to still be active, since they "share" the same url:
http://localhost/admin/tools/supre/clients
http://localhost/admin/tools/supre/clients/create

**Comment by Shidersz** [comment]
@MathiasOliveira Maybe you can use the [active attribute](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/8.-Menu-Configuration#the-active-attribute) with a `regex` or the `*` character. For example:

```php
[
    'text'   => 'Clientes',
    'url'    => 'admin/tools/supre/clients',
    'active' => ['admin/tools/supre/clients*'],
]
```

**Comment by MathiasOliveira** [comment]
That does work, however I use routes instead of urls, and with routes i haven't found a way to make it work:
```
[
    'text' => 'Clientes',
    'icon' => 'nav-icon fas fa-fw fa-users',
    'route' => 'clients.index',
    'active' => ['clients.*'],
],
```

**Comment by Shidersz** [comment]
@MathiasOliveira the `active` attribute always match with the urls. Also, at some point, a route is finally converted to an url. So, you can use routes, but always define the `active` attribute to match urls, like on next example:

```php
[
    'text' => 'Clientes',
    'icon' => 'nav-icon fas fa-fw fa-users',
    'route' => 'clients.index',
    'active' => ['admin/tools/supre/clients*'],
],
```

**Comment by MathiasOliveira** [comment]
Makes sense, thank you.
