### ISSUE TITLE
[Reopen Issue] View/Display menu in sidebar depending on their roles

### ISSUE THREAD

**Issue by sweggggg** [jeroennoten/Laravel-AdminLTE#81]
I reopen issue #72 

I was unable to figure out how to use the custom filter.

Thinking wanted to do like this

[
            'text'        => 'Users',
            'url'         => 'users',
            'icon'        => 'file',
            'label_color' => 'success',
            'can'         => 'manage-blog',
            'role'        => 'User',
 ],

but any solution is fine

**Comment by sweggggg** [comment]
anyone?

**Comment by janvleugels** [comment]
I'm also unable to figure that out... 

'menu' => [
        'MAIN NAVIGATION',
        [
            'text' => 'Blog',
            'url'  => 'admin/blog',
            'can'  => 'manage-blog',
        ],
        [
            'text'        => 'Pages',
            'url'         => 'admin/pages',
            'icon'        => 'file',
            'label'       => 4,
            'label_color' => 'success',
        ],
... etc...

When I change the 'text' => 'Pages' tot 'text' => 'Pages TEST', the changes ar not pushed to the view, I also tried with 'php artisan view:clear' but still no changes...

I'm newbie in Laravel, how to find the $adminlte->menu() method in the page.blade.php?

**Comment by dicarlosystems** [comment]
As an example of how I did this using spatie/permission:

```
class RoleMenuFilter implements FilterInterface
{
    public function transform($item, Builder $builder)
    {
        if (isset($item['roles']) && ! (Auth::user())->hasAnyRole($item['roles'])) {
            return false;
        }

        return $item;
    }
}
```

**Comment by dicarlosystems** [comment]
This is how I implemented it:

```
class RoleMenuFilter implements FilterInterface
{
	public function transform($item, Builder $builder)
	{
		if (! $this->isVisible($item)) {
			return false;
		}

		if (isset($item['header'])) {
			$item = $item['header'];
		}

		return $item;
	}

	protected function isVisible($item)
	{
        // check if user is a member of specified role(s) or has been granted explicit permission
		if (isset($item['roles']) && ! (Auth::user())->hasAnyRole($item['roles'])) {
			if (isset($item['can']) && ! (Auth::user())->can($item['can'])) {
				return false;
			}
		}

		return true;
	}
}
```

And the menu config in adminlte.php:
  [
        'text' => 'Users',
            'icon' => 'users',
            'url'  => 'admin/users',
            'can'  => 'list-user',
            'roles' => [
                'admidn',
            ],
        ],

**Comment by dicarlosystems** [comment]
Here's how I implemented it when using spatie/permission:

```

class RoleMenuFilter implements FilterInterface
{
	public function transform($item, Builder $builder)
	{
		if (! $this->isVisible($item)) {
			return false;
		}

		if (isset($item['header'])) {
			$item = $item['header'];
		}

		return $item;
	}

	protected function isVisible($item)
	{
        // check if user is a member of specified role(s) 
		if (isset($item['roles'])) {
			if (! (Auth::user())->hasAnyRole($item['roles'])) {
				// not a member of any valid roles; check if user has been granted explicit permission
				if (isset($item['can']) && (Auth::user())->can($item['can'])) {
					return true;
				} else {
					return false;
				}
			} else {
				return true;
			}
		} else {
			// valid roles not defined; check if user has been granted explicit permission
			if (isset($item['can'])) {
				// permissions are defined
				if ((Auth::user())->can($item['can'])) {
					return true;
				} else {
					return false;
				}
			} else {
				// no valid roles or permissions defined; allow for all users
				return true;
			}
		}
	}
}
```

And the menu config:
```
[
    'text' => 'Users',
    'icon' => 'users',
    'url'  => 'admin/users',
    'can' => 'list-user',
    'roles' => [
        'admin',
    ],
],
```

**Comment by greksazoo** [comment]
I use Laratrust with this code.
`<?php

namespace App\Filter;

use Illuminate\Support\Facades\Auth;
use JeroenNoten\LaravelAdminLte\Menu\Builder;
use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;

class MenuFilter implements FilterInterface
{
public function transform($item, Builder $builder)
{
if (isset($item['role']) && ! Auth::user()->hasRole($item['role'])) {
return false;
}

return $item;
}
}`

and here is a menu config

`[
		'text' => 'Users',
		'url'  => 'users',
		'icon' => 'users',
		'role' => 'su',
],`

**Comment by gbaltazar** [comment]
Where I need to save the new filter class?

**Comment by jeroennoten** [comment]
Wherever you want in the app directory, as long as you reference it correctly in the configuration.

**Comment by megha-b89** [comment]
please anyone help how to show sidebar menu separately for user and admin

**Comment by megha-b89** [comment]
if i add can it hide for both admin and user plz help me

**Comment by desyashasyi** [comment]
> I am using jeremykenedy laravel-roles. how can i do this? Please Help

Any solution?

**Comment by reymaro0** [comment]
> I use Laratrust with this code.
> `<?php
> 
> namespace App\Filter;
> 
> use Illuminate\Support\Facades\Auth;
> use JeroenNoten\LaravelAdminLte\Menu\Builder;
> use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
> 
> class MenuFilter implements FilterInterface
> {
> public function transform($item, Builder $builder)
> {
> if (isset($item['role']) && ! Auth::user()->hasRole($item['role'])) {
> return false;
> }
> 
> return $item;
> }
> }`
> 
> and here is a menu config
> 
> `[ 'text' => 'Users', 'url' => 'users', 'icon' => 'users', 'role' => 'su', ],`

**app/Providers/AppServiceProvider.php**

`    public function boot()
    {
        $this->register();
        
        \Gate::define('1', function ($user) {
            if ($user->roleId == '1') {
                return true;
            }
            return false;
        });
        
        \Gate::define('2', function ($user) {
            if ($user->roleId == '2') {
                return true;
            }
            return false;
        });
        
        \Gate::define('3', function ($user) {
            if ($user->roleId == '3') {
                return true;
            }
            return false;
        });
    }`

**Comment by mohan9a** [comment]
Thanks @chrisdicarlo,

For those wo want full explanation. Here it is:

1. Create RoleMenuFilter.php file under App\Filters
2. Copy below code and paste it
`<?php

namespace App\Filters;

use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
use Auth;

class RoleMenuFilter implements FilterInterface
{
	public function transform($item)
	{
		if (! $this->isVisible($item)) {
			return false;
		}

		if (isset($item['header'])) {
			$item = $item['header'];
		}

		return $item;
	}

	protected function isVisible($item)
	{
        // check if user is a member of specified role(s) 
		if (isset($item['roles'])) {
			if (! (Auth::user())->hasAnyRole($item['roles'])) {
				// not a member of any valid roles; check if user has been granted explicit permission
				if (isset($item['can']) && (Auth::user())->can($item['can'])) {
					return true;
				} else {
					return false;
				}
			} else {
				return true;
			}
		} else {
			// valid roles not defined; check if user has been granted explicit permission
			if (isset($item['can'])) {
				// permissions are defined
				if ((Auth::user())->can($item['can'])) {
					return true;
				} else {
					return false;
				}
			} else {
				// no valid roles or permissions defined; allow for all users
				return true;
			}
		}
	}
}`
3. Add 'App\Filters\RoleMenuFilter::class,' under filters in config/adminlte.php file. So your filters will be as below:
`'filters' => [
        JeroenNoten\LaravelAdminLte\Menu\Filters\GateFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\HrefFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\SearchFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\ActiveFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\ClassesFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\LangFilter::class,
        JeroenNoten\LaravelAdminLte\Menu\Filters\DataFilter::class,
        App\Filters\RoleMenuFilter::class,
    ],`

4. Then add any menu you want to show for particular role by defining roles values in same config/adminlte.php (standard way)
`[
            'text'        => 'Users',
            'url'         => 'admin/users',
            'icon'        => 'fas fa-users',
            'roles' => [
                'Super Admin',
            ],
        ],`

**Comment by adamyulian** [comment]
> Thanks @chrisdicarlo,
> 
> For those wo want full explanation. Here it is:
> 
> 1. Create RoleMenuFilter.php file under App\Filters
> 2. Copy below code and paste it
> 
> ```
> <?php
> 
> namespace App\Filters;
> 
> use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
> use Auth;
> 
> class RoleMenuFilter implements FilterInterface
> {
> 	public function transform($item)
> 	{
> 		if (! $this->isVisible($item)) {
> 			return false;
> 		}
> 
> 		if (isset($item['header'])) {
> 			$item = $item['header'];
> 		}
> 
> 		return $item;
> 	}
> 
> 	protected function isVisible($item)
> 	{
>         // check if user is a member of specified role(s) 
> 		if (isset($item['roles'])) {
> 			if (! (Auth::user())->hasAnyRole($item['roles'])) {
> 				// not a member of any valid roles; check if user has been granted explicit permission
> 				if (isset($item['can']) && (Auth::user())->can($item['can'])) {
> 					return true;
> 				} else {
> 					return false;
> 				}
> 			} else {
> 				return true;
> 			}
> 		} else {
> 			// valid roles not defined; check if user has been granted explicit permission
> 			if (isset($item['can'])) {
> 				// permissions are defined
> 				if ((Auth::user())->can($item['can'])) {
> 					return true;
> 				} else {
> 					return false;
> 				}
> 			} else {
> 				// no valid roles or permissions defined; allow for all users
> 				return true;
> 			}
> 		}
> 	}
> }
> ```
> 
> 3. Add 'App\Filters\RoleMenuFilter::class,' under filters in config/adminlte.php file. So your filters will be as below:
> 
> ```
> 'filters' => [
>     JeroenNoten\LaravelAdminLte\Menu\Filters\GateFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\HrefFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\SearchFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\ActiveFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\ClassesFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\LangFilter::class,
>     JeroenNoten\LaravelAdminLte\Menu\Filters\DataFilter::class,
>     App\Filters\RoleMenuFilter::class,
> ],
> ```
> 
> 4. Then add any menu you want to show for particular role by defining roles values in same config/adminlte.php (standard way)
> 
> ```
> [
>     'text' => 'Users',
>     'url' => 'admin/users',
>     'icon' => 'fas fa-users',
>     'roles' => [
>         'Super Admin',
>     ],
> ],
> ```

Do I have to install Spatie?

**Comment by mohan9a** [comment]
> > Thanks @chrisdicarlo,
> > For those wo want full explanation. Here it is:
> > 
> > 1. Create RoleMenuFilter.php file under App\Filters
> > 2. Copy below code and paste it
> > 
> > ```
> > <?php
> > 
> > namespace App\Filters;
> > 
> > use JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface;
> > use Auth;
> > 
> > class RoleMenuFilter implements FilterInterface
> > {
> > 	public function transform($item)
> > 	{
> > 		if (! $this->isVisible($item)) {
> > 			return false;
> > 		}
> > 
> > 		if (isset($item['header'])) {
> > 			$item = $item['header'];
> > 		}
> > 
> > 		return $item;
> > 	}
> > 
> > 	protected function isVisible($item)
> > 	{
> >         // check if user is a member of specified role(s) 
> > 		if (isset($item['roles'])) {
> > 			if (! (Auth::user())->hasAnyRole($item['roles'])) {
> > 				// not a member of any valid roles; check if user has been granted explicit permission
> > 				if (isset($item['can']) && (Auth::user())->can($item['can'])) {
> > 					return true;
> > 				} else {
> > 					return false;
> > 				}
> > 			} else {
> > 				return true;
> > 			}
> > 		} else {
> > 			// valid roles not defined; check if user has been granted explicit permission
> > 			if (isset($item['can'])) {
> > 				// permissions are defined
> > 				if ((Auth::user())->can($item['can'])) {
> > 					return true;
> > 				} else {
> > 					return false;
> > 				}
> > 			} else {
> > 				// no valid roles or permissions defined; allow for all users
> > 				return true;
> > 			}
> > 		}
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Add 'App\Filters\RoleMenuFilter::class,' under filters in config/adminlte.php file. So your filters will be as below:
> > 
> > ```
> > 'filters' => [
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\GateFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\HrefFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\SearchFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\ActiveFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\ClassesFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\LangFilter::class,
> >     JeroenNoten\LaravelAdminLte\Menu\Filters\DataFilter::class,
> >     App\Filters\RoleMenuFilter::class,
> > ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Then add any menu you want to show for particular role by defining roles values in same config/adminlte.php (standard way)
> > 
> > ```
> > [
> >     'text' => 'Users',
> >     'url' => 'admin/users',
> >     'icon' => 'fas fa-users',
> >     'roles' => [
> >         'Super Admin',
> >     ],
> > ],
> > ```
> 
> Do I have to install Spatie?

You can if you want to. Would be nice if that roles can be accessible from Auth::user() so you can change condition at this line:
`if (! (Auth::user())->hasAnyRole($item['roles'])) {`
