### ISSUE TITLE
QUESTION: possibility to Install the v.1 on laravel 6.0

### ISSUE THREAD

**Issue by sauriio** [jeroennoten/Laravel-AdminLTE#810]
This is more a question than anything, it's possible to install the v.1 of this package, I tried to update the lib but there are some serious problem with how the layout is displayed and we need to maintain the same layout but we must update the laravel version of our project.

if there is a restraint please let me know.

Thanks in advance.

**Comment by resslinger** [comment]
We can not give support for the v1. Sorry for that.
