### ISSUE TITLE
Icons not showing and can't add to side bar

### ISSUE THREAD

**Issue by marcmaalouly** [jeroennoten/Laravel-AdminLTE#816]
I was using adminlte for a while now , suddenly all icons are no longer showing and when i add something to the side bar in config/adminlte.php it won't appear.[
![adminlte](https://user-images.githubusercontent.com/65512028/109199548-40c81e80-77a8-11eb-84bc-a2149ba7bf7f.PNG)
](url)

i've added to the sidebar something called organization , and as you can see its not appearing

**Comment by REJack** [comment]
check if your font-awesome css get loaded correctly

**Comment by marcmaalouly** [comment]
> check if your font-awesome css get loaded correctly

It was loading perfectly, Idk why it stopped loading.
What about the sidebar, it's not adding the new links and names when i add them in adminlte

**Comment by Shidersz** [comment]
@marcmaalouly Please share your menu configuration, have you defined and `url` or `route` attribute for the menu item called **organization**? Check required attributes for menu item [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu).

**Comment by marcmaalouly** [comment]
> @marcmaalouly Please share your menu configuration, have you defined and `url` or `route` attribute for the menu item called **organization**? Check required attributes for menu item [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu).

Yes, i did the same for all the other menus that are working fine!
![organization](https://user-images.githubusercontent.com/65512028/109208694-50009980-77b3-11eb-9a47-0d449cae51a3.PNG)

**Comment by Shidersz** [comment]
Maybe you have cached the Laravel's configuration.... see [Laravel's cache configuration](https://laravel.com/docs/8.x/configuration#configuration-caching). You can try executing `php artisan config:clear` from the console...

**Comment by marcmaalouly** [comment]
> Maybe you have cached the Laravel's configuration.... see [Laravel's cache configuration](https://laravel.com/docs/8.x/configuration#configuration-caching). You can try executing `php artisan config:clear` from the console...

Thanks man clearing cache fixed the sidebar problem! But the font-awesome icons are still not showing.

**Comment by Shidersz** [comment]
@marcmaalouly as @REJack says it should be a deployment problem. Check if you have the folder `public/vendor/fontawesome-free/` on your Laravel project, and in particular the file: `public/vendor/fontawesome-free/css/all.min.css`.

Also, try running `php artisan adminlte:install --only=assets`

**Comment by marcmaalouly** [comment]
> php artisan adminlte:install --only=assets

Thank you it worked :)
