### ISSUE TITLE
Add script methods at a general level

### ISSUE THREAD

**Issue by hernandoglobal** [jeroennoten/Laravel-AdminLTE#818]
| Question                | Answer
| ----------------------- | -----------------------
| Assue or Enhancementevel    | Add script methods at a general level
| Laravel Version         |  8.x
| Project Version         | 3

### Current Behavior

I install:
https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation

I need to edit the main layout of adminlte, because I need a script method to run in all views.
but I can't find the main layout to add my script methods.
"@extends ('adminlte :: page')"

when i run the command
"php artisan vendor: publish --provider =" JeroenNoten\LaravelAdminLte\ServiceProvider " --tag = views"

this shows me:
"Unable to locate publishable resources."

I tried running the command:
php artisan adminlte: install --type = full

and I select all the options to overwrite all "yes", "yes", "yes" ...
but when I run the command:
php artisan adminlte: status

everything installed, except what I think I need:
main_views | The default package main views | Not Installed | false |

![Captura](https://user-images.githubusercontent.com/79588523/109398945-cb765e00-790d-11eb-98ad-6f1d86256c86.PNG)

I need to add 3 js methods in all the views, and I don't want to repeat them for each view, this is how I would like to add it in the main layout "@extends ('adminlte :: page')" That means that I want it in the "page", so that these methods work in all views.

example of my methods:

```
<script>
    @if (session('update'))
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'updade ok xxxxx',
            showConfirmButton: false,
            timer: 1500
        })
@endif
</script>

<script>
    @if (session('delete'))
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: 'Delete ok  xxxx',
            showConfirmButton: false,
            timer: 1500
        })
        @endif
</script>
```
What could I do? Thank you very much to anyone who can help me.

 Steps to Reproduce

1. install laravel:
"laravel new project"

2. composer require jeroennoten/laravel-adminlte
3. composer require laravel/ui
4. php artisan adminlte:install --type=full
5. php artisan adminlte:status

**Comment by resslinger** [comment]
Please try following:

php artisan adminlte:install --type=full --with=main_views

The main views are not included with the install command.

**Comment by Shidersz** [comment]
@hernandoglobal To install **main_views** you need to use `php artisan adminlte:install --only=main_views`, read the [Artisan Commands Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Artisan-Console-Commands) to check how use the commands.

However it will be better if you include your custom `js` file as a plugin, see the [Plugins Section](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Other-Configuration#plugins) for that...

```php
'plugins' => [
    /* Other plugins definition... */
    ...
    'MyCustomFiles' => [
        'active' => true,
        'files' => [
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/custom-files/my-script-1.js',
            ],
            [
                'type' => 'js',
                'asset' => true,
                'location' => 'vendor/custom-files/my-script-2.js',
            ],
        ],
    ],
]
```

Then you can place your custom script file into `public/vendor/custom-files/` folder...

**Comment by hernandoglobal** [comment]
Thanks to all, after several days, and many tests I have been able to do it, with the command:

php artisan adminlte:install --type=full --with=main_views

and I also checked that it can be done with the command:
php artisan adminlte:install --only=main_views

Shidersz
I can't use it as a plugin, in fact all this was to use some conditionals from the Sweetalert2 plugin, but I didn't want to repeat the conditions every time, for every view.

Thanks to all.
