### ISSUE TITLE
Error: Class 'App\Http\Controllers\Datatables'

### ISSUE THREAD

**Issue by hernandoglobal** [jeroennoten/Laravel-AdminLTE#819]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | 8.x
| Project Version         | 3

### Current Behavior

I have activated the datatables plugin in adminlte.php config

```
plugins' => [
        'Datatables' => [
            'active' => true,
            'files' => [ ...
```

in my view I have a script to call the controller with ajax.
but when I request the information, the controller shows me the message:

`Error: Class 'App \ Http \ Controllers \ Datatables'`

so I have tried writing to the controller:

`use Yajra \ DataTables \ Facades \ DataTables;`
or
`use DataTables;
`

and it always shows me the same error.

I've been reading and they recommend installing:

`composer require yajra / laravel-datatables-oracle`

but why should I install this, if adminlte already includes the plugin, and I just have to activate it.

How can i make the correct call? what am I doing wrong? Thanks a lot.

### Steps to Reproduce

1.  in adminlte config
```
plugins' => [
        'Datatables' => [
            'active' => true,
            'files' => [ ...
```
2.  in the controller
```
public function getall(Request $request){
        $a = $request->anno;
        
        $sql = "SELECT * FROM `table`";
        $data = DB::select($sql);
        return Datatables::of($data)->make(true);
    }
``` 
or
```
public function getall(Request $request){
        $a = $request->date;
        
        $sql = "SELECT * FROM `table`";
        $data = DB::select($sql);
        return datatables($data)->make(true);
    }
``` 

3. View: 

```
function fill_datatable(date= '') {
            var dataTable = $('#table').DataTable({
                processing: true,
                serverSide: true,
                // scrollX: 500,
                scrollY: 500,
                ajax: {
                    url: "{{ route('api.rutas.index') }}",
                    data: {date: date}
                },
                columns: [
                    {data: 'date', name: 'date'},
                ],
                
            });
        }
```

**Comment by Shidersz** [comment]
@hernandoglobal For what I understand, the [Datatables](https://datatables.net/) is a **JQuery** plugin, there is nothing available on the **server-side / PHP** that is provided by the plugin. The idea to use an **ajax** call is just to get the data for the table on the `server-side` and return it to the `client-side`. On the `client-side` you usually parse this data (if needed) and generate the datatable's source data.

Now, from where you get the example that uses **Datatables** class on **php**? I believe that is no part of the `jQuery` plugin and comes from a custom package.

**Comment by hernandoglobal** [comment]
Shidersz, Thanks for explaining to me that datatables is something that runs on the client side, and not on the server side.

to use it server side, I must make use of:
composer require yajra/laravel-datatables-oracle

I thought it was another plugin, but upon reading it carefully it is a complement, for the same plugin "datatables".

The documentation show:
_This package is created to handle server-side works of DataTables jQuery Plugin via AJAX option by using Eloquent ORM, Fluent Query Builder or Collection._

now, when I use in my controller  the method:
`return Datatables($data)->make(true);`

Everything works.
Thank you very much for your light.
