### ISSUE TITLE
question : how to rename public dir to public_html

### ISSUE THREAD

**Issue by smtc7648** [jeroennoten/Laravel-AdminLTE#82]
Hello there,

I've developed my project in adminlte and now i want to publish it online for testing purpose in hostinger...

I need to rename public dir to public_html for publishing it what should I do? How to rename it? or any other solution please suggest...

**Comment by loekiedepo** [comment]
Note that your question doesn't really have to do with AdminLTE, but everything with Laravel.

Check out [this guide](https://medium.com/laravel-news/the-simple-guide-to-deploy-laravel-5-application-on-shared-hosting-1a8d0aee923e), worked for me everytime!

**Comment by jeroennoten** [comment]
Thanks @loekiedepo
