### ISSUE TITLE
how to implement database notification system in this system? please help

### ISSUE THREAD

**Issue by Sourajit-Maity** [jeroennoten/Laravel-AdminLTE#821]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

**Comment by Shidersz** [comment]
@Sourajit-Maity I don't believe you can get any help without a little explanation of what are you looking for. On my particular case, I can't even imagine what are you talking about...

So, I suggest you to add an example explaining your needs/goals. Thanks!

**Comment by Sourajit-Maity** [comment]
Thanks for your feedback sir.
When a user register then admin get some notification on his dashboard that a new user and new user's name has just registered like this type of dashboard notification not mail notification.
Can you plz suggest how to do that?

php artisan notifications:table
php artisan migrate
I use these command and my codebase is given below

This is my joiningnotification.php 
`<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class JoiningNotification extends Notification 
{
    use Queueable;
  
    public function __construct($user)
    {
        $this->user = $user;
    }

   
    public function via($notifiable)
    {
        return ['database'];
    }

  
    public function toArray($notifiable)
    {
        return [
           // 'data' => 'This is first notification'
            'name' => $this->user->name,
            'email' => $this->user->email,
        ];
    }
}

`

**Comment by Shidersz** [comment]
Hi @Sourajit-Maity , unfortunately I have no time to help you implement/program this feature. But, assuming you are saving notifications on the database as documented on [Laravel Database Notification ](https://laravel.com/docs/8.x/notifications#database-notifications) I share to you the main logic I will follow for this case:

1. On each new registration, store a notification on the notifications table and mark it as unread.
2. Implement the next logic on the admin dashboard **view** that executes every `X` seconds:
    1. Invoke a controller's method that will get the unread notification from the database.
    2. If the result set is not empty, display unread notifications on the dashboard (maybe with [Alert format](https://adminlte.io/themes/dev/AdminLTE/pages/UI/general.html))
3. When you dismiss or close an alert/notification from the admin dashboard, call another controller's method that will mark that particular notification as read on the database.

Take in consideration this is just an idea, without consider a lot of details.
