### ISSUE TITLE
Including Alpine JS after Livewire script

### ISSUE THREAD

**Issue by ruliarmando** [jeroennoten/Laravel-AdminLTE#826]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.12
| Project Version         | 3.5

### Current Behavior

![current](https://user-images.githubusercontent.com/2479917/111740126-c8d8aa00-88b6-11eb-960f-89af3873fe97.png)

Livewire is complaining alpine should be initialized after Livewire

![complain](https://user-images.githubusercontent.com/2479917/111740606-a004e480-88b7-11eb-9525-456161291e1f.png)

### Expected Behavior

Position the alpine.js script after the livewire script

### Steps to Reproduce

Activate livewire in adminlte.php config file then add the following code to the plugins section of the config
```php
...
'Alpine' => [
            'active' => true,
            'files' => [
                [
                    'type' => 'js',
                    'asset' => true,
                    'location' => 'vendor/alpine/alpine.min.js',
                ]
            ]
        ],
...
```

### Possible Solutions

I know that we can publish the main views and then modify the page layout, but i want to know if this is possible without publishing

**Comment by pieter-stephanus** [comment]
I don't think you can, and publishing the main views will help you a lot when enabling laravel mix.

**Comment by ruliarmando** [comment]
@pieter-stephanus right, i'll do the publishing method. Thank you for answering.
