### ISSUE TITLE
Error at deploy

### ISSUE THREAD

**Issue by samuel-lujan** [jeroennoten/Laravel-AdminLTE#827]
When some page of template are loaded show some error that says the class of layoutHelper was not found.

To find the layoutHelper all that a need to do is say that laoutHelper is some class. inserting ::class after layoutHelper path
![WhatsApp Image 2021-03-18 at 11 24 10 PM](https://user-images.githubusercontent.com/17858893/111811103-7945ae80-88b5-11eb-96b5-38933db17904.jpeg)

**Comment by Shidersz** [comment]
@samuel-lujan This was already solved on **master**
Check issue: #812 
Pull requests: #825 #813

**Comment by samuel-lujan** [comment]
oh thats okay! thanks :)
