### ISSUE TITLE
Dispay Usermenu Button With User's name(my field is named in spanish)

### ISSUE THREAD

**Issue by djcorea** [jeroennoten/Laravel-AdminLTE#838]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8
| Project Version         | Latest

### Current Behavior

I have my database in spanish so my users table is named "USUARIOS" and instead of name field is named "Nombre"
, in the button of the usermenu, my button looks like invisible cause it doesn't have any text, but when i change the name of  the column to "name" it display the name of the user logged in, but i need to keep that column name in spanish 

### Expected Behavior

To show user name but to bring it from my database in spanish.
### Steps to Reproduce

![image](https://user-images.githubusercontent.com/71236827/112551404-93d0c980-8d86-11eb-8755-2e3556efeee3.png)

**Comment by Shidersz** [comment]
Hi @djcorea , this project was developed to work with the default Laravel migrations. So **name** attribute is expected to exists for every user. However, I believe you can solve this from the **User Model**. Check next link:

https://stackoverflow.com/questions/43162915/laravel-5-best-way-to-modify-column-name-in-model

Maybe with something like next:

```php
class User extends Model
{
    // ...

    public $appends = [
        'name',
    ];

    public function getNameAttribute()
    {
        return $this->attributes['nombre'];
    }

    // ...
}
```

**Comment by djcorea** [comment]
Thanks @Shidersz  I solved my problem by changins Auth::user()->name to the name of my field in the views that were downloaded on vendor folder.

**Comment by Shidersz** [comment]
@djcorea OK, that is another solution. However, you need to [publish the views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) to the `resources/views/vendor/adminlte` folder, because the ones downloaded within the package will be overwritten on every package update.
