### ISSUE TITLE
ActiveChecker.php returns true while it should return false

### ISSUE THREAD

**Issue by schouinard** [jeroennoten/Laravel-AdminLTE#84]
Given Menu items and routes:

List all items: /items
Create a new item: /items/create 

And I am on /items/create
ActiveChecker::isActive returns true on both items because it checkExactOrSub instead of CheckExact

**Comment by jeroennoten** [comment]
This is intentional. Define custom `active` routes for the `/services` menu item as explained in the README: https://github.com/jeroennoten/Laravel-AdminLTE#active-menu-items

**Comment by schouinard** [comment]
You realise that any resource route must be overriden then? Pretty weird when you are building a CRUD app for multiple resource models no?

**Comment by jeroennoten** [comment]
It is very useful when you have a menu item with e.g. an edit button on the page that links to a sub-URL.

However, you are free to implement your own ActiveChecker, and replace it in the `filters` array in the config. Refer to https://github.com/jeroennoten/Laravel-AdminLTE#custom-menu-filters

Moreover, your point is valid and it may be a good idea to have an option in the config to enable/disable active checking for sub-URLs. I would definitely accept a pull requests that adds this.
