### ISSUE TITLE
which version we can use for laravel-8  PHP 8.0.2 

### ISSUE THREAD

**Issue by Nslkh** [jeroennoten/Laravel-AdminLTE#841]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue|Enhancement
| Laravel Version         | Used version of Laravel
| Project Version         | Used version of this project

**Comment by Shidersz** [comment]
The last release [v3.5.4](https://github.com/jeroennoten/Laravel-AdminLTE/releases/tag/v3.5.4). Read the [installation steps](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation)...
