### ISSUE TITLE
Interactive installer should install more

### ISSUE THREAD

**Issue by CyberPunkCodes** [jeroennoten/Laravel-AdminLTE#843]
The interactive installer should also assist with installing the additional items: auth_views, basic_views, basic_routes, main_views

**Comment by Shidersz** [comment]
@WadeShuler can you add more details of what you expect. We already have created a wiki page for the [Artisan Commands](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Artisan-Console-Commands)

**Comment by WadeShuler** [comment]
I kind of expect an interactive installer to be able to install everything.

I don't want the translations, but I want to install EVERYTHING else.

It doesn't look like I can do a `--type=full` and say `without translations`.

`basic`, `enhanced`, and `full` all add the translations.


So it seems I would have to use a `--with` 6 times:

```
php artisan adminlte:install --with=assets --with=config --with=main_views --with=auth_views --with=basic_views --with=basic_routes
```

Maybe add a question on the installer, like "Would you like to install additional items?". If yes, then ask them about all of the rest of the items..

```
Would you like to install additional items?

Would you like to install the main views?
Would you like to install the auth views?
Would you like to install the basic views?
Would you like to install the basic routes?
```

Maybe there is a way to install everything but the translations and I am missing it?

However, I still think the interactive installer should be able to install these additional items...

**Comment by Shidersz** [comment]
@WadeShuler thanks for the feedback, I will take this on consideration for future improvements on the artisan commands.

**Comment by dfsmania** [comment]
From version `v3.12.0` you are able to execute:

`php artisan adminlte:install --type=full --interactive`

To be asked about the installation of all resources. However, additional resources are used only to cover some particular situations and may be rarely used. So, we've decided not to include this procedure on the basic package installation.
