### ISSUE TITLE
QUESTION: Is it possible to change the inheritance?

### ISSUE THREAD

**Issue by Chiplex** [jeroennoten/Laravel-AdminLTE#845]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 8.12
| Project Version         | ^8.2

### Current Behavior

Why are the module controllers inherited from "Illuminate\Routing\Controller" and not from "App\Http\Controllers\Controller"?

### Expected Behavior

I want to reuse any function that comes from this controller "App\Http\Controllers\Controller"

### Steps to Reproduce
change from this:

```
<?php

namespace Modules\Core\Http\Controllers;

use Illuminate\Routing\Controller;

class CoreController extends Controller
{
    public function index()
    {
        $data = $this->GetPermissions(); // this does not work obviously 
        return view('core::index', compact("data"));
    }
}
```

to this:

```
<?php

namespace Modules\Core\Http\Controllers;

use App\Http\Controllers\Controller;

class CoreController extends Controller
{
    public function index()
    {
        $data = $this->GetPermissions(); // this works
        return view('core::index', compact("data"));
    }
}
```

### Possible Solutions

if I make the change, it will produce an error

**Comment by Chiplex** [comment]
> 
> 
> @Chiplex Project version **7.4.6** ?? We have no project with that version... Are you sure the issue is related to this package??

it's my mistake, it's already corrected

**Comment by Shidersz** [comment]
@Chiplex  Please review your issue. I have no idea what you are talking about, this packages is just an integration of the **AdminLTE** template into the **Laravel** framework.

> Why are the module controllers inherited from "Illuminate\Routing\Controller" and not from "App\Http\Controllers\Controller"?
Or add a reference to the file related to that question...

**Comment by Chiplex** [comment]
> 
> 
> @Chiplex Please review your issue. I have no idea what you are talking about, this packages is just an integration of the **AdminLTE** template into the **Laravel** framework.
> 
> > Why are the module controllers inherited from "Illuminate\Routing\Controller" and not from "App\Http\Controllers\Controller"?
> 
> Or add a reference to the file related to that question...

@Shidersz Please can you delete this issues 👉👈 , I was wrong repository 😓

**Comment by Shidersz** [comment]
@Chiplex I'm not sure if I can delete the issue. I just close it...
