### ISSUE TITLE
Confirm Password (lock screen) logic/flow doesn't work

### ISSUE THREAD

**Issue by WadeShuler** [jeroennoten/Laravel-AdminLTE#849]
The "Confirm Password" logic doesn't work because the "I forgot my password" link on the lock screen just takes them to the dashboard. They can't follow the "forgot password" procedure when they are already logged in.. So in order to reset their password, they would first need to be logged out.

I know we can code it ourselves. I just think out of the box, this repo should handle it.

**Comment by Shidersz** [comment]
hi @WadeShuler , I have it working on my environment. That link uses the configured `adminlte.password_reset_url`. Maybe is a problem with your Laravel routes, can you share they? Also, what Laravel authentication scaffolding have you installed?

**Comment by WadeShuler** [comment]
I see, it does work when using Laravel UI. I have 3 projects I am swapping between. I have my own actual project, then 1 for Laravel Breeze, then 1 for AdminLTE (with ui). I tracked the changes with Git on all 3 to identify what was changing/different between them. My main project is a hybrid since your repo isn't compatible with Breeze. I basically used Breeze for it, then am putting AdminLTE on it but keeping the Breeze way of doing things (especially the routes).

It appears that Laravel UI doesn't have any middleware on the password reset, as you can see in the source: [https://github.com/laravel/ui/blob/master/src/AuthRouteMethods.php#L63](https://github.com/laravel/ui/blob/master/src/AuthRouteMethods.php#L63)

However, Laravel Breeze has the guest middleware:

```
Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
                ->middleware('guest')
                ->name('password.request');
```

I am new to Laravel, but I assume the guest middleware is why it redirects me to the dashboard when I click the reset password link on the lock screen :) I didn't catch it because I didn't run migrations and login to test it out on the AdminLTE copy. Swapping between 3 copies is a pain. When I am done though, I will have a nice combination of your repo of AdminLTE for Breeze. Just about there.

I don't think it makes sense for a logged in user to be able to reset their password though, so I see why Breeze uses the guest middleware..

**Comment by Shidersz** [comment]
It is related to **Laravel Brezee** support...
