### ISSUE TITLE
Integrate Vue.js

### ISSUE THREAD

**Issue by webspeaks** [jeroennoten/Laravel-AdminLTE#85]
How can we integrate vue.js in this template?

**Comment by jeroennoten** [comment]
Just put the necessary `<script>` tags referring the JavaScript files (or containing inline JavaScript) in the `js` section.

**Comment by cgarrotti** [comment]
No working ! I put in my home.blade.php:
@section('js')
    <script src="{{ asset('js/app.js') }}"></script>
    <script>$('#example').DataTable(); </script>
@stop

and appear:

Uncaught TypeError: $(...).DataTable is not a function
    at home:728
