### ISSUE TITLE
Undefined constant "JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper"

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#851]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.34.0
| Project Version         | 3.5.4

### Current Behavior

After a `composer install` this error now appears:
```
Undefined constant "JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper" (View: /application/resources/views/vendor/adminlte/page.blade.php)
```
on
```
@inject('layoutHelper', \JeroenNoten\LaravelAdminLte\Helpers\LayoutHelper)
```

I have dig a bit and found that these are my Application Service Providers on `config/app.php`:
```
/*
* Application Service Providers...
*/
App\Providers\AppServiceProvider::class,
App\Providers\AuthServiceProvider::class,
App\Providers\BroadcastServiceProvider::class,
App\Providers\EventServiceProvider::class,
App\Providers\HorizonServiceProvider::class,
App\Providers\RouteServiceProvider::class,

App\Providers\TelescopeServiceProvider::class,
```

My guess is that Laravel missed the package's service provider?

Note: this project already used this package, so it already has all the configs and views published.

**Comment by resslinger** [comment]
The error was fixed in v3.5.5. Please make an update to this version over composer. This will not broke your project.

**Comment by Shidersz** [comment]
@MathiasOliveira these issues are already fixed with #825 and #813 . If you have published the main views, please follow the [update procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating), especially the **step 3**.

**Comment by MathiasOliveira** [comment]
@Shidersz I already have the latest version (3.5.4 from packagist), so there is nothing for me to update. 

I manually changed my views based on the PR you mentioned and it worked, thank you.

**Comment by Shidersz** [comment]
@MathiasOliveira Now sounds like a routing problem, can you share the routes definitions?

**Comment by MathiasOliveira** [comment]
Its not a routing problem, the application resolves fine the routes in the example above, its just the drop down headers that instead of expanding on click now have a link to localhost, but all items inside a drop down have the correct routes:

![image](https://user-images.githubusercontent.com/67007152/113183390-578be600-922a-11eb-83e1-620bcf1ae586.png)

**Comment by MathiasOliveira** [comment]
Nevermind, I was just an idiot and didn't ran `npm i`, found the errors on the dev console.

Thank you for help and sorry for wasting your time.
