### ISSUE TITLE
Issues with Blade-X component - Alert

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#859]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Enhancement
| Laravel Version         | 8.36.2
| Project Version         | dev-master

I am reviewing the newly added Blade-X components for use in our projects and I found few problems that I would be creating bug reports for - one for each component.

### Current Behavior
In the alert component
1. There is no way to have a heading less alert. The minimal alert component has a h5 header with default icon.
2. There is no way to completely remove the icon element. If we don't specify icon, it defaults to the theme icon. If we pass an empty string, the icon element is still rendered due to which title shifts by the element's margin.
3. Use of custom themes is not possible and results in an error. For example, we may want to create an alert of type 'missing' by defining a css class `.alert-missing`

### Expected Behavior
1. We should be able to create a minimal alert with only body text.
2. We should be able to create an alert with text header but no icon.
3. Alert classes should be extensible and support custom themes.

### Steps to Reproduce
```html
<x-adminlte-alert>Minimal example</x-adminlte-alert>
<x-adminlte-alert icon="">Minimal example</x-adminlte-alert>
<x-adminlte-alert title="Well done!">Minimal example</x-adminlte-alert>
<x-adminlte-alert icon="" title="Well done!">Minimal example</x-adminlte-alert>
{{-- line below results in an error --}}
<x-adminlte-alert theme="missing">Minimal example</x-adminlte-alert>
```
<img width="745" alt="Screenshot1" src="https://user-images.githubusercontent.com/11003751/114281074-e6360980-9a59-11eb-8c1d-96eb44e8f794.png">

#### Expected output is
<img width="745" alt="Screenshot2" src="https://user-images.githubusercontent.com/11003751/114281106-17163e80-9a5a-11eb-9106-812648813e11.png">

### Possible Solutions
1. Showing an icon without title should not be supported. If someone wants to show the icon without title, they can provide an empty string for title attribute.
2. There should be a way to disable the icon element when title is provided. eg `icon=""`.

I am submitting a PR that fixes the above issues.

**Comment by Shidersz** [comment]
Hi @adwiv 

> 1. There is no way to have a heading less alert. The minimal alert component has a h5 header with default icon.
> 2. There is no way to completely remove the icon element. If we don't specify icon, it defaults to the theme icon. If we pass an empty string, the icon element is still rendered due to which title shifts by the element's margin.

Accepted, when no `icon` or `title` attribute is defined, there will be no default value for they. When both are not used, the title section will not be rendered.

> 3. Use of custom themes is not possible and results in an error. For example, we may want to create an alert of type 'missing' by defining a css class `.alert-missing`

The `theme` attribute only accepts a predefined set of values:  dark, light, primary, secondary, info, success, warning or danger. We can't allow custom values here. To add custom style you can use the `class` attribute that will be merged with the `.alert` one, for example:

```blade
<x-adminlte-alert class="alert-missing">Minimal example</x-adminlte-alert>
```

Will now result in:

```html
<div class="alert border alert-missing">
    Minimal example
</div>
```

I made these improvements on you first PR #860
