### ISSUE TITLE
Issues with Blade-X component - Input & InputGroup

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#861]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8.36.2
| Project Version         | master

### Current Behavior
1. The generated `id` attribute always defaults to same value as `name` attribute and it is not possible to override it. The `id` attribute can be different from `name` in case of multiple forms on the same page or when `name` is specifies array element like `price[102]` while we want to use `price-102` for `id` attribute.
2. The `size` attribute [which is a valid attribute of input tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#htmlattrdefsize) is used for input group sizing instead and removed from output. It is commonly used to limit the number of characters allowed in the input field.
3. The support for [client side form validation](https://getbootstrap.com/docs/4.6/components/forms/#custom-styles) is not present, only server side validation can be used. Client side validation is almost always used in every website.

### Expected Behavior
1. The `id` attribute should default to `name` if it is not explicitly defined. Otherwise it must use the defined value.
2. Specifying `size` attribute on an input component should generate the corresponding size attribute in the html.
3. We should be able to define client side 'invalid-feedback' using the component which should be displayed.

### Steps to Reproduce
```html
<x-adminlte-input name="username" id="userid" value="100" size="5" label="Amount"/>
```
Generates the following (note id field is generated twice, and size field is missing)
```html
<div class="form-group">
    <label for="username">Amount</label>
    <div class="input-group">
        <input id="username" name="username" class="form-control" id="userid" value="100">
    </div>
</div>
```

### Possible Solutions
1. Add id attribute to the list of attributes handled by the component. If it is null, use the value of name attribute.
2. Use some other attribute name instead of size for input group sizing.
3. Allow defining a slot for invalid-feedback (and maybe one for valid-feedback too) to handle client size validations.

**Comment by Shidersz** [comment]
@adwiv Thanks for your feedback, I will review these enhancements after finishing some work with the **AdminLTE v3.1.0** integration.

**Comment by Shidersz** [comment]
@adwiv I'm working on this one, these are the changes I propose:

> Add `id` attribute to the list of attributes handled by the component. If it is null, use the value of name attribute.

Will be implemented as you have suggested.

> Use some other attribute name instead of size for input group sizing.

I'm going to rename the next properties for the **input-group-component** so they are more descriptive:
- `size` => `igroup-size`   (input group size)
- `input-group-class` => `igroup-class` (input group extra classes)
- `top-class` => `fgroup-class` (form group extra classes)

> Allow defining a slot for invalid-feedback (and maybe one for valid-feedback too) to handle client size validations.

You can use the `id` attribute to target the element using `jQuery` (for example) and change it to provide an invalid look, append extra container with a message, etc. For the moment I won't add any extra support to this.

Please, I will like to hear your opinion about these proposals?

**Comment by adwiv** [comment]
These sound good to me.

I would have preferred to have just one generic slot for html validations,
but it's not a deal breaker.

I have few more features in mind about bladeX components that I really
need, will post them once I get well.

**Comment by Shidersz** [comment]
@adwiv Thanks for your quick response. If any of these ideas is related to the **input-group-component** please share it here. Since all modifications made to this one impacts on most of the form components.

**Comment by adwiv** [comment]
No, input group component I had reviewed and had put all my wish list.

New features were related to missing select options component and one more
I don't remember right  now.

**Comment by Shidersz** [comment]
@adwiv I have found another issue related to the `input-group-component` and the use of a complex structure for the `name` attribute. When you setup the `name` attribute to a string like `person[1][first_name]`, for example, the input will be submitted to **php** inside some structure like next one:

```php
'person' => 
  array (
    1 => 
    array (
      'first_name' => 'John',
    ),
  ),
)
```

Then when a validation error is triggered, usually it will be related to name `person.1.first_name` but we are actually looking for the original name, i.e, `person[1][first_name]`.

To solve this, I have tested and it is possible to automatically generate the lookup name from the provided original name. But I'm not sure if for some particular situation we should provide a way so the user can setup this invalid lookup name in replacement of the auto generated one. What do you think?

**Comment by adwiv** [comment]
I don't think there is a need for user to provide his own lookup key for
errorbag. The keys are generated by the validator and we should be able to
replicate that.

However if the user generates custom error messages and wants to handle
them on his own by overriding our error handling, he should be able to do
it.

**Comment by Shidersz** [comment]
@adwiv Ok, my proposal is to automatically generate the lookup key for the **error bag** from the provided **name** attribute and support a new attribute called **error-key** that will provide a way to override the auto generated one.

**Comment by Shidersz** [comment]
@adwiv It would be nice if you can review the PR #873 when you get some time...
Thanks!

**Comment by adwiv** [comment]
@Shidersz The commit looks good. 

On issue I think lies in the function `makeErrorKey` where only `a-zA-Z0-9_-` characters are allowed as array key values. Laravel is actually very permissible, it even allows dot character. A typical use case can be use of email address or some unicode in array keys. I would suggest using `([^]]+)` instead so that it allows everything to mimic laravel behaviour.

Another change I can suggest is to change the class variable `size` to `igroupSize` for consistency sake, but that's only pedantic.

**Comment by Shidersz** [comment]
@adwiv Thanks for the your feedback. You are of great help. I prefer to keep `size` name internally because it is shorter and I do not have to split code into multiple lines to keep it under the 80 chars limit (but that is only a coding style).
