### ISSUE TITLE
top nav always visible

### ISSUE THREAD

**Issue by hernandoglobal** [jeroennoten/Laravel-AdminLTE#862]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Question
| Laravel Version         | 8.35.1
| Project Version         | 3.4.4

As I can leave permanent, the top menu. "topnav."
That is, I want it to always remain visible no matter how much it goes down with the scroll.

Thank you!

**Comment by Shidersz** [comment]
@hernandoglobal Use the **layout_fixed_navbar=true** on the configuration file, read more here:
[Layout Config](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#layout)
