### ISSUE TITLE
How to modify the login form?

### ISSUE THREAD

**Issue by victorhugorch** [jeroennoten/Laravel-AdminLTE#87]
I'm use Laravel 5.4 and my login not use "name, email, password" but other paramethers.

How can I edit this things in login form?

**Comment by jeroennoten** [comment]
Refer to [Customize views](https://github.com/jeroennoten/Laravel-AdminLTE#7-customize-views) in the README on how to edit the login form (and other views).

**Comment by eblucas** [comment]
Hello,

I ran  php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views

 to be able to customize the viwes  but I dont get the resources/views/vendor/adminlte.  folder.

Nothing changes, how can I customize the login and email sent?

Thanks
