### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tietnhathung** [jeroennoten/Laravel-AdminLTE#871]
please replace "almasaeed2010 / adminlte": "^ 3.0" instead of "almasaeed2010 / adminlte": ">= 3.0"

**Comment by Shidersz** [comment]
@tietnhathung can you give a better explanation? The new incoming release will use **AdminLTE v3.1.0**. We are working on integrating that...

**Comment by Shidersz** [comment]
Please, provide more information of your needs:
- Latest release **v3.5.4** uses: `"almasaeed2010/adminlte": "3.0.*"`
- The incoming release **v3.6.0** will use: `"almasaeed2010/adminlte": "3.1.*"`
