### ISSUE TITLE
Changed custom views do not apply

### ISSUE THREAD

**Issue by manhtqb** [jeroennoten/Laravel-AdminLTE#872]
I followed the Views Customization guide here: https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization

But when I tried to customize `resources/views/admin/vendor/adminlte/partials/sidebar/left-sidebar.blade.php` (like add CSS, remove element..) it didn't work, nothing applied.

I tried change `@extends('adminlte::page')` to `@extends('admin.vendor.adminlte.page')`, and I got this error: `Undefined variable: adminlte`

In a similar case when I tried to change the look of the login page, I edited `resources/views/admin/vendor/adminlte/auth/auth-page.blade.php`, but no changes were applied. I have to change `@extends('adminlte::auth.auth-page', ['auth_type' => 'login'])` to `@extends('admin.vendor.adminlte.auth.auth-page', ['auth_type' => 'login'])`, but it's worked that time.

So how can I full control of editing views?

Thanks!

**Comment by Shidersz** [comment]
@manhtqb 

> I tried change @extends('adminlte::page') to @extends('admin.vendor.adminlte.page'), and I got this error: Undefined variable: adminlte

There is no need for that change. This sounds more like you have executed the command to make a cache of your views:

```sh
php artisan view:cache
```

In that case, just execute:

```sh
php artisan view:clear
```

**Comment by manhtqb** [comment]
@Shidersz 
`php artisan view:clear`

I tried that command but it still doesn't work
Do you have any other solution?
Anyway, thank you for the reply!

**Comment by Shidersz** [comment]
@manhtqb Please, provide the changes you are trying to apply with a code example. That way I can test on my environment...

**Comment by manhtqb** [comment]
@Shidersz 
I found my mistake. That is I have moved the provider directory to another directory (like admin/provider).
I created a completely new project and everything worked perfectly.
Thank you for supporting me, I appreciate it.

**Comment by Shidersz** [comment]
@manhtqb Ok, nice to hear you have found a solution!

**Comment by ronlinet** [comment]
In my case it was missing the view composer in AppServiceProvider.  This may be posted somewhere in docs but I am going to post the the solution here. Something is telling me that other folks will land in this post the same as me. 
```
use Illuminate\View\Factory;
use Illuminate\Support\ServiceProvider;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;
use JeroenNoten\LaravelAdminLte\Http\ViewComposers\AdminLteComposer;

class AppServiceProvider extends ServiceProvider
{

/**
     * Bootstrap any application services.
     *
     * @param Factory $view
     * @return void
     */
    public function boot(Factory $view)
    {
        $view->composer('your.layout.name', AdminLteComposer::class);
    }

```
