### ISSUE TITLE
Illegal offset type (login.blade.php)

### ISSUE THREAD

**Issue by TyNguyen2k1** [jeroennoten/Laravel-AdminLTE#877]
How do i fix them? Thanks
![image](https://user-images.githubusercontent.com/64082226/116183294-ce43d280-a747-11eb-8c67-02e446f32748.png)
![image](https://user-images.githubusercontent.com/64082226/116183497-2da1e280-a748-11eb-9145-80ec4671b6a6.png)

**Comment by resslinger** [comment]
@TyNguyen2k1  The url / route should be directly add as value, for example:

`'login_url' => 'login'`

**Comment by TyNguyen2k1** [comment]
> @TyNguyen2k1  The url / route should be directly add as value, for example:
> 
> `'login_url' => 'login'`

Thanks !!!
