### ISSUE TITLE
[BUG] Datatables plugin not working

### ISSUE THREAD

**Issue by Minotti** [jeroennoten/Laravel-AdminLTE#879]
### Describe the bug
After activating the Datatable plugin I can't use it. I keep getting the error Uncaught TypeError: $ (...). DataTable is not a function. I already tried to use the solution in another Issue but it didn't solve it.

| Item    | Version
| ------- | -------
| Laravel | 8
| Project | "jeroennoten/laravel-adminlte": "^3.5"
| OS      | Ubuntu 20.04

**Comment by Shidersz** [comment]
@Minotti Please provide the configuration you are using for the plugin and how you use it on the blade view. Also, in case you have not already read, check the following link:

- [Plugins Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration)

**Comment by Shidersz** [comment]
Closed because no feedback...
