### ISSUE TITLE
 vendor:publish --provider=“JeroenNoten\LaravelAdminLte\ServiceProvider” --tag=config  don’t work

### ISSUE THREAD

**Issue by oryxtc** [jeroennoten/Laravel-AdminLTE#88]
my laravel version is 5.4；
when I run     
`php artisan vendor:publish --provider=“JeroenNoten\LaravelAdminLte\ServiceProvider” --tag=config`  
it don’t work;

but I try Remove quotation marks
`php artisan vendor:publish --provider=JeroenNoten\LaravelAdminLte\ServiceProvider --tag=config`

it Expected work！！

**Comment by jeroennoten** [comment]
That is because you are using the wrong quotation marks. Use the straight `"` instead of the curly `“`, as shown in the README.
