### ISSUE TITLE
[BUG] Unable to locate a class or view for component [adminlte-datatable]

### ISSUE THREAD

**Issue by hani-borsen** [jeroennoten/Laravel-AdminLTE#885]
### Describe the bug
Fist of all thank you for your great work. This is really awsome!

I can't get datatables working:

I get this error:
InvalidArgumentException
Unable to locate a class or view for component [adminlte-datatable].

And I can't seem to find any of the components refered to on this page:
https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Components-Categories
'This package provides some blade-x components' ...

### Steps To Reproduce
Install with:
composer require jeroennoten/laravel-adminlte
php artisan adminlte:install
php artisan adminlte:plugins install --plugin=datatables --plugin=datatablesPlugins

Create a basic view (and a route), "resources/views/test.blade.php":
-----------------------------------------------------------------------------------------------------
```
@extends('adminlte::page')
@section('plugins.Datatables', true)

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
    {{-- Setup data for datatables --}}
    @php
    $heads = [
        'ID',
        'Name',
        ['label' => 'Phone', 'width' => 40],
        ['label' => 'Actions', 'no-export' => true, 'width' => 5],
    ];

    $btnEdit = '<button class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
                    <i class="fa fa-lg fa-fw fa-pen"></i>
                </button>';
    $btnDelete = '<button class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                    <i class="fa fa-lg fa-fw fa-trash"></i>
                </button>';
    $btnDetails = '<button class="btn btn-xs btn-default text-teal mx-1 shadow" title="Details">
                    <i class="fa fa-lg fa-fw fa-eye"></i>
                </button>';

    $config = [
        'data' => [
            [22, 'John Bender', '+02 (123) 123456789', '<nobr>'.$btnEdit.$btnDelete.$btnDetails.'</nobr>'],
            [19, 'Sophia Clemens', '+99 (987) 987654321', '<nobr>'.$btnEdit.$btnDelete.$btnDetails.'</nobr>'],
            [3, 'Peter Sousa', '+69 (555) 12367345243', '<nobr>'.$btnEdit.$btnDelete.$btnDetails.'</nobr>'],
        ],
        'order' => [[1, 'asc']],
        'columns' => [null, null, null, ['orderable' => false]],
    ];
    @endphp

    {{-- Minimal example / fill data using the component slot --}}
    <x-adminlte-datatable id="table1" :heads="$heads">
        @foreach($config['data'] as $row)
            <tr>
                @foreach($row as $cell)
                    <td>{!! $cell !!}</td>
                @endforeach
            </tr>
        @endforeach
    </x-adminlte-datatable>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop
```
-----------------------------------------------------------------------------------------------------

| Item    | Version
| ------- | -------
| Laravel | Laravel Framework 8.40.0
| Project | almasaeed2010/adminlte v3.0.5, jeroennoten/laravel-adminlte v3.5.4
| OS      | Ubuntu 20.04.2 LTS

**Comment by hani-borsen** [comment]
I was expecting to find a folder with components ...
```
ls -al vendor/jeroennoten/laravel-adminlte/resources/views/
total 32
drwxrwxrwx 4 root root 4096 Mar 22 16:23 .
drwxrwxrwx 4 root root 4096 Mar 22 16:23 ..
drwxrwxrwx 3 root root 4096 Mar 22 16:23 auth
-rwxrwxrwx 1 root root 4697 Mar 22 16:23 master.blade.php
-rwxrwxrwx 1 root root 1933 Mar 22 16:23 page.blade.php
drwxrwxrwx 6 root root 4096 Mar 22 16:23 partials
-rwxrwxrwx 1 root root  825 Mar 22 16:23 plugins.blade.php
```

**Comment by Shidersz** [comment]
Hi @hani-borsen , there is no official release with the components, they are under development. Check issue #866 , there is an explanation of how you can use the `dev-master` branch in case you want to play with them now.

**Comment by hani-borsen** [comment]
@Shidersz thank you so much for the rapid response.
I'll go with dev-master and keep and eye on your next release.

Kind regards
Hasse

**Comment by Shidersz** [comment]
@hani-borsen Nice, any feedback about the components is welcome. So, feel free to open an issue or a feature request...
