### ISSUE TITLE
[FEATURE] Add support to old() on bladeX components

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#889]
### Is your request related to a problem? Please describe.
Currently, in each of Create or Edit blade file, we have to define values for input ourselves which I generally do like this.

```xml
model-edit.blade.php
<x-adminlte-input name="phone" value="{{ old('phone') ?? $model->phone ?? '' }}"/>
```

```xml
model-create.blade.php
<x-adminlte-input name="phone" value="{{ old('phone') ?? '' }}"/>
```
The `old()` function retrieves the submitted value in case of validation errors. 

Copying and pasting above code (as is common during development) can cause mistakes since phone field is used thrice.

### Describe the solution you'd like
I would like that we should be able to attach a model like this.

```xml
model-create.blade.php
<x-adminlte-input name="phone" :model="$model"/>
```
Then in our component we generate the value attribute if model is defined (using name field of the model)
```php
@if($model)
value="{{ old($name) ?? $model->$name ?? '' }}"
@endif
```

This can be useful in input as well as textarea and select fields (for selected option)

**Comment by Shidersz** [comment]
@adwiv I will address this after the first release with components, so I don't keep delaying it.

**Comment by Shidersz** [comment]
@adwiv I will start with this one soon. For the moment, I don't like the fact that the model's property to lookup for the value is coupled with the `name` HTML attribute. That will create problems in at least two situations:

- When you need to use an HTML `name` attribute that is different from the property of the model holding the value
- When you need to use a complex HTML `name` attribute, as we already discussed on #861 

So, maybe we can add a new `enable-old-value` property to the form components. When setting it to `true`, the HTML `value` property may be calculated from the one you have provided for the component, as next:

```blade
@isset($enableOldValue)
    value="{{ old($name, $attributes->get('value') ?? '' ) }}"
@endisset
```

This way, you may use the components you have provided like:

```blade
model-edit.blade.php
<x-adminlte-input name="phone" value="{{ $model->phone_number }}" enable-old-value/>
```

Note you may need to ensure `$model->phone_number` always exists, or use `$model->phone_number ?? ''` instead.

```blade
model-create.blade.php
<x-adminlte-input name="phone" enable-old-value/>
```

Without the `enable-old-value` property you still can implement your own logic to create the `value`, so you can cover very particular situations...

What do you think?

**Comment by Shidersz** [comment]
List of components to add `old()` support:

**BASIC**
- [x] x-adminlte-input
- [x] x-adminlte-select
- [x] x-adminlte-select2
- [x] x-adminlte-textarea

**ADVANCED**
- [ ] x-adminlte-input-date
- [ ] x-adminlte-input-switch
- [ ] x-adminlte-select-bs
- [ ] x-adminlte-text-editor
- [ ] x-adminlte-date-range
- [ ] x-adminlte-input-color
- [ ] x-adminlte-input-slider

**Comment by Nemachtilli** [comment]
No work enable-old-support, how to use?

`<x-adminlte-text-editor name="content"  value="{{ $post->content }}" enable-old-suport/>`

and upload file or picture gives the following error SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content

how to implement unisharp/laravel-filemanager?

**Comment by dfsmania** [comment]
@Nemachtilli

First, to add preset data to the `<x-adminlte-text-editor>` component, do not use the `value` property, the behavior is the same used on a `textarea`, you need to put the data into the tag, as next:

```blade
<x-adminlte-text-editor name="content" enable-old-suport>
    {{ $post->content }}
<x-adminlte-text-editor/>
```
or the next code, if your `$post->content` contains `html` markup
```blade
<x-adminlte-text-editor name="content" enable-old-suport>
    {!! $post->content !!}
<x-adminlte-text-editor/>
```

For your second issue, look at the error message, your SQL query to insert the data fails because data is too big for the column `content`. Also, we do not provide support for external packages like `unisharp/laravel-filemanager`.

**Comment by Nemachtilli** [comment]
Hi @dfsmania thank you very much it helped me a lot in my first question.

I have the following code, where i use a filemanager.

modifying height of summernote does not work, error in console is $ is not a function at, please help me


`<script>
        
        $(document).ready(function() {

            // Define function to open filemanager window
            var lfm = function(options, cb) {
                var route_prefix = (options && options.prefix) ? options.prefix : '/laravel-filemanager';
                window.open(route_prefix + '?type=' + options.type || 'file', 'FileManager',
                    'width=900,height=600');
                window.SetUrl = cb;
            };

            // Define LFM summernote button
            var LFMButton = function(context) {
                var ui = $.summernote.ui;
                var button = ui.button({
                    contents: '<i class="note-icon-picture"></i> ',
                    tooltip: 'Insert image with filemanager',
                    click: function() {

                        lfm({
                            type: 'image',
                            prefix: '/laravel-filemanager'
                        }, function(lfmItems, path) {
                            lfmItems.forEach(function(lfmItem) {
                                context.invoke('insertImage', lfmItem.url);
                            });
                        });

                    }
                });
                return button.render();
            };

            // Initialize summernote with LFM button in the popover button group
            // Please note that you can add this button to any other button group you'd like
            $('#summernote').summernote({
                height: 3100,
                styleTags: [
                    'p',
                    {
                        title: 'Blockquote',
                        tag: 'blockquote',
                        className: 'blockquote',
                        value: 'blockquote'
                    },
                    'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'
                ],
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'lfm', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                    ['buttons', ['lfm']],
                ],
                buttons: {
                    lfm: LFMButton
                }
            })
        });
    </script>`

**Comment by REJack** [comment]
> modifying height of summernote does not work, error in console is $ is not a function at, please help me

if you get $ is not a function error, then you scripts is loaded before jquery itself.

**Comment by Nemachtilli** [comment]
@REJack hello How to load jquery? sorry i'm new

**Comment by REJack** [comment]
It's loaded by default, otherwise you would't able to open the Sidebar Menu or even use a Dropdown. 

Where you placed the script? You need to place the script inside `@section('js') YOUR SCRIPT HERE @endsection`,
like its discribed in [the usage docs](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage).

**Comment by Nemachtilli** [comment]
@REJack thanks for the reply.

I did this, but that didn't work for me

`@section('js')
    <script> console.log('Hi!'); </script>
@endsection`

The following if it worked for me, I still do not understand what happens or what is my error

`@section('adminlte_js')
    <script> console.log('Hi!'); </script>
@endsection`

**Comment by dfsmania** [comment]
@Nemachtilli Please open an issue related to your problem with details. Discussion here is out of context!

**Comment by adwiv** [comment]
@Nemachtilli I always prefer to use push instead of section for js. This ensures one section doesn't by mistake overwrite another.

```js
@push('js') 
<script> console.log('Hi!'); </script> 
@endpush
```

**Comment by Nemachtilli** [comment]
hi, I have a text input type with the name name

`<x-adminlte-input name="name" label="Tu nombre" placeholder="Escríbe tu nombre" label-class="text-lightblue"
                enable-old-suport>
                <x-slot name="prependSlot">
                    <div class="input-group-text">
                        <i class="fas fa-user text-lightblue"></i>
                    </div>
                </x-slot>
                {{ $profile->name }}
            </x-adminlte-input>`
            
   my store method I have a request
   
   `public function rules()
    {
        switch ($this->method()) {
            case "POST": {
                return [
                    'name' => 'required|min:6|max:100',
                    'email' => 'required',
                    'birthday' => 'required',
                    'phone' => 'required|min:10|max:14',
                    'location' => 'required|min:6|max:25',
                    'bio' => 'required|min:100|max:250',
                    'hobbies' => 'required|array',
                    'avatar' => 'required',
                ];
            }
            case "PUT": {
                return [
                    'name' => 'required|min:6|max:100',
                    'email' => 'required',
                    'birthday' => 'required',
                    'phone' => 'required|min:10|max:14',
                    'location' => 'required|min:6|max:25',
                    'bio' => 'required|min:100|max:250',
                    'hobbies' => 'required|array',
                    'avatar' => 'required',
                ];
            }
            default: {
                return [];
            }
        }
    }`

if you only add information in one input, other inputs don't, the old function doesn't work

link to watch the video

https://screencast-o-matic.com/watch/c3jwYcVTmJM
