### ISSUE TITLE
around menu configuration at runtime

### ISSUE THREAD

**Issue by johnef** [jeroennoten/Laravel-AdminLTE#89]
**first** : after I registered `MenuBuilding` event and done everything

~~~
$events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $items = Blog::all()->map(function (Blog $page) {
                return [
                    'text' => $page['title'],
                    'url' => '#'
                ];
            });
            $event->menu->add($items);
        });
~~~ 

Got 

> Undefined index: text (View: C:\wamp\www\meshwebsite\resources\views\vendor\adminlte\partials\menu-item.blade.php)

**Second** : I need only to get the count of the blogs and put it in 'label' => 4,
if I did this in the AppServiceProvider it will be inserted on the top of the side menu which I don't want 

also I didn't understood this point 
`in the boot of any service provider`

**Comment by gus16710** [comment]
Hello Johnef im actually working with the menu, but i need your help, how do you registered MenuBuilding event?? I don´t kwon how to do that.

Please help.. :(

**Comment by johnef** [comment]
@gus16710 OK this part is easy just registering an event you need use artisan command
`php artisan event:generate` 
You can review this part from here https://laravel.com/docs/5.4/events#registering-events-and-listeners

**Comment by gus16710** [comment]
@johnef thanks for your help, i do the next steps:

" register a handler or callback for the MenuBuilding event"

I think i have to create a new event in the "EventServiceProvider" file

Like:

protected $listen = [
'App\Events\MenuBuilding' => [
'App\Listeners\MenuBuilding',
],
];

then i run the command php artisan event:generate

then i do the next like the documentation

class AppServiceProvider extends ServiceProvider
{

public function boot(Dispatcher $events)
{
    $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
        $event->menu->add('MAIN NAVIGATION');
        $event->menu->add([
            'text' => 'Blog',
            'url' => 'admin/blog',
        ]);
    });
}
}

But here im lost. :(

Please if you can tell me the correct steps to do it correctly.

**Comment by jeroennoten** [comment]
@gus16710 Hi, you do not have to do anything in you EventServiceProvider. This is already done by the package. The rest seems ok.
