### ISSUE TITLE
[FEATURE] Add a way to add options to select component

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#890]
### Is your request related to a problem? Please describe.
We currently add options to select component using the slot.
```xml
<x-adminlte-select name="myoption">
    @foreach($options as $option)
          <option @if($option->id == $model->myoption) selected @endif
                  value="{{ $option->id }}">{{ $option->name }}</option>
    @endforeach
</x-adminlte-select>
```

### Describe the solution you'd like
It would be great if we can pass the select options to the component so that it generates them automatically. Something like this:
```xml
<x-adminlte-select name="myoption" :model="$model" :array="$options"/>
<x-adminlte-select name="myoption" :value="$model->myoption" :array="$options"/>
<x-adminlte-select name="myoption" :model="$model" 
        :options="$options" option-key="id" option-value="name" 
         empty="true" empty-text="Select ..."/>
```

By combining with model attribute from #889 or using a value attribute, we can also mark correct option as selected.

This way we can offer support for both simple array (key-value pairs) as well as for collections.

**Comment by Shidersz** [comment]
@adwiv I'm not so comfortable with adding a lot of extra attributes to the component to manage the `options` collection you propose. The idea is good, but maybe we can use `:options-cfg="$optionsCfg"` and `:options-data="$options"` and avoid using the `option-key`, `option-value`, `empty`, `empty-text`, etc...

**Comment by adwiv** [comment]
@Shidersz A config object would be great. If we give sensible defaults like in the example given by you, most users might not need options-cfg attribute at all and make it work with options-data only.

**Comment by Shidersz** [comment]
@adwiv I will address this after the first release with components.

**Comment by adwiv** [comment]
@Shidersz It appears that the solution is much simpler. 

We can create an options component which gets nested within the select component.

```html
<x-adminlte-select name="myoption">
    <option value="">Select option...</option>
    <x-adminlte-options :options="$options" selected="1"/>
    <x-adminlte-options :options="['Red','Blue','Green']"/>
    <x-adminlte-options :options="\App\Models\User::pluck('name','id')->all()" :selected="$model->user_id"/>
</x-adminlte-select>
```

I have created a component and tested the above code. Only two parameters - options and selected are supported. options parameter is always an array and selected can be either a value or an array (to support multiple selections). All the requirements of the original post can be supported

If this sounds okay, will send a PR.

**Comment by Shidersz** [comment]
@adwiv It sounds good to me, if you create a PR I will review as soon as I get some time...
