### ISSUE TITLE
[QUESTION] Dark mode

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#891]
In adminlte v3 there is a dark mode available for use
![image](https://user-images.githubusercontent.com/67007152/117495686-58601800-af4c-11eb-8e29-7b2bdae43edf.png)

Is it possible to use that in this package?

**Comment by Shidersz** [comment]
Hi @MathiasOliveira , that is part of the recent **AdminLTE v3.1.0** release. We are currently working on integrating this new version within the package. It will be a nice option to include. So, I will schedule this as a task for the incoming new release **v3.6.0**. Would you like a configuration option for this feature, or prefer a new menu item for a toggle button in the navbar?

**Comment by MathiasOliveira** [comment]
I feel like a configuration option would be the best.

**Comment by REJack** [comment]
@MathiasOliveira for now add simply `dark-mode` into the config value `classes_body`.

**Comment by Shidersz** [comment]
Note the option mentioned by @REJack will only work if you are using the `dev-master` branch of this package.

**Comment by REJack** [comment]
@Shidersz is the AdminLTE v3.1 not available in the actual releases? 😄

**Comment by MathiasOliveira** [comment]
@Shidersz A setting in the `configs/adminlte.php` , something like:
````
/*
    |--------------------------------------------------------------------------
    | Admin Panel Classes
    |--------------------------------------------------------------------------
    |
    | Here you can change the look and behavior of the admin panel.
    |
    | For detailed instructions you can look the admin panel classes here:
    | https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration
    |
    */

    'dark_mode' => true|false,
````

**Comment by Shidersz** [comment]
@REJack No, I'm still working on the integration with the new blade components, some enhancements and old requirements. All will be released with version **3.6.0**.

**Comment by REJack** [comment]
Oh ok ^^ how is it going? 😄

**Comment by Shidersz** [comment]
@MathiasOliveira PR #893 already created for the dark mode option. On the future I will create a new special navbar menu item for toggle the dark mode.
