### ISSUE TITLE
[BUG] Nested dropdowns don't work while layout is in topnav and viewport is in mobile

### ISSUE THREAD

**Issue by MathiasOliveira** [jeroennoten/Laravel-AdminLTE#892]
### Describe the bug
While you have `'layout_topnav'` set to true all nested dropdowns don't work while your viewport is in mobile.

### Steps To Reproduce
1. set `'layout_topnav' => true,` in `configs/adminlte.php`
2. use chrome dev tools to simulate a mobile view.
2. Click on any nested dropdowns

### Screenshots
https://youtu.be/x4UwTlBUm10

### Environment

| Item    | Version
| ------- | -------
| Laravel | v8.34.0
| Project | v3.5.4
| OS      | Win 10 20H2 + WSL2 Ubuntu 20.04

### Additional context
The submenu does open if you hold the dropdown item.
https://youtu.be/0yhCPhTwtog

**Comment by MathiasOliveira** [comment]
Here you go:
````
[
    'text' => 'Ferramentas',
    'icon' => 'nav-icon fas fa-tools',
    'can' => [
        'supre.clients.index',
        'supre.support.index',
        'supre.users.online',
        'exporter.index',
    ],
    'submenu' => [
        [
            'text' => 'Nexello Supre',
            'icon' => 'nav-icon fas fa-boxes',
            'can' => [
                'supre.clients.index',
                'supre.support.index',
                'supre.users.online',
            ],
            'submenu' => [
                [
                    'text' => 'Clientes',
                    'icon' => 'nav-icon fas fa-user-tie',
                    'route' => 'supre.clients.index',
                    'can' => 'supre.clients.index',
                    'active' => ['admin/tools/supre/clients/*'],
                ],
                [
                    'text' => 'Usuários Suporte',
                    'icon' => 'nav-icon fas fa-user-cog',
                    'route' => 'supre.support.index',
                    'can' => 'supre.support.index',
                    'active' => ['admin/tools/supre/support_users/*'],
                ],
                [
                    'text' => 'Usuários Online',
                    'icon' => 'nav-icon fas fa-user-check',
                    'route' => 'supre.users.online',
                    'can' => 'supre.users.online',
                ],
            ],
        ],
    ],
],
````

**Comment by Shidersz** [comment]
@MathiasOliveira I can't reproduce your issue on my local environment. I think we need to gather more information, for example:

1. Can you try the [demo test page for layout topnav](https://adminlte.io/themes/v3/pages/layout/top-nav.html) and check if the problem exists there for the `dropdown` example? Note the demo pages uses the new **AdminLte v3.1.0** that will be introduced with the next package release, and perhaps may solve the problem.

2. Use the browser inspector tool and check the list of event listeners attached to the **anchor tag** (`<a>`) for your dropdown menu. Maybe there is a custom listener on your code for the `click` event. Check next image for an example of what I mean:

    ![Screenshot from 2021-05-12 13-55-45](https://user-images.githubusercontent.com/63609705/118014950-22df7400-b32a-11eb-9f82-e3b222bfc2f8.png)

**Comment by MathiasOliveira** [comment]
@Shidersz I checked and on that demo page the bug doesn't exist.

Also there is no custom click event on the dropdown item:
![image](https://user-images.githubusercontent.com/67007152/118017157-a69a6000-b32c-11eb-9060-8ecada70fd9b.png)

**Comment by Shidersz** [comment]
@MathiasOliveira Ok, let just wait to the new release that integrates **AdminLTE v3.1.0** and we check again later.

**Comment by Shidersz** [comment]
@MathiasOliveira Please, can you check if this issue persist on the new v3.6.0 release?

**Comment by MathiasOliveira** [comment]
@Shidersz Sorry, but I have been moved from one project to another and the project that used AdminLTE is now considered dead.

Sorry for taking your time.
