### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elfeffe** [JeroenNoten/Laravel-AdminLTE#9]
```
FatalErrorException in ServiceProvider.php line 100:
syntax error, unexpected '.'
```

Any idea about what am I doing wrong?

**Comment by JeroenNoten** [comment]
Right now, this package requires PHP 7, you're probably running PHP 5. However, I can refactor some code to make this support PHP 5 as well.

**Comment by elfeffe** [comment]
ok, I check with PHP7
Thank you

**Comment by elfeffe** [comment]
any idea if it works with https://github.com/jenssegers/laravel-mongodb ?

**Comment by JeroenNoten** [comment]
I guess it should work with that package, yes.

**Comment by JeroenNoten** [comment]
Hi! PHP 5.5 and higher is now supported.
