### ISSUE TITLE
[BUG] One route remains http in an https APP_URL environment

### ISSUE THREAD

**Issue by 831220** [jeroennoten/Laravel-AdminLTE#904]
The basic starting url of the site is https, however when:
0-https://myserver_url.com/admin
1-Goes to the login page, because I am not logged yet.
2-Fill the user/pass fields
3-Click on the login button*(_Note this on browser console!!!!_) ->one of the requests is asking for http:// !!??
*(**basically degenerated https://myserver_url.com/admin** to **http://myserver_url.com/admin**)
4-As the request is unsecure, my server rejects it.

I was expectig that all login routes requested for https as my APP_URL= https://myserver_url.com

### Environment

| Item    | Version
| ------- | -------
| Laravel | 8.x
| OS      | Ubuntu 20.04
Php 7.4
AdminLTE v3

**Comment by Shidersz** [comment]
We use `url()` laravel helper to make the urls. Check next link, it provides a way to force all urls with `https` schema:

https://dcblog.dev/laravel-force-https-with-url-helper

**Comment by 831220** [comment]
> We use `url()` laravel helper to make the urls. Check next link, it provides a way to force all urls with `https` schema:
> 
> https://dcblog.dev/laravel-force-https-with-url-helper

Did'nt worked, but thanks anyway.....
