### ISSUE TITLE
Change main-sidebar width

### ISSUE THREAD

**Issue by nihadatakishiyev** [jeroennoten/Laravel-AdminLTE#906]
Hi there. 

I would love to change the sidebar width in my project, but after looking through the documentation I could not find any clean way of doing that. It would be perfect if there was a config option to adjust the width of the left sidebar. 

I would highly appreciate any quick fix on the problem.

**Comment by Shidersz** [comment]
@nihadatakishiyev I'm not sure if that is possible. That is related to the underlying [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) project. Please, open a QUESTION in that project to check if that is possible.

@REJack any idea?

**Comment by nihadatakishiyev** [comment]
@Shidersz If I'm not mistaken, in the original AdminLTE project there should be _variables.scss file in which we can adjust the width variable. However, I couldn't find that file here

**Comment by Shidersz** [comment]
@nihadatakishiyev Those are pre-build files, we use the distributed files on this project (`min.css` and `min.js`). I have inspected the options available on the [documentation](https://adminlte.io/docs/3.1//index.html) but did not found any related to the sidebar width.

The `adminlte` project is downloaded on the `vendor/almasaeed2010/adminlte/` folder when you composer require this project. Then, the distributed files are installed into the `public/vendor/adminlte` folder when you execute `php artisan adminlte:install`. We do not mess with the pre-build files. If you find any way to customize this on the distributed files we will try to include it here.

**Comment by andcarpi** [comment]
You whould need a special class like "small_sidebar" or "big_sidebar" in the original adminlte project, so we could use it to customize it in this package.

Another option is to rebuild the adminlte with your changes and then overwrite the dist files in the public folder.
Note that you could lose those changes when updating this package.

**Comment by Shidersz** [comment]
Closed, we need support from `AdminLTE` package to provide a way to change the sidebar width without rebuilding the package. As @andcarpi mentioned, the only option now is to download the `AdminLTE` package, make changes on `build/scss/_variables.scss` and rebuild the package. Finally, you will need to copy the new generated dist files to the public folder `public/vendor/adminlte/dist` of your Laravel project.
