### ISSUE TITLE
[QUESTION] Passing a $config into an x-component for select2

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#909]
I'm trying to pass my `$config` for my select2 into the x-component following the [guidelines here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Forms-Components#select2). However, I noticed that if I add a `placeholder` to the config:

    $config = [
        "data" => $data,
        "placeholder" => "Select a type...",
    ];

The placeholder doesn't show, and it is automatically selecting the first option in my list.. I've tried removing it from the `$config`, and using `data-placeholder`, but when I did that, it still didn't show my placeholder. But if I remove the `:config="$config"` and leave the `data-placeholder`, I see my placeholder.

Here's my actual blade:
```php
@php
    $data = [];

    /** @var array $types */
    foreach($types as $key => $value)
    {
        $data[] = (object)[ 'id' => $key, 'text' => $value];
    }

    $config = [
        "data" => $data,
        "placeholder" => "Select a type...",
    ];
@endphp

<x-adminlte-select2 name="typeSelect" :config="$config" fgroup-class="typeSelect">
    <x-slot name="prependSlot">
        <div class="input-group-text text-maroon">
            <i class="fas fa-laptop"></i>
        </div>
    </x-slot>
</x-adminlte-select2>
```

Here's the JS that it outputs:
```js
    $(() => {
        $('#typeSelect').select2( {"data":[{"id":1,"text":"Handheld"},{"id":2,"text":"Console"},{"id":3,"text":"PC"},{"id":4,"text":"Handheld\/Console"}],"placeholder":"Select a type...","theme":"bootstrap4"} );
    })
```
Is this an issue with the `select2` plugin, or am I doing something silly again?

**Comment by Shidersz** [comment]
Hi @PiousVenom I will check this later, but I think that you need a first empty option on the data for the placeholder to show, as on the example provided:

```blade
{{-- With prepend slot, label and data-placeholder config --}}
<x-adminlte-select2 name="sel2Vehicle" label="Vehicle" label-class="text-lightblue"
    igroup-size="lg" data-placeholder="Select an option...">
    <x-slot name="prependSlot">
        <div class="input-group-text bg-gradient-info">
            <i class="fas fa-car-side"></i>
        </div>
    </x-slot>
    <option/>                                <=== NOTE THIS!
    <option>Vehicle 1</option>
    <option>Vehicle 2</option>
</x-adminlte-select2>
```

On the plugin [example](https://select2.org/placeholders#single-select-placeholders) they provide, they use an empty option. However I'm not sure hot to add empty option from `data` source. Maybe [this example](https://select2.org/placeholders#default-selection-placeholders) can help you.

**Comment by PiousVenom** [comment]
The empty option did it for me. I didn't even notice that. Thank you.
