### ISSUE TITLE
[QUESTION] Passing data to x-adminlte-select2 based on another x-adminlte-select2 selection

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#911]
### Question
I've got 2 `x-adminlte-select2` on my page: Game and Platform. What I'm looking for is, I want to populate Platform options based upon selection of Game. Is this possible? I have the Platform data in an array already, just waiting for the Game ID to display it.

### Environment

 Item    | Version
| ------- | -------
| Laravel | 8.42.1
| AdminLTE| 3.6
| OS      |  Windows 10

**Comment by Shidersz** [comment]
@PiousVenom There is no built-in for this on the package. But, generally, for these type of dynamism you use `Javascript/jQuery`. The idea may be:
- Listen for `change` event on the **game** selection and register a `callback`.
- When `callback` invoked, use the **game** selection id/value to repopulate the **platform** selection inner `HTML` with a new set of options. In case you do not have data available for the **platform** selection on the client side, you can trigger an AJAX request to the server to get the new set of options.

**Comment by PiousVenom** [comment]
> @PiousVenom There is no built-in for this on the package. But, generally, for these type of dynamism you use `Javascript/jQuery`. The idea may be:
> 
> * Listen for `change` event on the **game** selection and register a `callback`.
> * When `callback` invoked, use the **game** selection id/value to repopulate the **platform** selection inner `HTML` with a new set of options. In case you do not have data available for the **platform** selection on the client side, you can trigger an AJAX request to the server to get the new set of options.

Thanks. I'd had a feeling that may be the case. No worries, though. Thank you.
