### ISSUE TITLE
[QUESTION] How to add new colors? 

### ISSUE THREAD

**Issue by GJakobi** [jeroennoten/Laravel-AdminLTE#915]
Sorry for the question, but I'm having quite of a problem trying to add new colors. I've already tried to compile in the app/css file, but it did not work. How do I compile directly to the adminlte css file?

**Comment by Shidersz** [comment]
@GJakobi Not sure If I understand what you want to do. However, you can add your custom `css` files pushing to the `css` tag. Assuming you have created a file on `public/css/my-custom-file.css` with a new set of color definitions, you can do:

```blade
@extends('adminlte::page')
...
...
...
@push('css')
    <link rel="stylesheet" href="{{ asset('css/my-custom-file.css') }}">
@endpush
```

Other alternative is to add the file as a [plugin](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration) on the config file.

On the other hand, we do not support any build and/or compilation process for the **AdminLTE** template. We just use the distributed files (`min.css` and `min.js`) that are published on the `public/vendor/adminlte/dist/` folder. If you need more details, give a review to the `vendor/jeroennoten/laravel-adminlte/resources/views/master.blade.php` to see how we use the **AdminLTE** template.

**Comment by GJakobi** [comment]
Thank you very much, when I added the file as a plugin it worked.
