### ISSUE TITLE
'usermenu_enabled' Not Working In Other Views Laravel. How do I configure it? 

### ISSUE THREAD

**Issue by saadabdurrazaq** [jeroennoten/Laravel-AdminLTE#916]
I am trying many times to display user menu in other views, but not working. It only can be displayed in Dashboard and Home. How do I configure it?

**Comment by Shidersz** [comment]
Please, add a minimal example of code of a view where the use rmenu isn't working after you have enabled it on the configuration file. Also, add a screenshot showing the issue, and routes definitions you are using to access the view. Hard to help without details...

**Comment by Shidersz** [comment]
This will be closed, no feedback from author...
