### ISSUE TITLE
[QUESTION] AdminLTE 3.1 IFrame supported?

### ISSUE THREAD

**Issue by warquia** [jeroennoten/Laravel-AdminLTE#917]
How to use the iFrame from the new version 3.1?, when I follow these steps (https://adminlte.io/docs/3.1//javascript/iframe.html) the page is totally misconfigured.

Is there support for this?

Thx

**Comment by Shidersz** [comment]
Hi @warquia there is no underlying support for that feature currently. You can try [publishing](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) the views from this package and edit the `resources/views/vendor/adminlte/page.blade.php` file to customize the `content-wrapper` as explained on the documentation. If you get it work, please share your work, so we can enhance the package on the future. Maybe a new `layout_iframe` configuration option will be required for this...

**Comment by warquia** [comment]
Hello @Shidersz , I realized that internally there is no treatment about it, I will try to make it work and I will report in more detail.
Thx...
