### ISSUE TITLE
[QUESTION] Is there any way to reduce adminlte.min.css size?

### ISSUE THREAD

**Issue by 831220** [jeroennoten/Laravel-AdminLTE#920]
Is there any way to downsize o speed up css loading of the adminLTE ??  If I use adminlte.min.css is almost 2 minutes loading in my 4G network. And if I use laravel mix then is app.css the one that takes minutes to load. What am I doing wrong_?

**Comment by Shidersz** [comment]
Hi @831220 , I think the mainteiners of the **AdminLTE** package are working to reduce the `adminlte.min.css` on the next release. Check next link:

https://github.com/ColorlibHQ/AdminLTE/issues/3530

Unfortutately, we can't do nothing from this project without underlying support. Based on that link, on the future maybe we can define a new option on the config file to use  the `slim` file without the dark mode style.

**Comment by 831220** [comment]
@Shidersz Thanks, Now I guess a solution can be to copy+paste in a shorter file only the css clasess that I am actually using.
Will that be a titanic task, considering adminlte size?

**Comment by Shidersz** [comment]
@831220 Considering that this package uses the `AdminLTE` template classes to create the main layout, and other elements, I will be hard to check what classes do you really need and the work may take long time. I believe you should open a ticket on the [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) project and ask if there exists a way to build the distributed files without certain features (like dark mode) from the current `master` branch.

If you can accomplish that, then you can replace the files under `public/vendor/adminlte/dist/` laravel folder by the new ones. Or create a new `public/vendor/adminlte-custom/` and put the new files there, then edit `resources/views/vendor/adminlte/master.blade.php` file of this project to include the new files.

**Comment by 831220** [comment]
Understood! @Shidersz Thanks a lot!
I guess enabling gzip compression on my nginx will also help
