### ISSUE TITLE
[QUESTION] What is the best method to place custom global methods?

### ISSUE THREAD

**Issue by Restingo** [jeroennoten/Laravel-AdminLTE#925]
I want to place some logic that reads `session()->get('success')` and shows a sweetalert2 toast if there is something set. Should I publish the views, can I only publish one and if yes, which one should I choose to insert that code? Thank you.

**Comment by Shidersz** [comment]
I won't publish any view, just create your own base layout that will be an extension of [the one provided by this package](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Usage), for example:

```blade
{{-- resource/views/layout.blade.php --}}

@extends('adminlte::page')

{{-- You may add other layout customizations here... --}}

@if(! empty(session()->get('success')))
    {{-- Your code to trigger the sweetalert2 toast... --}}
@endif
```

Then, you may use the previous layout to define all the blade view of your application:

```blade
{{-- resource/views/test.blade.php --}}

@extends('layout')

{{-- Page Content Header --}}
@section('content_header')
    <h1>TEST</h1>
@stop

...
...
...
```

**Comment by Restingo** [comment]
@Shidersz thank you man, it works like a charm!
