### ISSUE TITLE
[QUESTION] setting logout item in left sidebar

### ISSUE THREAD

**Issue by neoacevedo** [jeroennoten/Laravel-AdminLTE#926]
I'm following this post: https://github.com/jeroennoten/Laravel-AdminLTE/issues/830 but I don't get how to set the logout button (with the logout form) in the left sidebar (from the adminlte.php config file).

I'm using only the left sidebar because I don't need a lot of links. I have only 4 few links which includes the profile link (easy) and the logout, which I need as the menu-item-logout-link blade, but I don't have a clue how to achieve it.

I don't need also, to override any layout. The design for the logic is simple.

**Comment by Shidersz** [comment]
Hi @neoacevedo This package do not provide a built-in support for logout link on the **left sidebar**. We provide logout functionality only on the **top navbar** using a button or an user menu, if you properly setup the configuration file and the underlying Laravel authentication scaffolding.

However, you can [publish the package views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and make some customizations on the file `resources/views/vendor/adminlte/partials/sidebar/left-sidebar.blade.php` to include the form mentioned on the issue you have linked, for example:

```blade
{{-- resources/views/vendor/adminlte/partials/sidebar/left-sidebar.blade.php --}}

<aside class="main-sidebar {{ config('adminlte.classes_sidebar', 'sidebar-dark-primary elevation-4') }}">

    {{-- Sidebar brand logo --}}
    @if(config('adminlte.logo_img_xl'))
        @include('adminlte::partials.common.brand-logo-xl')
    @else
        @include('adminlte::partials.common.brand-logo-xs')
    @endif

    {{-- Sidebar menu --}}
    <div class="sidebar">
        <nav class="pt-2">
            <ul class="nav nav-pills nav-sidebar flex-column {{ config('adminlte.classes_sidebar_nav', '') }}"
                data-widget="treeview" role="menu"
                @if(config('adminlte.sidebar_nav_animation_speed') != 300)
                    data-animation-speed="{{ config('adminlte.sidebar_nav_animation_speed') }}"
                @endif
                @if(!config('adminlte.sidebar_nav_accordion'))
                    data-accordion="false"
                @endif>
                {{-- Configured sidebar links --}}
                @each('adminlte::partials.sidebar.menu-item', $adminlte->menu('sidebar'), 'item')

                {{-- Custom logout link --}}
                <form method="POST" action="{{ route('<logout-route-name>') }}">
                    @csrf

                    <a href="#" onclick="event.preventDefault(); this.closest('form').submit();">
                        {{ __('adminlte::adminlte.log_out') }}
                    </a>
                </form>
            </ul>
        </nav>
    </div>

</aside>
```

I have not tested it, but the idea to follow may be this one.

**Comment by neoacevedo** [comment]
Good, based in your suggestion, I achieved it with the following steps:

I ran `php artisan adminlte:install --only=main_views`

After it, I edited the _navbar.blade_ and _navbar-layout-topnav.blade_ files under _resources/views/vendor/adminlte/partials/navbar_, commenting  the lines related about **Auth::user()** located in the navbar right links.

And at last, I edited the file _sidebar/left-sidebar.blade_ adding just below sidebar links the user menu link:
```php
{{-- User menu link --}}
@if(Auth::user())
    @if(config('adminlte.usermenu_enabled'))
        @include('adminlte::partials.navbar.menu-item-dropdown-user-menu')
    @else
        @include('adminlte::partials.navbar.menu-item-logout-link')
    @endif
@endif
```

**Comment by Shidersz** [comment]
Ok, but note those blade layouts use specific AdminLTE syntax for the `navbar` section, you may need to tune those files so they look nicely on the sidebar...

Also, take into consideration that on a package update procedure you will need to re-apply these changes again. It will be a nice idea to create a backup of your custom files when you get into a stable point.
