### ISSUE TITLE
[QUESTION] Using AdminLTE Widgets

### ISSUE THREAD

**Issue by neoacevedo** [jeroennoten/Laravel-AdminLTE#927]
About adminlte widgets, how do I must use it?

Following the Wiki https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Widget-Components#info-box and implementing this info-box example: `<x-adminlte-info-box title="528" text="User Registrations" icon="fas fa-lg fa-user-plus text-primary"
    theme="gradient-primary" icon-theme="white"/>`, in the rendered view, the widget isn't rendered but else is passed as I put in the blade file.

**Comment by Shidersz** [comment]
@neoacevedo what version of Laravel and this package are you using?

**Comment by neoacevedo** [comment]
I'm using L6 and the package version is 3.6.1

**Comment by Shidersz** [comment]
@neoacevedo Well, that is a problem, because blade-x components are only supported with **Laravel >= 7.x**. So, you can use the components we provide on your framework. Read the first note on the [components documentation](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Components-Categories).
