### ISSUE TITLE
[QUESTION] Component customization

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#932]
I've been adding some extra customization to various components (i.e., SmallBox, making the icon itself as a link, or overwriting the style on the text). Just curious if there'd be any interest in adding this customization in by default? I'd be willing to do a PR if there's agreement to it.

**Comment by Shidersz** [comment]
@PiousVenom Contributions are welcome. If you have time, create a PR for each component you have enhanced, so we can review these changes in details. Also take in mind we look for general purposes options and/or customizations instead of very particular ones.
