### ISSUE TITLE
laravel-adminlte/src/ServiceProvider.php

### ISSUE THREAD

**Issue by geniusforapp** [jeroennoten/Laravel-AdminLTE#94]
app-root/runtime/repo/vendor/composer/../jeroennoten/laravel-adminlte/src/ServiceProvider.php): failed to open stream: No such file or directory

**Comment by geniusforapp** [comment]
@jeroennoten please help me i add this ready project and now i am stuck with it it dose not work 👍

**Comment by jeroennoten** [comment]
Please explain in detail what you tried and what did not work as expected.

**Comment by geniusforapp** [comment]
i add the library and with the same steps and the ia cannot run the project coz it gives me that services provider of adminlte notfounded :\
