### ISSUE TITLE
Blade component should also contains basic table along with dataTable

### ISSUE THREAD

**Issue by Sitesh1064** [jeroennoten/Laravel-AdminLTE#942]
Blade component should also contains basic table along with dataTable

**Comment by Shidersz** [comment]
You mean, a new component that represents a basic HTML table?

**Comment by Sitesh1064** [comment]
yes

**Comment by Shidersz** [comment]
Won't solve. The `Datatables` plugins already provides a lot of features. For the moment, if you dislike it, there is always the possibility you create your own component with a basic HTML table, or use any other tool available...
