### ISSUE TITLE
[QUESTION] How to integrate real time notification into this package ?

### ISSUE THREAD

**Issue by marwandhiaurrahman** [jeroennoten/Laravel-AdminLTE#943]
How to integrate real time notification to this package ? It can or not ?

**Comment by Shidersz** [comment]
Please, explain with more details what you want to do...

The package currently provides a [Navbar Notification Widget](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Special-Menu-Items#navbar-notification) that you can use/implement to provide some sort of notifications.

**Comment by marwandhiaurrahman** [comment]
Wow, that's great and very helpful.
but as for the Navbar Notification Widget it seems I still have to learn. hehe
