### ISSUE TITLE
[FEATURE] Publishing the Components classes for better customization

### ISSUE THREAD

**Issue by PiousVenom** [jeroennoten/Laravel-AdminLTE#944]
### Describe the solution you'd like
When publishing main views, I'd like `src/Components/` to be published as well. The reasoning for this is so that when using the component, I can create my own variables to be passed in to the `x-component` without having to modify the file in the `vendor` folder, and risking it being overwritten. Having the ability to fully customize the components by creating new variables to pass in will allow for a better per instance customization. 

Example:
I've got a customization on `small-box` to be able to turn the icon into a link. If I did this on the component that's published, every time I used `small-box`, the icon is a link. But I may not want that. Nor would I want that link to point to the same location every time. Modifying the `src/Components/Widget/SmallBox.php` to have a link variable was the only way to make this happen.

**Comment by Shidersz** [comment]
Yea, actually we need to create a new **asset** called components to manage publishing of components, and views related to components should not be published when installing main views. I'm without time currently, and there are other things with priority, but I will get into this on the future...
