### ISSUE TITLE
[BUG] Content height bugs when page loads

### ISSUE THREAD

**Issue by arthurmgb** [jeroennoten/Laravel-AdminLTE#945]
I installed AdminLTE on Laravel and I always come across this bug. What happens is that when I load the page for some reason the content height is calculated wrongly and this white "div" in the footer appears for a few seconds, I tried many solutions on the internet and none of them solved my problem 100%. I also tried modifying the .wrapper, .content-wrapper classes, but without success. How do I solve this problem?

![adminlte](https://user-images.githubusercontent.com/62814691/124405437-07368f80-dd15-11eb-8677-364442713ada.png)

**Comment by Shidersz** [comment]
I just tested this issue and I have confirmed it is a bug from the underlying [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) package when you do not use a **footer**. Please, open an issue there...

The only alternative you have now is to define a footer on your pages:

```blade
...
...
...
@section('footer')
    {{-- Add your footer content here --}}
@stop
```

**Comment by arthurmgb** [comment]
Thanks, I just opened an issue in the package repository.

**Comment by Shidersz** [comment]
Related AdminLTE issue is: https://github.com/ColorlibHQ/AdminLTE/issues/3822

Problem is already solved and may be fixed in next AdminLTE release...
