### ISSUE TITLE
Translate InputDate component

### ISSUE THREAD

**Issue by IvanIndia** [jeroennoten/Laravel-AdminLTE#947]
Hello,

I am trying to change the language of the InputDate component, but I am not able to display it in a language other than English.

![image](https://user-images.githubusercontent.com/46484767/125515836-e70858ec-818d-4f07-a7a0-56aae63a79c4.png)

How can I do it?

Thanks.

Regards.

**Comment by Shidersz** [comment]
Maybe you can use the [locale option](https://getdatepicker.com/5-4/Options/#locale) of the underlying plugin. Give an advice if you get it work...

**Comment by IvanIndia** [comment]
I have managed to configure it by importing the moment-with-locales file into the adminlte.php and configuring it later in the view.

![image](https://user-images.githubusercontent.com/46484767/126030857-87eff689-844f-41c0-8016-eba50b5218ab.png)

![image](https://user-images.githubusercontent.com/46484767/126030870-6d77ac1e-a3de-44ef-a82c-515b7cd15e6d.png)

Hope it helps someone.

Regards.

**Comment by Shidersz** [comment]
@IvanIndia Nice, thanks for share it!
