### ISSUE TITLE
[FEATURE] Legacy User Menu

### ISSUE THREAD

**Issue by LindolfoJunior** [jeroennoten/Laravel-AdminLTE#951]
Senhores, 

no Admin LTE contem uma opção para ativar o menu de usuário legado, porém, não encontrei como ativar esta funcionalidade nesta versão para o laravel.

Segue o link: [https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html](https://adminlte.io/themes/dev/AdminLTE/pages/examples/legacy-user-menu.html)

Poderiam incluir esta opção para não haver que editar diretamente nas views?

**Comment by Shidersz** [comment]
Legacy User Menu is already included whit this package, see:

https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#user-menu

However, it will only be displayed if user is authenticated. So you may need to include some authentication scaffolding from Laravel, this package work nicely with the `laravel/ui` one. See:

- https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Installation (STEP 3)
- https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Authentication-Views

Please, next time use English to ask questions...

**Comment by LindolfoJunior** [comment]
Hi @Shidersz!

Thanks for the instruction. I am currently using laravel/sanctum but I will study how to use this feature with sanctum.

Thanks again.

Ps: Sorry for using Portuguese.
