### ISSUE TITLE
[BUG] Can't use html entities in input label

### ISSUE THREAD

**Issue by adwiv** [jeroennoten/Laravel-AdminLTE#952]
### Describe the bug
The value of label argument in input group is encoded while it is output. This creates a situation where we can't use html entities as they too are encoded in the output.

```html
@php($val = "a < b")
<x-adminlte-input name="rank" label="&nbsp;"/>
<x-adminlte-input name="max" label="{{$val}}"/>
```

should generate
```html
<label for="rank">&nbsp;</label>
<label for="max">a &lt; b</label>
```

but generates 
```html
<label for="rank">&amp;nbsp;</label>
<label for="rank">a &amp;lt; b</label>
```

### Similar bugs
The same problem of double encoding occurs in title of Alert and Card and maybe a few other components as well. Eg.
```html
<x-adminlte-card title="Hello&nbsp;World"/>
```
In my opinion, it is safe to assume that the value of any attribute is already encoded, so should be output unescaped using `{!! !!}` instead of `{{ }}`

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | v8.49.2
| Project | v3.6.1
| OS      | 10.15.7

**Comment by Shidersz** [comment]
Hi @adwiv , to get

```blade
<label for="rank">&nbsp;</label>
<label for="max">a &lt; b</label>
```

you can try with next ones:

```blade
@php($val1 = "&nbsp;")
@php($val2 = "a &lt; b")
<x-adminlte-input name="rank" :label="$val1"/>
<x-adminlte-input name="max" :label="$val2"/>
```

I will check this in the future. Currently I can't find any official documentation about `{!! !!}` usage on the components, and I want to be sure it does not introduce any security issue.

**Comment by Shidersz** [comment]
@adwiv Have you tested the previous code. Can we close this one or we still need a fix?

**Comment by adwiv** [comment]
@Shidersz The suggested code doesn't seem to solve the issue. The labels are still encoded. Have you tested it?

**Comment by adwiv** [comment]
My use case is very simple (and maybe common).

```html
<form class="d-flex">
  <x-adminlte-input name="name" label="Name"/>
  <x-adminlte-input name="email" label="Email"/>
  <x-adminlte-input name="action" type="submit" label="&nbsp;"/>
</form>
```

The `&nbsp;` in label is important to align the submit button property. 

I can understand how its difficult to fix given that the label value may either be passed as a variable or specified in the view file and to be on the safe side we should always reencode.

If you have any solution for above, it would be great. Else we can close the issue as 'wontfix'.

**Comment by Shidersz** [comment]
@adwiv I haven't understand your goal, since you write:

> should generate

> ```<label for="rank">&nbsp;</label>```
> ```<label for="max">a &lt; b</label>```

I believed you wanted the text that represents the html entity as output, not the rendered html entity.

We can leave this open, in case we found an elegant solution on the future. Currently, you may try using the component attributes (`fgroup-class`, `igroup-class`) to add extra classes for align the elements...
