### ISSUE TITLE
QUESTION: How to change direction of adminlte from ltr ro rtl ?

### ISSUE THREAD

**Issue by m7mda3yad** [jeroennoten/Laravel-AdminLTE#956]

**Comment by m7mda3yad** [comment]
QUESTION: How to change direction of adminlte from ltr ro rtl

**Comment by Shidersz** [comment]
@m7mda3yad That is not possible right now. The underlying [AdminLTE](https://github.com/ColorlibHQ/AdminLTE) package will introduce this feature on `v4.0.0` (currently under development). So we need to wait for that release, before adding support...
