### ISSUE TITLE
[BUG] - Navbar Darkmode Widget Not Working

### ISSUE THREAD

**Issue by thalesbarbosab** [jeroennoten/Laravel-AdminLTE#960]
### Describe the bug
I follow the doc on section Special Menu Items / Navbar Darkmode Widget and put the darkmode-widget into my navbar items, but not work. The widget is not display. Im using the correct version for this release.

Follow my config/adminlte.php file configuration.
See into this file on line 239.

### AdminLTE config file
[config-adminlte.txt](https://github.com/jeroennoten/Laravel-AdminLTE/files/6951933/config-adminlte.txt)

### Composer Files
[composer.json.txt](https://github.com/jeroennoten/Laravel-AdminLTE/files/6951946/composer.json.txt)
[composer.lock.txt](https://github.com/jeroennoten/Laravel-AdminLTE/files/6951941/composer.lock.txt)

### Expected behavior
Must be display the widget darkmode icon

### Screenshots
![darkmode icon not display](https://user-images.githubusercontent.com/58126736/128655892-59925e93-a54f-4a94-a308-80359ab219d9.png)

| Item    | Version
| ------- | -------
| Laravel | v8.53.1
| Php      | v7.4
| Project | v3.6.1
| OS       | Homestead - Ubuntu 18.04.4 LTS

**Comment by resslinger** [comment]
The darkmode is not included in v3.6.1. This feature will be available in the next release.

**Comment by thalesbarbosab** [comment]
So you need to adjust the documentation, as it says you already have this function in version 3.6.1.

"Important: This item is only available for package versions > v3.6.1 and Laravel >= 7.x (because the item is implemented with an underlying blade component)."
