### ISSUE TITLE
[Question] How can I use paging, pagination in datatable?

### ISSUE THREAD

**Issue by tuyendev** [jeroennoten/Laravel-AdminLTE#961]
Hi, I'm new here and starting learning your project.
When I start working with the data table, to let the table can do paging or pagination. I need to fetch all data from database, and it's definitely not a good way. I tried to find documents to custom this but I got nothing.
Could you tell me what can I do to make it work? Or I need to customize by myself

**Comment by Shidersz** [comment]
I think you need to use the **server side** feature of the Datatables plugin if you don't want to fetch all data at once. The next closed issue may help as a starting point for you #931
