### ISSUE TITLE
InvalidArgumentException Unable to locate a class or view for component [adminlte-navbar-darkmode-widget]. (View: /home/scervantesc/erp/resources/views/vendor/adminlte/partials/navbar/menu-item.blade.php) http://localhost:8000/ventas

### ISSUE THREAD

**Issue by scervantesc** [jeroennoten/Laravel-AdminLTE#963]

**Comment by Shidersz** [comment]
@scervantesc How do you get into that error? There is no release available with the **dark mode widget**, it is only available on the current **dev-master** branch. It appears that the `vendor/jeroennoten/Laravel-AdminLTE/resources/views/components/layout/navbar-darkmode-widget.blade.php` can't be found on your environment...

**Comment by scervantesc** [comment]
Do you speak Spanish?

**Comment by resslinger** [comment]
Support only in english.

**Comment by Shidersz** [comment]
> 
> 
> Do you speak Spanish?

You can always use a translation tool, like google translate...

**Comment by scervantesc** [comment]
Not the best option, not that accurate

**Comment by scervantesc** [comment]
I have doubts on how to solve this error, I am a newbie in laravel

**Comment by Shidersz** [comment]
As I say previously, first, you are not using an official package release (darkmode widget was not released, it is only present on the current master development branch). Second, the error says a component can't be found on your Laravel application. So check the next file is available on your framework:

```sh
vendor/jeroennoten/laravel-adminlte/resources/views/components/layout/navbar-darkmode-widget.blade.php
```

Also, share the content of `/home/scervantesc/erp/resources/views/vendor/adminlte/partials/navbar/menu-item.blade.php` so we can see if match with the version of the master branch.

**Comment by scervantesc** [comment]
So it recommends me not to use this version.? 

the file if it exists in vendor/jeroennoten/laravel-adminlte/resources/views/components/layout/navbar-darkmode-widget.blade.php 

**content of /home/scervantesc/erp/resources/views/vendor/adminlte/partials/navbar/menu-item.blade.php**

```
@inject('navbarItemHelper', 'JeroenNoten\LaravelAdminLte\Helpers\NavbarItemHelper')

@if ($navbarItemHelper->isSearch($item))

    {{-- Search form --}}
    @include('adminlte::partials.navbar.menu-item-search-form')

@elseif ($navbarItemHelper->isNotification($item))

    {{-- Notification link --}}
    <x-adminlte-navbar-notification
        :id="$item['id']"
        :href="$item['href']"
        :icon="$item['icon']"
        :icon-color="$item['icon_color'] ?? null"
        :badge-label="$item['label'] ?? null"
        :badge-color="$item['label_color'] ?? null"
        :update-cfg="$item['update_cfg'] ?? null"
        :enable-dropdown-mode="$item['dropdown_mode'] ?? null"
        :dropdown-footer-label="$item['dropdown_flabel'] ?? null"
    />

@elseif ($navbarItemHelper->isFullscreen($item))

    {{-- Fullscreen toggle widget --}}
    @include('adminlte::partials.navbar.menu-item-fullscreen-widget')

@elseif ($navbarItemHelper->isDarkmode($item))

    {{-- Darkmode toggle widget --}}
    <x-adminlte-navbar-darkmode-widget
        :icon-enabled="$item['icon_enabled'] ?? null"
        :color-enabled="$item['color_enabled'] ?? null"
        :icon-disabled="$item['icon_disabled'] ?? null"
        :color-disabled="$item['color_disabled'] ?? null"
    />

@elseif ($navbarItemHelper->isSubmenu($item))

    {{-- Dropdown menu --}}
    @include('adminlte::partials.navbar.menu-item-dropdown-menu')

@elseif ($navbarItemHelper->isLink($item))

    {{-- Link --}}
    @include('adminlte::partials.navbar.menu-item-link')

@endif
```

**Comment by Shidersz** [comment]
> So it recommends me not to use this version.?

Use at your own risk, it is a branch that is on constant development (I won't recommend it for production environment). You can use it to review/test new incoming features, like darkmode widget, for example.

Your files seems fine. I have started a fresh Laravel installation with this project and I do not see that error. Maybe you broken something in your Laravel framework.

What Laravel version are you using? You may also try downloading source code of the master branch and compare it with you `vendor/jeroennoten/laravel-adminlte` to see if you have any broken change.

**Comment by Shidersz** [comment]
Closed, because no feedback...
