### ISSUE TITLE
IFrame mode not working

### ISSUE THREAD

**Issue by Nafay-niazi** [jeroennoten/Laravel-AdminLTE#966]
@extends('adminlte::page', ['iFrameEnabled' => true])

this isn't working on my project why???

**Comment by Shidersz** [comment]
@Nafay-niazi Please, first invest some time and make some effort on your own. This feature was upload yesterday on the master development branch (no official release with this feature). So be sure you are using the master branch on your project. Second, you should follow the [Update Procedure](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Updating) ALWAYS! This feature includes new views and modification on some other views. So, in case you have published your views, you will need to manually update those (as indicated on the update procedure).

**Comment by Nafay-niazi** [comment]
hey brother thank you so much for your quick reply, I really appreciate it!!
