### ISSUE TITLE
Datatables language

### ISSUE THREAD

**Issue by dsiksik** [jeroennoten/Laravel-AdminLTE#967]
How can I use translation (in french) in the Datables component ?

**Comment by Shidersz** [comment]
Use the `config` attribute of the component to configure the underlying **Datatables plugin**.

For examples on how to use `config` attribute check next link: https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Tool-Components#datatables

For the language configuration of Datatables check the plugin documentation:

- https://datatables.net/reference/option/language
- https://datatables.net/plug-ins/i18n/

**Comment by dsiksik** [comment]
Thanks :)

**Comment by Megamil** [comment]
I managed to add it like this in $config:

$config = ['language' => [ 'url' => '/json/datatable-pt-BR.json' ]];
