### ISSUE TITLE
[BUG] gerring error while running project  

### ISSUE THREAD

**Issue by arindammondal1** [jeroennoten/Laravel-AdminLTE#968]
getting error while trying to login in the project using user name and password.

Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Menus\MenuFilter::transform($item, JeroenNoten\LaravelAdminLte\Menu\Builder $builder) must be compatible with JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface::transform($item)

### Expected behavior
home page should be open

<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 24px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment</h3><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Complete the next environment information.</p>

Item | Version
-- | --
Laravel | 8
OS | Windows 10

</body>
</html>

**Comment by arindammondal1** [comment]
Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Menus\MenuFilter::transform($item, JeroenNoten\LaravelAdminLte\Menu\Builder $builder) must be compatible with JeroenNoten\LaravelAdminLte\Menu\Filters\FilterInterface::transform($item)

**Comment by Shidersz** [comment]
It appears that your custom **MenuFilter** filter is not compatible with the new **FilterInterface**. Probably, because you have updated the package from a very old version. Read [Custom Menu Filters Examples](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) to check how you must defined your filters and adequate your code.
