### ISSUE TITLE
[BUG] require is not defined

### ISSUE THREAD

**Issue by leonidaswilliams** [jeroennoten/Laravel-AdminLTE#971]
Hi

I have followed the steps described in the Installation wiki page, but when I try to log in, the user authentication is OK but when it is redirected to the /home page I have an error telling: "Uncaught ReferenceError: require is not defined" about a line in the app.js that says: require('./bootstrap')

I have tried to make npm install but no success

Laravel: 8.56

Could you help me please?

Thanks in advance

**Comment by Shidersz** [comment]
Closed, no more feedback from the author...
