### ISSUE TITLE
Error message Not showing in componet

### ISSUE THREAD

**Issue by tmgomas** [jeroennoten/Laravel-AdminLTE#972]
I implement Input component and i try to validate the value. validation working fine but not showing error messages ..

```
<x-adminlte-input name="stu_sur_name" id="stu_sur_name" label="Sur Name"  igroup-size="sm" placeholder="Dimul Gomisge">
    <x-slot name="prependSlot">
      <div class="input-group-text">
        <i class="fas fa-user text-lightblue"></i>
      </div>
</x-slot>
</x-adminlte-input>   
```

Can any one help this

**Comment by tmgomas** [comment]
its Working with Normal Blade .. I am using Livewire Validation ... Its not working with liveiwre

**Comment by tmgomas** [comment]
Its not working with the Components

**Comment by Shidersz** [comment]
@tmgomas you need to see the error message on the **Laravel error's bag**. I have explained previosuly how you can trace it. So, please share what you see on the trace for the Laravel  error's bag.

**Comment by tmgomas** [comment]
@Shidersz  

Yes no issue with Error Bag and its not working with error Key .. i try this method and its working 

```
<x-adminlte-input name="company_name" class="{{ $errors->has('company_name') ? 'is-invalid' : '' }}" wire:model.defer="company_name" label="Company Name ( School Name )" placeholder="placeholder" fgroup-class="col-md-12 col-lg-12"/>
               
<x-adminlte-input name="company_s_name" error-key="company_s_name" wire:model.defer="company_s_name" label="Short Name ( KPS )" placeholder="placeholder" fgroup-class="col-md-12 col-lg-6"/>

``` 

Error Key is not working

**Comment by Shidersz** [comment]
Ok, please, share what you see on the error's bag after submitting an invalid value for both inputs. I need to see your error's bag format in order to track any issue. Take into account that these components where not intended to work with **Livewire** and there may be some sort of conflict with it...

**Comment by Shidersz** [comment]
@tmgomas have you found a solution for this? Share the indicated trace otherwise...

**Comment by Shidersz** [comment]
Closed, no feedback!

**Comment by yungifez** [comment]
Check if your config is using livewire first of all

**Comment by tmgomas** [comment]
any one got any answer ?

**Comment by Shidersz** [comment]
Hi @tmgomas from what I can guess, it appears that **Livewire** do not flash errors into the session. Please, try the next fix temporarily.

Open the file `vendor/jeroennoten/laravel-adminlte/resources/views/components/form/input-group-component.blade.php` and edit next lines:

```blade
{{-- Error feedback --}}
@if($isInvalid() && ! isset($disableFeedback))
    <span class="invalid-feedback d-block" role="alert">
        <strong>{{ $errors->first($errorKey) }}</strong>
    </span>
@endif
```

by replacing by next ones:

```blade
@if($errors->has($errorKey) && ! isset($disableFeedback))
    <span class="invalid-feedback d-block" role="alert">
        <strong>{{ $errors->first($errorKey) }}</strong>
    </span>
@endif
```

If this solution works, please tell us and we going to make a fix soon...

**Comment by tmgomas** [comment]
> Hi @tmgomas from what I can guess, it appears that **Livewire** do not flash errors into the session when your validation fails, since **Livewire** do not make a full page reload on these cases. See next links for more info:
> 
> * https://stackoverflow.com/questions/63986147/how-in-laravel-livewire-set-flash-message-with-validation-erros
> * [Validation errors are not flashed to session livewire/livewire#621](https://github.com/livewire/livewire/issues/621)
> 
> This conflicts with our current code since we put the error display logic inside the component class, and it appears that validation errors are only available on the blade files for **Livewire**. Please, understand this package wasn't focused on supporting **Livewire**. For the moment, try the next fix temporarily:
> 
> Open the file `vendor/jeroennoten/laravel-adminlte/resources/views/components/form/input-group-component.blade.php` and edit next lines:
> 
> ```
> {{-- Error feedback --}}
> @if($isInvalid() && ! isset($disableFeedback))
>     <span class="invalid-feedback d-block" role="alert">
>         <strong>{{ $errors->first($errorKey) }}</strong>
>     </span>
> @endif
> ```
> 
> by replacing by next ones:
> 
> ```
> @if($errors->has($errorKey) && ! isset($disableFeedback))
>     <span class="invalid-feedback d-block" role="alert">
>         <strong>{{ $errors->first($errorKey) }}</strong>
>     </span>
> @endif
> ```
> 
> If this solution works anyway, please tell us and we going to try to address this problem..

Thanks its Working 
Sry for the delay

**Comment by Shidersz** [comment]
@tmgomas Please, may you ignore the previous temporal solution I gave to you and try the changes introduced on https://github.com/jeroennoten/Laravel-AdminLTE/pull/1035

Your feedback is very important in order to fix this on the next versions...

**Comment by Shidersz** [comment]
@asartz May you also check if applying the changes from the pull request #1035 fixes this problem?

**Comment by asartz** [comment]
@Shidersz yes, i can confirm it is working as expected. thank you for your efforts
