### ISSUE TITLE
[Question] Laravel-AdminLTE menu

### ISSUE THREAD

**Issue by firdausriawan2** [jeroennoten/Laravel-AdminLTE#976]
hi, I'm a little confused when I want to create a menu for a user, I want to know how to create a different menu for the admin and user roles.

can it be done in config?

**Comment by Shidersz** [comment]
Not so easy as just editing the configuration. This package offers next supports:
- Support to [Laravel's Gate](https://laravel.com/docs/8.x/authorization#gates) with the [can attributte](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) of the menu items. Permissions should be configured with Laravel's Gate.
- Support to [custom filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) over the menu. There is an example on how you can integrate [Laratrust](https://laratrust.santigarcor.me/). Permissions are configured with the Laratrust package.
- Support to [create the menu dinamically](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime) (at run time). That way you can define your own logic to create the menu depending on the logged user.

**Comment by firdausriawan2** [comment]
> 
> 
> Not so easy as just editing the configuration. This package offers next supports:
> 
>     * Support to [Laravel's Gate](https://laravel.com/docs/8.x/authorization#gates) with the [can attributte](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) of the menu items. Permissions should be configured with Laravel's Gate.
> 
>     * Support to [custom filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) over the menu. There is an example on how you can integrate [Laratrust](https://laratrust.santigarcor.me/). Permissions are configured with the Laratrust package.
> 
>     * Support to [create the menu dinamically](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime) (at run time). That way you can define your own logic to create the menu depending on the logged user.

thanks for the instructions

**Comment by firdausriawan2** [comment]
> 
> 
> Not so easy as just editing the configuration. This package offers next supports:
> 
>     * Support to [Laravel's Gate](https://laravel.com/docs/8.x/authorization#gates) with the [can attributte](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#the-can-attribute) of the menu items. Permissions should be configured with Laravel's Gate.
> 
>     * Support to [custom filters](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#custom-menu-filters) over the menu. There is an example on how you can integrate [Laratrust](https://laratrust.santigarcor.me/). Permissions are configured with the Laratrust package.
> 
>     * Support to [create the menu dinamically](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime) (at run time). That way you can define your own logic to create the menu depending on the logged user.

Thanks, Very helpful
