### ISSUE TITLE
[Question] Laravel-AdminLTE rtl mode

### ISSUE THREAD

**Issue by tahahassen** [jeroennoten/Laravel-AdminLTE#977]
hi sir , i'd like to thank you for this package it is very helpful , i read the doc and usage instruction but i would like to know if this template support rtl mode , and if it did .. could you please give me some hint on how to switch from ltr to rtl mode.
thank you previously

**Comment by Shidersz** [comment]
Not currently, read issue #974 , we need to wait for support on the underlying **AdminLTE** package first...

**Comment by tahahassen** [comment]
ah okay , thank you
