### ISSUE TITLE
Include div id=app for Vuejs

### ISSUE THREAD

**Issue by hectordufau** [jeroennoten/Laravel-AdminLTE#978]
### Is your request related to a problem? Please describe.
For vuejs, adminlte template doesn't have a div id=app

### Describe the solution you'd like
Just put < div id="app" > around @yield('body') on master.blade

### Describe alternatives you've considered
Another alternative is add on page.blade a < div id="app" > inside < div class="wrapper" >

### Additional context
![image](https://user-images.githubusercontent.com/12888215/133408765-b68269f0-8c31-48f5-ad35-eae12e3e194d.png)

**Comment by Shidersz** [comment]
I believe there is no sense for this. I never worked with **vue.js** (still), but looking at the examples [here](https://vuejs.org/v2/guide/) the `id="app"` is merely defined to have a way to target the element from the **Vue** framework and make it reactive.
