### ISSUE TITLE
[Question] Adminlte2 for laravel >= 7.x

### ISSUE THREAD

**Issue by SoftplaceEmil** [jeroennoten/Laravel-AdminLTE#979]
Hi, big fan of the repo here, used in many projects.
I will cut to the matter at hand.
I have a project that started around 2.5 years ago and runs Laravel 5.8 and adminlte2 with this plugin.
I was upgrading the project to Laravel 8.x and i got stopped by composer because this package's 2.x version only supports Laravel v6.x.
Is it possible to increase the supported laravel version for adminlte2?

**Comment by resslinger** [comment]
The support for adminlte2 has stopped. Please change to adminlte3.
