### ISSUE TITLE
Rollback Auth Views

### ISSUE THREAD

**Issue by ascanipek** [jeroennoten/Laravel-AdminLTE#980]
How do I revert to default laravel auth views from adminlte auth views?

**Comment by Shidersz** [comment]
I believe Laravel do not come with default authentication views, currently there are differents packages that offers authentication scaffoldings (like **brezee**, **jetstream** or the legacy **laravel/ui**). Depending on the scafoolding you are using, there may be a command on it to reinstall the auths views. For **laravel/ui** (the first authentication scaffolding) you may check [here](https://github.com/laravel/ui#installation).

**Comment by ascanipek** [comment]
I first installed the laravel/ui package, but then I ran it for adminlte's auth views.
php artisan adminlte:install --only=auth_views

But I can't return to the default laravel/ui auth views.

**Comment by Shidersz** [comment]
From **laravel/ui** documentation:

> Once the laravel/ui package has been installed, you may install the frontend scaffolding using the ui Artisan command:
> 
> // Generate basic scaffolding...
> php artisan ui bootstrap
> php artisan ui vue
> php artisan ui react
> 
> // Generate login / registration scaffolding...
> php artisan ui bootstrap --auth
> php artisan ui vue --auth
> php artisan ui react --auth

have you tried executing `php artisan ui bootstrap` and `php artisan ui bootstrap --auth`?

**Comment by Shidersz** [comment]
Closed, no feedback!
