### ISSUE TITLE
How to add a language selector in navbar-right

### ISSUE THREAD

**Issue by invaders-xx** [jeroennoten/Laravel-AdminLTE#981]
### Describe the bug
I would like to add a language selector wih flag-icon in the topnav right section.

I started by adding Event::listen(BuildingMenu::class, function (BuildingMenu $event) {} in EventServiceProvider but I don't know how to go further. Many thanks for your help.

### Environment

| Item    | Version
| laravel-adminlte | 3.7
| Laravel | 8

**Comment by Shidersz** [comment]
@invaders-xx If you take a look to the source file that represents the top navbar:

https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/navbar/navbar.blade.php

you can see it yields two sections for add customs navbar items:

- `content_top_nav_left`
- `content_top_nav_right`

I do not have experience implementing a language selector item, but you can still add custom items on the navbar. Also, you may take next example as a reference for implement a language selector menu item:

https://adminlte.io/themes/v3/pages/examples/language-menu.html#

**Comment by invaders-xx** [comment]
many thanks for your feedback.
