### ISSUE TITLE
How to enable navbar on Desktop and sidebar on Phone? (Responsive view)

### ISSUE THREAD

**Issue by fasa79** [jeroennoten/Laravel-AdminLTE#983]
| Question                | Answer
| ----------------------- | -----------------------
| Issue or Enhancement    | Issue
| Laravel Version         | 8
| Project Version         | 3.7

### Current Behavior

The current version of top nav bar is not responsive on phone. When the top nav bar is enabled, it will also enable on small screen mode. Even, after including the array ['xs' => false, 'xl' =>true] on the top nav bar adminlte config, it still enabled on small screen.

### Expected Behavior

Need to be able to include responsive array on top nav bar field, so top navbar will be available only on desktop view while sidebar will be enabled on small screen view.

![Capture](https://user-images.githubusercontent.com/48919366/133958156-b644c3de-d7b7-4b7a-97ac-60e18192d234.PNG)

**Comment by Shidersz** [comment]
Please, read the Wiki about [Layout and styling configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Layout-and-Styling-Configuration#layout). Responsive usage is only available for **layout_fixed_navbar**

> **layout_fixed_navbar**
> 
> Enables/Disables the fixed navbar (top navigation) mode, here you can set to true or an array for responsive usage. 

A fixed navbar means the navbar won't scroll with the page, you can check the behavior on next link:

https://adminlte.io/themes/v3/pages/layout/fixed-topnav.html

On the other hand, there is no option to have only a top navbar for desktop size, and a sidebar for other sizes. However, you can have a top navbar layout:


> **layout_topnav**
> 
> Enables/Disables the top navigation only layout, this will remove the sidebar and put your links at the top navbar. Can't be used with layout_boxed.

and tune next option to collapse items into an hamburger button:


> **classes_topnav_nav**
> 
> Extra classes for the top navigation. Classes will be added to element nav.main-header.navbar. When enabling layout_topnav the recommendation is to use navbar-expand-md to get items auto collapsed into a menu button on low screen sizes. Otherwise, stay with navbar-expand class.

**Comment by fasa79** [comment]
Thank you so much brother @Shidersz . Tuning classes_topnav_nav is what I need to make things responsive.
