### ISSUE TITLE
How to disable register url?

### ISSUE THREAD

**Issue by claytongf** [jeroennoten/Laravel-AdminLTE#984]
The question is about disabling the register url in AdminLTE as well.
I disable the register route in web.php as follows:
`Auth::routes(['register' => false]);`

But this is not enough for the link at the login page disapears.
in login.blade.php, I can delete the code below:
`{{-- Register link --}}
    @if($register_url)
        <p class="my-0">
            <a href="{{ $register_url }}">
                {{ __('adminlte::adminlte.register_a_new_membership') }}
            </a>
        </p>
    @endif`

But the $register_url still exists with url. How may I disable it?

**Comment by Shidersz** [comment]
Refers to the Wiki: [Urls Configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#urls)

> **register_url**
> 
> Changes the register URL. Set this option to false to hide the register link shown on the login view.
