### ISSUE TITLE
How to dynamically set menu labels?

### ISSUE THREAD

**Issue by nunodonato** [jeroennoten/Laravel-AdminLTE#986]
Hi folks,
I'm using this for the first time. I've been going through the docs but so far haven't found an answer.

I want to use the menu item "label" to show a counter of unread items. Unfortunately, I can't seem to call any laravel function in the config file, as the app breaks. Only with static values it works. Which kind of beats the point of it, I guess.... so maybe I'm missing something?

thanks in advance

**Comment by Shidersz** [comment]
Hi @nunodonato , To setup initial value for the label, you may need to [configure the menu item at runtime](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Menu-Configuration#menu-configuration-at-runtime). To update it periodically, you may need to setup an `id` attribute for the menu item. That `id` will be added to the `<li>` that wraps the menu item. Then you can use `Javascript/jQuery` to update the label periodically using an ajax call to the server.

**Comment by nunodonato** [comment]
Hi @Shidersz 
I read that section and copied the code 
`use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;

class EventServiceProvider extends ServiceProvider
{
    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        Event::listen(BuildingMenu::class, function (BuildingMenu $event) {
            // Add some items to the menu...
            $event->menu->add('MAIN NAVIGATION');
            $event->menu->add([
                'text' => 'Blog',
                'url' => 'admin/blog',
            ]);
        });
    }
}
`
Inside the boot method

**Comment by nunodonato** [comment]
@Shidersz thanks!!
