### ISSUE TITLE
[BUG] Datatable plugin javascript error

### ISSUE THREAD

**Issue by advantobcn** [jeroennoten/Laravel-AdminLTE#988]
In a view with tables of records, I have added @section ('plugins.Datatables', true), the table has the class assigned .data-table and in the js section I have added
```
<script>
     $ (document) .ready (function () {
         $ ('. data-table'). DataTable ();
     });
</script>
```

When loading the view the following error appears:
Uncaught TypeError: c is undefined
     jQuery 8
     <anonymous> http: //pim.test/admin/parameters: 1243
     jQuery 13 

![Screenshot_180](https://user-images.githubusercontent.com/91724665/135589793-199e15f6-ffc6-4f56-8f7a-cd405c935cc2.png)
![Screenshot_179](https://user-images.githubusercontent.com/91724665/135589795-c1df9857-6aec-49d8-88dc-565c739925c7.png)
![Screenshot_178](https://user-images.githubusercontent.com/91724665/135589798-a83c7264-07e0-4c6a-b573-ac6ec4ed1af3.png)
![Screenshot_181](https://user-images.githubusercontent.com/91724665/135589960-27ffb9b6-10aa-4107-b47e-f7e6c8146fe8.png)

### Environment
Complete the next environment information.

| Item    | Version
| ------- | -------
| Laravel | 8

**Comment by Shidersz** [comment]
Hi @advantobcn , on the pugins configuration **do not** use `asset => true` if you are going to use files from the CDNs. Read [Plugins configuration](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Plugins-Configuration) for more details about the `asset` property. The `asset => true` implies the file needs to be located on the same server. Maybe that will solve your problem...

**Comment by advantobcn** [comment]
Thank you Shidersz, I've set asset to false, but the jquery error is still there.
Which jquery version can we test?

**Comment by Shidersz** [comment]
Closed, no feedback...
