### ISSUE TITLE
Menu configuration at runtime Laravel 5.4

### ISSUE THREAD

**Issue by gus16710** [jeroennoten/Laravel-AdminLTE#99]
Im tring to configure the adminlte menu at runtime, i add the code like explain the readme file:

use Illuminate\Contracts\Events\Dispatcher;
use JeroenNoten\LaravelAdminLte\Events\BuildingMenu;

class AppServiceProvider extends ServiceProvider
{

    public function boot(Dispatcher $events)
    {
        $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add('MAIN NAVIGATION');
            $event->menu->add([
                'text' => 'Blog',
                'url' => 'admin/blog',
            ]);
        });
    }

}

But it happend nothing in the adminlte template.

Then i add the same code to the EventServiceProvider.php 

public function boot(DispatcherContract $events)
    {
        parent::boot($events);

        //
        $events->listen(\JeroenNoten\LaravelAdminLte\Events\BuildingMenu::class, function (BuildingMenu $event) {
            $event->menu->add('MAIN NAVIGATION');
            $event->menu->add([
                'text' => 'Blog',
                'url'  => 'admin/blog',
            ]);
        });
    }

But i have the next error 

Declaration of App\Providers\EventServiceProvider::boot() should be compatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot()

Im using Laravel 5.4

**Comment by jeroennoten** [comment]
Don't put it in your EvenServiceProvider. Put it in AppServiceProvider or add your own custom one.

**Comment by gus16710** [comment]
I have the next code into AppServiceProvider into boot method

public function boot(Dispatcher $events)
{
    $events->listen(BuildingMenu::class, function (BuildingMenu $event) {
        $event->menu->add('MAIN NAVIGATION');
        $event->menu->add([
            'text' => 'Blog',
            'url' => 'admin/blog',
        ]);
    });
}

Whats next to view this into my blade template???
