### ISSUE TITLE
[QUESTION]: Sidebar Menu Flicker Effect

### ISSUE THREAD

**Issue by javierjpm** [jeroennoten/Laravel-AdminLTE#992]
I use the below code in all index pages of my project (contacts, products, invoices, etc.), but every time a get into de index, the sidebar reloads all images of de menu items.  How can I avoid this issue? or am i doing something wrong?

@extends('adminlte::page')

@section('title', 'MyApp')

@section('content_header')
    Contacts
@stop

@section('content')
    My code ....
@stop

Regards...

**Comment by Shidersz** [comment]
@javierjpm Please upload a video showing the issue you are facing. For what I know, all pages are reloaded when you jump from one to another...

**Comment by javierjpm** [comment]
I mean, I would like to avoid the flicker of the icons. Regards

https://user-images.githubusercontent.com/81401360/136321096-852ead0f-d2cb-4c57-9744-5280b266373d.mp4

.
