### ISSUE TITLE
[FEATURE] Configurable usermenu image method name

### ISSUE THREAD

**Issue by uldiszarins** [jeroennoten/Laravel-AdminLTE#999]
To show the user image in user menu I need to enable it in config (usermenu_image => true) and use adminlte_image() function in Models/user.php - the problem is that the method name is in snake case and that is not the PSR12 standart. I am using phpcs to validate code after it is pushed to the repository. And since it is throwing the error i cant use this AdminLTE feature.

```
FILE: /var/www/html/app/Models/User.php
FOUND 1 ERROR AFFECTING 1 LINE
58 | ERROR | Method name "User::adminlte_image" is not in camel caps format
```

Would it be possible to somehow configure the name of method that is used in Models/User.php? And if I do not set it then it uses the default method name.

**Comment by Shidersz** [comment]
Hi @uldiszarins , by the moment you can [publish the main views](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Views-Customization) and change the method name on the published [menu-item-dropdown-user-menu.blade.php](https://github.com/jeroennoten/Laravel-AdminLTE/blob/master/resources/views/partials/navbar/menu-item-dropdown-user-menu.blade.php) file. You may also submit a Pull Request with the new method names.

Take into consideration it is not the only method used to extract data from the user's model (see [here](https://github.com/jeroennoten/Laravel-AdminLTE/wiki/Basic-Configuration#user-menu)). So, I do not consider appropriate having multiple configurations for such methods names. It will be better to meet standards and let an open door to customize the views (by publishing) for other particular cases.
